### ISSUE TITLE
Unable to bind port with a container

### ISSUE THREAD

**Issue by pokix** [docker/docker-py#1001]
Hello dear friends.

I'm trying to run a container using docker-py and bind ports with the host. I'm afraid I'm not experimented with Docker, but I try many things and I can't see where my mistake is.

Here is my code for create the container : 

`from docker import Client
cli = Client(base_url='tcp://172.16.3.87:2375', version='1.18')
container_id = cli.create_container(
        'busybox',
        'ls',
        name='test',
        ports=[1111],
        host_config=cli.create_host_config(port_bindings={
                1111:8000
        },
        publish_all_ports=True)
)
print(container_id)`

The container is created, but there is no bind : 

`CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                  NAMES
d3ad8566958d        busybox             "ls"                42 seconds ago      Created                                    test`

However, the host received the command. I captured the incoming traffic on 2375 port. Here is the result : 

`{"Tty": false, "NetworkDisabled": false, "Image": "busybox", "Cmd": ["ls"], "StdinOnce": false, "HostConfig": {"PortBindings": {"1111/tcp": [{"HostPort": "8000", "HostIp": ""}]}, "PublishAllPorts": true}, "AttachStdin": false, "MemorySwap": 0, "Memory": 0, "ExposedPorts": {"1111/tcp": {}}, "AttachStderr": true, "AttachStdout": true, "OpenStdin": false}`

Has someone experimented the same issue ?

Thank you by advance!

**Comment by shin-** [comment]
I'm pretty sure you need to `cli.start` your container.

**Comment by pokix** [comment]
I tried but it doesn't solve the problem

**Comment by shin-** [comment]
Is your container stopped when you look at port bindings? A stopped container releases the ports it binds while running. I assume that's what you're seeing. Use the `top` command instead of `ls` to have a long-running container and you should see your code working as expected.

**Comment by pokix** [comment]
Yes, that was the issue. It is working now.

Thank you very much for your answers!
