### ISSUE TITLE
'tmpfs' support?

### ISSUE THREAD

**Issue by DarkFranX** [docker/docker-py#1003]
Hi, I saw some work going on for tmpfs support and I was wondering if the function was implemented in the dev build. If no, may I ask when it will? Or can I do something about it? 

I need this function to be able to manipulate files inside a read-only container.

Thanks in advance!

**Comment by dnephin** [comment]
It was merged in #994, it's in master now and will be in the 1.8.0 release

**Comment by DarkFranX** [comment]
Isn't that merge request adding the support for the 'tmpfs' parameter _**declaration**_ only? I just cloned the project and the option is accepted, but it doesn't actually do anything. 

Thanks again.

**Comment by dnephin** [comment]
I don't understand the question. It accepts the param and passes it to the docker API which adds the tmpfs to the container. What behaviour do you expect from it?

**Comment by DarkFranX** [comment]
For example, adding the following in host_config: 

`tmpfs={ '/test' : '' }`

does not create the desired 'test' volume inside the container.
