### ISSUE TITLE
GELF logging driver support

### ISSUE THREAD

**Issue by samzhang111** [docker/docker-py#1012]
Docker 1.8 has added native Graylog integration with a GELF logging driver: https://www.graylog.org/blog/28-centralized-docker-container-logging-with-native-graylog-integration.

From the command line, a container can be created with the gelf driver like so: `docker run --log-driver=gelf --log-opt gelf-address=udp://<GraylogIP>:12201 busybox echo Hello Graylog`.

I propose adding support for this driver type into the `create_container` method.

**Comment by shin-** [comment]
Support for custom log drivers is already implemented.
Here's what you want to do:
```python
from docker import Client
from docker.utils import LogConfig

c = Client()
log_cfg = LogConfig(LogConfig.GELF, { 'gelf-address': 'udp://<GraylogIP>:12201' })
host_cfg = c.create_host_config(log_config=log_cfg)
c.create_container('busybox', 'echo Hello Graylog', host_config=host_cfg)
```

Related issues:
#718 #724

**Comment by jefsayshi** [comment]
Thanks for the help. Here is the code that I got working.

```python
from docker import Client
from docker.utils import LogConfig

c = Client()
log_cfg = LogConfig(type=LogConfig.types.GELF, config={ 'gelf-address': 'udp://<GraylogIP>:12201' })
host_cfg = c.create_host_config(log_config=log_cfg)
c.create_container('busybox', 'echo Hello Graylog', host_config=host_cfg)
```
