### ISSUE TITLE
Add other filters to ClientAPI.containers documentation

### ISSUE THREAD

**Issue by SakuraSound** [docker/docker-py#1016]
I am happy to know through my own testing that the filter tag "ancestor" works for the containers function.  If the other filters work as well, it may be good to add them to the "Available Filters" list in the documentation, so that others know that it works. If this is something that I can do, please point me in the right direction.

Example use:  `c = cli.containers(filters={"ancestor": "custom/redis"})` properly returns those containers that spawned from the custom/redis image.

**Comment by SakuraSound** [comment]
I issued a pr for updating the documentation. Am I missing something. I want to help at least clean up the docs on this project

**Comment by bfirsh** [comment]
Thanks for the contribution! This should be live now.
