### ISSUE TITLE
CpuShares moved to HostConfig in API version 1.18 

### ISSUE THREAD

**Issue by dnephin** [docker/docker-py#1030]
See:
- https://docs.docker.com/engine/reference/api/docker_remote_api_v1.17/#create-a-container
- https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#create-a-container

Looks like we're still passing it in container config. I wonder if engine is supporting this still?

It's breaking with swarm.

**Comment by joshpurvis** [comment]
I needed this for swarm, so I implemented the changes in PR #1160.

**Comment by bfirsh** [comment]
Fixed in #1160.
