### ISSUE TITLE
Why bump to client API version to 1.22? What is workaround?

### ISSUE THREAD

**Issue by CaptTofu** [docker/docker-py#1032]
Hi there,

The latest version of docker-py fails on Ubuntu 15.04 with ansible because the version in docker-py was bumped. I've tried docker 1.9.1 and still it fails because it's client api 1.21. 

This breaks all Ubuntu 15.04 users who want to use Ansible and the docker module. 

What is the best workaround? I edited constants.py but that seems to be a hack.

**Comment by dnephin** [comment]
Pass `version` to the `Client` constructor: http://docker-py.readthedocs.org/en/stable/api/

**Comment by thaJeztah** [comment]
Also may be worth updating, because Ubuntu 15.04 is EOL'd and won't receive updates (including security updates)

**Comment by shin-** [comment]
1.22 is the API version for engine 1.10. We try to keep the default version close to that of the latest engine release (although in practice we've been one step behind lately).

As Daniel said, this is easy to configure when using `docker-py` by itself. I believe `ansible` gives you an option to do so as well, but my knowledge of the tool is limited.
