### ISSUE TITLE
Installation issue on drone.io

### ISSUE THREAD

**Issue by osallou** [docker/docker-py#1034]
When installing docker-py from pypi in drone.io (continuous integration), I face an error:

      Running setup.py egg_info for package docker-py
        error in docker-py setup command: Invalid environment marker: python_version < "3"
        Complete output from command python setup.py egg_info:
       error in docker-py setup command: Invalid environment marker: python_version < "3"

I use Python v2 and error occured only recently.

**Comment by osallou** [comment]
More info

    $ python --version
    Python 2.7.3
    $ pip --version
    pip 1.4.1 from /home/ubuntu/virtualenv/python2.7/lib/python2.7/site-packages (python 2.7)

**Comment by dnephin** [comment]
You need a more recent version of pip I believe. I think > 6.x

**Comment by osallou** [comment]
ok, I gonna force previous version to match available pip release in drone.io
Thanks
