### ISSUE TITLE
cli.logs got `requests.packages.urllib3.exceptions.ProtocolError`

### ISSUE THREAD

**Issue by ibigbug** [docker/docker-py#1035]
calling `cli.logs` on a long running container and follow the logs using `stream=True` will cause an Error.

such as:

`for line in cli.logs(sys.argv[1], stdout=True, stderr=True, stream=True, follow=True):`

gets an error like this:
## ![image](https://cloud.githubusercontent.com/assets/543405/14482662/8c7db5c2-0171-11e6-82e0-ae846aa3f7c0.png)

docker-py==1.8.0
Python 2.7.11
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

**Comment by TomasTomecek** [comment]
full stacktrace, complete reproducer and a version of `requests` would be very helpful

**Comment by ibigbug** [comment]
I found that may be a `requests` issue.

Requesting a docker host with `requests` directly also encounters the same issue.

To reproduce:

```python
r = requests.get('http://DOCKER_HOST/containers/A_LONG_RUNNING_CONTAINER_SUCH_AS_NGINX/logs?stdout=1&stderr=1&follow=1', stream=True)

while True:
    sys.stdout.write(r.raw.read(1024))
```

Tracestack:

```
¨ - - [15/Apr/2016:09:22:26 +0000] "GET /Traceback (most recent call last):
  File "client.py", line 29, in <module>
    sys.stdout.write(r.raw.read(1024))
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(859 bytes read)', IncompleteRead(859 bytes read))
```

with `requests==2.9.1`

With raw `httplib` to send this request is OK. I'm currently working into `urllib3` to see if there were any issues with it.

**Comment by TomasTomecek** [comment]
the issue may also be in docker engine, so feel free to try with curl too

**Comment by ibigbug** [comment]
Not seems to be a docker engine issue, curl or nodejs solution are both working correctly.

**Comment by ibigbug** [comment]
Debugging into https://github.com/python/cpython/blob/2.7/Lib/socket.py#L485, a break happend and httplib read an empty line, and https://github.com/python/cpython/blob/2.7/Lib/httplib.py#L637 closed the connection.

Do you have any ideas about how can the socket blocking `recv` receive an empty byte?
