### ISSUE TITLE
--ip and --ip6 options

### ISSUE THREAD

**Issue by IlyaSemenov** [docker/docker-py#1042]
I can specify specific IPv4 or IPv6 addresses when running `docker run --ip 1.2.3.4` manually, but it's not possible to do the same via API (thus, with automation tools like ansible).

`docker.Client.create_container()` should accept optional `ip` and `ip6` parameters.

**Comment by dnephin** [comment]
I believe these are specified under `networking_config`:

```python

create_container(..., networking_config={
  'EndpointsConfig': {
    'thenetworkname': {
      'IPAMConfig': {
        'IPv4Address': '...',
        'IPv6Address': '...',
      }
    }
  }
})

```

**Comment by shin-** [comment]
We should make this easier. It doesn't look like `create_network_config` (or `create_endpoint_config`) currently expose the functionality.

**Comment by mikroskeem** [comment]
ETA?
