### ISSUE TITLE
Feature request: set Swarm filter constraint on container create

### ISSUE THREAD

**Issue by Gnork** [docker/docker-py#1043]
With Docker Swarm it is possible to set filter constraints, in order to select a Swarm Agent with certain properties. With the CLI tool this can be accomplished by specifying the "-e" parameter as described in the [official documentation:](https://docs.docker.com/swarm/scheduler/filter/)

In the following example the node is selected by its name (agent1):
`docker run -it --rm -e constraint:node==agent1 ubuntu:trusty /bin/bash`

Maybe this is already possible with docker-py, but I couldn't figure it out.

Christoph

**Comment by dvenza** [comment]
Did you find a way to do it? Thanks!

**Comment by Gnork** [comment]
Hi.
It's actually easy if you know that the -e flag of the docker CLI means Environment Variable. So you can look up how to set them with docker-py and use the same parameters as with the CLI. 
I'm on my phone and can't give you a Code example. 
Hope this helps

**Comment by dvenza** [comment]
Thank you. If someone happens to get here looking for the same thing, you have to add an environment variable with the constraint as the name and None as the value.
I was trying passing an empty string and I got a weird error about not enough container slots.

**Comment by Gnork** [comment]
Are you using a dict? If I remember correctly, I had problems with them as well. But you can instead use a list, so that you don't need this "None Workaround".

**Comment by netoisc** [comment]
Hi @Gnork , I had the same problem. I've used docker-py too, defining env-vars through a dict and in my case I solved this problem by setting the **Key** with **constraint:node** and the **Value** with **=agent1**. Now, when I run containers i can see the filter correctly within swarm constraints ej. `"Labels": {
                "com.docker.swarm.constraints": "[\"node==agent1\"]"`
