### ISSUE TITLE
method containers() delivers old containers (already destroyed)

### ISSUE THREAD

**Issue by raimonbosch** [docker/docker-py#1045]
Hi,

Today I have tested docker-py 1.7.2 and I have found this error calling to method containers(). I am calling the method every 2-3 seconds in order to detect new containers that may arise. But the method is not delivering this new containers and instead it delivers the containers I had at the beginning.

I thought that I could solve that by reinstancing the docker Client for every call, but I bumped into the same error.

Is this a known issue?

```
self.cli = Client(base_url='unix://var/run/docker.sock')

      for container in self.cli.containers():
          ...
```

**Comment by shin-** [comment]
What version of docker are you using? Do you see the same issue if you do `watch -n 2 docker ps` in your shell?

**Comment by raimonbosch** [comment]
Version: Docker version 1.10.3, build 20f81dd

I tried to remove and add some containers and run "docker ps" and results are correct (also with watch -n 2 docker ps). So the problem must be in docker-py or in the way that it communicates with Docker API.

**Comment by raimonbosch** [comment]
Seems related to my code. I will reopen if I find a concrete error on docker-py.
