### ISSUE TITLE
Feature Request: Ability to dry-run an API call (that returns the JSON payload that would have been sent out to the host) 

### ISSUE THREAD

**Issue by SakuraSound** [docker/docker-py#1052]
It would be nice to have the ability to see the payload generated from a call to a (remote) docker host, with the option of performing either a dry-run of the request, or as a return value from the call. Scenarios where you are doing analysis of the payload (for error reporting, bug tracking), auditing requests that get sent to docker from a remote source (i.e. auditing a service that communicates with docker), or for testing purposes (or other purposes that I can not think of at this time). 

Considering this seems to use requests to send payloads, [requests PreparedRequest](http://docs.python-requests.org/en/master/api/#requests.PreparedRequest) could be an area to look at for providing said functionality.

I can take a look at ways this could be implemented, and would love some feedback as to the feasibility and usefulness (maybe I am crazy...)

**Comment by shin-** [comment]
I think this covers most use-cases:

```python
import docker


class DryRunClient(docker.Client):
    def request(self, method, url, params=None, data=None, headers=None,
                *args, **kwargs):
        return {
            'method': method,
            'url': url,
            'params': params,
            'data': data,
            'headers': headers
        }

    def _result(self, response, *args, **kwargs):
        return response

    def _raise_for_status(self, *args, **kwargs):
        pass

    def _stream_helper(self, response, *args, **kwargs):
        return response

    def _get_result(self, container, stream, response):
        return response

    def _get_result_tty(self, stream, response, is_tty):
        return response
```

Some methods like `stop`, `pause` or `rename` will not return any value regardless (because the API provides an empty response when those operations are successful) so if you're interested in those as well, you would need to tweak them manually.
