### ISSUE TITLE
host => guest?

### ISSUE THREAD

**Issue by robnagler** [docker/docker-py#1069]
I am a confused by the use of `host`, which seems to mean `guest` in the docker-py code and documentation. Shouldn't, for example, `create_host_config` be `create_guest_config`, because it is generating the configuration for the container? Thanks.

**Comment by shin-** [comment]
`HostConfig` is the name of that object in the [Docker API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-a-container).
As I understand it, the rationale is this specific part of the configuration specifies how the container will interact with the host (run limits, volumes binds, port mappings...)

HTH.

**Comment by robnagler** [comment]
Keep to the Docker API naming makes sense. Thanks for the answer.
