### ISSUE TITLE
Can't specify the auth config path

### ISSUE THREAD

**Issue by wukai-gd** [docker/docker-py#1073]
```
docker-py==1.8.1
Python 2.7.5
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```
Can I add a parameter to specify the config path?

**Comment by wukai-gd** [comment]
def __init__(self, base_url=None, version=None,
                 timeout=constants.DEFAULT_TIMEOUT_SECONDS, tls=False):
        super(Client, self).__init__()

        if tls and not base_url:
            raise errors.TLSParameterError(
                'If using TLS, the base_url argument must be provided.'
            )

        self.base_url = base_url
        self.timeout = timeout

        self._auth_configs = auth.load_config()

**Comment by shin-** [comment]
Use the `DOCKER_CONFIG` environment variable.

**Comment by wukai-gd** [comment]
@shin- ok, it works for me.
