### ISSUE TITLE
create_container doesn't work, It return 404

### ISSUE THREAD

**Issue by yoyoidea** [docker/docker-py#1074]
I read docker-py docmentation.  I try to run:

```
from docker import Client
cli = Client(base_url='http://10.9.24.32:6732')
container = cli.create_container(image='busybox:latest', command='/bin/sleep 30')
```

but it return some error, like this:
`Traceback (most recent call last):
  File "/Users/yoyo/drcloud/DianCloud/test.py", line 3, in <module>
    container = cli.create_container(image='hello-world', command='/bin/sleep 30')
  File "/Library/Python/2.7/site-packages/docker/api/container.py", line 120, in create_container
    return self.create_container_from_config(config, name)
  File "/Library/Python/2.7/site-packages/docker/api/container.py", line 135, in create_container_from_config
    return self._result(res, True)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 158, in _result
    self._raise_for_status(response)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 153, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("404 page not found")`

then I print the docker-py request url:

`http://10.9.24.32:6732//v1.22/containers/create`

But it readlly cann't be request.  So I think maybe docker changed they API,  but docker-py isn't update?

**Comment by shin-** [comment]
You probably need to remove the trailing slash in your `base_url`. The request URL you're showing is invalid because it has two slashes at the beginning of the path.

**Comment by yoyoidea** [comment]
It didn't have the tralling slash in my `base_url` . You can direct request 
`http://10.9.24.32:6732/v1.22/containers/create`,  it will return 404, you can try it.  
but request `http://10.9.24.32:6732/containers/create`, It works.

**Comment by yoyoidea** [comment]
This question already solve， I made a mistake.  Thx for your help.

**Comment by shin-** [comment]
Ah, it seems like you were using an API version that's greater than the one your Docker engine supports. You can use the `version` parameter in the `Client` constructor to specify a lower version, or use the `AutoVersionClient` instead.
