### ISSUE TITLE
Feature Request: docker.from_env(version='auto')

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker-py#1075]
Feature request to add auto api version support for ```docker.from_env()``` similar to ```docker.Client(version='auto')```?

I noticed that one of the suggestions from #402 for the ```version='auto'``` option was now available for ```docker.Client()``` but doesn't work for ```docker.from_env()```.

**Comment by shin-** [comment]
Agreed.
For now, the current workaround would be
```python
from docker import Client
from docker.utils import kwargs_from_env

c = Client(version='auto', **kwargs_from_env())
```
