### ISSUE TITLE
how can docker-py filter containers in state "Dead“

### ISSUE THREAD

**Issue by BlueShells** [docker/docker-py#1077]
I know I can use the 
“containers(quiet=True,filters={'status':'exited'})”
to get the exited containers ,but I also want to get the container that status is "Dead",I know I can list all the containers and do the loop and check the status one by one ,I wonder if there is a simple way like when I get the exited containers

**Comment by shin-** [comment]
`filters={'status': 'dead'}` should work. https://docs.docker.com/engine/reference/commandline/ps/#filtering

**Comment by BlueShells** [comment]
it works ,but also need all=True
