### ISSUE TITLE
Add Swarm management

### ISSUE THREAD

**Issue by bfirsh** [docker/docker-py#1085]
[In Docker 1.12, Swarm management is being added to the Remote API.](https://github.com/docker/docker/pull/23362) We should support that in docker-py too.

[I made a half-arsed start in case anyone wants to carry it and work on it.](https://github.com/bfirsh/docker-py/commit/8a0416f40808f01e05a55d7f34d195467e8e77c7)

**Comment by ghostsquad** [comment]
@bfirsh - I saw your demo at DockerCon, pretty cool. I'd love to help carry the torch. I'm working on a hack for the Hackathon inspired by your work.

**Comment by bfirsh** [comment]
@ghostsquad Feel free! I'm not working on it at the moment. :)

**Comment by Tuxity** [comment]
Any ETA for that awesome feature ?
I saw the milestone 1.10.0 but don't know if it's A question of days, weeks or months

**Comment by shin-** [comment]
Sorry, no ETA for 1.10.0 yet.

#1127 and #1147 have been merged to master, so I'm closing this.

**Comment by shin-** [comment]
1.10.0 now available on pypi.
