### ISSUE TITLE
create_ipam_config() got an unexpected keyword argument 'subnet'

### ISSUE THREAD

**Issue by mikroskeem** [docker/docker-py#1088]
https://docker-py.readthedocs.io/en/latest/networks/ this tells me I can use subnet argument, but when I launch my program it throws `TypeError: create_ipam_config() got an unexpected keyword argument 'subnet'`

docker-py version is 1.8.1

**Comment by shin-** [comment]
Oops, that documentation is indeed incorrect. Here's how you need to proceed:

```python
ipam_pool = docker.utils.create_ipam_pool(subnet='xxx')
ipam_cfg = docker.utils.create_ipam_config(pool_configs=[ipam_pool])
```

I am reworking the networking docs as part of #1083 , so I'll fix that mistake there as well.

**Comment by mikroskeem** [comment]
Okay thanks! It worked :+1:
