### ISSUE TITLE
Provide a Mock implementation

### ISSUE THREAD

**Issue by samalba** [docker/docker-py#109]
Any usage of docker-py requires unit testing. The latter requires a Fake client that does not require a docker daemon to be running. Providing a mock implementation will avoid every single user to re-implement its own mock.

This is a nice to have.

**Comment by wallrj** [comment]
I started some work on this in #693. Please comment on the PR if you have time.

**Comment by bfirsh** [comment]
It's far from complete, but it exists now! :tada: 

https://github.com/docker/docker-py/blob/master/tests/unit/fake_api_client.py
