### ISSUE TITLE
`containers` would return empty NetworkID

### ISSUE THREAD

**Issue by kujiy** [docker/docker-py#1093]
I obviously couldn't get NetworkID with [containers](http://docker-py.readthedocs.io/en/stable/api/#containers) api. Other properties are good.

```
{
	'Networks': {
		'myNetWork': {
			'IPAddress': '172.30.0.17',
			'IPPrefixLen': 16,
			...
			'NetworkID': '',             <========
			...
		}
	}
}
```

Is this problem or am I wrong?

> Docker version 1.11.1,
docker-py 1.8.1,
pip 8.1.2

Here is a test script.

```py
#!/usr/bin/python3

from docker import Client
cl = Client(base_url="unix://var/run/docker.sock")

# get containers
cons = cl.containers()

for con in cons:
        print(con["Names"])
        print(con["Image"])
        print(con["NetworkSettings"])
        break
```

If it needs to fix, I wanna try it.

**Comment by TomasTomecek** [comment]
docker-py doesn't have anything to do with this -- whole response is generated in docker engine, you should report at docker/docker.

I have also experienced pretty inconsistent data in networking part, e.g. when you disable network namespace with `--net=host`, there's nothing in there.

**Comment by thaJeztah** [comment]
Looks like https://github.com/docker/docker/issues/23596, and fixed by https://github.com/docker/docker/pull/23635, which will be in docker 1.12

**Comment by shin-** [comment]
Thanks @thaJeztah !
