### ISSUE TITLE
get_image function raise a timeout

### ISSUE THREAD

**Issue by kZk93** [docker/docker-py#1098]
When i'm trying to save my image using the following python commands:
  cli = Client(base_url='tcp://127.0.0.1:2375')
  image = cli.get_image(new_image)
  image_tar = open('new_image_api.tar', 'w')
  image_tar.write(image.data)
  image_tar.close()

It raise
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=60)

My docker deamon raise 
Can't add file /var/lib/docker/tmp/docker-export-601225857/032e1789d3ece898230e065002eb5614139f0a8c426a4729c73f4e4a7af7f3c8/layer.tar to tar: io: read/write on closed pipe 

Is there any way of setting up an higher timeout delay since it's a big image (more than 700MB) ?

**Comment by kZk93** [comment]
Never mind it's totally my bad I should read Client doc more carefully, I adjust my timeout

**Comment by vklonghml** [comment]
@kZk93 how did you resolve this problem, any details, thks.

**Comment by TomasTomecek** [comment]
@vklonghml please open a new issue

image size is definitely relevant; in order to save an image 700 MB big, the bandwidth needed for such scenario is `700 MB / 60 seconds = 11.6 MB/s` -- on a system with high load, this may not be as simple as you think
