### ISSUE TITLE
Setting the appropriate version value 

### ISSUE THREAD

**Issue by black-perl** [docker/docker-py#1099]
Hi, 

I am using `auto` as the version parameter while creating a `Client` instance. The problem I am facing is I cannot get `put_archive` working using this. I know that it requires at least version  `1.2` for working so I changed `version` to `1.2`. After that, `put_archive` worked okay apart from the issue that it fails to **put** large file. I guess a `post` request is sent behind the scenes and it's a `python-requests` [issue](https://github.com/kennethreitz/requests/issues/2422).

But the problem I face when I set the `version` to `1.2` is the client returns the following errors on commands like `create_container`: 
```Shell
 404 Client Error: Not Found ("client and server don't have same version (client : 1.22, server: 1.18)")
```

So, what should be the appropriate value of `version` to get `put_archive` and other functions working at the same time.

Specs:
 ```Shell
docker-py==1.8.1
Python 2.7.6
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by shin-** [comment]
Hi!

1. Pretty sure you mean `1.20`, not `1.2` - they're not the same thing.
2. The version of Docker Engine you are currently using is too old - the `put_archive` method wasn't implemented at the time. You need to update the engine to a more recent version.

**Comment by black-perl** [comment]
Thanks !
