### ISSUE TITLE
Run a series of commands in a running container and check the status

### ISSUE THREAD

**Issue by black-perl** [docker/docker-py#1100]
Hi, some questions :

I need to run a series of commands in a running container and later on check their status( i.e whether they succeeded or not). So, I used the following approach : 

```Shell
$ ex = cli.exec_create(<container-id>, cmd="bash -c 'cd /bin; ls ; echo $?'")
$ resp = cli.exec_start(ex.get("Id"))
$ resp

# Split the return string value by '\n' and check last element to be 0
['cat','ls',....,'0']
=> 0 (success)
```

Is there a better approach to do this ? This solution sounds a bit hacky to me :sweat_smile:  

Also, is there  a procedure to change the `workdir` of my container ? I guess once we set it while creating the container, it cannot be changed( I want to avoid doing `cd` each time while running a command in a directory and check its status ).

Thanks.

**Comment by shin-** [comment]
A better approach would be to call `client.exec_inspect()` on `ex['Id']` and retrieve the status from the resulting dict. :)

```python
ex = cli.exec_create(container_id, cmd="bash -c 'cd /bin; ls'")
resp = cli.exec_start(ex)
cli.exec_inspect(ex)['ExitCode']  # == 0
```

As for changing the `workdir` of an existing container, I don't think that's possible, at least not in a way that's exposed by the Docker API.

**Comment by black-perl** [comment]
Thanks for replying ! Looks promising :)
