### ISSUE TITLE
Follow symlinks when creating context

### ISSUE THREAD

**Issue by znewman01** [docker/docker-py#1101]
I work on a product that depends on docker-py to upload a Docker context, and I have a request from a user to allow following symlinks on local disk when creating this context.

It'd be an easy fix to either add an option to do this, or to make it the default behavior:
https://github.com/docker/docker-py/blob/538a1db9dd210ee4824f0203341586b9aa3f2419/docker/utils/utils.py#L94
I'm happy to make a PR if this is desired behavior.

Possibly relevant prior discussion: <https://github.com/docker/docker/issues/1676>, in which Docker maintainers declined to add such an option to the Docker CLI for reasons of repeatable builds.

**Comment by TomasTomecek** [comment]
[`build`](https://github.com/docker/docker-py/blob/538a1db9dd210ee4824f0203341586b9aa3f2419/docker/api/build.py#L16) call supports `fileobj` so you can easily prepare the context yourself.

**Comment by shin-** [comment]
If the core project has explicitly decided not to support it, I don't think it would be a good idea for us to do so. As Tomas pointed out, you can use the `fileobj` tactic as a workaround (at your own risk), but for equivalent parameters, behavior should stay consistent with the engine.
