### ISSUE TITLE
Support create volume Labels options

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#1102]
First, check the remote API:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/

     {
      "Name": "tardis",
      "Labels": {
        "com.example.some-label": "some-value",
        "com.example.some-other-label": "some-other-value"
      },
    }

It provides ``Labels`` options. But docker-py doesn't support it right not.

Second, in docker-py's document give the following example:

    volume = cli.create_volume(
      name='foobar', driver='local', driver_opts={'foo': 'bar', 'baz': 'false'}

    docker.errors.APIError: 500 Server Error: Internal Server Error ("create foobar: invalid option key: "foo"")

But driver_opts is not working. What kinds of driver_opts can we use?

**Comment by TomasTomecek** [comment]
> But driver_opts is not working. What kinds of driver_opts can we use?

Those should be available here: https://docs.docker.com/engine/admin/logging/overview/

**Comment by shin-** [comment]
These were added "recently", so we don't have support for them yet
@linlinlinlin FYI, `driver_opts` is different. It corresponds to
> DriverOpts - A mapping of driver options and values. These options are passed directly to the driver and are driver specific.

in the docs.

@TomasTomecek those are logging drivers, not volume drivers :pensive:

**Comment by linlinlinlin** [comment]
@shin Thanks for your support. Is there are any existing DriverOpts as an example we can use in Ubuntu environment?

**Comment by TomasTomecek** [comment]
`/facepalm` sorry about the noise, I should read more carefully.
