### ISSUE TITLE
Support updating the restart policy attribute of a running container

### ISSUE THREAD

**Issue by gkze** [docker/docker-py#1106]
Hi,

It looks like updating the restart policy of a running container is not supported yet (https://github.com/docker/docker-py/blob/88811a26593e8a87e8d820d8820736fea6d8d20a/docker/api/container.py#L404).

Is there any work being done on this? Didn't want to duplicate efforts, I would be more than happy to issue a PR.

Thanks!

**Comment by mferon** [comment]
Hi,

Here is a pull request about it : #1158
