### ISSUE TITLE
Attach Already created volume to Container By Volume name 

### ISSUE THREAD

**Issue by saraswat2385** [docker/docker-py#1110]
We can create volumes independently  and give them some name,
i want to use already created volume while calling create_container without using volume_from 

we can attach already created volumes using following docker command, But it's not happening using dockerpy

docker run -d -P -v xldVolume:/mnt/sda1/var/lib/docker/volumes/xldVolume/_data --name tanmay busybox:latest

**Comment by shin-** [comment]
This would be the equivalent code using docker-py:
```python
import docker
c = docker.Client()
ctnr = c.create_container(
    'busybox:latest',
    name='tanmay',
    volumes=['/mnt/sda1/var/lib/docker/volumes/xldVolume/_data'], 
    publish_all_ports=True,
    detach=True, 
    host_config=c.create_host_config(
        binds=['xldVolume:/mnt/sda1/var/lib/docker/volumes/xldVolume/_data']
    )
)
c.start(ctnr)
```

**Comment by saraswat2385** [comment]
Hi @shin- 

I am getting following error

**docker.errors.APIError: 500 Server Error: Internal Server Error ("device or resource busy") in <script>** 

while starting container ....


any idea ?????

**Comment by saraswat2385** [comment]
@shin- Thanks For help
