### ISSUE TITLE
Inconsistent behaviour between docker/docker-compose when logging in.

### ISSUE THREAD

**Issue by WadeWaldron** [docker/docker-py#1116]
We recently encountered an issue similar to the one documented here:

https://github.com/docker/compose/issues/1622

During the investigation of this issue we came across a work around that suggests an inconsistency in the way that logins are handled.

When we would use `docker login` to try to pull from a Dockerhub private repo, it would work using `docker pull` but fail with `docker-compose pull`. We were using docker login and not specifying a server. Using --verbose when doing the `docker-compose pull` or `docker-compose up` revealed that it was looking for a registry entry for docker.io but was unable to find one. I changed to docker login docker.io and everything started working.

Delved deeper and noticed that when I did a docker login and didn't specify a server, it would put an entry such as:

```
"": {
    "auth": "token"
}
```

However if I specify docker.io then I get:

```
"docker.io": {
    "auth": "token"
}
```

The interesting thing is that for doing a docker pull it seems unnecessary to supply the server name. It is only when doing a docker-compose pull that it matters.

**Comment by shin-** [comment]
I believe this was fixed some time ago.
