### ISSUE TITLE
Search request data

### ISSUE THREAD

**Issue by anselal** [docker/docker-py#1118]
Hi,

I have a grid with a toolbar, in which I do not load any data when it is initialised. I overload the onSearch method like this to load data from an url which works fine:

`onSearch: function (event, eventData) {
                    w2ui['search'].clear();
                    w2ui['search'].load('http://127.0.0.1:5000/search/' + eventData.searchValue);
                }`

The parameters requested are: `"GET /search/opensuse?cmd=get-records&limit=100&offset=0&sort[0][field]=star_count&sort[0][direction]=desc HTTP/1.1"`

I also overload the onReload method like this:
`onReload: function (event) {
                    this.toolbar.disable('pull');
                    var search_value = w2ui['search'].searchData[0].value;
                    w2ui['search'].clear();
                    w2ui['search'].load('http://127.0.0.1:5000/search/' + search_value);
                }`

But when I retype a search term, or refresh or even clear the search field I get more request parameters like `"GET /docker/search/opens?cmd=get-records&limit=100&offset=0&search[0][field]=name&search[0][type]=text&search[0][operator]=contains&search[0][value]=opensuse&searchLogic=OR&sort[0][field]=star_count&sort[0][direction]=desc HTTP/1.1"`

**I do not get `search[0][value]` on my first search or after I clear the search field.**
**Is this because the grid is empty, so there is nothing to search for?**

**But why is a request sent when I clear the search field? Is it necessary ?**

**Comment by anselal** [comment]
I managed to get rid of the `search[0][value]` on onReload by replacing `clear` with `reset` but I lose my search string.

**Comment by shin-** [comment]
Hi @anselal ,

This doesn't look like a docker-py issue.

**Comment by anselal** [comment]
Hi @shin- I am really really sorry. I posted on the wrong project.
