### ISSUE TITLE
LogConfig does not work with other options set together

### ISSUE THREAD

**Issue by pyang30** [docker/docker-py#1136]
```python
#!/usr/bin/env python
from docker import Client
import docker

def test_valid_log_driver_and_log_opt():

    client = Client("tcp://172.16.226.128:4243")
    log_config = docker.utils.LogConfig(
            type='json-file',
            config={'max-file': '100'}
            )

    container = client.create_container(
            "busybox", ['true'],
            host_config=client.create_host_config(log_config=log_config)
            )
    restart_policy = {"name": "always"}
#    client.start(container, restart_policy=restart_policy)
    client.start(container)
    info = client.inspect_container(container)
    container_log_config = info['HostConfig']['LogConfig']
    print container_log_config

if __name__ == "__main__":
    test_valid_log_driver_and_log_opt()
```

The above code comes form test/container_test.py, when I send  the only one param "container" to client.start, the container's log config will be set correctly, but if I give two or more params to client.start, like restart_policy={xxx:xxx}, privileged=True or binds=xxx, or network_mode=xxx, the log config will not be set, it will use the default 'json-file'.

My test environment is:
 docker-py == 1.6.0  docker 1.8

and  docker-py=1.8 docker 1.11

**Comment by shin-** [comment]
Don't pass any config in `Client.start`, it is [deprecated](http://docker-py.readthedocs.io/en/stable/api/#start) for good reason.

https://github.com/docker/docker/pull/17799
https://github.com/docker/docker-py/issues/578
