### ISSUE TITLE
Have to pass dictionary of kwargs as positional arg to create_endpoint_config

### ISSUE THREAD

**Issue by mattarchie** [docker/docker-py#1138]
**Issue**
Contrary to documentation, create_endpoint_config does not take keyword arguments, it takes self, args, and kwargs as positional arguments, which requires a call with only kwargs to use None for the args position. This is confusing and should at least be documented properly, but it would be better if the desired behavior listed in the documentation were the true behavior of the code.

**Details**
When I try to use create_endpoint_config to provide an ipv4 address to my container, I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 148, in create_endpoint_config
    return create_endpoint_config(self._version, *args, **kwargs)
TypeError: create_endpoint_config() got an unexpected keyword argument 'ipv4_address'
```

I'm using the following to create my network config:
```
new_client = Client(base_url="unix:///var/run/docker.sock")
new_client.start(new_client.create_container(image="nginx",name="test",detach=True,
             networking_config=new_client.create_networking_config({
                  'docker_macvlan':new_client.create_endpoint_config(ipv4_address='10.10.10.14')
             })
))
```

I tried:

- `new_client.create_endpoint_config(ipv4_address='10.10.10.14')`
  - Error as above
- `new_client.create_endpoint_config(kwargs={'ipv4_address':'10.10.10.14'})`
  - Similar error as above: unexpected keyword kwargs
- `new_client.create_endpoint_config({'ipv4_address':'10.10.10.14'})`
  - JSON parsing error: `docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal string into Go value of type []string")`
- `new_client.create_endpoint_config('10.10.10.14')`
  - The JSON parsing error again

But the only one that works is `new_client.create_endpoint_config(None,{'ipv4_address':'10.10.10.14')` due to the fact that the declaration of create_endpoint_config in container.py is `def create_container_config(self, *args, **kwargs)` where self, *args, and **kwargs are all positional arguments. These being positional arguments and thus requiring that None in the args position is very strange and makes one's code less readable.

Furthermore, the documentation says you can use create_endpoint_config as I originally tried, which is simply not the case in my experience.

> Client.create_endpoint_config
> 
> Create an endpoint config dictionary to be used with Client.create_networking_config.
> 
> Params:
> 
> aliases (list): A list of aliases for this endpoint. Names in that list can be used within the network to reach the container. Defaults to None.
> links (list): A list of links for this endpoint. Containers declared in this list will be linked to this container. Defaults to None.
> ipv4_address (str): The IP address of this container on the network, using the IPv4 protocol. Defaults to None.
> ipv6_address (str): The IP address of this container on the network, using the IPv6 protocol. Defaults to None.
> link_local_ips (list): A list of link-local (IPv4/IPv6) addresses.
> Returns An endpoint config dictionary.
> 
> ```
> endpoint_config = docker_client.create_endpoint_config(
>     aliases=['web', 'app'],
>     links=['app_db'],
>     ipv4_address='132.65.0.123'
> )
> ```

**Version Info:**
docker-py==1.8.1
Python 2.7.11

Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:
 OS/Arch:      linux/amd64

**OS Info:**
Fedora release 23 (Twenty Three)

**Comment by mattarchie** [comment]
_Note: Sorry for the length of my issue and this comment, but I wanted to give as much detail as possible. Any help resolving this would be much appreciated - maybe I'm just missing something... In the meantime, I will just build the networking_config dictionary myself given I now know the format._

Okay, I just realized that this doesn't work either. I'm not sure if it's an issue with passing things in as a dictionary or with the way the kwargs are passed onto the utils.create_endpoint_config method, but I'm finding that the ipv4_address is showing up as a link, rather than in the IPAMConfig and then docker is auto-assigning an IPAddress within the network range.

I built a test functions to see how the *args, **kwargs thing works and it seems like the way you have args and kwargs should work... And I now see why I am getting the ip address as a link using `None,{'ipv4_address':'10.10.10.10'}` given it's being accepted as an arg instead. I tried getting around this by passing in an extra None arg prior to the dict as a work around, but this gives an error on the number of inputs: `TypeError: create_endpoint_config() takes at most 3 arguments (4 given)`.

Given my tests, I'm very confused why I'm getting the error from container.create_endpoint_config for passing in ipv4_address='10.10.10.10' as a kwarg.

**Test Function**
```
def func(*args,**kwargs):
     print "args:", args
     print "kwargs:", kwargs
     if (not args or args[0] is None) and not 'arg' in kwargs:
             kwargs['arg'] = 0
     elif 'arg' in kwargs:
             return
     elif args[0]==2:
             return
     else:
             argl = list(args)
             argl[0] += 1
             args = tuple(argl)
     func(*args,**kwargs)
```

**Input and Output from Tests**

In: `func(None,key='val')`
Out:
```
args: (None,)
kwargs: {'key': 'val'}
args: (None,)
kwargs: {'key': 'val', 'arg': 0}
```

In: `func(0,key='val')`
Out:
```
args: (0,)
kwargs: {'key': 'val'}
args: (1,)
kwargs: {'key': 'val'}
args: (2,)
kwargs: {'key': 'val'}
```

In: `func(key='val')`
Out:
```
args: ()
kwargs: {'key': 'val'}
args: ()
kwargs: {'key': 'val', 'arg': 0}
```

In: `func(0,{'key':'val'})`
Out:
```
args: (0, {'key': 'val'})
kwargs: {}
args: (1, {'key': 'val'})
kwargs: {}
args: (2, {'key': 'val'})
kwargs: {}
```

**Comment by shin-** [comment]
Your issue is actually much simpler than that. You're using docker-py 1.8.1, which didn't support the ipv4_address parameter in `create_endpoint_config`. The documentation available [here](http://docker-py.readthedocs.io/en/latest/networks/) is for docker-py 1.9, which is currently at the "release candidate" stage. Sorry about the confusion that may have caused.

I'd suggest using the release candidate (`pip install -U docker-py==1.9.0rc2`) for now, or wait a few more days for the 1.9.0 release. Alternatively, if you'd rather keep using 1.8.1 for now, you can construct the `endpoint_config` dictionary yourself.
```python
new_client.start(new_client.create_container(image="nginx",name="test",detach=True,
             networking_config=new_client.create_networking_config({
                  'docker_macvlan': {'IPv4Address': '10.10.10.14'}
             })
))
```

**Comment by mattarchie** [comment]
oh... I did make sure to do a pip install -U docker, but I never even thought that the "latest" version of the docs would point to a release candidate version. Is there anyway to add a "dev" or "rc" version to the docs and keep "latest" as whichever the newest release is? I think that would definitely be helpful going forward.

I am currently using `'docker_macvlan': { 'IPAMConfig': {'IPv4Address': '10.10.10.14'} }` for the `endpoint_config` dict and that is working. But if the IPAMConfig layer isn't needed that work make it cleaner, so I'll take a look at that.

Thanks for the response @shin- !

**Comment by shin-** [comment]
You probably do need the `IPAMConfig` part - I typed that last part a bit too quickly, sorry. 

As for the docs, `stable` is the documentation for the current stable release (currently 1.8.1), while latest (as you realized) is extracted from the `master` branch. Supposedly, accessing http://docker-py.readthedocs.io/ directly should redirect you to the `stable` docs, but I understand it can be confusing when coming in from an external link.

**Comment by mattarchie** [comment]
Oh, I see what you mean. That makes sense - stable vs. latest. I guess I'd just assumed I would the links I followed would give me the stable version and that there would be some kind of banner possibly to warn if you were on latest, just in case.

Thank you for the assistance, I'll close this ticket now. Looking forward to the new version release.
