### ISSUE TITLE
Remove multiple volumes

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#1157]
From docker cli, it can use `docker vollume rm foobar1 foobar2` to remove multiple volumes.

But in docker-py only can remove volume one by one.

**Comment by shin-** [comment]
The docker CLI just runs a loop removing each volume 1 by 1, see https://github.com/docker/docker/blob/master/api/client/volume/remove.go#L46-L53

Since it's not an API feature, I think it's reasonable to let the implementer handle that themselves.
