### ISSUE TITLE
Why isn't there an equivalent feature to `docker run --rm` ?

### ISSUE THREAD

**Issue by ironhouzi** [docker/docker-py#1163]
Having to manually remove the container requires async handling in order to wait for the container to stop. This isn't a big problem, but it would seem so much more intuitive and simple to just provide an `rm=True` parameter to `create_container()`.

**Comment by shin-** [comment]
It's not part of the API - it's a feature of the docker client. This has been discussed at length before: #77 #330 #870 #890

**Comment by dnephin** [comment]
The `rm` option was actually just moved to the server side: https://github.com/docker/docker/pull/20848

It will be in the engine 1.13 release, so API version 1.25
