### ISSUE TITLE
Support for stacks

### ISSUE THREAD

**Issue by ashishjain14** [docker/docker-py#1173]
While browsing through the code and documentation I have found  that client library currently doesn't support features like stack deploy, stack rm etc. This is something which is required to deploy a DAB generated by compose and would be required if we want to utilize the docker swarm mode.

Can you please advice what is plan around these newly added features is docker v1.12?

**Comment by kleptog** [comment]
There are various patches already merged for this I believe, see for example #1127 and #1147.

**Comment by shin-** [comment]
Hi @ashishjain14 , the commands you are referring to (`docker stack ...`) are actually handled by the docker CLI, meaning they are a client-side feature. Those commands then perform remote operations like creating services and managing tasks, which are implemented in the PRs @kleptog references.

Re-implementing those features in python might or might not be outside of the scope of `docker-py`. As of now, it is not on the immediate roadmap.

**Comment by approxit** [comment]
Any plans for release date docker-py with Docker Swarm mode from 1.12?

**Comment by shin-** [comment]
I'm not ready to commit to a date yet, but it should happen soon. In the meantime, the master branch is fairly solid so feel free to play around with it until then.

**Comment by ashishjain14** [comment]
Thanks @shin-  will try the master branch and get back.

**Comment by shin-** [comment]
1.10.1 is on pypi now!

**Comment by bfirsh** [comment]
Oops, see this also includes stack commands. Re-opening and renaming.

**Comment by xeor** [comment]
Based on the comment about stacks being implemented on the cli side. Will this issue then ever get resolved? Or is `subprocess.run()` the best way to do this for now?

**Comment by shoxxdj** [comment]
Any update about this feature ?

**Comment by craigt1212** [comment]
Any news regarding this issue?

**Comment by Sarniak1991** [comment]
Any plans regarding stack commands?

**Comment by matthewmrichter** [comment]
It's not very confidence inspiring for the future of Swarm if this does not get added..

**Comment by rnickle** [comment]
I just built a whole flow using the docker-py SDK, and I was expecting to implement stack deploy and was shocked when I found the support wasn't there.

**Comment by ferm10n** [comment]
It sounds like all the underlying actions `docker stack ...` commands perform are supported by docker-py (service creation and managing tasks). Maybe all we'd need to do is implement whatever logic is in the docker-cli and do yaml parsing here too?

(or uh, maybe call subprocess internally :sweat_smile:)

**Comment by dajose** [comment]
@ferm10n any luck with that approach?

**Comment by ndeloof** [comment]
docker-py project mission is to offer "A Python library for the Docker Engine API", not to re-implement the docker CLI in python.

**Comment by dajose** [comment]
@ndeloof so just close the issue :roll_eyes:

**Comment by gabrieldemarmiesse** [comment]
If you want some software that wraps the CLI for you in a pretty way, you can try https://github.com/gabrieldemarmiesse/python-on-whales . You'd use docker-py if you need to do low level things and you can use python-on-whales for high-level things (like stacks).

It all depends on your use case.
