### ISSUE TITLE
the command "echo 'test1 teip' >> test.txt" didn't run with using exec_create exec_start

### ISSUE THREAD

**Issue by fw0037** [docker/docker-py#1174]
the code in python is running below:
```
>>> from docker import Client
>>> cli = Client(base_url='unix://var/run/docker.sock')
>>> exec_instance=cli.exec_create(container='hello',cmd="/bin/echo 'test1 teip'>>/test.txt",user='root',tty=True)
>>> print exec_instance
{u'Id': u'4a5111b3d6fc5619e7279f926af4ca4c18c2a84f9bd6cb61f76d744260717b0c'}
>>> exec_id = exec_instance["Id"]
>>> print cli.exec_inspect(exec_id)
{u'OpenStderr': True, u'OpenStdout': True, u'ContainerID': u'077ca2bac756d71a0b84c97091154428fae170e1f84f396d846a4be920fa5739', u'DetachKeys': u'', u'CanRemove': False, u'Running': False, u'ProcessConfig': {u'user': u'root', u'tty': True, u'entrypoint': u'/bin/echo', u'arguments': [u'test1 teip>>/test.txt'], u'privileged': False}, u'ExitCode': None, u'ID': u'4a5111b3d6fc5619e7279f926af4ca4c18c2a84f9bd6cb61f76d744260717b0c', u'OpenStdin': False}
>>> data=cli.exec_start(exec_id, stream=True,detach=False)
>>> for line in data:
...     print line 
... 
test1 teip>>/test.txt

>>> 
```
but we didn't find the 'test1 teip' in the file text.txt, how could us to do with the command?

**Comment by fw0037** [comment]
docker -v
Docker version 1.11.2, build b9f10c9

 python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by shin-** [comment]
Can you clarify what you are trying to do? Is `test.txt` a file on your host, or inside the container? How would you accomplish the same thing with the docker CLI?

**Comment by fw0037** [comment]
Inside the container. I would running the command "/bin/echo 'test1 teip'>>/test.txt" to add  'test1 teip'  into the file /test.txt  inside the container with using docker CLI.  But I didn't find 'test1 teip'  exists in file test.txt.

**Comment by shin-** [comment]
For the indirection (`>>`)to be understood as part of the command, you need to pass it as an argument to `sh -c`, like so: `sh -c '/bin/echo test1 teip >> test.txt'`. This applies to the docker CLI and docker-py.

```python
from docker import Client
cli = Client(base_url='unix://var/run/docker.sock')
exec_instance=cli.exec_create(container='hello',cmd="sh -c '/bin/echo \'test1 teip\'>>/test.txt'",user='root',tty=True)
cli.exec_start(exec_id, stream=True,detach=False)

```

**Comment by fw0037** [comment]
Fine. Thanks.

**Comment by shin-** [comment]
Happy to help!
