### ISSUE TITLE
how could us to expose the ports like docker run command when create container with docker-py

### ISSUE THREAD

**Issue by fw0037** [docker/docker-py#1175]
the code like below:
cli.create_container(
  image="c-engine_webphere8.5/redhat6.5_jdk1.7",stdin_open=True,tty=True,command="/bin/bash",name="hello", ports=[8080,9043,9060,9085,9443], 
  host_config=cli.create_host_config(port_bindings="8080/tcp":[{"HostPort": 9100,"HostIp": "0.0.0.0"}],"9043/tcp":[{"HostPort": 9101,"HostIp": "0.0.0.0"}],"9060/tcp":[{"HostPort": 9102,"HostIp": "0.0.0.0"}],"9085/tcp":[{"HostPort": 9103,"HostIp": "0.0.0.0"}],"9080/tcp":[{"HostPort": 9104,"HostIp": "0.0.0.0"}])
)
c=cli.start(container='hello',port_bindings={"9085/tcp": [{"HostPort": 9103, "HostIp": "0.0.0.0"}],"9060/tcp": [{"HostPort": 9102, "HostIp": "0.0.0.0"}],"9043/tcp": [{"HostPort": 9101, "HostIp": "0.0.0.0"}],"8080/tcp": [{"HostPort": 9100, "HostIp": "0.0.0.0"}],"9443/tcp": [{"HostPort": 9104, "HostIp": "0.0.0.0"}]})

but the results is like below:
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                                                                                                    NAMES
4512cd736354        c-engine_webphere8.5/redhat6.5_jdk1.7   "/bin/bash"              38 seconds ago      Up 4 seconds        9100-9104/tcp, 0.0.0.0:9101->9043/tcp, 0.0.0.0:9102->9060/tcp, 0.0.0.0:9103->9085/tcp 

how could us to set the ports like below
0.0.0.0:9100->8080/tcp, 0.0.0.0:9101->9043/tcp, 0.0.0.0:9102->9060/tcp, 0.0.0.0:9103->9085/tcp, 0.0.0.0:9104->9443/tcp

**Comment by fw0037** [comment]
python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

**Comment by shin-** [comment]
You can find detailed information on port bindings [in our docs](http://docker-py.readthedocs.io/en/stable/port-bindings/). Let me know if that answers your question!

**Comment by fw0037** [comment]
I am referring to the docs to do, but the results of the implementation of the line when the results obtained with the command is inconsistent, I guess it is not brought under control container port by the file DockerFile .

**Comment by shin-** [comment]
You're definitely not using the syntax prescribed in the docs, and you're passing your port bindings in `start` as well, which is incorrect. Please review the documentation I linked to once more and make sure you're following the proper procedure.

**Comment by fw0037** [comment]
Yes, I found the ports list is incorrect. And now I get the results I want.

**Comment by shin-** [comment]
Glad you could solve it!
