### ISSUE TITLE
test output in xunit

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker-py#1176]
Is there a way to make the integration tests output in xunit format?  If not can we add at patch or some type of option to make this possible?

**Comment by dnephin** [comment]
There are a few options: http://stackoverflow.com/a/19126329/444646

I like the idea of using a `pytest` since it's an awesome test framework: http://doc.pytest.org/en/latest/usage.html#creating-junitxml-format-files

I believe docker-py already uses it as a test runner.

**Comment by crosbymichael** [comment]
Whatever tech is the best works for me as long as it produces xunit output ;)

Some background, we are working on getting this for jenkins to help the docker integration suite run in parallel and since the docker-py tests run during this it will have to produce the expected output of the rest of the test results.

**Comment by shin-** [comment]
@crosbymichael In `hack/make/test-docker-py`, you can change line 17 to something like
```sh
test_env PYTHONPATH="$dockerPy" py.test --junitxml=/path/to/results.xml "$dockerPy/tests/integration"
```

Does that answer your question?

**Comment by crosbymichael** [comment]
@shin- perfect thanks!
