### ISSUE TITLE
Change shared memory in container when creating a container via docker Client

### ISSUE THREAD

**Issue by SpheMakh** [docker/docker-py#1182]
The current version of docker allows the user to change the size of shared memory inside a container, via ```
docker run --shm-size
```
but the docker-py `Client.create_container()` does not support this yet. 

This is bound to happen again as docker adds more features, so maybe you should consider taking *args into `Client.create_container()` which would be parsed directly into the `docker run` command.

**Comment by shin-** [comment]
We do support it already. `shm_size` needs to be passed through the [HostConfig](http://docker-py.readthedocs.io/en/stable/hostconfig/).

**Comment by shin-** [comment]
#923
