### ISSUE TITLE
HostConfig not retrieved correctly for containers

### ISSUE THREAD

**Issue by tallandtree** [docker/docker-py#1193]
**Environment:**
python 2.7
docker_py 1.9.0
docker server/client Version: 1.12.1
docker server/client API: 1.24
OS: debian jessie/ubuntu 16.04

**Description**
The `container['HostConfig'] is not correctly read from docker container configuration.
In this example I have at least one container running, in which the host configuration contains port bindings and restart_policy.

**Reproducesteps**

```
python
>>> from docker import *
>>> cli = Client(base_url='unix://var/run/docker.sock')
>>> cli.containers()
>>> cli.containers()[0]['HostConfig']
{u'NetworkMode': u'default'}
```

Only HostConfig NetworkworkMode is set to default. Rest of the parameters are missing.

**Comment by shin-** [comment]
Hi!

This is what the Docker API returns. If you need to obtain more `HostConfig` data, you can do so using [`Client.inspect_container`](http://docker-py.readthedocs.io/en/stable/api/#inspect_container).

HTH!
