### ISSUE TITLE
Does a `ReadTimeoutError` mean there are no more `Client.stats(...)` to be collected?

### ISSUE THREAD

**Issue by michaelbarton** [docker/docker-py#1194]
Using the Client.stats(..., stream = True) command I occasionally get `ReadTimeoutError` and `StopIteration` errors. The `StopIteration` errors are to be expected however I am not sure how to handle the `ReadTimeoutError` errors, does this mean that there are no more stats to be collected and that I should treat it as `StopIteration` or that I should try and ignore the error and keep trying to get the `next()` item from the stats stream?

It seems from my intuition and experimentation that  `ReadTimeoutError` is equivalent to `StopIteration` for the case of collection container stats as I seem to get them almost interchangeably.

Could you also tell me how the stats stream is collecting data? It seems to collect at roughly ~1-2 second intervals and return them to the generator.

I am using OSX, Python 2.7.11, docker-py 1.8.1, Docker Version 1.11.2, Docker API version 1.23

**Comment by michaelbarton** [comment]
From reading the source code the default timeout for the docker-py client is 60 seconds. In #1009 it is described that the interval for stats collection is 1 second. Therefore should it be possible to collect 60 intervals of docker stats per minute or (as I assume might be the case) that the processing of the cgroup data that will push the time required to greater than one second?

**Comment by TomasTomecek** [comment]
Looks like this may be related to https://github.com/docker/docker-py/issues/1195.

**Comment by michaelbarton** [comment]
I will close this issue as #1195 describes the problem much better.
