### ISSUE TITLE
Multiple TCP connections to service port

### ISSUE THREAD

**Issue by GinoHereIam** [docker/docker-py#1209]
Hello!

I am running in Jenkins a matrix job. So 3 jobs trying to access my script which is running docker-py. All jobs running the same image "_myimage_" named like below with Ubuntu Xenial. Those jobs are running on the same Linux slave (Ubuntu Xenial), means they access the same service. Though, 1 of 3 jobs are running successfully. The other 2 jobs running in this issue:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.22/build?q=False&pull=False&t=myimage&nocache=False&forcerm=False&rm=False (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fedc89be8d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Is there an option to allow multiple TCP connections? Can't find anything in the docs. :(

Regards
Gino

**Comment by GinoHereIam** [comment]
Hi Tomas,
it's running from multiple processes.

**Comment by TomasTomecek** [comment]
And can you also post how you are running docker engine? Isn't it hidden behind a proxy by any chance?

**Comment by GinoHereIam** [comment]
Hi Tomas,

no no, there is no any proxies. Everything happens in same network.

the method looks like this:
```python
def CreateAndStart(self, image="tag/build_image:latest", stream=True):

        self.image = image
        self.stream = stream

        # Host specific parameters
        self.volumes = ['/ssd', '/opt', '/nfs']
        self.binds = ['/ssd:/ssd:rw', '/opt/:/opt:rw', '/nfs:/nfs:rw']
        Dockify.LOGGER.info("Create container!")
        self.container = self.cli.create_container(
            image=self.image, tty=True, volumes=self.volumes,
            host_config=self.cli.create_host_config(binds=self.binds))
        Dockify.LOGGER.info("Start container: %s", self.container)

        try:
            self.cli.start(container=self.container.get('Id'))
            if self.stream is True:
                res = [l for l in self.cli.logs(
                    self.container, follow=True, stdout=True,
                    stderr=True, stream=True)]
                Dockify.LOGGER.info("".join(res))
            else:
                Dockify.LOGGER.info("".join(self.cli.logs(
                    self.container, follow=True, stdout=True,
                    stderr=True, stream=False)))
            ret = self.cli.wait(self.container.get('Id'))
            sys.exit(ret)

        except (TypeError, RuntimeError, NameError) as ex:
            raise ex
```

**Comment by GinoHereIam** [comment]
@TomasTomecek you've got new information for me? Could you figure out the issue?

**Comment by TomasTomecek** [comment]
I'm sorry but that code is not helpful at all:

1. it's full of unrelated information
2. it's actually completely unrelated

Your exception in your original post states that connection to `/build` endpoint failed while code provided by you doesn't mention build in any way.

Please provide a minimal reproducer which we can copy and run on our machines.

**Comment by GinoHereIam** [comment]
The actual problem is that I have 3 Jobs which are trying to access the same URL as mentioned **at same time:**
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.22/build?q=False&pull=False&t=myimage&nocache=False&forcerm=False&rm=False`

All 3 jobs take the same image to build a container as I have shown the code above. I don't build a new image, I take the one which is already built. That's why I am confused it's unrelated information for you.  
As it looks for me the **endpoint doesn't take more than one TCP connection.** Which is pretty bad for us.

A minimal producer would be, you set up a Jenkins with the matrix plugin. In the matrix configuration are at least 2 configurations with same job. This job is what I do above with the Python. Each configuration run this job and try to a container with same image.

My set up:  
Jenkins  =>          Another host / Docker Service   =>  Back to Jenkins  
|  Job 1 &&  Job 2  |  => /build?q=False?t=myimage ...   => 1. Job Pass  | 2. Job Fail 

So it is no docker-py problem. Shall I open a ticket on the docker project site?

**Comment by TomasTomecek** [comment]
> So it is no docker-py problem. Shall I open a ticket on the docker project site?

Definitely.

I'm still really curious how is this even possible: with `docker` client you can build in parallel without any issues, so it may be possible that `docker-py` plays some role in this issue.

The way I would debug this: build a job that tries to access other URLs (e.g. `/version`); alternatively configure docker to listen on UNIX socket, not on a port (could this be the issue?); and finally: try parallel connection without jenkins (with `curl`, with `docker-py`). All these could narrow down the possibilities to the real cause.

**Comment by GinoHereIam** [comment]
Do you think parallel build shouldn't work?

**Comment by GinoHereIam** [comment]
To access the `/version` doesn't work as to trigger a long running job in docker. I saw that all jobs accessed `/version` in different. So they don't block each other in the connection. Do you have another idea to break the problem down?

**Comment by GinoHereIam** [comment]
:D found the issue ... the daemon was wrong configured on one slave but other one was fine. I hate systemd. Thanks for help!

**Comment by TomasTomecek** [comment]
Glad you solved it.
