### ISSUE TITLE
Client.create_service(networks=...) fails

### ISSUE THREAD

**Issue by approxit** [docker/docker-py#1212]
With `docker-py==1.10.2` trying to create service with networks settings fails with:

```
500 Server Error: Internal Server Error ("{"message":"json: cannot unmarshal string into Go value of type swarm.NetworkAttachmentConfig"}")
```

There is no documentation example how to handle it properly so i look for example in tests... Nothing.

Docker go sources defines [NetworkAttachmentConfig](https://github.com/docker/docker/blob/3ea762b9f6ba256cf51bd2c35988f0c48bccf0b0/api/types/swarm/network.go#L72) like dict of two keys.

Docker-py documentation states for `networks (list): List of network names or IDs to attach the service to. Default: None.` which is false and **untested**.

Temporary walkaround: 

```
Client.create_serivce(networks=[{'Target': 'some_network_name'}])
```

**Comment by shin-** [comment]
That's fair. I went by the description given here: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#create-a-service

But clearly this is incorrect.

**Comment by approxit** [comment]
Ow, I get it now... Totally misleading. It looks like every parameter need to be checked.

In `TaskTemplate` `placement` parameter suffers same situation.

```
500 Server Error: Internal Server Error ("{"message":"json: cannot unmarshal array into Go value of type swarm.Placement"}")
```

Temporary walkaround: 
```python
Client.create_service(
    task_template=TaskTeplate(
        placement={
            'Constraints': ['node.hostname==some_hostname']
        }
    )
)
```
