### ISSUE TITLE
Service Port Publishing Example

### ISSUE THREAD

**Issue by lllama** [docker/docker-py#1233]
Does the library support defining ports on a service? (i.e. with swarm) It looks like the endpoint_config parameter could be used for this but I can't see an example in the docs. (The general API docs also seem a little confused about how to define ports.)

**Comment by shin-** [comment]
We need to improve things on our end in terms of usability, but something like
```python
client.create_service(task_template, endpoint_config={
  'Ports': [
    { 'Protocol': 'tcp', 'PublishedPort': 8080, 'TargetPort': 80 },
  ]
})
```
should work, I think.

**Comment by lllama** [comment]
Unfortunately this doesn't seem to work for me. If I patch docker/api/service.py to use `EndpointSpec` instead of `Endpoint` then the other `Ports` example will work, however.

**Comment by shin-** [comment]
Yeah, I was unfortunately working with an outdated API documentation while implementing that feature. It seems it has been updated since and we need to fix the field's name in our request.

Thank you for reporting it.

**Comment by zhourunlai** [comment]
so now use ```endpoint_spec```  instead of  ```endpoint_config```(low-level api support), right?

```
client.create_service(task_template, endpoint_spec={
  'Ports': [
    { 'Protocol': 'tcp', 'PublishedPort': 8080, 'TargetPort': 80 },
  ]
})
```
