### ISSUE TITLE
Receiving -  docker.errors.APIError: 500 Server Error: Internal Server Error using get_image() function 

### ISSUE THREAD

**Issue by Paramhans** [docker/docker-py#1237]
Hello,

I am following official Dockerpy API documentation (https://docker-py.readthedocs.io/en/stable/api/#get_image) But after following exact same example, I cant get the image from the cloud. Receiving the following Error:

> docker.errors.APIError: 500 Server Error: Internal Server Error ("{"message":"reference does not exist"}")

I have also attached the screenshot. Is there something that I'm doing wrong ? or some problem is going on ?

![image](https://cloud.githubusercontent.com/assets/6920524/18982332/e5fab782-8702-11e6-9938-7c17e6da325e.png)

**Comment by shin-** [comment]
Did you pull `fedora:latest` before calling `get_image`? It needs to be available locally first.

**Comment by Paramhans** [comment]
Hey,
Thanks for your reply! Yes, the image was available locally. I was facing this problem because of my host machine weird behaviour, anyway, it is working now.
