### ISSUE TITLE
pids_limit not working

### ISSUE THREAD

**Issue by arkkanoid** [docker/docker-py#1238]
Hi, 
I've set a pids_limit paramater to 20. 
`host_config=cli.create_host_config(
            ...
        mem_limit='128m',
        mem_swappiness=0,
        cpu_shares=512,
        pids_limit=20)`
But the output in docker inspect is:  
`"PidsLimit": 0,`

Other parameters like mem_limit are working properly.
I'm using docker-py v1.10.3
docker client v1.12.1

**Comment by shin-** [comment]
I tried to reproduce the issue with the following code snippet, but wasn't able to:

```python
import docker

c = docker.from_env()
hc = c.create_host_config(pids_limit=20)
cid = c.create_container('busybox', 'true', host_config=hc)
c_data = c.inspect_container(cid)
assert c_data['HostConfig']['PidsLimit'] == 20
```

Can you try running this in your own environment and report back? Also, what OS / Python version are you using?

**Comment by arkkanoid** [comment]
I tried your code snippet running on ubuntu 14.04 and in a virtual machine with the same OS.
In both cases, after run the code the pid_limit is 0.
docker-py v1.10.3
docker client v1.12.1
Python 3.5.2

**Comment by pacoxu** [comment]
@arkkanoid 

I can not reproduce it with docker-py 1.10.3 as well.
>>> import docker
>>> c = docker.from_env()
>>> hc = c.create_host_config(pids_limit=20)
>>> cid = c.create_container('redis', 'true', host_config=hc)
>>> c_data = c.inspect_container(cid)
>>> assert c_data['HostConfig']['PidsLimit'] == 20
>>> assert c_data['HostConfig']['PidsLimit'] == 19
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

**Comment by CGNonofr** [comment]
According to the documentation (https://docs.docker.com/engine/reference/commandline/create/), pidsLimit only works with a kernel >= 4.3.
