### ISSUE TITLE
unable to push to AWS ECR

### ISSUE THREAD

**Issue by iverberk** [docker/docker-py#1246]
I'm trying to push an image to ECR but it fails with:

```
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

I believe this is because it tries to ping the registry and gets an unauthorized response from ECR. It's basically not sending any auth information with the request even though I logged in successfully. Regular Docker registry works because it doesn't require auth for a valid response. Can it be taken into account that ECR does not allow unauthorized requests to its v1/v2 ping endpoints? Thanks.

**Comment by TomasTomecek** [comment]
The error message is response from docker daemon, not from the registry. If you start your docker daemon with `--insecure-registry <hostname.with.port.to.the.registry>` it should fix the issue (since apparently it's running on `HTTP` not on `HTTPS`).

**Comment by iverberk** [comment]
@TomasTomecek thanks for your response! The AWS ECR registry is definitely not running on http (I tried that and it don't want to use it over http anyway) so setting that daemon option is not going to fix it I think. Also, I believe the response (HTTP error 40x) is actually coming from the registry (maybe proxied through the daemon). AWS might be using a custom implementation. I hope you can take another look at this. Thanks!

**Comment by shin-** [comment]
What version of docker-py are you using?

**Comment by TomasTomecek** [comment]
Could you please `curl -v https://<hostname:port>/v2/` the ECR endpoint?

This is what I get when using distribution:

```
$ docker run --net=host registry:2
...
::1 - - [06/Oct/2016:06:57:59 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.50.3"
```

```
$ curl -v http://localhost:5000/v2/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5000 (#0)
> GET /v2/ HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.50.3
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Thu, 06 Oct 2016 06:57:59 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{}%
```

A little followup to @shin-'s request: providing the code which is failing would be much appreciated.

**Comment by iverberk** [comment]
@TomasTomecek I get the following output:

```
curl -v https://123456789012.dkr.ecr.eu-west-1.amazonaws.com/v2/                                                                                                          +4282 9:04
*   Trying 54.77.217.207...
* Connected to 123456789012.dkr.ecr.eu-west-1.amazonaws.com (54.77.217.207) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.dkr.ecr.eu-west-1.amazonaws.com
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> GET /v2/ HTTP/1.1
> Host: 123456789012.dkr.ecr.eu-west-1.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 06 Oct 2016 07:04:41 GMT
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Basic realm="https://123456789012.dkr.ecr.eu-west-1.amazonaws.com/",service="ecr.amazonaws.com"
< Content-Length: 16
< Connection: keep-alive
<
Not Authorizied
* Connection #0 to host 123456789012.dkr.ecr.eu-west-1.amazonaws.com left intact
```
I've put a workaround in the library to not ping it starts with my URL id and then it works no problem. The distribution allows non-authorized requests to that endpoint, Amazon ECR does not. The docker-py version 1.2.3. Thanks for looking!

**Comment by TomasTomecek** [comment]
docker-py 1.2.3 is super ancient; please upgrade to latest version

```
$ pip install -U docker-py
```

**Comment by iverberk** [comment]
Very sorry about this. Apparently I have this ancient version on my local dev environment and was under the impression that it was latest (ran a pip install but it was already there it seems and I didn't notice). A fresh install on the server shows that this case has been accounted for. Sorry for the noise and thanks for looking.
