### ISSUE TITLE
How to change shared memory size in container when creating a container

### ISSUE THREAD

**Issue by fw0037** [docker/docker-py#1249]
the code is like below:
root@SZX1000137715:/var/lib/docker/rundata/c-engine/1.1.50.2/shell/docker-py-1.9.0# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docker import Client
>>> cli = Client(base_url='tcp://10.21.127.24:2375')
>>> c = cli.create_container(image="oracle_11g_r1/redhat6.5_jdk1.7", stdin_open=True, tty=True, command="/bin/bash", name="Common_Data_1.0.1.3",ports=[1521], host_config=cli.create_host_config(privileged=True,**shm_size =8589934592**,port_bindings={"1521/tcp":("0.0.0.0",8011)})) 
>>> c = cli.start(container='Common_Data_1.0.1.3', binds={}, port_bindings={"1521/tcp":("0.0.0.0",8011)})
>>> 

then I had created an container which named Common_Data_1.0.1.3, but when I logged in this container and input command "df -h", the shm_size didn't be changed, like below:

sh-4.1# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          493G   21G  447G   5% /
none            493G   21G  447G   5% /
tmpfs            16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/xvde1      493G   21G  447G   5% /etc/resolv.conf
/dev/xvde1      493G   21G  447G   5% /etc/hostname
/dev/xvde1      493G   21G  447G   5% /etc/hosts
**shm              64M     0   64M   0% /dev/shm**
tmpfs            16G     0   16G   0% /proc/kcore
tmpfs            16G     0   16G   0% /proc/latency_stats
tmpfs            16G     0   16G   0% /proc/timer_stats
tmpfs            16G     0   16G   0% /proc/sched_debug
sh-4.1# 

the docker version and python version is below:
root@SZX1000137715:/var/lib/docker/rundata/c-engine/1.1.50.2/shell/docker-py-1.9.0# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
root@SZX1000137715:/var/lib/docker/rundata/c-engine/1.1.50.2/shell/docker-py-1.9.0#python --version
Python 2.7.6

**how to change the size of shm_size (/dev/shm) to be 8G ?**

**Comment by pacoxu** [comment]
ShmSize - Size of /dev/shm in bytes. The size must be greater than 0. If omitted the system uses 64MB.

I think your system may not have enough memory. That's why you meet this issue.

Try 1 GB if your system can.

**Comment by shin-** [comment]
I can't reproduce the issue when using the same arguments on my machine. Can you try and run the following command: `docker run --shm-size 8G busybox df -h`? What size do you see then for `/dev/shm`?

**Comment by fw0037** [comment]
root@SZX1000137723:/opt/bin# docker run --shm-size 8G iquoter_s_webphere8.5/redhat6.5_jdk1.7 df -h
Filesystem     1K-blocks     Used Available Use% Mounted on
rootfs         515929528 24237548 465477632   5% /
none           515929528 24237548 465477632   5% /
tmpfs           16463404        0  16463404   0% /dev
tmpfs           16463404        0  16463404   0% /sys/fs/cgroup
/dev/xvde1     515929528 24237548 465477632   5% /etc/resolv.conf
/dev/xvde1     515929528 24237548 465477632   5% /etc/hostname
/dev/xvde1     515929528 24237548 465477632   5% /etc/hosts
**shm              8388608        0   8388608   0% /dev/shm**
tmpfs           16463404        0  16463404   0% /proc/kcore
tmpfs           16463404        0  16463404   0% /proc/latency_stats
tmpfs           16463404        0  16463404   0% /proc/timer_stats
tmpfs           16463404        0  16463404   0% /proc/sched_debug
root@SZX1000137723:/opt/bin# 

but when I create a new container with image  iquoter_s_webphere8.5/redhat6.5_jdk1.7, the container's shm size is already 64m.

root@SZX1000137723:~# docker exec -it 42633bf55408 /bin/sh
sh-4.1# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          493G   26G  442G   6% /
none            493G   26G  442G   6% /
tmpfs            16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/xvde1      493G   26G  442G   6% /etc/resolv.conf
/dev/xvde1      493G   26G  442G   6% /etc/hostname
/dev/xvde1      493G   26G  442G   6% /etc/hosts
**shm              64M     0   64M   0% /dev/shm**
tmpfs            16G     0   16G   0% /proc/kcore
tmpfs            16G     0   16G   0% /proc/latency_stats
tmpfs            16G     0   16G   0% /proc/timer_stats
tmpfs            16G     0   16G   0% /proc/sched_debug
sh-4.1#

**Comment by fw0037** [comment]
I found if I remove other fields when start the docker container with docker-py, it will be available. it's like below:

from docker import Client
cli = Client(base_url='tcp://10.21.127.24:2375')
c = cli.create_container(image="oracle_11g_r1/redhat6.5_jdk1.7", stdin_open=True, tty=True, command="/bin/bash", name="Common_Data_1.0.1.3",ports=[1521], host_config=cli.create_host_config(privileged=True,shm_size =8589934592,port_bindings={"1521/tcp":("0.0.0.0",8011)})) 
**c = cli.start(container='Common_Data_1.0.1.3')**

**Comment by shin-** [comment]
Oh yeah I missed that in your first post, sorry. [Do not pass any argument to `start` other than the container name / ID. It's deprecated and it doesn't work on newer engines.](https://github.com/docker/docker-py/issues/750)

**Comment by shin-** [comment]
By the way, I highly recommend you use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) when pasting code or console output in Github issues - it makes it much easier to read.

**Comment by fw0037** [comment]
the issue had been fixed. thanks.

**Comment by ujsyehao** [comment]
@fw0037 Can you tell me how to create a container which can set shared memory size?
