### ISSUE TITLE
NpipeSocket.makefile still crashes

### ISSUE THREAD

**Issue by shin-** [docker/docker-py#1251]
As reported here: https://github.com/docker/compose/issues/4012#issuecomment-253057779

**Comment by friism** [comment]
@shin- can you perhaps add a test for this? I'm also happy to help you test

**Comment by shin-** [comment]
@friism The problem is that we don't really have anything setup to do CI in a Windows + Docker environment, as far as I know. And the dependency on `win32file` and `win32pipe` makes it very difficult to do any sort of testing in other environments.

My manual tests on Windows didn't reveal the issue, either, so I'm not sure what exactly is causing this.

**Comment by HuanhuanSunMSFT** [comment]
$Env:DOCKER_HOST = "localhost:2375" fixes this issue though
