### ISSUE TITLE
[Question]Adding files to container

### ISSUE THREAD

**Issue by MTRNord** [docker/docker-py#1253]
I wanted to add files to an running container with my script. How can I do that?

**Comment by shin-** [comment]
You want to look at [`Client.put_archive`](http://docker-py.readthedocs.io/en/stable/api/#put_archive).

For an example of usage, you can refer to those [integration tests](https://github.com/docker/docker-py/blob/master/tests/integration/container_test.py#L524-L566)

**Comment by MTRNord** [comment]
I think that is what I did search :) thanks.
