### ISSUE TITLE
Setting replicas count for swarm service in 'replicated' mode

### ISSUE THREAD

**Issue by maq123** [docker/docker-py#1260]
Hi,

as far I can see there is no support to set the actual of replicas a deployed service would have.

As per https://docker-py.readthedocs.io/en/latest/services/ , I can select the mode but no way to specify the copies count...

**Comment by shin-** [comment]
Try `mode={'Replicated': {'Replicas': n}}`

Sorry the docs is misleading about that part. I'll look into fixing it.

**Comment by kshenk1** [comment]
👍  Just ran into this myself.
