### ISSUE TITLE
test_only_uses_tls: failure on Fedora with 1.10.4

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker-py#1265]
So I was updating docker-py in Fedora land to `1.10.4` and this happened during the RPM build process:

```
tests/unit/ssladapter_test.py:27: in test_only_uses_tls
    assert ssl_context.options & OP_NO_SSLv2
E   AssertionError: assert (2181170175L & 0)
E    +  where 2181170175L = <ssl.SSLContext object at 0x3ffa4cbdde8>.options
```

https://kojipkgs.fedoraproject.org//work/tasks/2344/16112344/build.log

Since we unbundle urllib3 from requests it could be the issue. Or some system default changed. Didn't have time to dig through.

Creating the issue just to see if any other distros bumped into this.

**Comment by shin-** [comment]
That's odd, that test has been here for a while - why would it start failing now?
