### ISSUE TITLE
_stream_helper within Client.py occasionally fails to parse chunked data

### ISSUE THREAD

**Issue by mobiuscog** [docker/docker-py#1280]
I've encountered a situation on a limited number of machines where, when performing a build with heavy stdout, something about the JSON encoding from the daemon makes the _stream_helper fail with invalid JSON.

I've attached a test python file and Dockerfile, which if placed in their own directory would reproduce the problem on a couple of machines. I've also included the monkey-patch fix (uncomment line 19) which demonstrates, using examples from elsewhere, how it may be possible to change _stream_helper, although I suspect this may cause backwards compatibility issues, so may not be a valid fix.

Unfortunately, I can't actually reproduce this problem on most of my machines - just a couple of Windows machines in a restricted environment. However, as the patch _does_ fix the problem on those machines, it suggests it's not completely the environment that is the issue.

[bugtest.zip](https://github.com/docker/docker-py/files/560357/bugtest.zip)

The easiest solution in this case was to remove the -v from the tar command, but I felt I should raise the issue as I had a code change that mitigated it.

HTH.

**Comment by shin-** [comment]
I believe this is now handled properly thanks to `docker.utils.json_stream`
