### ISSUE TITLE
Add support for storage opts in `container_create`

### ISSUE THREAD

**Issue by jbweston** [docker/docker-py#1300]
Since Docker 1.12 (after [this pull request](https://github.com/docker/docker/pull/19367) was merged)
it is possible to pass `--storage-opt size=<size>` to `docker create` in order to set the size of the root filesystem of a container.

As far as I can tell this feature is not yet available in `docker-py` (I have grepped the docs and looked at the arguments of [`create_host_config`](https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L624) and [`create_container_config`](https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L1033))

Will this feature be added at some point / would anyone be available to answer questions about a possible implementation?

**Comment by robottwo** [comment]
Second for this feature.
