### ISSUE TITLE
don't require backports.ssl_match_hostname on Python 2.7.9+

### ISSUE THREAD

**Issue by carlwgeorge** [docker/docker-py#1318]
The entirety of Python 3.4's ssl module was [backported into Python 2.7.9](https://www.python.org/downloads/release/python-279/).  I believe this means that docker-py's requirement condition (< 3.5) on backports.ssl_match_hostname is slightly inaccurate.  A Python 2.7.9 user doesn't need the backports.ssl_match_hostname dependency.

* https://github.com/docker/docker-py/blob/6a16edee3e7110e0439ef067e5c11db51bd4371a/requirements.txt#L4
* https://github.com/docker/docker-py/blob/6a16edee3e7110e0439ef067e5c11db51bd4371a/setup.py#L23

Unfortunately, the main code that imports match_hostname is doing an import based on the Python version.  It would be more sane to use a try except like the test suite does.

* https://github.com/docker/docker-py/blob/6a16edee3e7110e0439ef067e5c11db51bd4371a/docker/ssladapter.py#L20-L21
* https://github.com/docker/docker-py/blob/6a16edee3e7110e0439ef067e5c11db51bd4371a/tests/unit/ssladapter_test.py#L4-L11

Please update docker-py such that backports.ssl_match_hostname isn't installed on systems that don't need it (Python 2.7.9+).

P.S. On a similar note, should the PY3 minimum be 3.4, not 3.5?

**Comment by TomasTomecek** [comment]
This is a very similar answer I provided on [Red Hat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1399804#c1).

Unfortunately ssl module in python 2.7.{9,10} is not on par with ssl in 3.5: it doesn't support `serverAltName` matching:

 * https://hg.python.org/cpython/file/2.7/Lib/ssl.py#l249
 * https://hg.python.org/cpython/file/3.5/Lib/ssl.py#l263
 * cherry-picked code in [backports.ssl_match_hostname](https://bitbucket.org/brandon/backports.ssl_match_hostname/commits/a8ef5d616d92405a4a74fbcb4bf026cf4d18f030?at=default)

More info: https://bugzilla.redhat.com/show_bug.cgi?id=1229409#c9

So we can't do this yet :/

**Comment by shin-** [comment]
Thanks Tomas!

I'm going to close this for the time being. If the feature makes it into older Python versions at one point we can revisit this.
