### ISSUE TITLE
'ProtocolError('Connection aborted.', error(99, 'Cannot assign requested address'))'

### ISSUE THREAD

**Issue by dineshputchala** [docker/docker-py#1346]
bash-4.1$ docker -v
Docker version 1.12.3, build 6b644ec

Installed pip using below command,

yum install --nogpgcheck python-pip

bash-4.1$ pip install docker-py
Collecting docker-py
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(99, 'Cannot assign requested address'))': /simple/docker-py/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(99, 'Cannot assign requested address'))': /simple/docker-py/

Could you tell me how to resolve above errors?

**Comment by shin-** [comment]
Are you able to `pip install` anything else? Most likely there's an issue with your network setup.

**Comment by dineshputchala** [comment]
other command with pip as also facing same issue , I will check this issue in pip forum !
thanks !
