### ISSUE TITLE
How to get Env Variables List?

### ISSUE THREAD

**Issue by gcavalcante8808** [docker/docker-py#1349]
Hello Folks,

I'm trying to create an Low Level Discovery for Zabbix that automatically 'discover' the address of a container that have a virtualhost (through the VIRTUAL_HOST env variable normally used by the jwilder nginx-proxy image), but i can't figure out how to do it with the current library. How can I achieve this?

Thanks in advance.

**Comment by shin-** [comment]
`client.inspect_container(ctnr_id)['Env']` would do the trick, if I understand correctly what you're asking.
