### ISSUE TITLE
Regarding interactive /bin/bash using exec

### ISSUE THREAD

**Issue by fjhaveri** [docker/docker-py#1357]
Is it possible to do interactive bash using docker-py exec command as docker cli support ?

**Comment by shin-** [comment]
Yes. See https://github.com/d11wtq/dockerpty that does that.

**Comment by fjhaveri** [comment]
Is this supported for windows 7 ?

**Comment by james-knott** [comment]
dockerpty does not work anymore. Any other way to connect interactively with python?
