### ISSUE TITLE
Ability to stop docker-py.events() generator from another thread?

### ISSUE THREAD

**Issue by approxit** [docker/docker-py#1358]
When we want to listen for live docker events with docker-py we have 2 options:

- Fetch events with time limits like `since` and `until`. If `until` is the future date, code is blocking until we meet that date (but not pass over). Minimal time resolution for `since` and `until` is one second.

- Fetch events live without time limits. Generator is blocking until some event pops out.

In projects based on for eg. Python Twisted, we have single event loop thread. We can't run blocking queries, because we don't want to block whole application. That's why we execute blocking code in threads. Each 2 options I mentioned above we have problems.

- Fetching events without time limits can't be stopped. And when whole application is closing, thread is still running, so Twisted waits forever for ~thread.join. We have 0 control over generator, because it uses internal waits for some events. We can't use a variable to tell thread that is should be still running. We are totally stuck.

- We are forced to use fetching with time limits. We want to get events live, so we make smallest possible time chunks. Even smallest chunks gives us up to 1 second delay, so it's not live. I don't even mention about logic to manage that chunked fetching.

Two scenarios are bad.

Is there something that I'm not aware of, or we really can''t do much more?

**Comment by TomasTomecek** [comment]
I'm using `threading.Event` for that: https://github.com/TomasTomecek/sen/blob/24dcbb63ca1dd9af2247f0cd25074dc41b27fc52/sen/tui/views/main.py#L63 https://github.com/TomasTomecek/sen/blob/24dcbb63ca1dd9af2247f0cd25074dc41b27fc52/sen/tui/views/main.py#L44

**Comment by approxit** [comment]
@TomasTomecek Thanks for response.

Yes, threading.Event WOULD do the job, but [browsing your code](https://github.com/TomasTomecek/sen/blob/fc1ac27e8839cced643d7081eba362a06cd7cb75/sen/docker_backend.py#L785) I think you're getting to point I wrote about:
> Fetch events live without time limits. Generator is blocking until some event pops out.

So yes, you are using theading.Event, but it will stop that thread [as soon as new event arrives](https://github.com/TomasTomecek/sen/blob/fc1ac27e8839cced643d7081eba362a06cd7cb75/sen/tui/init.py#L45) and you will [return to your code that can check threading.Event](https://github.com/TomasTomecek/sen/blob/fc1ac27e8839cced643d7081eba362a06cd7cb75/sen/tui/init.py#L55). Not earlier.

Browsing even more I've finally found [this stackoverflow question](http://stackoverflow.com/questions/33688000/stop-docker-py-events-stream-iteration) which answer would work. A little dirty hack... @shin- any chances to make it a little more official?

**Comment by TomasTomecek** [comment]
Would be nice if this was part of docker-py -- ability to shut down the generator.

I agree that you have to wait for next event to pop up. I don't mind that in my application and certainly understand when this is not acceptable in your application.

**Comment by approxit** [comment]
In version 2 of `docker-py` we have `attach_socket` in container methods. Socket-like object would be a just right for this issue with events.

@shin-, any chances to make `events_socket` method?

**Comment by rycus86** [comment]
@approxit this should now be done in https://github.com/docker/docker-py/pull/1965, thanks to @shin-
