### ISSUE TITLE
Swarm tests fail if host has multiple network interfaces

### ISSUE THREAD

**Issue by bboreham** [docker/docker-py#1359]
```
__________________ ERROR at setup of ServiceTest.test_create ___________________
tests/integration/models_services_test.py:14: in setUpClass
    client.swarm.init(listen_addr=helpers.swarm_listen_addr())
docker/models/swarm.py:96: in init
    self.client.api.init_swarm(**init_kwargs)
docker/utils/decorators.py:35: in wrapper
    return f(self, *args, **kwargs)
docker/api/swarm.py:102: in init_swarm
    self._raise_for_status(response)
docker/api/client.py:208: in _raise_for_status
    raise create_api_error_from_http_exception(e)
docker/errors.py:30: in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
E   APIError: 500 Server Error: Internal Server Error for url: http://172.17.0.1:12375/v1.24/swarm/init ("could not choose an IP address to advertise since this system has multiple addresses on different interfaces (10.0.2.15 on enp0s3 and 192.168.48.11 on enp0s8)")
```

**Comment by shin-** [comment]
Thank you for the report. We mostly run our tests inside containers (`make integration-dind`) but it's still worth looking into for sure.

**Comment by saifulhoque26** [comment]
In model/swarm.py, the client.api.init_swarm(**init_kwargs) method is being called without advertise_addr. That's where the problem is. If there is multiple interface advertise_addr  (or interface) should be given.

`        init_kwargs = {}
        print kwargs
        for arg in ['advertise_addr', 'listen_addr', 'force_new_cluster']:
            print arg
            if arg in kwargs:
                print arg
                init_kwargs[arg] = kwargs[arg]
                print kwargs[arg]
                del kwargs[arg]
        init_kwargs['swarm_spec'] = SwarmSpec(**kwargs)
        print init_kwargs
        self.client.api.init_swarm(**init_kwargs)
        self.reload()`

**Comment by bboreham** [comment]
@saifulhoque26 it seems to be tricky to code this for arbitrary test environments.

Perhaps the test should be skipped if multiple interfaces are present?
