### ISSUE TITLE
support request: testing client code that uses docker(-py) 2

### ISSUE THREAD

**Issue by funkyfuture** [docker/docker-py#1369]
after updating to the new sdk, i haven't figured out how to test client code that makes use of the new api, in particular how to mock the low-level `APIClient` properly.

here's a reduced example how i tested my code before the update. note, that this uses `pytest-mocker`, a wrapper around the `mock` library. (addendum: i also tried using `mock` directly, resulting in the same issues)

```python
def test_options(value, result, mocker):
    labels = {'deck-chores.options': value}
    mocker.patch('deck_chores.config.Client.inspect_container',
                 return_value={'Image': '', 'Config': {'Labels': labels}})
    assert parse_labels('container_id') == result
```

the `deck_chores.config` module is where the docker client is instantiated that is used all around the client code.

i tried different things to mock `DockerClient.api.inspect_container` resp. `APIClient.inspect_container`, but none worked. looking at the unittests of the sdk itself, it doesn't seem to be trivial. are there any guidelines how to update tests or how client code should be tested?

**Comment by funkyfuture** [comment]
to elaborate a little more.

to get the labels to parse (within `parse_labels` above), the code called `client.inspect_container`, now it calls `client.api.inspect_container`.

my first approach was to mock like this: 

```python
mocker.patch('deck_chores.config.DockerClient.api.inspect_container',
             return_value={'Image': '', 'Config': {'Labels': labels}})
```

which yields this error:

```
thing = <class 'docker.client.DockerClient'>, comp = 'api'
import_path = 'deck_chores.config.DockerClient.api'

    def _dot_lookup(thing, comp, import_path):
        try:
            return getattr(thing, comp)
        except AttributeError:
>           __import__(import_path)
E           ImportError: No module named 'deck_chores.config.DockerClient'; 'deck_chores.config' is not a package
```

indeed, that is a module (where `DockerClient` is imported), not a package. so, i don't get the error message, my guess is this is due to the fact that the `api` attribute is bound when the client is initialized.

the next try is this what follows the paradigm 'mock where it is used' that worked so far for me.

```python
mocker.patch('docker.api.client.ContainerApiMixin.inspect_container',
             return_value={'Image': '', 'Config': {'Labels': labels}})
```

which evokes this when `client.api.inspect_container` is called:

```
self = <docker.client.DockerClient object at 0x7f9fe4441390>, name = 'api'

    def __getattr__(self, name):
        s = ["'DockerClient' object has no attribute '{}'".format(name)]
        # If a user calls a method on APIClient, they
        if hasattr(APIClient, name):
            s.append("In Docker SDK for Python 2.0, this method is now on the "
                     "object APIClient. See the low-level API section of the "
                     "documentation for more details.")
>       raise AttributeError(' '.join(s))
E       AttributeError: 'DockerClient' object has no attribute 'api'
```

no idea what's going on here.

----

my guess is that mocking a less complex assembled class would work. in my case that would need an `image` and a `labels` property on `models.containers.Container` and the latter also on `models.images.Image`. that seems feasible to me anyway. shall i go for it? (yep, other models would have labels too).

**Comment by shin-** [comment]
Assuming you already had / have code that works with docker-py 1.x, I would simply use the `APIClient` class directly instead of going through a new layer of indirection with `DockerClient`. There doesn't appear to be a good reason in my mind to invoke `DockerClient.api.inspect_container` versus `APIClient.inspect_container`.
This would have the side-benefit of leaving your test-suite mostly intact (apart from some basic `Client -> APIClient` rename, I imagine)

**Comment by funkyfuture** [comment]
for two reasons i'd rather not want to do this:

- i'm using methods on a `DockerClient` instance anyway
- i couldn't use `from_env` to get an instance of an `APIClient`

essentially i would rather use the 1.x than using a seemingly partly redundant api.

regarding the last thoughts in my previous post: would there be a problem to add higher-level access to the mentioned properties? in my understanding these are missing anyway. but maybe there was a reason to not include them in the models.

**Comment by PriyaT113** [comment]
Hai,
 I'm working on mock unit test for docker client voumes create.

class TestVolumes(TestBase):
    @mock.patch('docker.from_env')
    def test_create_docker_volume(self,client_volumes_create):
        client_volumes_create.return_value.volumes.create.return_value="test"
        client_volumes_create().volumes.create.assert_called_with(name="test",drive"loacl",driver_opts={})
output:
AssertionError: Expected call: create(driver_opts={}, driver='local', name='test')
Not called
Please help me
