### ISSUE TITLE
AttributeError: 'module' object has no attribute 'from_env'

### ISSUE THREAD

**Issue by JordanSussman** [docker/docker-py#1370]
Currently on OS X El Capitan 10.11.6

```
$ pip freeze | grep docker && python --version && docker version
docker==2.0.0
docker-compose==1.7.0
docker-py==1.8.1
docker-pycreds==0.2.1
dockerpty==0.4.1
Python 2.7.11
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
```

Attempting to run test file with contents of:

```
import docker
client = docker.from_env()
```

Following error:
```
$ python docker.py
Traceback (most recent call last):
  File "docker.py", line 1, in <module>
    import docker
  File "/Users/docker.py", line 3, in <module>
    client = docker.from_env()
AttributeError: 'module' object has no attribute 'from_env'
```

**Comment by narenst** [comment]
@JordanSussman I'm running into the same issue, did you happen to figure out the cause?

**Comment by adeslade** [comment]
@narenst Looks like there was a file named `docker.py` which was being imported instead of the docker library.

**Comment by narenst** [comment]
Thanks @adeslade. Turns out I had a previous installation of docker-py 1.10.6 installed in the same virtualenv. It was not enough to just uninstall it, I had to recreate my env. It worked after that.

**Comment by aftabnaveed** [comment]
For me the main fail was the same as  the main docker module. Renaming it worked for me.

**Comment by lianjy357** [comment]
You can rename the file name from "docker.py" to another name, such as "dockers.py", which may have an effect.
你将文件名修改从“docker.py”重命名成其他的名字，如“dockers.py”，或许就有效果。

**Comment by caio-vinicius** [comment]
Solution: the name of the file need to be different from "docker.py"

**Comment by HZ2PP** [comment]
I faced the same issue. I find that I named my python file as 'docker.py', which would mislead the python compiler to import package from my own 'docker.py' but not from the docker package. Hope that be useful to you. Good luck!

**Comment by kenorb** [comment]
Related: #1743.
