### ISSUE TITLE
How to get exec_run exit_code?

### ISSUE THREAD

**Issue by nctustartup** [docker/docker-py#1381]
Hi,

I create an ubuntu container and then running ```exec_run``` later. But I can not get the exit_code. ```exec_run``` just return output bytecode. I don't know whether the executing result is successful or not.

```
>>> import docker
>>> client = docker.from_env()
>>> container = client.containers.run('ubuntu', command=['/bin/bash'], tty=True, detach=True)
>>> container.exec_run(['not_exist'])
b'rpc error: code = 2 desc = oci runtime error: exec failed: exec: "not_exist": executable file not found in $PATH\r\n'
>>>
```

I can use ```APIClient.exec_create(), APIClient.exec_start() and APIClient.exec_inspect()``` to achieve the goal. Is there has any high level api to use?

Thanks for your reply.

**Comment by ariaviran** [comment]
I also encountered this issue.
It appears there is no high-level API for this

**Comment by shin-** [comment]
Yes, this is something we need to figure out. Thanks for bringing it to our attention.

**Comment by roidelapluie** [comment]
Opened PR #1495

**Comment by funkyfuture** [comment]
imo, with the next breaking release `Container.exec_run` should return two values in that order: the exit code and the tty stream, if `stream` is `False`.

**Comment by shin-** [comment]
@mitar Use the low-level API for this. There's no way for the client to detect reliably when the exec command has stopped running in an asynchronous manner

**Comment by ClaytonSmith** [comment]
Hope this helps: 
```
exec_handle = docker_client.exec_create(...)
stream = docker_client.exec_start(exec_handle, stream=True)

# Stream handling

docker_client.exec_inspect(exec_handler['Id']).get('ExitCode') 
```

**Comment by funkyfuture** [comment]
meanwhile the API provides [`Container.exec_run`](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.exec_run) that is solving the problem.

**Comment by timini** [comment]
[Container.exec_run](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.exec_run) does not solve the problem, since it cannot return stream and exit code at the same time
