### ISSUE TITLE
client.images.list() and RepoTags = []

### ISSUE THREAD

**Issue by kixiro** [docker/docker-py#1401]
<pre>
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'2.0.1'
>>> cli = docker.from_env()
>>> cli.images.list()
[<Image: ....
....
..., Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 16, in __repr__
    return "<%s: '%s'>" % (self.__class__.__name__, "', '".join(self.tags))
  File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 34, in tags
    tag for tag in self.attrs.get('RepoTags', [])
TypeError: 'NoneType' object is not iterable
>>>

**Comment by leroygr** [comment]
Same issue for me with version `2.0.1`

**Comment by bfirsh** [comment]
Fix is in #1393

**Comment by shin-** [comment]
Closing via #1393
