### ISSUE TITLE
Push new version to Pypi

### ISSUE THREAD

**Issue by jocelynthode** [docker/docker-py#1406]
It would be great to upgrade the version on Pypi as well

**Comment by ZelphirKaltstahl** [comment]
Will this still be done? Is there a reason this has been closed? Maybe some policy, which prevents upgrading it on PyPI?

**Comment by jocelynthode** [comment]
@ZelphirKaltstahl : It was a mistake on my part. the pypy repository for docker-py changed as they now call it "docker" so you have to use the docker repo on pypy and install "docker" from pip to get the 2.0 version as it is writtent in the README.md. [Here](https://pypi.python.org/pypi/docker/) is the repo.

I think there should still be a redirection of some sort on the docker-py repository of pypy to point to the new version.

**Comment by ZelphirKaltstahl** [comment]
@jocelynthode Thanks! I initially searched on PyPI for `docker-py` immediately before going to the GIT repository.

**Comment by bfirsh** [comment]
Yeah, that should be clearer. Sorry about that.

https://github.com/docker/docker-py/issues/1431
