### ISSUE TITLE
Newbie question about container.list()

### ISSUE THREAD

**Issue by elacheche** [docker/docker-py#1416]
Hey!

I was checking the list method from [conainters.py in models](https://github.com/docker/docker-py/blob/master/docker/models/containers.py), as I can see it calls the [containter.py from api](https://github.com/docker/docker-py/blob/master/docker/api/container.py)..

When executing the list method you'll get the running containers IDs, if I understand the code well, when "--quiet" is set to True, it should return IDs only, however, that option is always False, so why you get the containers IDs and not the Names?

**Comment by elacheche** [comment]
No one is checking issues?

**Comment by bfirsh** [comment]
I'm not sure I understand what your question is. Could you clarify / reword?

**Comment by elacheche** [comment]
Thanks fr the reply

Why when I use the [list() method](https://github.com/docker/docker-py/blob/master/docker/models/containers.py#L721)  it returns only the containers IDs, if we compare it with docker ps:

- docker ps --quiet=false returns id + name + other info
- docker ps --quiet=true returns id only

The quiet arg in [here](https://github.com/docker/docker-py/blob/master/docker/api/container.py#L131) is always False, so why it returns only the ID, also why *if quiet:* in there, is there other methods that use that and can change it to True? because the list() method can't do that..

**Comment by shin-** [comment]
The `list()` method returns a list of `Container` objects. All of them hold a complete set of information about the container in their `.attrs` member.

See http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container

**Comment by elacheche** [comment]
Thank you.. My bad, didn't understand well what was written in the docs..
