### ISSUE TITLE
put_archive - must specify all data options

### ISSUE THREAD

**Issue by vmindru** [docker/docker-py#1422]
put_archive is using requests.Session.put in the background, the doc must state all options that can be passed as data.

from http://docs.python-requests.org/en/master/api/

`data -- (optional) Dictionary, bytes, or file-like object to send in the body of the Request.`

**Comment by ijc** [comment]
Looks like this proposal was rejected in https://github.com/docker/docker-py/pull/1423#issuecomment-275771000, closing.
