### ISSUE TITLE
Update docker-py PyPI package to point at new package

### ISSUE THREAD

**Issue by bfirsh** [docker/docker-py#1431]
[The old package name is causing confusion.](https://github.com/docker/docker-py/issues/1406)

https://pypi.python.org/pypi/docker-py should have a big notice pointing at here: https://pypi.python.org/pypi/docker

**Comment by niels-bom-md** [comment]
Ah hell yeah that was confusing 😕.

I contacted the PyPI package's maintainer, let's hope he responds :-)

https://twitter.com/niels_bom/status/850361509800800256

**Comment by orodbhen** [comment]
Please fix this. Very confusing.

**Comment by shin-** [comment]
[Fixed](https://pypi.python.org/pypi/docker-py)
