### ISSUE TITLE
Question regarding new HostConfig setup

### ISSUE THREAD

**Issue by twllight** [docker/docker-py#1434]
Hello,

I'm migrating my docker-py code to 2.0.0 and have been looking for an answer as to how to migrate my host config creation. Here is what I have so far:
`
 host_config = HostConfig(privileged     = True, 
                              dns                  = ship_opts['cont_dns'],
                              dns_search     = ship_opts['cont_search'],
                              mem_limit      = ship_opts['cont_memory'][0],
                              port_bindings  = forwarded_ports,
                              network_mode   = ship_opts['cont_network_type'],
                              binds          = mount_points,
                              restart_policy = {"MaximumRetryCount": 5, "Name": "always"})
`
I'm getting an error with the creation of the HostConfig:

Error in host_config creation: __init__() takes at least 2 arguments (9 given)

I've imported the docker.types above:

from docker.types import ( IPAMConfig, IPAMPool, HostConfig )

And I can view the HostConfig object. What am I missing here I'm sure it's something silly.

Thank you

**Comment by twllight** [comment]
I forgot to add my docker-py version:
docker==2.0.2
python:
Python 2.7.5

**Comment by twllight** [comment]
Ah I found the issue, HostConfig now requires an api version parameter sent to it. Sorry about the noise!

**Comment by shin-** [comment]
FWIW, you can also use `client.api.create_host_config()` which will fill in the version for you.
