### ISSUE TITLE
image build error on master with docker 1.12.6

### ISSUE THREAD

**Issue by SebastienDorgan** [docker/docker-py#1450]
Hello,
ImageCollection.build regex error check is wrong with docker 1.12.6 API, you can fix it this way:
________________________________________________________
        if 'stream' in event:
            match = re.search(r'(Successfully built |sha256:)([0-9a-f]+)',
                              event.get('stream', ''))
            if match:
                image_id = match.group(2)
                return self.get(image_id)
____________________________________________________________
Regards,
Sébastien Dorgan

**Comment by shin-** [comment]
Thanks! Integrated that fix in #1460

**Comment by sdorgancs** [comment]
Glad this help :)
