### ISSUE TITLE
print win32pipe.NMPWAIT_NOWAIT

### ISSUE THREAD

**Issue by asierra01** [docker/docker-py#1456]
I think they change the variable name, so the file npipesocket.py, needs to update the code line 179 to self._timeout = win32pipe.NMPWAIT_NOWAIT
I was running script and it error me out on settimeout(0)

**Comment by shin-** [comment]
What version of pypiwin32 is installed in your environment? `pip freeze | grep pypiwin32` to find out.  It should be `219`.

**Comment by asierra01** [comment]
it looks that's what I have c:\python27\lib\site-packages\pypiwin32-219-py2.7-win-amd64.egg\win32pipe.pyd. Let me do more research. I notice you guys do make test, let me see if the test cover something like 
....
         isinstance(command_output,docker.transport.npipesocket.NpipeSocket) == True:
           print command_output.gettimeout()
           command_output.settimeout(0)
....
