### ISSUE TITLE
Set network mode on image build

### ISSUE THREAD

**Issue by diego-treitos** [docker/docker-py#1457]
I need to set the network mode to `host` when building an image. From command line I can do this with `docker build --network host .` but I dont see any option in `docker-py` to do this in http://docker-py.readthedocs.io/en/2.0.2/api.html#module-docker.api.build.

Could this option be added ?

**Comment by philtay** [comment]
Duplicate of https://github.com/docker/docker-py/issues/1397

**Comment by diego-treitos** [comment]
You are right @philtay. I couldn't find any reference to this problem but this is clearly a duplicate. I am closing it.
