### ISSUE TITLE
how to specify dependency on docker-py v1 and v2?

### ISSUE THREAD

**Issue by jizhilong** [docker/docker-py#1476]
As the pypi project name for docker-py changed from `docker-py` to `docker` since release 2.0, how should I write a version specifier looks like `docker-py >= 1.8.1, < 2.2`?

**Comment by TomasTomecek** [comment]
Right now, it's impossible to do such thing in `requirements.txt`.

You could potentially pin to `docker` in `requirements.txt`, while in `setup.py`, you could check what version of `docker-py` is already installed -- and if there is none, pin to latest.

Anyone has a better idea?
