### ISSUE TITLE
The options 'detach' and 'remove' cannot be used together

### ISSUE THREAD

**Issue by al3xdelarge** [docker/docker-py#1477]
The options 'detach' and 'remove' are not conflicting in current versions of docker.

Lines in  docker-py/docker/models/containers.py can be removed.
```
        if detach and remove:
            raise RuntimeError("The options 'detach' and 'remove' cannot be "
"used together.")
```

**Comment by nsteinmetz** [comment]
I would agree but noticed that for old version of docker (like the one in Debian), I think it's still the case. You can't have both.

With recent versions, I agree you can use both.

**Comment by ztlpn** [comment]
Workaround for this and #1579 (checked with docker-py=2.2.1 and docker API v.1.27)
```python
client = docker.from_env()
image = client.images.get('hello-world')
host_config = client.api.create_host_config(auto_remove=True)
container_id = client.api.create_container(image.id, detach=True, host_config=host_config)['Id']
container = client.containers.get(container_id)
container.start()
```

**Comment by shin-** [comment]
Closing via #1545
