### ISSUE TITLE
images.list() on Swarm always returns intermediate images even if called with 'all=False' (default)

### ISSUE THREAD

**Issue by ppizzo** [docker/docker-py#1487]
images.list(all=True) and images.list(all=False) work as expected on a local Docker engine.

But if I execute the same commands against a Swarm cluster, I always get all images including intermediate ones, regardless of the value of the parameter 'all' (which should be set to False by default, by the way).

I create the client by loading Swarm env variables before starting Python and then using docker.from_env() statement.

I'm using the latest Docker version to date (client API 1.26, server API 1.25). Tried to change API version from 1.21 to 1.25 but the result is still the same: I cannot get the list of images without getting also the intermediate layers in the output.

The official docker client works as expected: I get the intermediate images only if I pass the '-a' switch to 'docker images'.

**Comment by shin-** [comment]
That's weird - that endpoint is pretty standard. What version of Swarm are you using? What version of the SDK?

**Comment by ppizzo** [comment]
Hi, many thanks for your answer. My Docker version is as follows:
```
Client:
 Version:      1.13.1-cs1
 API version:  1.25 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:53:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.1.0
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   009d87a
 Built:        Thu Feb  9 00:47:21 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I think I'm using the latest stable version because I installed it with `pip3 install docker` on a Python 3 container based on the latest Alpine stable release.

I've also tried to run run the script on the physical engine (i.e. not in a container) and the result is still the same: I get all images, even the intermediate layers not tagged which are skipped by default by `docker images`.

**Comment by ppizzo** [comment]
Any progress on this? In the meanwhile I've upgraded to 1.13.1-cs2 but still no luck. There's no way to remove intermediate levels from APIs.

```
Client:
 Version:      1.13.1-cs2
 API version:  1.25 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   ad32da7
 Built:        Thu Feb 23 16:38:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.1.0
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   009d87a
 Built:        Thu Feb  9 00:47:21 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by shin-** [comment]
Belated update if anyone's still watching - this is a Swarm issue and can't be resolved at the client level.
