### ISSUE TITLE
 container id only 10

### ISSUE THREAD

**Issue by jameyang** [docker/docker-py#1491]
# code:
print client.containers.list(all=True)
print docker.version

# output:
[<Container: 4ba3e59b9f>, <Container: fc5d8c6f28>, <Container: 72b6c75141>, <Container: 42685100cd>, <Container: 1d383bbd99>]
2.1.0

This is container id only 10 ? 
Here is my docker host container ID
# docker ps -a -q
4ba3e59b9fed
fc5d8c6f2845
72b6c751412a
42685100cdbc
1d383bbd9958

**Comment by ppizzo** [comment]
Based on the output you posted, the results look identical: 5 containers with Python API, 5 container with native Docker client. Also the IDs are the same.

So, what's the problem?

**Comment by jameyang** [comment]
@ppizzo, hi.   This is docker-py get container id is 10 number. Actually the container id is 12 number.
<Container: 4ba3e59b9f>  === 4ba3e59b9fed

**Comment by ppizzo** [comment]
@jameyang, now I understand: you were talking about the number of digits.
That's just an abbreviated representation. Actually internal IDs are even more longer than 10 or 12 digits. If you inspect the containers you should be able to see the complete IDs (64 digits if I remember well)

**Comment by jameyang** [comment]
@ppizzo , sorry , i don't say clear .  that's it.

this is my code:

import docker
docker_host = 'tcp://172.28.250.59:1234'
client = docker.DockerClient(base_url=docker_host)
print client.containers.list()

this is output:

![image](https://cloud.githubusercontent.com/assets/12868951/23534365/64aeccae-fff2-11e6-922d-084eab6787a3.png)

but, actually container id is this:
![image](https://cloud.githubusercontent.com/assets/12868951/23534411/b8baba7e-fff2-11e6-9d59-65d60a7c7afc.png)

docker-py get id two fewer than it actually was

**Comment by jameyang** [comment]
@ppizzo , hi, i found the reason. 
this is file:  docker\models\resource.py

    @property
    def short_id(self):
        """
        The ID of the object, truncated to 10 characters.
        """
        return self.id[:10]

edit it : 

    @property
    def short_id(self):
        """
        The ID of the object, truncated to 10 characters.
        """
        return self.id[:12]

now is ok.
