### ISSUE TITLE
[2.1.0] auto_remove : unexpected keyword argument

### ISSUE THREAD

**Issue by nsteinmetz** [docker/docker-py#1504]
Hi,

Trying 2.1.0 version, I tried the following syntax:

```
dc.containers.run(image, command=command, detach=True, name=task['name'], volumes=volumes, auto_remove=True)
```
But I got:
```
Traceback (most recent call last):
  File "dtcli.py", line 116, in <module>
    main()
  File "dtcli.py", line 113, in main
    dc.containers.run(image, command=command, detach=True, name=task['name'], volumes=volumes, auto_remove=True)
  File "/home/nsteinmetz/.virtualenvs/datatask2/lib/python2.7/site-packages/docker/models/containers.py", line 657, in run
    detach=detach, **kwargs)
  File "/home/nsteinmetz/.virtualenvs/datatask2/lib/python2.7/site-packages/docker/models/containers.py", line 700, in create
    create_kwargs = _create_container_args(kwargs)
  File "/home/nsteinmetz/.virtualenvs/datatask2/lib/python2.7/site-packages/docker/models/containers.py", line 879, in _create_container_args
    raise create_unexpected_kwargs_error('run', kwargs)
TypeError: run() got an unexpected keyword argument 'auto_remove'
```

Whereas the [doc](https://docker-py.readthedocs.io/en/stable/containers.html) says it should exist:

>>>
auto_remove (bool) – enable auto-removal of the container on daemon side when the container’s process exits.
>>>

**Comment by nsteinmetz** [comment]
Indeed, `auto_remove` in not in one of the two lists: https://github.com/docker/docker-py/blob/master/docker/models/containers.py#L778-L850 and so the error is raised as this keywork is not managed by one of the configuration filters above.

**Comment by shin-** [comment]
Thanks for the report! Looks like the same issue as #1497 .

You should be able to use `remove` instead to the same effect.

**Comment by nsteinmetz** [comment]
Hi @shin- 

Oups indeed, I search one issues but not on PR - my bad.

So now my point is #1477 

Thanks,
Nicolas

**Comment by KingAlawaka** [comment]
Hi, 
This is not an issue, but since I am getting the same error, I will post my question here. 
I want to pass some arguments to my python script when executing 

`container1 = client.containers.run('cont_image',remove=True, detach=True,name='cont1',a="first",b="second")`

Can anyone help me with the correct way to pass the arguments (a and b) to my container python script?
Thanks in advance,
Pasindu
