### ISSUE TITLE
Force Remove volume

### ISSUE THREAD

**Issue by PlayMa256** [docker/docker-py#1506]
Calling version on APIClient returns 1.24 as api version.

`client = docker.APIClient(base_url='unix://var/run/docker.sock')`
`client.version()`
```
{u'ApiVersion': u'1.24',
 u'Arch': u'amd64',
 u'BuildTime': u'2016-10-26T21:39:14.007365648+00:00',
 u'GitCommit': u'6b644ec',
 u'GoVersion': u'go1.6.3',
 u'KernelVersion': u'3.16.0-4-amd64',
 u'Os': u'linux',
 u'Version': u'1.12.3'}
```
Following the documentation,  remove_volume can have a force option on it. 
`remove_volume(name, force=False)`

But when you call it, you get: **force removal was introduced in API 1.25**

I installed docker using pip, following docs. Is this a bug?

**Comment by shin-** [comment]
See http://docker-py.readthedocs.io/en/stable/api.html
> version (str) – The version of the API to use. Set to `auto` to automatically detect the server’s version. Default: `1.24`

If you know your Engine supports 1.25 (you can find out using `docker version`), you can instantiate `APIClient` with the appropriate `version` param.
Or use `auto`.
