### ISSUE TITLE
docker py usage

### ISSUE THREAD

**Issue by SergeyPirogov** [docker/docker-py#1509]
According to documentation to start using docker py I need to write:

docker-py (1.10.6)

```
import docker
cli = docker.from_env()
cli.containers.run("ubuntu", "echo hello world")
```
but doing that, I am getting an error:

```
cli.containers.run("ubuntu", "echo hello world")
AttributeError: 'function' object has no attribute 'run'
```

What the hell?

**Comment by shin-** [comment]
You're reading the documentation for the Docker Python SDK (`docker>=2`) but using the legacy docker-py  library (`docker-py==1.10.6`). The documentation for the version you're currently using is [here](http://docker-py.readthedocs.io/en/1.10.4/), but please upgrade (`pip uninstall docker-py ; pip install docker`) when you get the chance!

**Comment by SergeyPirogov** [comment]
Well it will be great to mention this somewhere it the Readme.

**Comment by shin-** [comment]
We already do: https://github.com/docker/docker-py#installation

**Comment by SergeyPirogov** [comment]
Oh yes, sorry and thank you for your help.

**Comment by shin-** [comment]
No problem :+1: Thank you for your patience!
