### ISSUE TITLE
docker info command

### ISSUE THREAD

**Issue by SergeyPirogov** [docker/docker-py#1513]
I can't find api methon that is similar to docker inspect <container hash>. Could you please help?

**Comment by shin-** [comment]
Are you using the low-level API (`APIClient`) or high-level API (`DockerClient`)?

**Comment by SergeyPirogov** [comment]
I want to use newer api, but if it's not possible I am ok to use APIClien

**Comment by shin-** [comment]
Check out the `attrs` attribute on the `Image`, `Container`, `Network` and `Volume` objects.

- http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.attrs
- http://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.Image.attrs
- http://docker-py.readthedocs.io/en/stable/networks.html#docker.models.networks.Network.attrs
- etc.
