### ISSUE TITLE
Add support for floats in "since" kwarg on logs().

### ISSUE THREAD

**Issue by mccalluc** [docker/docker-py#1515]
The [documentation](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.logs) is clear:
> since (datetime or int) – Show logs since a given datetime or integer epoch

but it's easy for someone to overlook that and pass in something based on a float from `time.time()` and `since` will just be ignored. Would a PR that supported any number or a datetime be welcome?

```
django-docker-engine==0.0.1
docker==2.1.0
docker-pycreds==0.2.1
Python 2.7.13 :: Continuum Analytics, Inc.
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by shin-** [comment]
Yes - I agree it shouldn't be ignored. Raising an error if a float is provided would be the appropriate course of action.

**Comment by fopinappb** [comment]
I know this has been closed long time ago, but maybe it should be revisited as apparently the API does support floats (for added - and useful - precision).

https://github.com/moby/moby/issues/41784#issuecomment-822371593
