### ISSUE TITLE
EndpointSpec has Target and Published ports the wrong way round?

### ISSUE THREAD

**Issue by david-terrett** [docker/docker-py#1516]
2.1.0 Python 3.4.5 Docker 1.12.6

I am attempting to create an end point with the published port set to zero so that Docker will assign the published port but, although the dictionary passed to EndpointsSpec is documented as having TargetPort as the keys and PublishedPort as the values, the code in convert_service_ports appears to have them the other way round.

**Comment by johannespostler** [comment]
I can confirm this in the following setup:

Docker version 17.09.0-ce
Python 3.6.3
docker-py 2.7.0

**Comment by ijc** [comment]
This appears to have been fixed with https://github.com/docker/docker-py/commit/f85f31a91a908771a70cffc89b7af36be921627d (by switching the docs over)
