### ISSUE TITLE
Cannot wait blocking generator output from events()

### ISSUE THREAD

**Issue by ColinHuang** [docker/docker-py#1523]
Since upgrade to `docker 2.2.0`. 

API 'events()' using same API client time out. 
So I got `UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.` exception message.

But in my use case, `containers()` or other client APIs are reasonable to set an default timeout.
But `events()` should have another timeout setting for users.

**Comment by shin-** [comment]
Ah, right, that's going to be an issue. Thank you for reporting it!
