### ISSUE TITLE
Ask: Is there a way to change scale/replicas of an existing service

### ISSUE THREAD

**Issue by edmBernard** [docker/docker-py#1538]
Is there a way to change scale/replicas of an existing service ?
The docker cli command is `docker service scale SERVICE=NUMBER` but i don't find the equivalent in docker-py.

**Comment by shin-** [comment]
You can use [`Service.update`](http://docker-py.readthedocs.io/en/stable/services.html#docker.models.services.Service.update) or [`APIClient.update_service`](http://docker-py.readthedocs.io/en/stable/api.html#docker.api.service.ServiceApiMixin.update_service) with an updated [mode `ServiceMode`](http://docker-py.readthedocs.io/en/stable/api.html#docker.types.ServiceMode) attribute.

**Comment by edmBernard** [comment]
I try to use APIClient : 
```python
serv= client.services.list()[0]
docker.APIClient.update_service(serv.id, version=serv.version+1, mode=docker.types.ServiceMode("replicated", replicas=3))
```

and I got this error : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/docker/utils/decorators.py", line 29, in wrapper
    if utils.version_lt(self._version, version):
AttributeError: 'str' object has no attribute '_version'
```

**Comment by shin-** [comment]
`APIClient` is a class. It needs to be instantiated.

**Comment by edmBernard** [comment]
I got it to work : 

```python
client = docker.from_env()                                 
serv = client.services.list()[0]
serv.update(name=serv.name, command="replicas", args=["2"])
```

thx for your help
