### ISSUE TITLE
Swarm mode service create --with-registry-auth

### ISSUE THREAD

**Issue by rogergithub3** [docker/docker-py#1541]
When I create service, how can I put --with-registry-auth parameter?

**Comment by pacoxu** [comment]
you need login the docker repo first and then create service with registry auth.

> docker login daocloud.io

> docker service create --with-registry-auth -p 80  daocloud.io/daocloud/dao-2048:latest

**Comment by rogergithub3** [comment]
Thank you, if I try your code it's working, but I'm using docker sdk for python (https://docker-py.readthedocs.io/en/stable/).

My code:
```
client.login(username=username, password=password, registry=host)
client.services.create("image")
```
I want to pass to create() the parameter "--with-registry-auth" that's a option parameter in docker doc (https://docs.docker.com/engine/reference/commandline/service_create/#options)

When I create service, how can I put --with-registry-auth parameter?

**Comment by pacoxu** [comment]
auth is a header for creating service

You can just try this and the service can be run successfully.
> import docker
> client = docker.DockerClient(base_url='unix://var/run/docker.sock')
> client.login('admin', 'admin' , registry='https://registry_ip/')
> client.services.create("registry_ip/daocloud/dubbo")


And if you don't login, you will get error like 
> import docker
> client = docker.DockerClient(base_url='unix://var/run/docker.sock')
> client.services.create("registry_ip/daocloud/dubbo")

`g0tkajlos1h9   \_ infallible_kowalevski.1  registry_ip/daocloud/dubbo  HOST  Shutdown       Rejected 18 seconds ago  "No such image: registry_ip…"`

**Comment by rogergithub3** [comment]
Great. Thank you.

**Comment by frankli0324** [comment]
this is not an appropriate answer. if you login on the master node, and create a service on a slave node, you will get the same answer.
