### ISSUE TITLE
"infinite" waiting with exit_status = container.wait()

### ISSUE THREAD

**Issue by antoineVerlant** [docker/docker-py#1555]
Hello everyone, 
While I was running an container via the client.containers.run() function I had a trubble because I never had any return from this function.
Looks like the problem was the line 671 
`exit_status = container.wait()`
I waited for at least 10 minute, and nothing happened.
I don't need logs for now so I just set `detach=True` to avoid the problem.
I don't know why it happened but I guess I should tell you this.

**Comment by shin-** [comment]
Thank you for the report. I'm assuming you started a long-running container, like a server? In which case using `detach=True` makes a lot of sense.
What behavior did you expect to see instead?

**Comment by antoineVerlant** [comment]
Yes, a long running container (odoo container), so I should have logs. I have logs when I do the docker logs command manually.
In my case it's not a problem.

**Comment by shin-** [comment]
Yes - for long-running processes, either use `detach=True` or [`create`](http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.create) + [`start`](http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.start).
