### ISSUE TITLE
Does `for line in docker_container.logs(stream=True):` assures I read one line at a time?

### ISSUE THREAD

**Issue by danechitoaie** [docker/docker-py#1564]
Does `for line in docker_container.logs(stream=True):` assures I read one line at a time?
Sometimes it seems I read parts of a line and not a full line.

Is there any way to make sure I read a full line (or EOF) until I process the output? As I need to read it one full line at a time to be able to strip the ANSII escape chars.

**Comment by shin-** [comment]
Sorry, there is no such guarantee.
