### ISSUE TITLE
Network.connect() (and disconnect()) should take "**kwargs"

### ISSUE THREAD

**Issue by ysong-skyhook** [docker/docker-py#1569]
The Network.connect() only accepts 'container' as input args. It should accept other args as called out in the comment section, and pass them to the underlying APIClient (NetworkApiMixin).connect_container_to_network() (which accepts them).

**Comment by andrewreece** [comment]
Agreed - in particular, the `force` argument in `Network.disconnect()` would be useful to have available.

**Comment by shin-** [comment]
Fixed by #1573
