### ISSUE TITLE
images.build fails when using tag argument.

### ISSUE THREAD

**Issue by andyneff** [docker/docker-py#1577]
When using the `tag` kwarg on `client.images.build`, it will always throw a Build Error.

The api.build output looks like this

```
['{"stream":"Step 1/4 : FROM scratch\\n"}\r\n',
 '{"stream":" ---\\u003e \\n"}\r\n',
 '{"stream":"Step 2/4 : LABEL com.nvidia.volumes.needed \\"nvidia_driver\\"\\n"}\r\n',
 '{"stream":" ---\\u003e Using cache\\n"}\r\n',
 '{"stream":" ---\\u003e 36ec3942c5f5\\n"}\r\n',
 '{"stream":"Step 3/4 : SHELL /usr/local/nvidia/bin/nvidia-smi\\n"}\r\n',
 '{"stream":" ---\\u003e Running in f875d54529eb\\n"}\r\n',
 '{"stream":" ---\\u003e b750cf87aed6\\n"}\r\n',
 '{"stream":"Step 4/4 : CMD -L\\n"}\r\n',
 '{"stream":" ---\\u003e Running in f3f9e21b8171\\n"}\r\n',
 '{"stream":" ---\\u003e 61c46a80da73\\n"}\r\n',
 '{"stream":"Successfully built 61c46a80da73\\n"}\r\n',
 '{"stream":"Successfully tagged 5b3bc129-d296-4b7d-872c-bc7117d4f327:latest\\n"}\r\n']
```

The problem can be tracked down to [here](https://github.com/docker/docker-py/blob/2.2.1-release/docker/models/images.py#L164-L167). The code is assuming the "Successfully built" comes last, however in the tag case, this is not true.

Two ideas are to either 

1. Search the last two lines
2. Or in case that is not enough, search all the lines for "Successfully built"

I'm using docker server 17.05.0-ce-rc1

**Comment by shin-** [comment]
Thank you for the report!

**Comment by joebloggs12** [comment]
Is there a way to pass the tag without using the `tag` kwarg? Or perhaps to somehow stop the Build Error from being thrown?

**Comment by andyneff** [comment]
@joebloggs12 To work around it, I tagged the version after building in a separate command. But it look like #1581 will solve this problem once and for all when it is released.
