### ISSUE TITLE
Pull image with tag fails

### ISSUE THREAD

**Issue by biran0079** [docker/docker-py#1585]
library version: 2.2.1
docker version: 1.23
Repro steps:
- remove busy box images if any
- pull busy box image with tag = 1
`docker.from_env(version='auto').images.pull('busybox', tag='1')`
Gives
`docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: busybox")`

**Comment by shin-** [comment]
Thanks for the report. See my comment there for a workaround: https://github.com/docker/docker-py/issues/1548#issuecomment-297853720
