### ISSUE TITLE
Simultaneous detach and remove not supported

### ISSUE THREAD

**Issue by illera88** [docker/docker-py#1594]
Hi,

Detach (-d) and remove(--rm) options are not simultaneously supported by the python API but no longer conflict as of docker version 1.13.0. [See here in the code.](https://github.com/docker/docker-py/blob/master/docker/models/containers.py#L679)

There was a pull request that moves the --rm option daemon-side and allows for running containers detached with the removal option: https://github.com/docker/docker/pull/20848

Do you think you can remove that API restriction?

Cheers

**Comment by illera88** [comment]
I think this is not a duplicated. The problem is that both parameters can't be used simultaneously not that the `auto_remove` parameter is actually `remove`.

What is the duplicate issue?

**Comment by shin-** [comment]
#1477
