### ISSUE TITLE
Following suggestions for image.save results in really slow saves

### ISSUE THREAD

**Issue by BrendanDrewZippy** [docker/docker-py#1595]
I'm trying to write out an image which has a modest number of unionfs layers (5) and which is pretty small when I do docker image ls (~200MiB). The code I use to save the image looks like this:

```py
    with open(outputImageFileName, 'wb', buffering=0) as outputImage:
        with deployImage.save() as imageBytes:
            for chunk in tqdm(imageBytes, leave=True, miniters=1):
                outputImage.write(chunk)
```

Saving the image this way takes well upwards of 28 minutes on a brand new MacBook pro with plenty RAM and big SSD whereas from the command line it is nearly instant. 

For what it's worth, when I tried to do a little detective work, I found that the current version of urllib3 has arguments to the call to `stream` which, amongst other things, makes [it possible to control the size of chunks being transferred](http://urllib3.readthedocs.io/en/latest/reference/#urllib3.response.HTTPResponse.stream); however, this interface does not appear to be supported on the  object that are returned by `Image.save()`

**Comment by BrendanDrewZippy** [comment]
More info:

```
python --version
Python 3.6.1
```

installed via homebrew, pip freeze shows

```
appdirs==1.4.3
docker==2.2.1
docker-pycreds==0.2.1
gitdb2==2.0.0
GitPython==2.1.3
packaging==16.8
pyparsing==2.2.0
requests==2.14.0
six==1.10.0
smmap2==2.0.1
tqdm==4.11.2
virtualenv==15.1.0
websocket-client==0.40.0
```

**Comment by shin-** [comment]
As pointed out in our [docs](http://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.Image.save), You should call `stream()` on `imageBytes` and iterate on that.

```python
In [6]: img = c.images.get('docker/compose:1.13.0')

In [7]: f = open('/tmp/compose.tar', 'w')

In [8]: resp = img.save()

In [10]: for chunk in tqdm.tqdm(resp.stream(), leave=True, miniters=1):
    f.write(chunk)
   ....:     
300it [00:00, 4722.71it/s]

In [11]: f.close()

In [12]: f = open('/tmp/compose.tar', 'w')

In [13]: resp = img.save()

In [14]: for chunk in tqdm.tqdm(resp, leave=True, miniters=1):
    f.write(chunk)
   ....:     
71273it [01:25, 837.72it/s]

**Comment by BrendanDrewZippy** [comment]
D'oh. Sorry about that -- should have caught that. Thanks!
