### ISSUE TITLE
Integration test for service_logs fails

### ISSUE THREAD

**Issue by andyneff** [docker/docker-py#1597]
The test_service_logs integration test fails when I run it locally.

## Docker version

```
Client:
 Version:      17.05.0-ce-rc2
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   c57fdb2
 Built:        Thu Apr 27 08:19:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce-rc2
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c57fdb2
 Built:        Thu Apr 27 08:19:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I'm not sure if this is even a concern for the project, it's just that since I am using an RC of docker right now, apparently the experimental flag is turned on (ExperimentalBuild is True) for me (not that I want it to even test service_logs). And thus this test is run (unlike on the CI servers I believe). So running `make test` for me locally always fails because of this.

The problem appears to be that instead of getting the expected result of `hello\n` its empty instead, the so `next(logs)` actually throws a StopIteration exception

**Comment by shin-** [comment]
Looks like an engine breakage... that test definitely works with 17.04.0.
