### ISSUE TITLE
Get a build error with a message saying image is successfully taged.

### ISSUE THREAD

**Issue by antoineVerlant** [docker/docker-py#1601]
Hi,
While I build an image with image = client.images.build(...) I get this error :
```
Build Error:
{u'stream': u'Successfully tagged cornichon:latest\n'}
```
Like you see it's not an error as long as the message says is successfully build. I can use a workaround to catch the error but I still think it shoudn't be one.
Thanks for your support

**Comment by shin-** [comment]
See #1577

It'll be fixed in the next release.
