### ISSUE TITLE
Shared memory size when creating service

### ISSUE THREAD

**Issue by sasavilic** [docker/docker-py#1608]
Hi, 

how can I specify shared memory size when creating docker service? When using cli tools, I have used so far `--mount type=tmpfs,destination=/dev/shm,tmpfs-size=<size>`, but it seams that class Mounts only allow bind or volume. And class Service specifies that mounts should be in form `src:dst:opts`. 

I am missing something or is this feature currently not supported?

**Comment by shin-** [comment]
The [`docker.types.Mount`](https://docker-py.readthedocs.io/en/stable/api.html#docker.types.Mount) class provides everything that's needed now.
