### ISSUE TITLE
Wrong default argument (--rm=False) for docker build

### ISSUE THREAD

**Issue by Dids** [docker/docker-py#1609]
When running `docker build`, it (by default) removes intermediate containers if they succeeded, otherwise it leaves them behind. This is achieved by Docker internally setting `--rm=true` when building. You can verify this [here](https://docs.docker.com/engine/reference/commandline/build/).

The issue with `docker-py` is that it defaults to `--rm=false`, meaning it always leaves the intermediate containers, which, in addition to not being default behavior, is highly annoying to have to cleanup, especially when using `docker-py` with third party software, where there's no direct control over `docker-py`.

The fix is to simply set `rm=False` to `rm=True` here:
https://github.com/docker/docker-py/blob/master/docker/api/build.py#L17

**Comment by Dids** [comment]
Here's a quote from the file above:
```
rm (bool): Remove intermediate containers. The ``docker build``
                command now defaults to ``--rm=true``, but we have kept the old
                default of `False` to preserve backward compatibility
```

Do you still need to maintain compatibility? If so, there needs to be a better way to do so, instead of breaking compatibility with _new_ defaults.

**Comment by shin-** [comment]
This behavior is intentional and documented. I'm not sure what the issue is here.

**Comment by Dids** [comment]
The issue is that it's not removing intermediate containers by default, since it's not using the default value. To me, it'd make more sense to use default `docker build` values everywhere, even if it means dropping support for older Docker versions. I'll work around this for now, I guess.

**Comment by asottile** [comment]
Hitting this as well, is there a good reason for the inconsistency with cli `docker build`?
