### ISSUE TITLE
Question about stream flag when building image

### ISSUE THREAD

**Issue by danqing** [docker/docker-py#1610]
[This section of the docs](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build) says:

> **stream (bool)** – Deprecated for API version > 1.8 (always True). Return a blocking generator you can iterate over to retrieve build output as it happens

However, if I attempt to run something like:

```py
docker.images.build(path='docker/example/', tag='example', stream=True)
```

It is blocked until the image is built, and returns the image then.

What's a "blocking generator" and how is it supposed to be used?

Thanks!

**Comment by danqing** [comment]
[This](https://github.com/docker/docker-py/blob/master/docker/models/images.py#L166) seems to be the function. I don't see how `stream` plays any role here. It delegates to the low-level API but whether `stream` or not doesn't seem to affect how this method itself behaves. It intercepts the stream and does not return until the stream is over (effectively making it non-stream), iiuc.

**Comment by danqing** [comment]
anyone here? if this is an official project then the lack of support (or response) is a bit astonishing.

**Comment by shin-** [comment]
It's just a mistake in the documentation. `stream` has no effect on the high-level API.

**Comment by danqing** [comment]
So instead of "always true" it's actually "always false", correct?

**Comment by shin-** [comment]
Well no, it's always true in the sense that the logs are streamed in the background and processed to retrieve the image object that is then returned by the high-level API. As we mention higher in the docstring,

> If you want to get the raw output of the build, use the `build` method in the low-level API.

**Comment by haizaar** [comment]
May be the Return section [the docs](https://docker-py.readthedocs.io/en/stable/images.html) should clarify that image/logs are returned after build is done. Currently it mentions word "generator" and for those of us who migrate from older lower-level API (`docker.from_env().api.build(...)`) there is a place for confusion.
