### ISSUE TITLE
Updating a service seemingly needs all arguments

### ISSUE THREAD

**Issue by thomaco** [docker/docker-py#1611]
To update a service, one would expect to just run the update command on a service object, e.g. like this;
```
client = docker.from_env()
service = client.services.get('app')
service.update(mode={'Replicated': {'Replicas': i}})
```

This results in the following error:

> docker.errors.APIError: 500 Server Error: Internal Server Error ("rpc error: code = 2 desc = changing network in service is not supported")

However, the following command worked;
`service.update(name=service.name, mode={'Replicated': {'Replicas': i}}, networks=attrs['Spec']['Networks'])`

I would expect that when I run service.update(), it only updates the variables I'm sending to the command, and fetching the rest of the values from the existing service object. Am I correct in that currently, one has to be sure that all variables are sent to the update command, even those that are not updated?

**Comment by shin-** [comment]
#1521 #1503
