### ISSUE TITLE
service is not ready after return 

### ISSUE THREAD

**Issue by badbye** [docker/docker-py#1627]
When I create a new service using the `services.create` API, it returns an object immediately, the containers are not really ready.

Here is an example:
```
>>> service = client.services.create(**kwargs);service.tasks()   # nothing here
[]
>>> service.tasks()   # now it is ready
[{u'Slot': 1, u'Status': '...'}]
```
How could I ensure that the tasks are ready when the `service` object is returned.

**Comment by shin-** [comment]
We return a value as as soon as we receive a response from the API endpoint. As far as I know, there's no way to wait for the service to be "ready".
