### ISSUE TITLE
docker.client.from_env should support default tls option

### ISSUE THREAD

**Issue by biran0079** [docker/docker-py#1635]
`docker.DockerClient` allow `tls` param to set to `True` to use default options, but there is no way to configure `docker.client.from_env` to do similar thing.

**Comment by grahamlyons** [comment]
In that instance the configuration is taken from the environment, as described here: https://docs.docker.com/engine/security/https/

i.e. you can set `DOCKER_TLS_VERIFY`, `DOCKER_HOST`, and `DOCKER_CERT_PATH` and they'll be handled.

It's mentioned in the documentation - http://docker-py.readthedocs.io/en/latest/tls.html?highlight=configured+automatically+from_env() - but the specifics are in the main Docker docs, linked above.

**Comment by biran0079** [comment]
I see. Thanks for explanation!
