### ISSUE TITLE
Service Create do not have "replicas" option

### ISSUE THREAD

**Issue by saifulhoque26** [docker/docker-py#1638]
hi All, 

Thanks for good work. I tried to create a service using docker-py. 

But, client.services.create do not accept '--replicas' as a parameter. 

Error I get is: TypeError: create() got an unexpected keyword argument 'replicas'

Thank you

**Comment by qasim9641** [comment]
Did anyone solve this issue ?

**Comment by shin-** [comment]
```python
import docker

client = docker.from_env()
replica_mode = docker.types.ServiceMode('replicated', replicas=4)
client.services.create(mode=replica_mode, ...)
```
