### ISSUE TITLE
Fail to get port mapping with Service

### ISSUE THREAD

**Issue by osallou** [docker/docker-py#1651]
python *docker* version: 2.3.0
docker version: Docker version 17.03.1-ce, build c6d412e
OS: Debian GNU/Linux 8.6 (jessie)

Hi,
I try to create a service (and succeeds), but when I add port mapping, I have no error, but result/task shows no port mapping (checked with docker inspect on task).

After the  client.services.create(...), if I display returned Service object attrs I have:

    {
        u'Endpoint': {u'Spec': {}},
        u'ID': u'a5wss5r4jqecjezr0pk5g3nuv',
        u'Version': {u'Index': 476},
        u'UpdatedAt': u'2017-06-16T13:57:27.420376205Z',
        u'UpdateStatus': {u'StartedAt': u'0001-01-01T00:00:00Z', u'CompletedAt': u'0001-01-01T00:00:00Z'},
        u'Spec': {u'Mode': {u'Replicated': {u'Replicas': 1}},
        u'EndpointSpec': {u'Mode': u'vip', u'Ports': [{u'TargetPort': 22, u'PublishedPort': 10015, u'Protocol': u'tcp', u'PublishMode': u'ingress'}]},
        u'Name': u'amazing_lalande',
        u'TaskTemplate': {u'RestartPolicy': {u'Delay': 0, u'Window': 0, u'MaxAttempts': 0, u'Condition': u'none'}, u'Placement': {},
            u'ContainerSpec': {
                u'Mounts': [
                    {u'Source': u'/godshared/tasks/pairtree_root/18/task', u'Type': u'bind', u'Target': u'/mnt/go-docker'}
            ],
            u'Image': u'centos:latest@sha256:aebf12af704307dfa0079b3babdca8d7e8ff6564696882bcb5d11f1d461f9ee9', 

            u'Command': [u'/mnt/go-docker/wrapper.sh'],
            u'User': u'root'
         },
        u'Resources': {u'Reservations': {u'MemoryBytes': 1000000000, u'NanoCPUs': 1000000000}, 
        u'Limits': {u'MemoryBytes': 1000000000, u'NanoCPUs': 1000000000}}, u'ForceUpdate': 0}}, u'CreatedAt': u'2017-06-16T13:57:27.420376205Z'
    }

The Endpointspec shows the expected Ports mapping, but still my task shows no exported port.
Any idea of the issue ? My endpoint_spec parameter is "accepted" by the create request, but has no effect.

    CONTAINER ID        IMAGE                                                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
    d7e3c35de1c9        centos@sha256:aebf12af704307dfa0079b3babdca8d7e8ff6564696882bcb5d11f1d461f9ee9   "/mnt/go-docker/wr..."   5 seconds ago       Up 4 seconds                            amazing_lalande.1.bqgd3u9z62t39q6yn0oy57uh0

**Comment by shin-** [comment]
`EndpointSpec` is apparently properly set on the service object, so it's likely you're running into an engine issue at that point.

**Comment by osallou** [comment]
However, running docker service create... -p 8080:80 works for example.
How can i check what is sent to docker engine to see if it receices what is
expected?
The service is created and ran correctly except the missing ports.

**Comment by osallou** [comment]
Looking at dockerd logs, port mapping info are indeed sent:

    Jun 19 07:45:59 swarm dockerd[17148]: time="2017-06-19T07:45:59.481101505Z" level=debug msg="Calling POST /v1.26/services/create"
    Jun 19 07:45:59 swarm dockerd[17148]: time="2017-06-19T07:45:59.481233796Z" level=debug msg="form data: {\"EndpointSpec\":{\"Ports\":[{\"Protocol\":\"tcp\",\"PublishedPort\":10018,\"TargetPort\":22}]},\"TaskTemplate\":{\"ContainerSpec\":{\"Args\":null,\"Command\":[\"sleep\",\"120\"],\"Image\":\"debian\"},\"Resources\":{\"Reservations\":{\"NanoCPUs\":1e+09}},\"RestartPolicy\":{\"Condition\":\"none\",\"Delay\":0,\"MaxAttempts\":0,\"Window\":0}}}"

So either it is engine issue, or api needs additional info about network (but raises no error). I created an issue on engine (https://github.com/docker/for-linux/issues/36)

**Comment by osallou** [comment]
Closing issue, problem was port mapping is not displayed the same way for containers and services.
