### ISSUE TITLE
docker and docker-py conflict not raised

### ISSUE THREAD

**Issue by osallou** [docker/docker-py#1652]
Versions:
docker==2.3.0
docker-py==1.10.6

Installing docker after docker-py does not raise any error but prevent correct behavior.
If docker-py was installed previously, this creates error at runtime.

Previous fix #1395 should have fixed the issue, but I still face the problem (I uninstalled docker-py and was ok, but can be an issue on other computers if user is not warned).

Reproduce:

    root@swarm:~# virtualenv toto
    Running virtualenv with interpreter /root/venv/bin/python2
    Using real prefix '/usr'
    New python executable in toto/bin/python2
    Also creating executable in toto/bin/python
    Installing setuptools, pip...done.
    root@swarm:~# . toto/bin/activate
    (toto)root@swarm:~# pip install docker-py
    Downloading/unpacking docker-py
      Downloading docker_py-1.10.6-py2.py3-none-any.whl (50kB): 50kB downloaded
    Downloading/unpacking docker-pycreds>=0.2.1 (from docker-py)
      Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
    Downloading/unpacking six>=1.4.0 (from docker-py)
      Downloading six-1.10.0-py2.py3-none-any.whl
    Downloading/unpacking requests>=2.5.2,!=2.11.0 (from docker-py)
      Downloading requests-2.18.1-py2.py3-none-any.whl (88kB): 88kB downloaded
    Downloading/unpacking backports.ssl-match-hostname>=3.5 (from docker-py)
      Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
      Running setup.py (path:/tmp/pip-build-IuFw6H/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
        
    Downloading/unpacking ipaddress>=1.0.16 (from docker-py)
      Downloading ipaddress-1.0.18-py2-none-any.whl
    Downloading/unpacking websocket-client>=0.32.0 (from docker-py)
      Downloading websocket_client-0.40.0.tar.gz (196kB): 196kB downloaded
      Running setup.py (path:/tmp/pip-build-IuFw6H/websocket-client/setup.py) egg_info for package websocket-client
        
    Downloading/unpacking certifi>=2017.4.17 (from requests>=2.5.2,!=2.11.0->docker-py)
      Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB): 375kB downloaded
    Downloading/unpacking urllib3>=1.21.1,<1.22 (from requests>=2.5.2,!=2.11.0->docker-py)
      Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB): 131kB downloaded
    Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.5.2,!=2.11.0->docker-py)
      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
    Downloading/unpacking idna>=2.5,<2.6 (from requests>=2.5.2,!=2.11.0->docker-py)
      Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
    Installing collected packages: docker-py, docker-pycreds, six, requests, backports.ssl-match-hostname, ipaddress, websocket-client, certifi, urllib3, chardet, idna
      Running setup.py install for backports.ssl-match-hostname
        
      Running setup.py install for websocket-client
        changing mode of build/scripts-2.7/wsdump.py from 644 to 755
        
        changing mode of /root/toto/bin/wsdump.py to 755
    Successfully installed docker-py docker-pycreds six requests backports.ssl-match-hostname ipaddress websocket-client certifi urllib3 chardet idna
    Cleaning up...
    
    (toto)root@swarm:~# pip install docker
    Downloading/unpacking docker
      Downloading docker-2.3.0-py2.py3-none-any.whl (108kB): 108kB downloaded
    Requirement already satisfied (use --upgrade to upgrade): docker-pycreds>=0.2.1 in ./toto/lib/python2.7/site-packages (from docker)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in ./toto/lib/python2.7/site-packages (from docker)
    Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2,!=2.11.0,!=2.12.2 in ./toto/lib/python2.7/site-packages (from docker)
    Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5 in ./toto/lib/python2.7/site-packages (from docker)
    Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16 in ./toto/lib/python2.7/site-packages (from docker)
    Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in ./toto/lib/python2.7/site-packages (from docker)
    Installing collected packages: docker
    Successfully installed docker
    Cleaning up...

**Comment by osallou** [comment]
pb occurs only with pip install
if we clone docker-py repo and try to install with python setup.py install, we can see the error:

(toto)root@swarm:~/toto/docker-py# python setup.py develop
ERROR: "docker-py" needs to be uninstalled before installing this package:

**Comment by rahulrajaram** [comment]
I think the problem is with the file, `docker-2.6.1-py2.py3-none-any.whl`, listed [here](https://pypi.python.org/pypi/docker/2.6.1#downloads).

Unzipping `docker-2.6.1-py2.py3-none-any.whl` shows that it does not contain a `setup.py` file, [which is where the check for `docker-py` is defined](https://github.com/docker/docker-py/blob/94e3d3dcb9d75d2302c5946d83ecae1e54a3b7c9/setup.py#L12). This looks like a problem in my opinion.

I have two questions following the above observations:

1. Is it necessary to publish `docker-2.6.1-py2.py3-none-any.whl`?
2. Is there a way that one can prefer downloading `docker-2.6.1.tar.gz` instead of `docker-2.6.1-py2.py3-none-any.whl`?

**Comment by shin-** [comment]
While it's a bit annoying that the check isn't performed when installing from the wheel, this is much less of a concern now that most people have upgraded from v1 to v2 (or for some, decided to stick with v1). As a result, this is not something we're looking to invest time into fixing.

Thank you for your understanding.

**Comment by rahulrajaram** [comment]
Thanks for your response @shin-
