### ISSUE TITLE
Add MAC address support in network/id/connect 

### ISSUE THREAD

**Issue by LuisPiedra** [docker/docker-py#1654]
This is possible at least from Docker Engine API v1.25 (https://docs.docker.com/engine/api/v1.25/#operation/NetworkConnect), and it's needed in case more than one network with a predefined MAC address is to be added to a container.

**Comment by LuisPiedra** [comment]
I have started to work in a pull request, but I have noticed that maybe most of network drivers does not honour the configuration provided for MAC address, so integration tests are failing.
I have filled an issue also in https://github.com/docker/libnetwork/issues/1811

**Comment by shin-** [comment]
PR for this #1756 

As I wrote there, we'll need to wait for engine support before merging it.

**Comment by radupaulstefan** [comment]
Hello, any update on this? I still cannot set the mac address with network/id/connect (v1.41) even if I provide the "MacAddress" parameter.

**Comment by LuisPiedra** [comment]
Closed because inactivity
