### ISSUE TITLE
Check resource error in container network API

### ISSUE THREAD

**Issue by matthewtberry** [docker/docker-py#1673]
```
docker python client v2.4.2
python v2.7.12
docker v17.03.1-ce
Ubuntu 16.04
```

PR #1649 updated the `check_resource` decorator to handle different resource names.  Container network API functions  `connect_container_to_network()` and `disconnect_container_from_network()` check 'image' as resource ID and not 'container'.

Reproduce using the following snippet:
```python
import docker

cli = docker.APIClient(base_url='unix:///var/run/docker.sock')
cli.pull(repository='ubuntu', tag='latest')

name = 'my_ubuntu'
container = cli.create_container(image='ubuntu:latest', name=name)
cli.connect_container_to_network(container=name, net_id='bridge')
```

This causes:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    cli.connect_container_to_network(container=name, net_id='bridge')
  File "/home/mberry/scratch/virtualenv/docker_py/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 17, in wrapped
    'Resource ID was not provided'
docker.errors.NullResource: Resource ID was not provided
```

**Comment by Evertude** [comment]
Is it possible that the same error occurs in: https://github.com/docker/docker-py/blob/master/docker/utils/decorators.py?

When I run docker-compose I get to that point.
![image](https://user-images.githubusercontent.com/7377709/29683707-4603ea7c-88dd-11e7-87f8-78ab0ba01795.png)


DockerToolbox-17.06.0a-ce
Docker-compose 1.14.0
Windows 7
Python 3.6.2

**Comment by shin-** [comment]
@Evertude Compose 1.14 doesn't have this fix, but it shouldn't hit this case to begin with. Can you create an issue on https://github.com/docker/compose with your Compose file and the exact command you're running?
