### ISSUE TITLE
APIError: 500 Server Error: Internal Server Error ("Invalid filter 'name'")

### ISSUE THREAD

**Issue by ymoses** [docker/docker-py#1680]
Since I upgraded docker-ce to 17.06, I can't prune stopped containers with name-based filters. (The same error happened with other kinds of filters).

The following code used to work:
`docker.from_env().containers.prune(filters=dict(name="foo"))`

and now I get this error:

>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/models/containers.py", line 807, in prune
>     return self.client.api.prune_containers(filters=filters)
>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/utils/decorators.py", line 35, in wrapper
>     return f(self, *args, **kwargs)
>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/api/container.py", line 950, in prune_containers
>     return self._result(self._post(url, params=params), True)
>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
>     self._raise_for_status(response)
>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "/opt/zappa-env/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.APIError: 500 Server Error: Internal Server Error ("Invalid filter 'name'")

**Comment by shin-** [comment]
Appears to be an engine issue:
```
$ docker container prune --filter name=foobar
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Error response from daemon: Invalid filter 'name'
```

Can you report it to https://github.com/moby/moby ?

**Comment by ymoses** [comment]
Of course. Thanks!

**Comment by ymoses** [comment]
This isn't a bug, I simply misunderstood the API:

https://github.com/moby/moby/issues/34121

**Comment by Anagha5** [comment]
Hi, 
I'm facing error with docker while using it with Azure ML Workbench. Unable to pull the image. Below are the error details. Please let me know how to go about the issue 

Error :
{'Error': MlCliError({'Error': 'Unable to start container', 'Response Content': APIError(HTTPError('500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.30/images/create?tag=1&fromImage=mlcrpacr95813916189d.azurecr.io%2Faicimage',),)},), 'Azure-cli-ml Version': '0.1.0a27.post3'}

**Comment by feliperuhland** [comment]
Hi @Anagha5. I think these problems are not related. It may be best to open a new issue with the steps for reproducing the problem and the versions of the applications and systems.

**Comment by chaseDream1314** [comment]
A new error has emerged after fixing the error above. The 500 server error can be solved by switching to linux container. It is easy to switch windows container to linux container by right clicking on the docker icon. My error are as follow:
(if you want to see more detailed information about the error, there is a url:
https://social.msdn.microsoft.com/Forums/en-US/5ff623a0-2768-43e1-84e8-81657d60c985/to-deploy-the-train-model-of-image-classification-cntk-with-docker-locally?forum=MachineLearning
) 

[Local mode] Running docker container.
[Local mode] Pulling the image from mlcrpacr8fb197558338.azurecr.io/imgclassapi1:18. This may take a few minutes, depending on your connection speed...
[Local mode] Pulling...............................................
Container port: 32770
[Local mode] Waiting for container to initialize...{
    "Azure-cli-ml Version": "0.1.0b2.post2",
    "Error": "Error, container failed to initialize. Please run 'az ml service logs realtime -i imgclassapi1' to determine the cause."

**Comment by chaseDream1314** [comment]
I just want to say why it is so hard to start a container? I am eager to deploy the rest API using azyre workbench, however, It's difficulty is amazing!
