### ISSUE TITLE
docker-py supports swarm config object operation

### ISSUE THREAD

**Issue by allencloud** [docker/docker-py#1681]
Hi, All,

We know that in docker-ce-17.06.0 which has api version of 1.30 supports config management (with PR https://github.com/moby/moby/pull/32336) in swarm mode. 

I think we need to support this in docker-py.

Thanks a lot ☀️

**Comment by kshenk1** [comment]
I'm also in favor of seeing this functionality as config usage is going to be essential to several services I'm currently shaking deployment operations out for.

**Comment by kshenk1** [comment]
Looks like this was addressed in 2.6.0?
https://github.com/docker/docker-py/releases/tag/2.6.0
https://docker-py.readthedocs.io/en/stable/api.html#docker.types.ConfigReference

**Comment by shin-** [comment]
Indeed! Sorry for not updating this issue back then.
