### ISSUE TITLE
Error trying to pass ip to container

### ISSUE THREAD

**Issue by robertknox** [docker/docker-py#1691]
I am trying to use docker-py to do pass in an ip to the container. This works fine from the command line:

 docker run -it --rm --net=br0 --entrypoint="/bin/sh"  -v `pwd`/../src:/app  --cap-add=NET_ADMIN --ip=172.27.153.11 mbussim

I order to do this from docker-py i gather I most first create a network config and then pass it in as an option?

However when I try to create the networking config I get an error:

networking_config = self.dockerAPIClient.create_networking_config({
            'network1': self.dockerAPIClient.create_endpoint_config(
                ipv4_address=ip
            )
        })

returns:

TypeError: unbound method create_endpoint_config() must be called with APIClient instance as first argument (got nothing instead)

**Comment by shin-** [comment]
The message is self-explanatory. You need to create an instance of `APIClient` and call `create_endpoint_config` with that instance.

**Comment by robertknox** [comment]
I think I am:

I have rewritten it to make things more obvious:

dockerAPIClient = docker.APIClient
        networking_config = dockerAPIClient.create_networking_config({
           'network1': dockerAPIClient.create_endpoint_config(
                ipv4_address=ip
           )
        })



 ipv4_address=ip
TypeError: unbound method create_endpoint_config() must be called with APIClient instance as first argument (got nothing instead)

I very much appreciate you help.

**Comment by shin-** [comment]
`APIClient` is a class. You need an instance of that class. [See here](https://en.wikipedia.org/wiki/Instance_(computer_science)) if you need a refresher.

**Comment by robertknox** [comment]
Thanks very much for taking the time to answer. 
But things are still not working. Now docker-py is complaining about the name: "networking_config"
TypeError: run() got an unexpected keyword argument 'networking_config'

dockerAPIClient = docker.APIClient()
        networking_config = dockerAPIClient.create_networking_config({
           'network1': dockerAPIClient.create_endpoint_config(
                ipv4_address="172.27.153.11"
          )
        })

        options = {
            "networking_config": networking_config,
            "detach": True,
            # "remove": True,
            "name": "mbussim_" + ip,
            "cap_add": "NET_ADMIN",
            "network": "br0",
            "volumes": {self.instance_dir_src_dir: {'bind': '/src', 'mode': 'rw'}}
        }

        self.dockcon = self.dockerclient.containers.run(self.dimg, **options)

**Comment by shin-** [comment]
Yes, that's not a valid option for `run`.

```python

    options = {
        "detach": True,
        # "remove": True,
        "name": "mbussim_" + ip,
        "cap_add": "NET_ADMIN",
        "network_mode": "none",
        "volumes": {self.instance_dir_src_dir: {'bind': '/src', 'mode': 'rw'}}
    }

    self.dockcon = self.dockerclient.containers.run(self.dimg, **options)
    network = self.dockerclient.networks.get('br0')
    network.connect(self.dockcon, ipv4_address='172.27.153.11')
```

**Comment by robertknox** [comment]
I tried this:

and got:docker.errors.APIError: 500 Server Error: Internal Server Error ("Container cannot be connected to multiple networks with one of the networks in private (none) mode")

Thanks again for taking the time to respond.

**Comment by robertknox** [comment]
I left out the "network_mode" option I did get this to work thanks to you.

-------------------------------------------------------------------------------------------
options = {
        "detach": True,
        "name": "mbussim_" + ip,
        "cap_add": "NET_ADMIN",
        "volumes": {self.instance_dir_src_dir: {'bind': '/src', 'mode': 'rw'}}
    }

    self.dockcon = self.dockerclient.containers.run(self.dimg, **options)
    network = self.dockerclient.networks.get('br0')
    network.connect(self.dockcon, ipv4_address='172.27.153.11')

I could then ping 172.27.153.11.

-------------------------------------------------------------------------------------------------

I can't tell you how appreciative I am. Thanks very much. But I am a little frustrated as well.
This seems to be documented no where, and deviates from the original Docker usage considerably.

Thanks again.
-r

**Comment by robertknox** [comment]
It seems that right after  this call: network.connect(self.dockcon, ipv4_address='172.27.153.11')
I get this error.

-----------------------------------------------------------------------------------------------------------------------
docker.errors.APIError: 500 Server Error: Internal Server Error ("service endpoint with name mbussim_172.27.153.5 already exists")

I am wondering if I need to flush out the endpoint service name?
How would I do that?

**Comment by robertknox** [comment]
It looks like docker is trying to start another container?
I took out the "name" option and tried again and got the same error:

docker.errors.APIError: 500 Server Error: Internal Server Error ("service endpoint with name mystifying_hugle already exists")

mystifying_hugle was of course the auto generated name that came into being at the time the docker container was created: at :

options = {
            "detach": True,
            "cap_add": "NET_ADMIN",
            "entrypoint": "/app/run_static_ip.sh",
            "network": "br0",
            "volumes": {self.instance_dir_src_dir: {'bind': '/app', 'mode': 'rw'}}
        }

        self.dockcon = self.dockerclient.containers.run(self.dimg, **options)
        network = self.dockerclient.networks.get('br0')
        network.connect(self.dockcon, ipv4_address='172.27.153.11')

All we are tying to do is assign the ip number ( 172.27.153.11 ) to the container.

**Comment by shin-** [comment]
You're trying to connect to the same network multiple times, first by declaring `network` in the `options` dict and then a second time by calling `connect` on the same network.

You can either remove `network` from `options` and let the container connect to `bridge` by default, or you can disconnect then reconnect to the same network:

```python
self.dockcon = self.dockerclient.containers.run(self.dimg, **options)
network = self.dockerclient.networks.get('br0')
network.disconect(self.dockcon)
network.connect(self.dockcon, ipv4_address='172.27.153.11')
```

**Comment by robertknox** [comment]
I tried both approaches. They both work.
I can't help but think simply passing in the ip address in run options would be the easy way to do this.
Why should we have to connect and disconnect and connect just to give the container an ip?
On the command line docker accepts an "--ip" option. Why should docker-py be different?
Regardless,
Thanks again for taking the time to respond. I can move forward.
-r

**Comment by shin-** [comment]
Matches the [engine API](https://docs.docker.com/engine/api/).
