### ISSUE TITLE
docker swarm cluster "No such image: get-envelope:l…" 

### ISSUE THREAD

**Issue by nikhilagrl** [docker/docker-py#1692]
docker@manager:~$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
x5lkolcbhoy6        getEnvelope         replicated          0/2                 get-envelope:latest   *:0->80/tcp,*:0->8080/tcp,*:8080->8080/tcp

docker@manager:~$ docker service ps getEnvelope
ID                  NAME                IMAGE                 NODE                DESIRED STATE       CURRENT STATE             ERROR                              PORTS
u2olg9x9tdw9        getEnvelope.1       get-envelope:latest   manager             Ready               Rejected 2 seconds ago    "No such image: get-envelope:l…"   

![docker hub](https://user-images.githubusercontent.com/20147849/28735457-13952dba-739a-11e7-9ec1-7f0aea70f0a0.png)

please help tp solve this issue.

I am getting "No such image: get-envelope:l…"  in swarm cluster in docker.

**Comment by shin-** [comment]
That's not a docker-py issue. Please recreate on moby/moby
