### ISSUE TITLE
logs trim data more than 16k

### ISSUE THREAD

**Issue by guyisra** [docker/docker-py#1696]
When reading the logs of the container, if line is longer than 16KB it gets cut off.

Is this a known issue?

**Comment by davidCarlos** [comment]
I'm having the same problem. In a long log message, part of it is not getting printed to stdout.

**Comment by shin-** [comment]
Does it happen with the CLI as well? When you `curl` the API endpoint?

**Comment by guyisra** [comment]
using `docker logs` doesn't reproduce the issue, only using docker-py

**Comment by shin-** [comment]
@guyisra What version of the library are you using?

**Comment by guyisra** [comment]
version 1.10.6

**Comment by shin-** [comment]
Oh, that's an old version. Improvements to log streaming have been made in 2.x, upgrading will probably help if you can do so.

**Comment by keis** [comment]
What I'm seeing at docker==2.4.2 is output chunked at the 16k boundary. So a longer message is yielded out of `logs(stream=True)` as multiple 16k messages.

Can this be tweaked?
Is it safe to assume 16k chunks can be rebuffered by the consumer?

**Comment by yxliang01** [comment]
@shin- Although it has been almost 2 years, I am unfortunately experiencing the same problem. This is troublesome. If running container in non-detach mode, there's no way to read the data chunk by chunk.

**Comment by shin-** [comment]
There's not nearly information in this report for it to be actionable. Please refer to our [Reporting guidelines](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues) and open a new issue with the necessary info.
