### ISSUE TITLE
Create new service from attrs of old service

### ISSUE THREAD

**Issue by mackeyja92** [docker/docker-py#1704]
It would be amazing if we could create new services with just the attrs from another service. For example, since the docker API no longer supports renaming a service I would like to just copy the attrs a currently running service, rm it, update the name in the attrs and then create a new one with the attrs. Currently doing so is a lot of work trying to hunt down all the arguments from the attrs to for the kwargs to create a new service.

**Comment by shin-** [comment]
Closing via #1807
