### ISSUE TITLE
client.containers is a function object?

### ISSUE THREAD

**Issue by gray808** [docker/docker-py#1705]
Simply running the example code from the main page:
`import docker`
`client = docker.from_env()`
`client.containers.run("ubuntu:latest", "echo hello world")`

**AttributeError: 'function' object has no attribute 'run'**

it imports fine, I get a <docker.client.Client object>, but then I slam into the above error.

**Comment by shin-** [comment]
You're using 1.x, the example is for 2.x
`pip uninstall docker-py && pip install -U docker`
