### ISSUE TITLE
client.services.create has no attribute 'create'

### ISSUE THREAD

**Issue by tylerjones4508** [docker/docker-py#1706]
**Issue**
I'm having issues with creating a service. It says that  `client.services.create` has no attribute 'create'. The host is the manager of the swarm. Here is what im seeing....

    Python 2.7.12 (default, Nov 19 2016, 06:48:10)
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import docker
    >>> client = docker.from_env()
    >>> client.services.create('ubuntu:latest',command='/bin/bash',name='Test' )
    Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
    AttributeError: 'function' object has no attribute 'create'

I have not started to add in the other options, im trying to figure out why `client.services.create` has no attribute. I have set up `client.swarm.init` and it works fine. I was following the documentation on 
https://docker-py.readthedocs.io/en/stable/services.html#module-docker.models.services

Maybe I am doing something completely wrong here? 

**SDK version, Docker version and python version**

    docker==2.4.2
    docker-py==1.10.6
    docker-pycreds==0.2.1
    Python 2.7.12
    Client:
    Version:      17.06.0-ce
    API version:  1.30
    Go version:   go1.8.3
    Git commit:   02c1d87
    Built:        Fri Jun 23 21:23:31 2017
    OS/Arch:      linux/amd64

    Server:
    Version:      17.06.0-ce
    API version:  1.30 (minimum version 1.12)
    Go version:   go1.8.3
    Git commit:   02c1d87
    Built:        Fri Jun 23 21:19:04 2017
    OS/Arch:      linux/amd64
    Experimental: false 

**OS**

    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Comment by tylerjones4508** [comment]
I also tried `client.services.get(service_id)` and `client.services.list(**kwargs)` and got the same result.

    root@tjones:~# docker service ls
    ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
    4j7snwo1d5ln        TEST                replicated          1/1                 nginx:latest        
    root@tjones:~# python 
    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import docker
    >>> client = docker.from_env()
    >>> client.services.get('4j7snwo1d5ln')
    Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
    AttributeError: 'function' object has no attribute 'get'
    >>> 
    >>> 
    >>> 
    >>> client.services.list()
    Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
    AttributeError: 'function' object has no attribute 'list'
    >>>

**Comment by shin-** [comment]
https://github.com/docker/docker-py/issues/1705#issuecomment-321703517
