### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by danqing** [docker/docker-py#1716]
Hi, 

I see that 2.5.0 just got released. Is there a changelog somewhere? It's hard to see what's in each version - seems that the latest version in the release page is still 2.4.0.

Thanks.

**Comment by shin-** [comment]
Pick one:
- http://docker-py.readthedocs.io/en/stable/change-log.html
- https://github.com/docker/docker-py/blob/master/docs/change-log.md
- https://github.com/docker/docker-py/releases/tag/2.5.0

**Comment by danqing** [comment]
Thanks!
