### ISSUE TITLE
docker-py creates containers with incorrect defaults in HostConfig

### ISSUE THREAD

**Issue by terminalmage** [docker/docker-py#1728]
When inspecting a container created using docker-py, several arguments will have their value in the HostConfig set to `null`/`None` rather than the empty list/dict which the docker CLI sets for them:

```
# python
Python 2.7.13 (default, Jul 21 2017, 03:24:34)
[GCC 7.1.1 20170630] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.APIClient()
>>> client.create_container('centos:7', command='bash', name='from_api', host_config=client.create_host_config())
{u'Id': u'94d935be4cc1375b2468ec4eda34662f158128dd9e921b53b717f884e797f215', u'Warnings': None}
>>>

# docker create --name=from_cli centos:7 bash
f76368a181e4e526474b7837f7f8a36cfcc8350d98b37f70ba85fc9d74bfa703

# python
Python 2.7.13 (default, Jul 21 2017, 03:24:34)
[GCC 7.1.1 20170630] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.APIClient()
>>> from_api = client.inspect_container('from_api')
>>> from_cli = client.inspect_container('from_cli')
>>> for key in sorted(from_api['HostConfig']):
...     if from_api['HostConfig'][key] != from_cli['HostConfig'][key]:
...         print('{0}: API created with {1} but CLI created with {2}'.format(key, from_api['HostConfig'][key], from_cli['HostConfig'][key]))
...
Devices: API created with None but CLI created with []
Dns: API created with None but CLI created with []
DnsOptions: API created with None but CLI created with []
DnsSearch: API created with None but CLI created with []
PortBindings: API created with None but CLI created with {}
RestartPolicy: API created with {u'MaximumRetryCount': 0, u'Name': u''} but CLI created with {u'MaximumRetryCount': 0, u'Name': u'no'}
>>>
```

**Comment by shin-** [comment]
As far as I can tell that should not cause any issue. We're not trying to emulate the Cali's behavior.

**Comment by terminalmage** [comment]
Fair enough, though it does make comparisons slightly more complicated. For our use case we are managing a named container with a desired configuration by using the `create_container` function in the APIClient to create a temporary container, and then comparing the Config and HostConfig in the existing and temp container for differences, replacing the existing container with the temp if any were discovered. If a container was created outside of docker-py, you end up with one container having an empty list for a given value and `None` for the other.

However:

* I can see how trying to match the CLI defaults can be a pain in the butt, as any changes to the defaults in Docker itself will cause docker-py to drift from Docker. Playing whack-a-mole like this is no fun.
* It can be worked around easily by just doing a boolean comparison when one side is `None`. `bool([])` is the same thing as `bool(None)`, and the passing of any DNS options would keep them from being set to `None` in the created container anyway.

Given the above, and since this isn't considered invalid behavior, I'll go ahead and close this. I appreciate the feedback!
