### ISSUE TITLE
nano_cpu and cpu_shares

### ISSUE THREAD

**Issue by danqing** [docker/docker-py#1730]
In the doc, there's (for `container.run`):

```
cpu_shares (int) – CPU shares (relative weight).
nano_cpus (int) – CPU quota in units of 10-9 CPUs.
```

It looks that if I want 50% CPU, `nano_cpus` should be `0.5 * 1e9`. However, that doesn't seem to be what I see in production (if I specify `0.9 * 1e9`, I will get maybe 30% CPU utilization rate, on a single-core machine). Also, if I use a 4-core CPU, and I want to use half of it (say 2 cores), what should I specify?

Similarly, `cpu_shares` is an `int`. What does relative weight mean? Is that on a scale of 100, so if I use 50% of the CPU I should put 50? Again, what if I have a 4-core CPU and want to use half of it?

I would love to get more clarity on these, and ideally be added to the docs.

Thanks!

**Comment by shin-** [comment]
Please refer to the [Docker documentation](https://docs.docker.com/engine/reference/run/#cpu-share-constraint) on this matter.

**Comment by danqing** [comment]
`nano_cpu` doesn't seem to be mentioned anywhere on the page.

**Comment by danqing** [comment]
Also, maybe I didn't find it, but is it possible to "run container on any 2 of the X CPUs"?

**Comment by shin-** [comment]
`nano_cpus` is the counterpart to `--cpus`. `cpuset_cpus` lets you assign CPUs

**Comment by danqing** [comment]
What does "counterpart" mean? And `cpus` (`cpu-period`, `cpu-quota`) only mentions 1 CPU scenario. What happens when there are more CPUs?

And is there an option to assign CPU numbers, not specific CPUs? Say I have two containers, each wanting 2 cores. Do I need to assign specific cores (1,2; 3,4) to them, or is there a way to tell them to use 2 cores each?

Thanks!

**Comment by shin-** [comment]
Here is a more comprehensive source: https://docs.docker.com/engine/admin/resource_constraints/#cpu which better describes what happens in a multi CPU scenario.

I don't know that there is a way to say "use any 2 CPUs", but you may wanna ask on the [forums](https://forums.docker.com) as it's a bit outside my area of expertise.
