### ISSUE TITLE
Add support for service.scale(replicas)

### ISSUE THREAD

**Issue by lhenry7** [docker/docker-py#1734]
The ability to scale a service from the API in a simple way would be great. Mimic docker service scale SERVICE=REPLICAS

**Comment by tobiasfielitz** [comment]
second this!

**Comment by shin-** [comment]
@tobiasfielitz It's an `update` call setting `mode` parameter with the appropriate number of replicas, i.e

```python
mode = ServiceMode('replicated', replicas=5)
service.update(mode=mode, fetch_current_spec=True)
```

That said, it'd be reasonable to have a method for that since it's a fairly common operation.

**Comment by feliperuhland** [comment]
Hi @shin-. Can I work on this? Thanks.

**Comment by tobiasfielitz** [comment]
@shin- thanks for pointing me at this, that should do (until @feliperuhland or anyone else has written a function for it).
Thanks for the great work guys!

**Comment by feliperuhland** [comment]
@tobiasfielitz @shin- I am already working on this!
