### ISSUE TITLE
Conflict between 'docker' and 'docker-py' packages on PyPI.

### ISSUE THREAD

**Issue by TheFriendlyCoder** [docker/docker-py#1738]
Based on my relatively quick analysis it would appear that there are 2 packages for this project on PyPI: one for v1.x and one for v2.x. At some point in the middle - perhaps in v2.0 - the name of the package was renamed from 'docker-py' to 'docker'. Typically this would not cause a problem since the two packages have unique names and thus should be able to be installed side-by-side, however from what I can tell v1 of the project installs to the same target folder as v2 (ie: site-packages/docker) which can cause all sorts of packaging conflicts. For a trivial example, simply try the following:

> pip install docker
> python -c 'from docker import APIClient'      # Operation succeeds
> pip install docker-py
> python -c 'from docker import APIClient'      # Operation fails

I hit this problem recently while working on a new Python project which uses the newer 'docker' package, but I attempted to install another 3rd party lib which transitively depends on 'docker-py'. Install it over top of my current runtime environment essentially corrupted my environment. Said project is already being updated to work with 'docker' but the underlying compatibility problems between 'docker' and 'docker-py' really should be resolved to avoid problems like this in other packages.

**Comment by shin-** [comment]
We are aware of this, unfortunately not much can be done at this point without breaking the codebase for a section of users.

**Comment by TheFriendlyCoder** [comment]
Hmmm - could you not create a dev branch from the same revision as the last 1.x release of the project, and simply change the default deployment folder from 'docker' to, say, 'docker_py'? Then you could release a new version of the docker-py package with this fix. This change should be largely if not totally transparent to users of the docker-py library, and would avoid the conflict with the newer v2 package.

**Comment by TheFriendlyCoder** [comment]
Hmmm - now that I think of it, this would break imports since the package name is still 'docker' :(

So maybe this isn't as easy to fix as I had hoped. :(

**Comment by TheFriendlyCoder** [comment]
Maybe someone could add a notice to the docker-py package on PyPI warning people that they shouldn't use that version of the library any more and that it conflicts with the newer version of the library. Then at least there'd be an incentive, albeit a small one, for people to adopt the newer version.
