### ISSUE TITLE
Mounting volume with Docker service in Swarm mode

### ISSUE THREAD

**Issue by njthykkathu** [docker/docker-py#1741]
Hello,
I am trying to create a docker service and mount docker.sock so that the container can talk to the engine and mount a volume. I created a local volume using ` docker volume create called  'my-vol'`

According to the Docker Python SDK document it says mounts parameter is a` list of str`, therefore I created one 

`mount = ["my-vol:/home/test:rw", "/var/run/docker.sock:/var/run/docker.sock:rw"]`

My docker service create code looks like this

```

service = self._client.services.create(image=task, command=cmd_args[0], args=cmd_args[1:], endpoint_spec=endpoint_spec, name=name, networks=['testing'], mounts=mount, restart_policy=restart_policy);

```

When I run it, I get the following error

`"json: cannot unmarshal string into Go struct field ContainerSpec.Mounts of type mount.Mount"`

I am new to all this containerising concept especially Docker. I hope my question makes sense. If anyone could help me out with this, would be much appreciated.

**Comment by shin-** [comment]
@njthykkathu What version of the library are you using? You might have better luck creating `Mount` instances instead of relying on string parsing: http://docker-py.readthedocs.io/en/stable/api.html#docker.types.Mount

**Comment by njthykkathu** [comment]
@shin- Docker version I use in 2.1.0. Would it be possible if you could give me an example?

**Comment by shin-** [comment]
@njthykkathu You should upgrade to 2.5.2 - The issue you're describing was [fixed a couple versions ago](https://github.com/docker/docker-py/blob/master/docs/change-log.md#bugfixes-3)

**Comment by ijc** [comment]
Closing based in previous comment
