### ISSUE TITLE
'module' object has no attribute 'from_env'

### ISSUE THREAD

**Issue by markzz** [docker/docker-py#1743]
```
import docker
docker_client = docker.from_env()
```

This give the error:

```
Traceback (most recent call last):
  File "/path/to/program.py", line 7, in <module>
    docker_client = docker.from_env()
AttributeError: 'module' object has no attribute 'from_env'
```

This is also not unique to this function, the rest of the module is missing as well and this has been installed via pip.

Python2 and Python3 are both affected.

**Comment by gtseres** [comment]
What version of the module are you using? Could you please share the following?

```python
docker.version
docker.__path__
```

My guess is that either you have a version where `from_env()` is not implemented.

**Comment by markzz** [comment]
docker.__path__ showed the issue and I resolved it. Closed.

**Comment by jeanpaul87** [comment]
> What version of the module are you using? Could you please share the following?
> 
> ```python
> docker.version
> docker.__path__
> ```
> 
> My guess is that you have a version where `from_env()` is not implemented.

i did `pip list` to list all my pip package installed and uninstalled all packed that had docker in them (one of them was docker-py than i only installed docker with `pip install docker`

**Comment by kenorb** [comment]
Try:

```
pip3 install requests==2.31.0
```

as per #3256 

The following requirements.txt works for me:

```
ansible
docker
molecule
molecule-docker
requests==2.31.0
```
