### ISSUE TITLE
On first run, of a new box, docker-py fails to run a container

### ISSUE THREAD

**Issue by Brett55** [docker/docker-py#1744]
On the very first run of a new box, docker-py fails to run a container. On subsequent runs of the same script, docker-py works flawlessly. The container simply exits immediately and only runs "sh" with no args. I'm using latest docker 2.5.1 and docker 17.03ce. I can reproduce this every time. 

My guess is that a file is written to on the first run which causes the proper initialization.

**Comment by gtseres** [comment]
Could you please share some code to reproduce this?

**Comment by Brett55** [comment]
```self._container = self._docker_client.containers.run(image=self._image_id,
                                                                     command=self.run_paramaters.command,
                                                                     volumes=volumes,
                                                                     devices=devices,
                                                                     detach=True)```

**Comment by gtseres** [comment]
Please also make sure that you attach the information mentioned [here](https://github.com/gtseres/docker-py/blob/master/CONTRIBUTING.md#reporting-issues)
