### ISSUE TITLE
Question : docker service ps <service id>

### ISSUE THREAD

**Issue by shabbirkagalwala** [docker/docker-py#1748]
Is there a way to do a docker service ps using docker py? I can do client.api.inspect_service('id') but this does not show node or the task information. 

Sorry if this question does not belong here.

Thank you!

**Comment by shin-** [comment]
`client.tasks(filter={'service': service_id})`

**Comment by shabbirkagalwala** [comment]
@shin- Thank you! Just a small correction, it is "filters" instead of "filter" took a while to get that figured out!
