### ISSUE TITLE
Allow adding host:ip mapping when creating a docker service with docker-py

### ISSUE THREAD

**Issue by clockfly** [docker/docker-py#1749]
By https://docs.docker.com/engine/reference/commandline/service_create/#options, I can add host:ip mapping in container /etc/hosts with syntax like this:
```
docker service create --host <host-name>:<ip> 
```

How can I do this with docker-py? I cannot find info on http://docker-py.readthedocs.io/en/stable/services.html

**Comment by shin-** [comment]
Closing via #1783
