### ISSUE TITLE
I get image with both tag and repostory <none>

### ISSUE THREAD

**Issue by kyjsqd222** [docker/docker-py#1750]
I save image use the method:
>>> image = cli.images.get("fedora:latest")
>>> resp = image.save()
>>> f = open('/tmp/fedora-latest.tar', 'w')
>>> for chunk in resp.stream():
>>>     f.write(chunk)
>>> f.close()
but when I load the image saved by the above,the image has no tag or repository,I cannot find out why .

docker python sdk 2.5.1
docker version 17.06.2-ce

**Comment by shin-** [comment]
Try `resp = cli.api.get_image('fedora:latest')` instead. I think image.save() will always use the image's ID as argument, which causes this to happen:

>  If name is an image ID, [...] only that image (and its parents) are returned, but with the exclusion of the `repositories` file in the tarball, as there were no image names referenced.

[[source]](https://docs.docker.com/engine/api/v1.31/#operation/ImageGet)

**Comment by kyjsqd222** [comment]
@shin- that works! thank you.
