### ISSUE TITLE
Docker Image.tag parameter inconsistency

### ISSUE THREAD

**Issue by wontonst** [docker/docker-py#1757]
Similar to #1441

Everywhere I'm used to `image.remove('repo:tag')` `image.run('repo:tag')` but for some reason the `Image.tag` method wants it like `image.tag('repo', 'tag')`

Either way is fine for me - I actually like separating repo and tag, but you need to decide on one and stay consistent throughout the API.

**Comment by shin-** [comment]
Thank you for your report.

The parameters map directly to the ones of the remote API. As such, I don't believe any adjustment is necessary.
