### ISSUE TITLE
from_env() - incorrect default version

### ISSUE THREAD

**Issue by derwebcoder** [docker/docker-py#1759]
When running `docker.from_env()` without specifying the version, the default version will be set to 1.26 according to http://docker-py.readthedocs.io/en/stable/client.html.
But running an older version of docker might not support this version.

The problem is not actually the version mismatch. There is no warning or error message when using from_env() like this. The problem is, that different error messages appear later on in the code, for example when running docker.build. Then you will get something like `ConnectionResetError: [Errno 104] Connection reset by peer`. But this is very misleading, even Google does not help in this case. Setting `from_env(version="auto")` solves this problem.

Would'nt it not be more sane to set `version="auto"` as default? 
Or at least update the examples, for example in the README, where you run just `from_env()`. New users without an up to date environment might not be able to find the solution right away when running in this kind of issue.

**Comment by shin-** [comment]
Looks like an engine issue - it shouldn't respond to requests with an API version it doesn't recognize.
