### ISSUE TITLE
creat a service and run it with number of replicas

### ISSUE THREAD

**Issue by bingzhang** [docker/docker-py#1763]
I can use command line to create a service with number of replicas to run in swarm mode.

I follow the document to use DockerClient to create a service, but it seems there is no way to set number of replicas, and also how I run this service with number of containers?  
http://docker-py.readthedocs.io/en/stable/services.html

**Comment by shin-** [comment]
http://docker-py.readthedocs.io/en/stable/api.html#docker.types.ServiceMode

**Comment by bingzhang** [comment]
Thank you. And may I know how to set disk limit for all containers of a service, please? Is there a class like resources to set limits for cpu and memory?

**Comment by shin-** [comment]
As far as I know, that's not an available feature at this point in time. You would need to request it on [moby/moby](https://github.com/moby/moby) first.

**Comment by bingzhang** [comment]
Thank you. I will close this one.
