### ISSUE TITLE
cpu_count Windows only

### ISSUE THREAD

**Issue by diocas** [docker/docker-py#1768]
Hi,

I want to use cpu_count on linux, but in the documentation it says that's "Windows only". Any intention of adding it in the future? Is there a technical reason for not providing this option for linux?

Thanks

**Comment by shin-** [comment]
I think it's due to a difference in implementation at the system level. You might be able to achieve a simiar result on UNIX systems using `cpuset_cpus`. [moby/moby](https://github.com/moby/moby) is probably a better place to ask this :)

**Comment by diocas** [comment]
In the documentation, they say that it's similar to _cpu-period_ + _cpu-quota_. But they recommend using the _cpus_ flag on version 1.13 and up (whatever the system). They don't say not to use it in any case, that's why I was asking why docker-py was blocking this option for other systems.
Thanks

**Comment by shin-** [comment]
We're not blocking it at the SDK level, but it's not going to work on Linux. The equivalent to the `--cpus` flag in the CLI is `nano_cpus`.

**Comment by fkromer** [comment]
@shin- There are couple of issues which are about how to control cpu configuration of a container. I am not sure if I understood the configuration options properly. Are you open to a PR which adds an explanation about the different configuration options in `docker-py`? Would you review it or would someone else review it?
