### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Skeen** [docker/docker-py#1779]
Hello,

According to the METADATA information on the package;

    cat site-packages/docker-2.2.1.dist-info/METADATA

    Metadata-Version: 2.0
    Name: docker
    Version: 2.2.1
    ...
    License: UNKNOWN

Rather then UNKNOWN, perhaps it should say `Apache 2.0`.

**Comment by shin-** [comment]
That was fixed for 2.3.0 onward by #1518
