### ISSUE TITLE
[Question] Docker Stats 

### ISSUE THREAD

**Issue by shabbirkagalwala** [docker/docker-py#1795]
I am trying to stream docker stats, using the code below, but can't figure out why **precpu_stats** is always zero. Since **precpu_stats** is always zero and does not contain the key **system_cpu_usage**, I am not able to get the CPU % for containers.
     
    while True:
        cont_list = client.containers.list(filters={'status':'running'})
        for i in cont_list: 
            stats = client.api.stats(i.id,stream=True,decode=True)
            p=next(stats)
            print(p["precpu_stats"])

This is the output I get (I only have one container running):

> {'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}
{'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}
{'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}
{'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}
{'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}
{'cpu_usage': {'total_usage': 0, 'usage_in_kernelmode': 0, 'usage_in_usermode': 0}, 'throttling_data': {'periods': 0, 'throttled_periods': 0, 'throttled_time': 0}}

Any help is appreciated.

**Comment by shabbirkagalwala** [comment]
Its an apache-php container with a few additional components, which i start using docker run. Also I can see CPU % when i enter the docker stats command.

<img width="921" alt="shabbirkagalwala_ _docker_stats_ _204x27" src="https://user-images.githubusercontent.com/17373413/32496986-b762c718-c390-11e7-8bef-332fd512e5dd.png">

**Comment by thaJeztah** [comment]
The stats endpoint in this case is a streaming endpoint, so the client has to stay connected to get the "previous" and "current" stats; The "previous" (`precpu_stats`) one will be reset if you disconnect, and open a new connection.

(I have no experience with the `docker-py` SDK, but possibly this will help you further 😅)

**Comment by thaJeztah** [comment]
LOL, there's where my Python knowledge ends 😅

**Comment by shabbirkagalwala** [comment]
@thaJeztah Haha, thank you for letting me know what was happening, I will try to work

**Comment by shabbirkagalwala** [comment]
I am not sure if this is the right way to do this, but I got it working this way. 

    def calculateCPUPercentUnix(v):
        cpuPercent = 0.0
        previousCPU = v['precpu_stats']['cpu_usage']['total_usage']
        cpuDelta = v['cpu_stats']['cpu_usage']['total_usage'] - previousCPU
        previousSystem = v['precpu_stats']['system_cpu_usage']
        systemDelta = v['cpu_stats']['system_cpu_usage'] - previousSystem
        if systemDelta > 0.0 and cpuDelta > 0.0:
            cpuPercent = (cpuDelta / systemDelta) * len(v['cpu_stats']['cpu_usage']['percpu_usage']) * 100
            return "{0:.2f}".format(cpuPercent)
        else:
            return cpuPercent


    while True:
        cont = client.containers.list(filters={'status':'running'})
        for v in cont: 
             stats = client.api.stats(v.id,stream=True,decode=True)
              while True:
                  for i in stats:
                      try:
                           cpuPercent = calculateCPUPercentUnix(i)
                      except KeyError:
                           continue
                      print(cpuPercent)
                   break
              break

**Comment by TomasTomecek** [comment]
What I usually ended up doing is that I copied exactly what docker cli is doing:
https://github.com/TomasTomecek/sen/blob/67794e176e70fa77d01e2acae381b92e501c0e17/sen/util.py#L162
https://github.com/TomasTomecek/sen/blob/67794e176e70fa77d01e2acae381b92e501c0e17/sen/docker_backend.py#L664
