### ISSUE TITLE
Consider generating code from Swagger API spec

### ISSUE THREAD

**Issue by masaeedu** [docker/docker-py#1806]
I recently tried generating a [JS client](https://www.npmjs.com/package/docker-client) for the Docker API from the [Swagger spec](https://raw.githubusercontent.com/moby/moby/master/api/swagger.yaml) in the main [moby repository](https://github.com/moby/moby/) repository. Having used it extensively for some integration testing work, I found that the Swagger spec is pretty mature, and that a client autogenerated from it is quite usable for simple as well as complex tasks.

Perhaps it would be a good idea to substitute the "low-level API" part of this project with something automatically generated from the Swagger spec? This would be beneficial in several ways:

 - A large community of users relying on code generated from the Swagger spec would help to feed back into improving the accuracy of the spec (and hence all other generated clients + the API docs)
 - Less duplicated effort in maintaining documentation and signatures for endpoints
 - If integration tests are specified as a sequence of inputs/expected outputs against the spec endpoints, multiple client implementations can share a test suite

There is a Python code generator in the [swagger-codegen](https://github.com/swagger-api/swagger-codegen/) project that can be used as a starting point. The generator currently chokes on the spec; I need to debug whether the issue is in the spec or the code generator (I had to do a similar exercise when generating the JS client).

**Comment by shin-** [comment]
Thank you for your suggestion.

You're welcome to do this if you want, but it would be a separate project. This SDK has built up a large user base that relies on the existing interface, and while an autogenerated is easier to keep up to date, I think there is something to be said for thoughtful, language-aware design as well.
