### ISSUE TITLE
swarm services: extra_hosts set in wrong format

### ISSUE THREAD

**Issue by stsaid** [docker/docker-py#1822]
Dear all,
we encounter issues with setting `extra_hosts` for swarm services on docker-py 2.6.1

```
docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**What we do**
```
extra_hosts = dict()
extra_hosts.update({'domain.com': '8.8.8.8'})
client.services.create(name='myservice', image='nginx', hosts=extra_hosts)
```

**Result**
The entry is not found in `/etc/hosts` in the container.
The attribute `Hosts` of the service's `ContainerSpec` shows the following syntax: `domain.com:8.8.8.8`
However, the syntax should have been `8.8.8.8 domain.com`

**Analysis**
docker-py uses this line to format `extra_hosts` (https://github.com/docker/docker-py/blob/2.6.1/docker/utils/utils.py#L569):
```
 '{}:{}'.format(k, v) for k, v in sorted(six.iteritems(extra_hosts))
```

According to swarm's API (https://github.com/moby/moby/blob/d91c5f42eb37c6f88cec4021c10c0a1ded1785c3/api/types/swarm/container.go#L65), the ContainerSpec of a TaskSpec expects `extra_hosts` in the format described per http://man7.org/linux/man-pages/man5/hosts.5.html which is:
```
IP HostnameA
```

**Workaround**
Currently, we compensate this as follows:
```
create_service_kwargs = docker.models.services._get_create_service_kwargs(...)
create_service_kwargs['task_template']['ContainerSpec']['Hosts'] = ['8.8.8.8 domain.com']
client.api.create_service(**create_service_kwargs)
```

Maybe you can comment on this.

Thanks and Regards,
Stephen

**Comment by mhank** [comment]
Hi, I'm currently an undergraduate student taking a course on virtualization. For our final project, my group of two is required to find open-source issues to work on in our last few weeks. This issue sounded manageable for the time frame and our skill level. Is anybody already working on this and does this sound reasonable?
Thank you

**Comment by stsaid** [comment]
Yes, this should not be too complicated. Go ahead!

However, first an thorough analysis should be done, whether our assumptions hold true.
Docker commenting on this would be nice also.

**Comment by mhank** [comment]
Currently running into an issue in which one of the tests is failing because the updated format of the extra hosts does not match that expected by Docker run's --add-host flag. Not sure how to address this, as it seems that it would require modifying parts of Docker/its docs, unless we're missing/misunderstanding something. Would you mind giving us some guidance @shin- ?

**Comment by thaJeztah** [comment]
The format in the service-create API request needs to be `["<ip-address> <hostname>", "<ip-address-2> <hostname 2>"]`

For example, here's the request that's sent by the docker cli for `docker service create --name  foo --host some-host:1.1.1.1 nginx:alpine`;

```json
{
  "EndpointSpec": {
    "Mode": "vip"
  },
  "Labels": {},
  "Mode": {
    "Replicated": {}
  },
  "Name": "foo",
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Hosts": [
        "1.1.1.1 some-host"
      ],
      "Image": "nginx:alpine@sha256:34aa80bb22c79235d466ccbbfa3659ff815100ed21eddb1543c6847292010c4d"
    },
    "ForceUpdate": 0,
    "Placement": {
      "Platforms": [
        {
          "Architecture": "amd64",
          "OS": "linux"
        }
      ]
    },
    "Resources": {
      "Limits": {},
      "Reservations": {}
    }
  }
}
```

Also note that entries should not be sorted when creating  a service; the order in which extra hosts are provided should be kept (see https://github.com/docker/cli/pull/651)

The conversion that's used in the Docker CLI can be found here; https://github.com/docker/cli/blob/97b148b440f052679bd80cf2779801494c428afe/cli/compose/convert/service.go#L388-L399
