### ISSUE TITLE
How to write to container's stdin ?

### ISSUE THREAD

**Issue by Shiri-Naim** [docker/docker-py#1839]
My container needs input to work and I am struggling with doing that via API but I am not able to do that.
I have tried many configurations for create and start functions, but it tells me that Socket is not writable. It's obvious that I am missing something.

It would be great if you could share a sample code of how we should do that ?

Thanks in advance.

**Comment by shin-** [comment]
Check out https://github.com/d11wtq/dockerpty

**Comment by qazbnm456** [comment]
I've built a project mimicking the behavior of Docker CLI with docker-py, and you may check out how I handle these commands: https://github.com/qazbnm456/tsaotun/tree/master/tsaotun/lib/Docker/Container.

I think you should focus on `exec` related commands which I also take advantage of https://github.com/d11wtq/dockerpty.
