### ISSUE TITLE
Running container sometimes hangs on docker 1.12

### ISSUE THREAD

**Issue by bzak9LD** [docker/docker-py#1843]
**Description:**
When using docker-py 2.7.0 with docker 1.12 `cli.containers.run` sometimes hangs. 

I believe this due to the:
- pull request "Retrieve container logs before container exits / is removed"
https://github.com/docker/docker-py/pull/1836
- bug in docker 1.12 that can cause a deadlock when asking for log of container
https://github.com/moby/moby/issues/27779

**Minimal test to reproduce:**
I was unable to reproduce this issue on different dockers than ```1.12.6, build 1398f24/1.12.6```. On this docker following code is sufficient:
```
import docker
cli = docker.from_env(version='auto')
cli.containers.run(image="busybox:latest", command="ls")
```
Killing this with Ctrl^C shows following backtrace:
```
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.oszXxbDvRO/lib/python2.7/site-packages/docker/models/containers.py", line 752, in run
    [line for line in out]
  File "/tmp/tmp.oszXxbDvRO/lib/python2.7/site-packages/docker/api/client.py", line 341, in _multiplexed_response_stream_helper
    header = response.raw.read(STREAM_HEADER_SIZE_BYTES)
  File "/tmp/tmp.oszXxbDvRO/lib/python2.7/site-packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/lib64/python2.7/httplib.py", line 578, in read
    return self._read_chunked(amt)
  File "/usr/lib64/python2.7/httplib.py", line 620, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

```

**Environment:**
This machine is a KVM VM.
```
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
$ pip freeze | grep docker
docker==2.7.0
docker-pycreds==0.2.1
$ python --version
Python 2.7.5
$ docker --version
Docker version 1.12.6, build 1398f24/1.12.6
```

**Comment by shin-** [comment]
Thank you for the report.

I'm not sure there's much we can do about it. Honestly, I'd encourage anyone still using 1.12 to upgrade ASAP because it's really outdated anyway. If that's not an option, using [create](http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.create) and [start](http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.start)  is still an option and will give you more control over what your code is doing.

**Comment by dimaryaz** [comment]
I'm seeing the same bug - but I'm using docker 1.13.1. It hangs every time.
