### ISSUE TITLE
Support for `--no-resolve-image`?

### ISSUE THREAD

**Issue by agxs** [docker/docker-py#1844]
The docker command line has a `--no-resolve-image` flag when doing `docker service create` to stop worker nodes querying the registry for images.

Can the python API do the same thing? I can't find anything mentioned in the documentation.

**Comment by shin-** [comment]
That flag looks like a client-only option.` The workers aren't querying the registry ; the Docker CLI is.

In other words, that's not something you need to worry about using the SDK.

**Comment by agxs** [comment]
Hmm that doesn't seem to match what we're seeing, although maybe I'm just misunderstanding the magic of the client :)

Our application does quite a lot of API requests to create services (Jupyterhub which creates a new docker service for each Notebook), and we're trying to improve performance as sometimes Notebooks take a long time to start.

If we use say `local.registry.url:5000/foo/bar` as the image name when calling `self.docker('create_service', task_tmpl, name=self.service_name, networks=networks, labels=labels)` then we see requests at the registry end from the workers. But if we change the image name to `local.registry.url:5000/foo/bar@sha256:7dbcb0e8c0d96d04449ddf32c4053c07ecfa2bfce79a69ce137e337c4ae40ad4` then the requests to the registry go away. Ideally we'd like to not have to specify the hash of the image.

If it wasn't clear, this is docker running in swarm mode.

**Comment by shin-** [comment]
Ah, it's possible the CLI uses the information it has locally to determine the sha associated with the image's tag instead of letting the daemon query the registry for it. You can probably imitate that with `docker-py` by doing something like
```python
image = 'local.registry.url:5000/foo/bar'
image_id = client.inspect_image(image)['Id']
```

and using the `image_id` value in your `create_service` call. HTH
