### ISSUE TITLE
save() method not implemented?

### ISSUE THREAD

**Issue by fgalan** [docker/docker-py#1845]
Looking to documentation http://docker-py.readthedocs.io/en/stable/images.html, I see a load() method:

> load(data): Load an image that was previously saved using **`save()`** (or `docker save`). Similar to `docker load`.

Howver, I have tried to find for a save() method in the doc, but I have been able to find it... Maybe I'm missing something? Maybe the save() method is not yet implemented in the version I'm using (just installed from pip, it is docker==2.7.0) or was removed in a previous version but the documentation was not fixed?

Thanks!

**Comment by shin-** [comment]
[It's here](https://github.com/docker/docker-py/blob/master/docker/models/images.py#L59-L80). Probably a bug with the docs generation. Thanks for pointing it out.

**Comment by shin-** [comment]
[Docs are now fixed](http://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.Image.save)
