### ISSUE TITLE
"update out of sequence" needs better error message

### ISSUE THREAD

**Issue by tobiasfielitz** [docker/docker-py#1848]
Getting:

`docker.errors.APIError: 500 Server Error: Internal Server Error ("rpc error: code = Unknown desc = update out of sequence")`

when executing: 

```
[..]
replicas = 3
service_mode = ServiceMode('replicated', replicas)
assert self.id and self.version
print('scale', self.id, self.version, service_mode)
client.api.update_service(self.id, self.version, mode=service_mode, fetch_current_spec=True)
```

The print statement prints the following:

`scale uctum3yr6rabl0fpk8ys6m77j 84772 {'replicated': {'Replicas': 3}}`

I have no idea what the error message is trying to tell me or what I am doing wrong.

**Comment by tobiasfielitz** [comment]
Error comes from passing in _service_node_ as _task_template_. Feel free to close if the error message is good enough when user uses API properly ;-)

**Comment by tobiasfielitz** [comment]
Seems to happen when self.version is an old version. I have to run
`version = api_client.inspect_service(self.docker_service_name)['Version']['Index']` (right) before scaling.

**Comment by shin-** [comment]
That's the engine's message - if you feel it is inadequate, please open an issue on the [moby/moby](https://github.com/moby/moby) repo.

**Comment by Hugo-C** [comment]
As this issue is the first coming up in google results, it is worth noting a [reload()](https://docker-py.readthedocs.io/en/stable/services.html?highlight=reload#docker.models.services.Service.reload) function exists and can be more clean to use if we don't care about commands orders/versions
