### ISSUE TITLE
install < 2

### ISSUE THREAD

**Issue by dfroger** [docker/docker-py#1851]
I'm using `salt 2016.11.2 (Carbon)`, and want to use  [dockerng.image_present](https://docs.saltstack.com/en/2016.3/ref/states/all/salt.states.dockerng.html#salt.states.dockerng.image_present), which tries to use `docker.Client`.

In `2.0.0`, [docker.Client has been renamed to docker.APIClient](https://github.com/docker/docker-py/blob/master/docs/change-log.md#breaking-changes).

So I tried to `pip install 'docker < 2'`, but I get:

```
  Could not find a version that satisfies the requirement docker<2 (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0)
No matching distribution found for docker<2
```

Is is still possible to `pip install` version `1.x.x`?

**Comment by dfroger** [comment]
This should work:

```
pip install https://github.com/docker/docker-py/archive/1.10.6.tar.gz
```

**Comment by dfroger** [comment]
The comand above is ok for me, I'm closing this (short) issue...

**Comment by shin-** [comment]
For 1.x, `docker-py` used to be the name of the pip package if you ever want to get it from pypi instead.

**Comment by dfroger** [comment]
great, thanks!
