### ISSUE TITLE
Official mock-client for docker-py?

### ISSUE THREAD

**Issue by kairichard** [docker/docker-py#1854]
There are situations where one wants to gain control over a client in order to better unit test an application. Same as for instance https://github.com/openstack/requests-mock
I have seen that there is `tests/unit/fake_api_client.py` which is a good start.  I inlined the relevant files into a project of mine without a problem.

But I wonder if there is any chance of packaging this up? Would the community be interested enough for such a thing to separately maintained? 

Discussions already happened:
- https://github.com/docker/docker-py/issues/1369
- https://github.com/docker/docker-py/pull/693
- https://github.com/docker/docker-py/issues/109

The benefit would a less brittle test infrastructure for every downstream project and less work for other trying to reinvent the wheel. What do you say?

**Comment by shin-** [comment]
Hi @kairichard 

While it's not a project I as the SDK maintainer am personally interested in taking on, you're more than welcome to create your own package based on `fake_api_client.py` as long as it's published in a way that's compatible with the [Apache Software License](https://github.com/docker/docker-py/blob/master/LICENSE).

HTH!

**Comment by kairichard** [comment]
Hi @shin- 
Thanks for clarifying - it did help. 
Once I get around to having something packaged up, I will post back into this thread.

**Comment by circa10a** [comment]
@kairichard You ever make any progress on this?

**Comment by kairichard** [comment]
@circa10a no sadly, I did not make progress as there simply was not enough need.
@shin- feel free to close.
