### ISSUE TITLE
Nvidia support?

### ISSUE THREAD

**Issue by mwilliammyers** [docker/docker-py#1877]
I know that a [PR](#1560) was being worked on to provide nvidia support, but apparently it is no longer necessary with [`nvidia-docker2`](https://github.com/NVIDIA/nvidia-docker), but I cannot find anything in the documentation.

Is it currently possible (provided [`nvidia-docker2`](https://github.com/NVIDIA/nvidia-docker) is properly installed/configured) to do the equivalent of:

It looks like this is available via the [`runtime`](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run) parameter?
```
docker run --runtime=nvidia nvidia/cuda nvidia-smi
```

and as of [`v17.12.0-ce`](https://github.com/NVIDIA/nvidia-docker/issues/141):
```
docker service create -t --generic-resource "gpu=1" nvidia/cuda nvidia-smi
```

It looks like the [`resources`](https://docker-py.readthedocs.io/en/stable/api.html#docker.types.Resources) API does not support `--generic-resource`...

**Comment by shin-** [comment]
For the first, `runtime` is available for `APIClient.create_host_config` and `DockerClient.containers.run` since 2.4.0. The service equivalent hasn't been worked on yet.

**Comment by mwilliammyers** [comment]
Thanks!

If I wanted to implement this, would I to need to update [`create_service()`](https://github.com/docker/docker-py/blob/master/docker/api/service.py#L90) and [`create()`](https://github.com/docker/docker-py/blob/master/docker/models/services.py#L132) ? 

Is this even available in the [Docker Engine HTTP API](https://docs.docker.com/engine/api/v1.35/#operation/ServiceCreate) (which I assume is what this package uses) yet?

**Comment by shin-** [comment]
@mwilliammyers Yes, I believe it is available in the API (otherwise the CLI wouldn't be able to implement it). It is listed under `Resources` [here](https://docs.docker.com/engine/api/v1.35/#operation/ServiceCreate)

For the implementation, [`Resources`](https://github.com/docker/docker-py/blob/master/docker/types/services.py#L298-L326) would need to be updated along with the methods you pointed out. Let me know if this is something you're interested in taking on.

**Comment by mwilliammyers** [comment]
Yeah I am interested in implementing this. I'll open a PR soon.

**Comment by mwilliammyers** [comment]
So I see a few options for implementing this:

**1.** Most explicit:

  ```python
  generic_reservations=[
     docker.types.DescreteGenericResource(kind='SSD', value=1),
     docker.types.NamedGenericResource(kind='GPU', value='UUID1')
  ]
  ```
  pros:

  - puts the burden of figuring things out like `value='1'` on the user
  - dockerd will give an error for e.g.: `docker.types.NamedGenericResource(kind='GPU', value=1)`

  cons:

  - cumbersome and awkward for the user

**2.** Determine `NamedResourceSpec` and `DiscreteResourceSpec` automatically with an `isinstance()` check:

  ```python
  generic_reservations=[
     docker.types.GenericResourceReservation(kind='SSD', value=3),
     docker.types.GenericResourceReservation(kind='GPU', value='UUID1')
  ]
  ```

  pros:

  - a little less awkward than option **1**

  cons:

  - still cumbersome and awkward for the user, doesn't gain ease of use

**3.** Use a list of `dict` and determine `NamedResourceSpec` and `DiscreteResourceSpec` automatically with an `isinstance()` check:

  ```python
  generic_reservations = [{'SSD': 3}, {'GPU': 'UUID1'}]
  ```

  pros:

  - a lot simpler/cleaner for the user

  cons:

  - less explicit, have to use `isinstance()` and all `str` values will be a `NamedResourceSpec` and all `int` values will be `DiscreteResourceSpec`.
  - Could lead to silent errors...

**4.** Use a list of `str` and determine `NamedResourceSpec` and `DiscreteResourceSpec` automatically with an `isinstance()` check:

  ```python
  generic_reservations = ['SSD=3', 'GPU=UUID1']
  ```

  pros:

  - matches the docker CLI

  cons:

  - Not very pythonic
  - A little awkward
  - Could lead to silent errors...

And for all cases, use `generic_reservations` like:

```python
 client.services.create(resources=docker.types.Resources(generic_reservations=generic_reservations))
```


What are your thoughts? Or does it not matter? There seems to be some variation of each throughout the existing API...

I have them all pretty much coded up so it doesn't a lot to me but I am partial to either **1** or **3**
