### ISSUE TITLE
Containers.create() cannot handle binds with Windows paths containing a ':'

### ISSUE THREAD

**Issue by makroeze** [docker/docker-py#1884]
### Issue
Containers.create() is unable to handle binds with Windows paths containing a ':' due to the string splitting logic in _host_volume_from_bind(bind). Given a bind of the form 'foo:c:/foo:rw', the path is identified as 'c' rather than 'c:/foo'.

### Environment
Windows 10 Desktop 1709
docker==2.6.0
docker-pycreds==0.2.1
Python 2.7.14
Client:
    Version:      17.06.0-dev
    API version:  1.34
    Go version:   go1.8.5
    Git commit:   e2ada66
    Built:        Thu Nov  2 23:37:13 2017
    OS/Arch:      windows/amd64
Server:
    Version:      17.06.0-dev
    API version:  1.34 (minimum version 1.24)
    Go version:   go1.8.5
    Git commit:   462d791
    Built:        Thu Nov  2 23:41:07 2017
    OS/Arch:      windows/amd64
    Experimental: false

**Comment by veyalla** [comment]
@shin Can you please take a look at this one? This is a blocker for us.
