### ISSUE TITLE
What's the difference between docker and docker-py?

### ISSUE THREAD

**Issue by wekay102200** [docker/docker-py#1892]
I found two docker operation modules.respectively are docker and docker-py.
they both can be installed from pip,which install commands are:
pip install docker-py 
pip install docker

What's the difference between them,Which module is the best way to operate docker?

**Comment by shin-** [comment]
`docker-py` is the old name of the `docker` package. New releases for the past year have only been made with the `docker` package name, so it is recommended that you use it if possible.

**Comment by shin-** [comment]
I've just updated [docker-py](the https://pypi.python.org/pypi/docker-py) description on PyPi. Hopefully that will prevent similar confusion in the future.

**Comment by WouldYouKindly** [comment]
Hi! Description of https://pypi.org/project/docker-py/ gives no hint that the package is deprecated. Would be lovely to fix that, cause it creates much confusion, and leads to installing both packages which breaks them completely.
