### ISSUE TITLE
Version 3.0.x is very slow to save image

### ISSUE THREAD

**Issue by goldmann** [docker/docker-py#1905]
As mentioned in the comment: https://github.com/docker/docker-py/issues/1352#issuecomment-363907057 the change to use generator (with chunk size set to `1`) in the image save method (applied in https://github.com/docker/docker-py/commit/388f291b13fca76f4974a1ee89225ff7f3afb85b#diff-cc05c8e27ac99930dc2a96358a502480) instead of directly exposing the response object makes it impossible to export bigger images.

Previously we could define the chunk size depending on the use case. We are dealing with big images (GB's of data) and not being able to specify the chunk size makes it impossible to use new version of the client library. I do see it as a regression.

This issue was also mentioned in #1352.

**Comment by shin-** [comment]
Yep, I already saw the posts in #1352 - we can keep the discussion there :)
