### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by sthuber90** [docker/docker-py#1911]
https://github.com/docker/docker-py/blob/ba0e5332de2fb032b5b21e8e2835244152927c0f/docker/models/images.py#L287

Trough this line I wondered why my code wasn't working as:
```
# works
client.pull(self.image, tag="latest")
# doesn't work
client.pull(name=self.image, tag="latest")
```

**Comment by TomasTomecek** [comment]
From the gist of your code, it seems that you are actually using this method:

https://github.com/docker/docker-py/blob/ba0e5332de2fb032b5b21e8e2835244152927c0f/docker/api/image.py#L308
