### ISSUE TITLE
Add support for --cpus run flag

### ISSUE THREAD

**Issue by ko-christ** [docker/docker-py#1920]
In Docker `1.13` or higher `--cpus` is the suggested option to configure CPU quota.
Option doesn't seem to be supported at the moment. 
https://docker-py.readthedocs.io/en/stable/containers.html

Any chance we could add support for the `--cpus` run flag?

**Comment by shin-** [comment]
It's called `nano_cpus` in the API

**Comment by n-a-sz** [comment]
It is not in the docs.... https://github.com/docker/docker-py/blob/master/docker/api/container.py#L512-L513

**Comment by n-a-sz** [comment]
For future reference, you have to provide the number of CPUs multiplied by 10^9
e.g. nano_cpus=2000000000 for 2 CPUs
