### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by Tabrizian** [docker/docker-py#1926]
When I try to install ```docker-py``` using ```pip install docker```, I get the error below:

```
Could not find a version that satisfies the requirement pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker) (from versions: 219)
No matching distribution found for pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker)
```

**Comment by Tabrizian** [comment]
I think it is because of this line in the dependencies
https://github.com/docker/docker-py/blob/8b246db271a85d6541dc458838627e89c683e42f/requirements.txt#L15

**Comment by shin-** [comment]
Are you using an implementation other than CPython?

**Comment by Tabrizian** [comment]
No, I'm using CPython.

```
>>> import platform
>>> platform.python_implementation()
'CPython'
```

**Comment by shin-** [comment]
Oh, sorry ; are you on Python 3.7?

**Comment by Tabrizian** [comment]
Yes

**Comment by shin-** [comment]
Okay ; unfortunately, that version isn't supported yet.

**Comment by Tabrizian** [comment]
Could you please say why this installation fails? I'm just wondering about it.

**Comment by shin-** [comment]
The `pypiwin32` package has a [220 release](https://pypi.python.org/pypi/pypiwin32/220) that's compiled for Python 3.6 and a [219 release](https://pypi.python.org/pypi/pypiwin32/219) that works with 2.7-3.5. The newer 223 release may work with 3.7, but I haven't had time to validate it yet.

**Comment by Tabrizian** [comment]
May I start working on it?

On Feb 26, 2018, at 11:20 PM, Joffrey F <notifications@github.com<mailto:notifications@github.com>> wrote:


The pypiwin32 package has a 220 release<https://pypi.python.org/pypi/pypiwin32/220> that's compiled for Python 3.6 and a 219 release<https://pypi.python.org/pypi/pypiwin32/219> that works with 2.7-3.5. The newer 223 release may work with 3.7, but I haven't had time to validate it yet.

**Comment by zhangxuehong** [comment]
When I run “”pip install docker” on windows cmd(administror), i got the error, PermissionError: [Errno 13] Permission denied: 'd:\\develope\\python35\\Lib\\site-packages\\pypiwin32_system32\\pythoncom35.dll'

i use python 3.5

**Comment by montao** [comment]
Still no python 3.7 support? The awsebcli seems to depend on docker-py. I get this error message with python 3.7:
```

 Could not find a version that satisfies the requirement pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker<4.0,>=3.3.0->docker-compose<1.22.0,>=1.21.2->awsebcli) (from versions: 219, 223)
No matching distribution found for pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker<4.0,>=3.3.0->docker-compose<1.22.0,>=1.21.2->awsebcli)
```

**Comment by jdstraye** [comment]
Yes, I have the same problem, trying to install aws-sam-cli. I just upgraded to pip 18.0 and when I tried again to "pip install aws-sam-cli," a lot of wheels were downloaded/updated. I was hopeful, but I ran into the same "requirements not met" problem. 

I would love for this to be fixed, but I also have work to do. It seems I can proceed by reverting to Python 3.6.6. When do you expect this compatibility issue to be fixed?

@Tabrizian , you mentioned that the 223 release may work. I notice that both docker and aws-sam-cli have the requirement pypiwin32==220 in the error reports. How can we try 223 to see if it works? Hopefully, this is not as basic as it sounds. If they were specified in a local requirements.txt I could do it, but these requirements seem to be coming from elsewhere.

**Comment by shin-** [comment]
Next release (3.5.0) will have Python 3.7 support. Thank you for your patience.

**Comment by jongio** [comment]
@shin- Do you have rough ETA for 3.5.0?  Thanks!

**Comment by shin-** [comment]
ETA: an hour or so :slightly_smiling_face:

**Comment by DarthJahus** [comment]
Best ETA ever!

`C:\Python37\Scripts\pip.exe install docker`
`...`
`Successfully installed docker-3.5.0 docker-pycreds-0.3.0`

Thanks, @shin-!
