### ISSUE TITLE
How can I get the full exception in a failed build?

### ISSUE THREAD

**Issue by cinjon** [docker/docker-py#1932]
I'm using this API and building images with `client.images.build(path="/../...", tag='foo:bar', quiet=False, rm=True)`. There is an exception being thrown in one of the DockerFile RUN statements, but the error returned just says `The command <....> returned a non-zero code: 1`. How do I get the full error from that exception?

**Comment by cinjon** [comment]
Hmm, I think I must be doing something silly. If I go to `~/repo` and run `docker build -t foo/bar . -f path/to/directory/DockerFile`, then everything works no problem. If I instead do it in a python environment with 
```
os.chdir('~/repo') 
client.images.build(path="path/to/directory", tag='foo/bar', quiet=False, rm=True)
```
Then it fails at a RUN command where I use pip to install packages from a requirements.txt.

**Comment by shin-** [comment]
The equivalent of your CLI command is `path=., dockerfile=path/to/directory/DockerFile`

**Comment by cinjon** [comment]
Aye, thanks. That works.
