### ISSUE TITLE
Python socket programming Error!

### ISSUE THREAD

**Issue by mkdthanga** [docker/docker-py#1933]
I got the following error when I tried to send a command to my server (Raspberry pi 3) from Windows 10 laptop (client). could anyone help me out with this issue! I'm new to python programming. Im trying to program socket connection between raspberry pi 3 & PC using Python!

Error: (In Git Bash)
mkdth@DESKTOP-4JO9FIB MINGW64 ~/OneDrive/Desktop/python progra
<img width="854" alt="python error socket" src="https://user-images.githubusercontent.com/36918728/36792513-1487bec2-1c9b-11e8-98bc-836b55633903.PNG">
ming
$ python client.py
Traceback (most recent call last):
  File "client.py", line 1, in <module>
    import socket
  File "C:\Users\mkdth\OneDrive\Desktop\python programing\socket.py", line 7, in <module>
    MESSAGE = sys.argv[1]
IndexError: list index out of range

mkdth@DESKTOP-4JO9FIB MINGW64 ~/OneDrive/Desktop/python programing
$

**Comment by shin-** [comment]
This is an issue tracker for the Docker Python SDK. Try stackoverflow.com
