### ISSUE TITLE
How do I use Prune so that it gets all of the images?

### ISSUE THREAD

**Issue by cinjon** [docker/docker-py#1939]
I built an image and then afterward ran `client.images.prune()`. The returned dict stated `{'ImagesDeleted': None, 'SpaceReclaimed': 0}`. I then ran `docker system prune -a -f` and saw that it deleted a lot of space (~1gb). I then tried client.images.remove, but that also did nothing.

What's the correct way of pruning the system from docker-py?

**Comment by nbrady-techempower** [comment]
Running into the same issue, there are actually prunes for everything:

`client.containers.prune()`
`client.images.prune()`
`client.networks.prune()`
`client.volumes.prune()`

Note that you're just calling it on images.

**Comment by robsco-git** [comment]
There also seems to be a discrepancy between using the Python API and the Docker command line for me.

**Comment by rsjethani** [comment]
I also have the same issue with server api version 1.37

**Comment by shin-** [comment]
The `-a` option in the CLI is equivalent to setting the `dangling` filter to `false`. (according to https://github.com/docker/cli/blob/master/cli/command/image/prune.go#L59)

In short, `docker image prune -a -f` translates as such: `client.images.prune(filters={'dangling': False})`

**Comment by rsjethani** [comment]
yes that worked! Thanks. Do we have 'until' filter available?

**Comment by rsjethani** [comment]
Ahh yes 'until' filter also works. But its not mentioned in the docs

**Comment by denisgolius** [comment]
> The `-a` option in the CLI is equivalent to setting the `dangling` filter to `false`. (according to https://github.com/docker/cli/blob/master/cli/command/image/prune.go#L59)
> 
> In short, `docker image prune -a -f` translates as such: `client.images.prune(filters={'dangling': False})`

How to sort docker containers  as it's do the command ?
`docker image prune -a --filter "until=72h"`
