### ISSUE TITLE
docker client.info() Swarm ControlAvailable field meaning + documentation

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker-py#1945]
Hi,

Does the docker `client.info()` field

```
    "Swarm": {
        ...
        "ControlAvailable": true,

```
mean that the node is a Swarm Manager or that there is enough quorum to manage the Swarm?

The doc just says that it maps to the `docker info` command, which appears to have 
```
Swarm: active
 NodeID: ...
 Is Manager: true
```

but it's not 100% clear if this is mapped in this way or if the `docker info` command is inferring if it's a manager by comparing the `NodeAddr` field with the `RemoteManagers` field.

Thanks

Hari

**Comment by shin-** [comment]
Here's how the Docker CLI uses the `ControlAvailable` field: https://github.com/docker/cli/blob/master/cli/command/system/info.go#L274-L275 

This seems to indicate that it is synonymous to "node is a Swarm manager"

HTH

**Comment by HariSekhon** [comment]
@shin- Thanks very much, that's what I thought.
