### ISSUE TITLE
ContainerApiMixin::restart(timeout=...) uses default read timeout which results in ReadTimeout exception

### ISSUE THREAD

**Issue by adw1n** [docker/docker-py#1950]
ReadTimeout is thrown when you restart or stop a container with a high timeout (e.g. 120sec) in case when the container needs over 60 seconds to stop. This requires users to write code like this:
```
try:
    my_container.client.api.timeout = 130
    my_container.restart(timeout=110)
finally:
    my_container.client.api.timeout = docker.constants.DEFAULT_TIMEOUT_SECONDS
```
or write their own `restart` method.

IMO better solution would be to use read timeout that is `max(docker.constants.DEFAULT_TIMEOUT_SECONDS, user_timeout + SOME_CONSTANT)`, because when someone stops a container with specified timeout (`user_timeout`) it's expected that there might be no data to read from the socket for at least `user_timeout`

**Comment by GaboGabitoo** [comment]
> ReadTimeout is thrown when you restart or stop a container with a high timeout (e.g. 120sec) in case when the container needs over 60 seconds to stop. This requires users to write code like this:
> 
> ```
> try:
>     my_container.client.api.timeout = 130
>     my_container.restart(timeout=110)
> finally:
>     my_container.client.api.timeout = docker.constants.DEFAULT_TIMEOUT_SECONDS
> ```
> 
> or write their own `restart` method.
> 
> IMO better solution would be to use read timeout that is `max(docker.constants.DEFAULT_TIMEOUT_SECONDS, user_timeout + SOME_CONSTANT)`, because when someone stops a container with specified timeout (`user_timeout`) it's expected that there might be no data to read from the socket for at least `user_timeout`

my_container.client.api.timeout

**Comment by GaboGabitoo** [comment]
try:
    my_container.client.api.timeout = 130
    my_container.restart(timeout=110)
finally:
    my_container.client.api.timeout = docker.constants.DEFAULT_TIMEOUT_SECONDS
