### ISSUE TITLE
Build context (.tar) is not prepared properly

### ISSUE THREAD

**Issue by DxCx** [docker/docker-py#1953]
Hey,

This morning I've updated to version `3.1.1` however, using this version i'm getting wired error from docker-engine build:
```
ERROR: Error processing tar file(exit status 1): mkdir /foodir/bardir: no such file or directory
```
and the actual building does not start.
took me some time to realise this is related to update i got this morning, 
Reverting back to version `3.0.1`, I could build again.

*NOTE*: `/foodir/bardir` is censored  due to security policy in my company,
so for the sake of this issue, lets assume this is the context:
- Dockerfile
- foodir
  - bardir
    - file

Also, path in error did start with `/` so i kept it there.

**Comment by shin-** [comment]
I'm not able to reproduce the issue with the example you describe:
```
$ tree 
.
├── Dockerfile
└── foo
    └── bar
        └── baz.txt

2 directories, 2 files
$ ipython
[...]
In [1]: import docker

In [2]: docker.version
Out[2]: '3.1.1'

In [3]: c = docker.APIClient()

In [4]: out = c.build('.')

In [5]: for x in out:
   ...:     print(x)
   ...:     
{"stream":"Step 1/2 : FROM busybox"}

{"stream":"\n"}

{"stream":" ---\u003e 5b0d59026729\n"}

{"stream":"Step 2/2 : ADD . /"}

{"stream":"\n"}

{"stream":" ---\u003e 1f811cf2c4b2\n"}

{"aux":{"ID":"sha256:1f811cf2c4b2a26603b27d4980ea50e94d0c2262dc43cbcfd8a7740b5ffdbdbc"}}

{"stream":"Successfully built 1f811cf2c4b2\n"}
```

Is there any more information you could provide that could help us diagnose this? Thanks!

**Comment by DxCx** [comment]
Well, it had much much more files then just those few..
I just gave an example of the error i was getting since i couldnt really share what i am building :/
Ill try to see if i can reproduce that with other sources, however, it looks like it is related to context creation on client side (since server/engine did not update)

Is there any changes around this area on the new version?

**Comment by shin-** [comment]
One thing that could be relevant is that we updated the processing of the  `.dockerignore` file to be more in line with the `docker` CLI (#1914). You might want to check that you're not accidentally excluding a folder that's supposed to be there during your build?

**Comment by DxCx** [comment]
Not intentionally :)
Ill try importing both packages and see if the functions around here returns different values.

Thanks that was very helpful, hope to provide with more info soon :)

**Comment by DxCx** [comment]
Just finished quick review of the patch, i bet thats the root cause for the breaking change in having.
Ill write a small python script to invoke my exculde_patterns om my project with both versions and report back with the findings :)
Helped me a ton! Thanks!

**Comment by mefyl** [comment]
If you give me the .dockerignore and the culprit file, I can assess whether it's included by the current code or not, and whether that's a bug or a feature.

**Comment by DxCx** [comment]
hey @shin- thanks for the fix!
i've just verified updating to 3.1.4 and it works =)
