### ISSUE TITLE
ports mapping error

### ISSUE THREAD

**Issue by crazychl** [docker/docker-py#1964]
Hello! my docker api version is 1.30, and I try to build dind with python , so I need to map the port 2375 inside to the port 7011 of host ,and I use the following code:
`maps = {'8080': '7009', '22': '7007', '2375': '7011', '7014': '7014', '7012': '7012', '7010': '7010'}
self.client.containers.run(detach=True, hostname=hostname, ports=maps)`

but the result is that :
`0.0.0.0:32768->2375/tcp` 
It does not bind the port 2375 correctly!
so how can I fix it?

**Comment by shin-** [comment]
It works fine as far as I can tell:
```python
import docker
c = docker.from_env()
maps = {'8080': '7009', '22': '7007', '2375': '7011', '7014': '7014', '7012': '7012', '7010': '7010'}
ctnr = c.containers.run('busybox', 'top', detach=True, ports=maps, hostname='abccdef')
ctnr.reload()
print(ctnr.attrs['NetworkSettings']['Ports'])
# {'22/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7007'}],
# '2375/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7011'}],
# '7010/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7010'}],
# '7012/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7012'}],
# '7014/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7014'}],
# '8080/tcp': [{'HostIp': '0.0.0.0', 'HostPort': '7009'}]}
```


Maybe it's an issue in your code?

**Comment by crazychl** [comment]
Is it possible that DockerClient will map port to random port in the case of insufficient  memory or CPU resources?

**Comment by shin-** [comment]
Why would CPU or memory have anything to do with port allocation ?
