### ISSUE TITLE
Error': 'Unable to start container' on Azure Data science VM

### ISSUE THREAD

**Issue by GuptaSudhir** [docker/docker-py#1976]
Docker details:::

docker version:
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
 
docker info:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.2-ee-6
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2125.amd64fre.rs1_release.180301-2139)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16GiB
Name: XXXXML
ID: 6TB6:7QZL:BKBJ:IUL5:DGME:TODD:2EXW:IM7G:RUWG:LT4T:AXIX:MGQG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

uname -a:
MSYS_NT-10.0 XXXXML 2.9.0(0.318/5/3) 2018-01-12 23:37 x86_64 Msys

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Environment used is Azure Data Science VM provided by Microsoft

Steps to reproduce the issue:
1. Create a model.pkl, and a service schema json file using GradientBoostAlgorithm in python

>> python .\model.py
C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when
a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
Export the model to model.pkl
Import the model from model.pkl
Score the model to -0.12369722257
Mean Square Error: 10293722662.7
>> python .\score.py
Schema generated

2. Set up an env running on Microsoft Datascience VM using following commands
az ml env setup -n devxxxxxazml -l westeurope
az ml env set -n devxxxxml -g devxxxxrg 

3. Run the following command to create an azure ML web service which then throws up the Error 'Unable to start container'

>>az ml service create realtime -f score.py --model-file model.pkl -s service_schema.json -n test -r python
 model.pkl
Successfully registered model
Id: fb152d55e79a425586858ab926d750d8
More information: 'az ml model show -m fb152d55e79a425586858ab926d750d8'
Creating new driver at C:\Users\DEMOUS~1\AppData\Local\Temp\tmpwqaang2h.py
 score.py
 service_schema.json
Successfully created manifest
Id: a9fe1179-5330-4757-a451-596aaed91380
More information: 'az ml manifest show -i a9fe1179-5330-4757-a451-596aaed91380'
Creating image.........Done.
Image ID: 5314aeeb-3254-4bb3-be17-ec2058022de2
More details: 'az ml image show -i 5314aeeb-3254-4bb3-be17-ec2058022de2'
Usage information: 'az ml image usage -i 5314aeeb-3254-4bb3-be17-ec2058022de2'
[Local mode] Running docker container.
[Local mode] Pulling the image from mlcrpacrd249573866a8.azurecr.io/test:5. This may take a few minutes, depending on your connection speed...
[Local mode] Pulling
{'Error': MlCliError({'Error': 'Unable to start container', 'Response Content': APIError(HTTPError('500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.30/images/create?fromImage=mlcrpacrd249573866a8.azurecr.io%2Ftest&tag=5',),)},), 'Azure-cli-ml Version': '0.1.0a27.post3'}

**Comment by shin-** [comment]
Not an SDK issue.

**Comment by TomasTomecek** [comment]
I would suggest contacting Azure support. As @shin- pointed out, your issue has nothing to do with this project since dockerd returns 500 as you can see in the log. Ideally, run dockerd with debug logs and check what's wrong.
