### ISSUE TITLE
container.status is not reflecting realtime status

### ISSUE THREAD

**Issue by 123swk123** [docker/docker-py#1985]
```python
def launch_and_check(self):
        if self.cnt_enc.status != 'running':
            self.cnt_enc.start()
            wait_cnt = 30
            while (self.cnt_enc.status != 'running') & (wait_cnt != 0):
                print(self.cnt_enc.status)
                time.sleep(1)
                wait_cnt = wait_cnt - 1
            if wait_cnt == 0:
                raise Exception('Unable to start '+CNT_SWK_ENC)
        else:
            print('running already')
```
I am checking the status for every second and status is reported as 'created' for 30sec, even though docker cli says container is running.

the below workaround works, here I am getting new container object every time

```python
def launch_and_check(self):
        if self.cnt_enc.status != 'running':
            self.cnt_enc.start()

            wait_cnt = 30
            while (self.cnt_enc.status != 'running') & (wait_cnt != 0):
                print(self.cnt_enc.status)
                # update container object
                self.cnt_enc = self.dck_clnt.containers.get(CNT_SWK_ENC)
                time.sleep(1)
                wait_cnt = wait_cnt - 1

            if wait_cnt == 0:
                raise Exception('Unable to start '+CNT_SWK_ENC)
        else:
            print('running already')
```

**Comment by shin-** [comment]
you'll need to call `reload()` to get the latest state.

**Comment by shalak** [comment]
@shin- Hi! I also lost some time not knowing that I need to call the `reload()` to get the current `status`. However, once the container is stopped (or failed to start the deamon, i.e. it's exited already) - the `reload()` raises `docker.errors.NotFound: 404 Client Error: Not Found ("No such container: bfd99c790547f27c766c66a29a35c8ef65f431a6baa24004a4e2d0df2b5800d6")` - is there a "nice" way to check the status of possibly already stopped container?
