### ISSUE TITLE
Document return type for `get_archive`

### ISSUE THREAD

**Issue by avirshup** [docker/docker-py#1987]
It's my impression that, as of version 3.0, `get_archive` now returns an iterator over the archive's content rather than a file-like object.

Is this correct? I so, I'd be happy to submit a quick PR to the documentation noting this change.

**Comment by shin-** [comment]
It returns a tuple as specified in the docs. The exact type of the first member of the tuple is an implementation detail ; it should be iterated over to retrieve the file data.

**Comment by avirshup** [comment]
Maybe I'm misunderstanding, but I'd consider the interface of the return type as a fundamental part of the API contract, not an implementation detail. So, it sounds like `Iterable[bytes]` is what we should expect for the stream object - would there be any objection to explicitly stating this in the documentation?

**Comment by shin-** [comment]
We agree ; please make a PR if you feel the documentation needs to be clearer on that point.

**Comment by avirshup** [comment]
Great, will do
