### ISSUE TITLE
How to use a dockerfile not named "Dockerfile" in `images.build(path=..)`?

### ISSUE THREAD

**Issue by stianlagstad** [docker/docker-py#1994]
This works well when my dockerfile is named `Dockerfile` in that path:
```
import os
import inspect
path_to_here = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
client.images.build(
    path=path_to_here,
    tag="myimage"
)
```

Is there a way to make it work and keep it as simple when my dockerfile is named something else, e.g. `Dockerfile.test`?

**Comment by shin-** [comment]
http://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build
