### ISSUE TITLE
How to get command stdout from exec_start with Docker Engine API >= 1.25

### ISSUE THREAD

**Issue by niebelung** [docker/docker-py#1995]
Hello,

I failed to read executed command output using docker-py's  exec_create/exec_start methods on a container on the environment where the Docker Engine API version was 1.26. On another environment with API 1.24 it works fine and returns a result string (and surprisingly an empty generator when passed stream=True). The exec_create was called with the default keyword arguments.
After looking through API docs I found out that /exec/(id)/start indeed returns no stream containing the executed command output on success starting from version 1.25.

So, is there any way to read the command output for versions >= 1.25?

**Comment by shin-** [comment]
[This](https://github.com/docker/docker-py/blob/master/tests/integration/api_exec_test.py#L63-L76) should work fine for all versions of the API.

**Comment by niebelung** [comment]
Thanks! Looks like it works on both environments.
