### ISSUE TITLE
Is there a way to check if the docker daemon is running?

### ISSUE THREAD

**Issue by dmccrevan** [docker/docker-py#1996]
I am currently writing functions to ensure docker is up and running in the system. When I run
```
client = docker.from_env()
print(client.info())
```
This gives me the following error: `requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

I found that this is thrown because the docker daemon is currently not running. Is there a way to check if the docker daemon is running?

**Comment by shin-** [comment]
You can check `client.ping()`, though you'll likely get the same kind of error will be raised if it can't establish a connection to the daemon.

**Comment by dmccrevan** [comment]
@shin- I tried `client.ping()` but go the same error, is there a feature in this SDK that checks this or should I try to use some other way?

**Comment by confiq** [comment]
What's wrong with `try: except DockerException`?

**Comment by dmccrevan** [comment]
@confiq @shin- 

I ended up just using some of the os package's built in features to figure this out.
