### ISSUE TITLE
Handling docker permissions: using a subprocess

### ISSUE THREAD

**Issue by mitar** [docker/docker-py#1998]
So currently the user running this library has to have or root permissions or be in the docker group (which is equivalent to root). For daily development use (I use this library to prepare environments for unit testing) both of these approaches seems dangerous to do on a regular basis.

I would suggest that this library spawns a subprocess which then asks for escaled privileges to root. And then library communicates with that process only. At the time of escalation user could be asked for the root or sudo password. This would allow user to control much better when a regular user (and this library) can access Docker.

A similar issue happens if one is using virtualenv. If you just develop using virtualenv as a regular user and then want to run a script which has to access Docker, but you do not want to have this regular user always permissions of docker group, you can use sudo. But this then breaks out of the virtualenv when executed.

**Comment by shin-** [comment]
Thank you for the suggestion; however, this is outside of the scope this library is designed to cover.
