### ISSUE TITLE
How can see log in real time from build ?

### ISSUE THREAD

**Issue by al3x609** [docker/docker-py#2000]
I try use api , but i need see log process like to docker build command on terminal.  how I can make this here.?
`#!/usr/bin/env python
import docker
import os
route=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
client = docker.from_env()
client.images.build(path=route, tag="test:1.0", rm=True, quiet=False, nocache=True)`

**Comment by shin-** [comment]
http://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build
