### ISSUE TITLE
docker-py : containers.run is not taking the values with string substituion

### ISSUE THREAD

**Issue by beldhia** [docker/docker-py#2004]
I am trying to use docker python SDK and getting into issue when i am trying to use the containers.run command and pass the values as variables using string substitution.

import docker
c= docker.DockerClient(base_url='tcp://ip_addrees_of_host_running_docker:2375') ;#connect to docker
#define some variable
image ='test-image' ; port =50002,p1=str(port);command ='some_command',volume=['/home/test:/opt/rec']
#spawn container 
c.containers.run('image=%s,ports={%d:%s},tty=true,command=%s,volume=%s,detach=True'%(test-image,port,p1,command,volume))
#on running the above command below error is thrown
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error parsing reference: "image=4afda5d85815,ports={5005:5005},tty=true,command='--receiver http --port 5005 -vvv --logfile /opt/tm_recievers/http_50005.txt',detach=True" is not a valid repository/tag: invalid reference format")

**Comment by attex** [comment]
i think you do not have to put these strings in quotes. Just write command=some_command

how does your Dockerfile look like?

**Comment by shin-** [comment]
@beldhia First and foremost, please refer to the [documentation](http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run).

> If `detach` is `True`, a **Container** object is returned instead.

You can call `logs()` on that object to retrieve that container's output.

**Comment by beldhia** [comment]
thanks @attex , my issue is resolved by directory passing the variables now.
 I have another requirement where in i need to pass the argument '-ports' as {portnumber:portnumer/udp} , but when  i am trying to pass it like this {50004:'50004/udp'} it is getting errored, as -ports expects dictionary.
Any suggestion how to get this working.
