### ISSUE TITLE
~/.docker/config.json overrides DockerClient.login()

### ISSUE THREAD

**Issue by corby** [docker/docker-py#2012]
If I use the cli docker tools to log into a custom registry (say AWS ECR) it generated a ~/.docker/config.json entry and caches the creds.

If the creds in the ~/.docker/config,json files are stale, and I use DockerClient.login or DockerClient.images.push with the auth_config parameter, the new credentials are ignored and the python library reads the creds in config.json which are stale.
So the push fails as long as the config.json file exists.

The current workarround is to delete the config.json file before doing a DockerClient.login

**Comment by shin-** [comment]
http://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient.login

> reauth (bool) – Whether or not to refresh existing authentication on the Docker server.
