### ISSUE TITLE
WaitNamedPipe API call in the npipesocket.py module doesn't work correctly from inside a Windows container

### ISSUE THREAD

**Issue by alex-codefresh** [docker/docker-py#2018]
I need to run docker-compose **from inside a Windows container** and make it connect to the **docker daemon on the host** which runs this container via a **named pipe mount** (*like docker run -v //./pipe/docker_engine://./pipe/docker_engine ...*). 

But the problem is that docker-compose uses the WinAPI call **[WaitNamedPipe](https://msdn.microsoft.com/en-us/library/aa365800.aspx)** in the module `npipesocket.py`, which seems is not supposed to work from inside a container and throws the error:

`pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')`

I have carefully checked that the named pipe is mounted correctly and available via the expected name. And I am able to work with the docker daemon on the same mounted named pipe using the docker-cli from inside the container

More details about the issue are here: https://github.com/docker/compose/issues/5934

**Comment by shin-** [comment]
`WaitNamedPipe` is not the issue. The Docker CLI uses it as well: https://github.com/docker/cli/blob/master/vendor/github.com/Microsoft/go-winio/pipe.go#L160 - and nothing indicates that it's not supposed to work from inside a container.

**Comment by alex-codefresh** [comment]
Thanks for the response

That makes sense. I have narrowed it down to a few lines of code and if the issue is not with the API call, then I don't understand why this throws the error:

```
import win32pipe

def connect(address):
        win32pipe.WaitNamedPipe(address, 10000)
        
connect('\\\\.\\pipe\\docker_engine')
```
If is specify any other named pipe, it works, but with with the mounted one it always throws this error. Could you give me some insights on this?

**Comment by atomictrout** [comment]
I'm seeing the same results with microsoft/windowsservercore:1803. The docker cli works fine (docker info) from within the windows container when the named pipe is mounted like this:

> docker run -v //./pipe/docker_engine://./pipe/docker_engine ...

However, trying to access the named pipe in the container from python appears to be an issue.
  File "C:\Python\lib\site-packages\docker\transport\npipesocket.py", line 50, in connect
    win32pipe.WaitNamedPipe(address, self._timeout)
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.').

**Comment by SLdragon** [comment]
WaitNamedPipe API call in the npipesocket.py module doesn't work correctly from inside a Windows container.
This is because currently WaitNamedPipeis not supported from inside of Windows Containers (however CreateNamedPipeClient works ok). It fails with ERROR_FILE_NOT_FOUND

I created a pull request just avoid using WaitNamedPipe API to fix this issue:
https://github.com/docker/docker-py/pull/2421

**Comment by rumpl** [comment]
Closing this since #2421 is merged.
