### ISSUE TITLE
inspect_container on repository image

### ISSUE THREAD

**Issue by dfoderick** [docker/docker-py#2020]
inspection_container only works on a .... er, well, container.
Is there any current support or plans to inspect an image that is not local?

Example: docker inspect fullcycle/web
will show me metadata including the all important LastTagTime.
Inspection_container on the same repository fails.

Edit:
I was wrong. `docker inspect` only shows metadata on the machine that I did the build on.
On another machine the LastTagTime is default date, not updated.

Please close this issue.

**Comment by funkyfuture** [comment]
@dfoderick please close this issue.
