### ISSUE TITLE
handle container exited ?

### ISSUE THREAD

**Issue by ikit** [docker/docker-py#2027]
Hi,

I'm using docker sdk on a web application.
On a specitic request, I run a deteach docker container, and I would like to execute some python when the container finish its job ('exited' status).

It seems that the only to do that is with the `container.wait()` method but it's also blocking my web application.
Is it possible to run this method as a coroutine ?

**Comment by shin-** [comment]
You can poll `container.reload()` -> `container.status` ; or just run `container.wait()` and your post- task in a thread or a celery worker?

**Comment by ikit** [comment]
Yes, it's what I did: waiting in another thread, It works like a charm :+1: .
