### ISSUE TITLE
Docs: How to install a debian package into an ubuntu container?

### ISSUE THREAD

**Issue by fkromer** [docker/docker-py#2029]
How can I install a package, let's say `package` into an pre-existing docker image, let's say into `ubuntu:14.04` without the need to rebuild an image from scratch via [`client.images.build()`](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build)?

**Comment by shin-** [comment]
Images are immutable. If you need to add something to an image, you'll need to create a new image ; the best way to do so is generally to use `build`, but `run` + `commit` can do the trick if you're only interested in adding, say, a single package to a base image.

**Comment by fkromer** [comment]
@shin- Thx a lot. In my case it should be sufficient to consider paramter `changes (str) – Dockerfile instructions to apply while committing` of [`Container.commit()`](https://docker-py.readthedocs.io/en/stable/containers.html?highlight=commit#docker.models.containers.Container.commit) of the running container.
