### ISSUE TITLE
How can I clear container logs?

### ISSUE THREAD

**Issue by fkromer** [docker/docker-py#2030]
I would like to execute several commands in a container using [`container.exec_run()`](http://docker-py.readthedocs.io/en/stable/containers.html?highlight=logs#docker.models.containers.Container.exec_run) and gather the logs after each command execution. Is it possible to clear the container logs (which one gets via [`container.logs()`](http://docker-py.readthedocs.io/en/stable/containers.html?highlight=logs#docker.models.containers.Container.logs)) somehow to achieve that? (It seems like the container logs persist a stopping and restarting of the container... means doing this as workaround is no option.)

**Comment by TomasTomecek** [comment]
AFAIK there is no way of doing that.

How about using the low level exec_create & exec_start API?
```
In [1]: import docker

In [2]: d = docker.APIClient()

In [3]: c = d.create_container("fedora:28", command=["sleep", "infinity"])

In [4]: d.start(c)

In [5]: e1 = d.exec_create(c, ["ls", "/"])

In [6]: d.exec_start(e1)
Out[6]: b'bin\nboot\ndev\netc\nhome\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nrun\nsbin\nsrv\nsys\ntmp\nusr\nvar\n'

In [7]: e2 = d.exec_create(c, ["ls", "/root"])

In [8]: print(d.exec_start(e2))
b'anaconda-ks.cfg\nanaconda-post.log\noriginal-ks.cfg\n'
```

**Comment by fkromer** [comment]
> AFAIK there is no way of doing that.
> 
> How about using the low level exec_create & exec_start API?

I hoped that I could get around the low level API :smirk: . I'd expect something like `e1 = d.exec_run(c, ["ls", "/"])` instead of `e1 = d.exec_create(c, ["ls", "/"])` but the [docs about `exec_create()`](https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.exec_api) clarified things (`"Sets up an exec instance in a running container."`). Thx.

**Comment by fkromer** [comment]
I am forced to use the low level API for all containers [`docker.api.client.APIClient`](http://docker-py.readthedocs.io/en/stable/api.html?highlight=APIClient#docker.api.client.APIClient) and it is not possible to control other containers via [docker.client.DockerClient](http://docker-py.readthedocs.io/en/stable/client.html#docker.client.DockerClient), right?

**Comment by TomasTomecek** [comment]
Why not? Do you have an example?

**Comment by fkromer** [comment]
@TomasTomecek I've not tried it so far. I thought someone have tried before? I can try it later in case...

**Comment by shin-** [comment]
@fkromer The API doesn't let you clear the logs. If you only need the output for the `exec` command, the return value of `exec_run` should handle that. Otherwise, use the `since` argument to limit the amount of logs you're getting each time?

**Comment by fkromer** [comment]
@shin- In this case its not about the `exec` command. But hint about the `since` argument is very helpful, thx.
