### ISSUE TITLE
Update CPU limitation

### ISSUE THREAD

**Issue by guillaume0811** [docker/docker-py#2034]
Hello,

If I set the cpu_period and cpu_quota when I launch the container, I can't update these settings.
I get this error:

> Cannot update container 485d3eef552f2a28c10b393731cee7b887e3de82bed8105b546378241a7a60fe: Conflicting options: CPU Period cannot be updated as NanoCPUs has already been set

How can I update the CPU limitation?

Thanks

**Comment by shin-** [comment]
From the error message, it seems like you're setting `cpus` when creating the container. The Docker daemon subsequently refuses to update period/quota as they're mutually exclusive options.

**Comment by guillaume0811** [comment]
Ok I understand.
Thank you
