### ISSUE TITLE
_create_container_args incorrectly handles volume and device paths that contain a colon

### ISSUE THREAD

**Issue by kavefish** [docker/docker-py#2037]
Calling the create API with a volume or device path containing a colon, e.g.:

```python 
client.containers.create("ubuntu:latest", volumes=['/sys/bus/usb/devices/1-3:1.0:/sys/bus/usb/devices/1-3:1.0'])
```
Results in the following error:

```python
APIError: 500 Server Error: Internal Server Error ("invalid volume specification: '/sys/bus/usb/devices/1-3:1.0:/sys/bus/usb/devices/1-3:1.0'")
```
API should support `--mount` functionality that allows explicit specification of `source` and and `destination` in parameter value. 

docker-py: 3.3.0
Python: 2.7.15rc1
engine: 17.12.1-ce
Ubuntu 18.04

**Comment by shin-** [comment]
Use the recommended dictionary notation:
```python
client.containers.create("ubuntu:latest", volumes={'/sys/bus/usb/devices/1-3:1.0': {'bind': '/sys/bus/usb/devices/1-3:1.0'}})
```

> API should support `--mount` functionality that allows explicit specification of `source` and and `destination` in parameter value. 

It already does. Please consult the documentation.

**Comment by kavefish** [comment]
I consulted the documentation and tried exactly what you suggested prior to submitting the bug report because it results in exactly the same error.
