### ISSUE TITLE
exec_run adds random char

### ISSUE THREAD

**Issue by chris3081** [docker/docker-py#2044]
Not sure what I'm doing wrong here but I keep getting a random char in the middle of the stream.. 

**example code chunk**

            cont = self._client.containers.get(container)
            result = cont.exec_run(cmd='/bin/ls', tty=False, stream=True, socket=True)
            for line in result.output:
                print(line.decode())

**outputs:**
$ python test.py
Lbin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var
vault

Process finished with exit code 0

a debug on the with with bin shows an extra char

b'\x01\x00\x00\x00\x00\x00**\x00L**bin\n'

Anyone know what this is and why?

Running Ubuntu 16.04
Server - Docker  1.13.1

Python Version: Python 3.5.2

**pip3 list**

Package           Version
----------------- ----------------------
certifi           2018.4.16
chardet           3.0.4
command-not-found 0.3
docker            3.3.0
docker-pycreds    0.2.3
idna              2.6
language-selector 0.1
pip               10.0.1
pygobject         3.20.0
python-apt        1.1.0b1+ubuntu0.16.4.1
requests          2.18.4
setuptools        20.7.0
six               1.10.0
ssh-import-id     5.5
ufw               0.35
urllib3           1.22
websocket-client  0.48.0
wheel             0.29.0

**Comment by thaJeztah** [comment]
If there's no TTY attached, the API uses a stream format that pretends each line with 8 bytes that can be used to (eg) determine if a line was printed on `stdout` or `stderr`; see https://docs.docker.com/engine/api/v1.37/#operation/ContainerAttach

**Comment by chris3081** [comment]
Thanks @thaJeztah, so based on that I'm guessing I need to write a handler in my code to determine that or is this something that should be handled in the exec_run code?

**Comment by TomasTomecek** [comment]
But docker-py should take care of that: https://github.com/docker/docker-py/blob/22b7b76142bd735c6be4f678dda8cf9d413e9f1c/docker/api/exec_api.py#L165

I would say it's a bug when such leftovers are left in place.

**Comment by thaJeztah** [comment]
> But docker-py should take care of that

Hm, looks like it should yes (sorry not too familiar with the docker-py codebase; my eye just fell on this ticket)

To be sure these random characters are indeed the 8-bytes of stream information; @chris3081 what happens if you start the container without `TTY`; do the random characters disappear? (In that case it would attach to the container output, and don't add the stream information)

**Comment by chris3081** [comment]
Good point @thaJeztah I've done some quick testing... I only see the random artifact when streaming is on and tty is off. 

Settings:
stream=False
scoket=False
tty=False
Output:  No artifact, output displays correctly with no formatting/colours

Settings:
stream=False
scoket=False
tty=True
Output: No artifact, output displays correctly with ansi formatting/colours

Settings:
stream=True
scoket=True
tty=False
Output: Artifact is present,  output shows Artifact on first line with directory, the rest of the output is correct with no formatting/colours

Settings:
stream=True
scoket=True
tty=True
Output: No Artifact, output displays correctly with ansi formatting/colours

**Comment by shin-** [comment]
You're asking for the raw socket, so no decoding is done by the SDK, causing the stdout/stderr byte to appear.

This is working as intended. 👍

**Comment by chris3081** [comment]
Is there a way I can stream the output but have the decoding done for me?

**Comment by shin-** [comment]
Yes - just don't set `socket` to `True`?

**Comment by chris3081** [comment]
your right @shin-  my bad, I appear to have misunderstood the documentation, I made the assumption that it was required due to it crashing out in windows without it being enabled. I've since found that that is due to issue #1997
