### ISSUE TITLE
Cannot create service with read_only attribute due to missing comma in CONTAINER_SPEC_KWARGS

### ISSUE THREAD

**Issue by jekyc** [docker/docker-py#2046]
Hi,

There seems to be a typo on the following line, which is missing a comma.

https://github.com/docker/docker-py/blob/22b7b76142bd735c6be4f678dda8cf9d413e9f1c/docker/models/services.py#L279

The effect of this, is that it is not possible to use the read_only flag for services.

**Comment by shin-** [comment]
Thanks for the report! Feel free to submit a PR!
