### ISSUE TITLE
Rename container no work fine on terminal output

### ISSUE THREAD

**Issue by al3x609** [docker/docker-py#2057]
`import docker`
`import time`
`client = docker.from_env()`
`cont = client.containers.run("ubuntu:latest", detach=True, name="ubuntu")`

`print(cont.attrs['Name'])`
`cont.rename("centos")`
`time.sleep(5)`
`print(cont.attrs["Name"])`

this code work fine, this rename the container but when run in the console, 
the output show "_ubuntu_" two times, Why?

![image](https://user-images.githubusercontent.com/4086644/41212436-85255bf4-6d03-11e8-9e9c-51406b90be5d.png)

Im using last API and python3.7
and this also happens with PyCharm CE IDE

**Comment by TomasTomecek** [comment]
This is a cached property: `cont.attrs["Name"]`, you should [reload](https://github.com/docker/docker-py/blob/master/docker/models/resource.py#L43) the metadata.
