### ISSUE TITLE
came across a issue, i need pip install docker-py or docker

### ISSUE THREAD

**Issue by xiaods** [docker/docker-py#2064]
why the example is not working on my mac
```
$ python
Python 3.6.5 (default, Mar 30 2018, 06:42:10) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.from_env()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'docker' has no attribute 'from_env'
```

**Comment by shin-** [comment]
You probably installed an old version of the package. Make sure you install the latest version.

**Comment by xiaods** [comment]
@shin- hi , i am confuse the package name: the Pypi have two version:
https://pypi.org/project/docker-py/
https://pypi.org/project/docker/

because my ansible dependency is docker-py, so i have install it, but it not working. i am currently dig the root cause.

**Comment by shin-** [comment]
`docker-py` is the old version of the package (latest release 1.10.6 which was several years ago). You can find the documentation for it here: http://docker-py.readthedocs.io/en/1.10.6/ - `docker.from_env()` was not part of the library back then.

I highly recommend using the `docker` package for new projects. Use a virtual environment to avoid conflicts with ansible.

**Comment by xiaods** [comment]
@shin got it.
