### ISSUE TITLE
APIError not raised when I create container with none image

### ISSUE THREAD

**Issue by WellingtonLucas** [docker/docker-py#2070]
I'm using SDK version 2.1.0; Docker version 1.13.1; API version 1.26; Python version 2.7; OS Ubuntu 16.04 LTS.

My code:
```
import docker
from docker import errors

client = docker.DockerClient(base_url='unix://var/run/docker.sock')

def test_create_container_none_image(self):
        with self.assertRaises(docker.errors.APIError):
            client.containers.create(None, 'ls', detach=True, name='alpine_test')

```
My output is "AssertionError: APIError not raised", and no other exception is raised.

With docker events, I received something like this:
`{"status":"create","id":"251980e10ca55f6658a4ebfa5b3c9f6ef80cb3f9ec45ed7dd895fa6384e80364","Type":"container","Action":"create","Actor":"ID":"251980e10ca55f6658a4ebfa5b3c9f6ef80cb3f9ec45ed7dd895fa6384e80364","Attributes":"name":"alpine_test"}},"time":1529633156,"timeNano":1529633156082904432}`

**Comment by TomasTomecek** [comment]
I'm using SDK version 1.24

There is no such version. `1.10` is the last minor release of version 1.

**Comment by TomasTomecek** [comment]
Can you also reproduce with the latest PyPI release?

**Comment by ijc** [comment]
Closing since this seems to have gone stale.
