### ISSUE TITLE
Info Request - Functional repalcement for build.stream?

### ISSUE THREAD

**Issue by jasonterando** [docker/docker-py#2080]
Minor UX issue...

HI, I have an old Python script that I've been using to build Docker images (using the low-level API) and push them to ECS.  I was using the build.stream parameter to capture streamed output during the build, show progress and detect errors.   Obviously, I had not updated docker-py for a while :)

After updating docker-py, build.stream is gone.  I can still get the output after the build, parse and display it, but I have lost the ability to display "progress".  Is there any ability to capture the stream output as build is running, or is that gone now?  Not a big deal if it is, just wondering.

**Comment by shin-** [comment]
Should still work the same as it used to:

```python
import docker

c = docker.APIClient()
stream = c.build('.', dockerfile='Dockerfile.run', rm=True)
for chunk in stream:
    print(chunk)
```

**Comment by devnore** [comment]
> Should still work the same as it used to:
> 
> ```python
> import docker
> 
> c = docker.APIClient()
> stream = c.build('.', dockerfile='Dockerfile.run', rm=True)
> for chunk in stream:
>     print(chunk)
> ```

This will do the building and when done display the log. Is there a way to display the output as it happens?

**Comment by shin-** [comment]
@devnore The `APIClient.build` method still works the same as it always has. `DockerClient.images.build` does behave as you describe - you should pick the tool that best matches your needs.
