### ISSUE TITLE
CancellableStream: AttributeError: module 'urllib3.contrib' has no attribute 'pyopenssl'

### ISSUE THREAD

**Issue by JayH5** [docker/docker-py#2082]
Hi there 👋,

It looks like 40711cb50189c4c39ed5a60c16910646a00f9acc introduced code that requires that `docker` is installed with the `tls` extra: https://github.com/docker/docker-py/blob/1e389b7cfe12eb04685d331a640cd8dac77206d1/docker/types/daemon.py#L60-L61

The `urllib3.contrib.pyopenssl` package is only available if the `tls` extra requirements are installed and I get an error like `AttributeError: module 'urllib3.contrib' has no attribute 'pyopenssl'` otherwise.

I don't _think_ it's necessary to install the `tls` extras for non-Windows, non-Python 2 platforms to have working HTTPS and it doesn't seem intentional that this is a requirement to use streams.

I'll try write a small PR to fix this.

**Comment by shin-** [comment]
Thanks for the report! I ended up fixing this as part of the work I was doing on #2165
