### ISSUE TITLE
Docker images sorted

### ISSUE THREAD

**Issue by GaboFDC** [docker/docker-py#2084]
I'm not totally sure if this is the right place to ask, but I didn't found any hint about this.
When I call the `client.images.list()` the returned list is in the same order than doing a `docker images` command.
This images seems to be sorted from newer to oldest. 
Will this always be sorted in this way? is there any guarantee that when I call this function, the last item of the list will always be the oldest image? or is just "coincidence" and if i want to get the oldest image is better to try some other method?

**Comment by shin-** [comment]
The source of truth for questions such as this one is the [API documentation](https://docs.docker.com/engine/api/v1.36/#operation/ImageList).

As you can see, it makes no guarantee that the image list will be ordered a certain way, so I wouldn't rely on it behaving a certain way.
