### ISSUE TITLE
[Question] Get docker client in gitlab-ci

### ISSUE THREAD

**Issue by fkromer** [docker/docker-py#2095]
I implemented tests which use `docker.from_env(version='auto')` to span some containers. On a plain local machine they are running just fine. But if I run these same tests locally in a docker container via `gitlab-runner exec docker ...` they fail because of `DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))`.

How can I get a docker client in a docker container run with `gitlab-runner exec docker...`?

**Comment by TomasTomecek** [comment]
This looks like a question for `gitlab-runner` project.

`No such file or directory` in this case usually means that the `docker.sock` is not present. So this indeed is probably a bug in `gitlab-runner` or a misconfiguration.

**Comment by fkromer** [comment]
@TomasTomecek Thx for the fast response. I'll post the question in the `gitlab-runner` project in case I don't get an answer to this [question on stackoverflow.com](https://stackoverflow.com/questions/51493037/how-can-i-get-a-docker-client-with-docker-py-inside-a-gitlab-ci-docker-container).
