### ISSUE TITLE
Interactive container - prompt for user input?

### ISSUE THREAD

**Issue by ScottBrenner** [docker/docker-py#2100]
Follow-up to #390.

In short, trying to do something like this with `docker-py`:
```
$docker run <...>
Name: <user input here>
```

I'm not able to get user input with `docker-py`, is this possible? Adding `stdin_open = True, tty = True` does not print the input prompt (like `Name:` above) - merely drops me into a shell where commands do nothing:

```
$<run my docker-py stuff>

why
no
prompt?
```

So, how can I prompt for and pass along user input?

**Comment by shin-** [comment]
It is possible. Check https://github.com/d11wtq/dockerpty for example.

**Comment by ScottBrenner** [comment]
Nice, thank you!

**Comment by grahamlyons** [comment]
@gaborbernat, I think it might just need the documentation to be updated: https://github.com/d11wtq/dockerpty/issues/79#issuecomment-464497516
