### ISSUE TITLE
implementation of inspect subcommands

### ISSUE THREAD

**Issue by Tryph** [docker/docker-py#2112]
Hi and thanks for the great and useful work on this tool.

Trying to inspect a network in order to find the gateway's IP, I did not find any way to do this via the docker-py module.

I found that the low-level API allows to inspect a container but it seems there is nothing to inspect a network. I have been forced to use subprocess to run a `docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' <network>` command, which is exactly what I wanted to avoid and the reason why I use docker-py

So I suggest to add the ability to inspect anything inspectable via the `docker` client and ideally to allow it via the hight-level API.

I would like to do a PR, but honestly I don't think I will have time for this. But I will be happy if it this feature is implemented one day :)

EDIT: hmm well... just seen that I should have looked better in the low level API doc... there is a function to inspect networks. This "issue" can be closed.

**Comment by shin-** [comment]
Glad you could find it. For the record, the equivalent of `inspect_network` in the high-level API is `client.networks.get("network_id").attrs`
