### ISSUE TITLE
containers.run with logstash

### ISSUE THREAD

**Issue by bahadircolak44** [docker/docker-py#2114]
Hello guys,
I really need help. I am completely lost. I need to run logstash container on python. On terminal I use 

`docker run -it -p 9563:9563 --rm -v "$PWD":/config-dir logstash-cont -f /config-dir/logstashConf.config`

and it is running perfectly but I couldn't figure out how to give my parameters for containers.run(...)

**Comment by shin-** [comment]
http://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run
