### ISSUE TITLE
Should provide a way to work with Docker hub repositories

### ISSUE THREAD

**Issue by arycloud** [docker/docker-py#2118]
There isn't any Class/method to work with Docker hub repositories, before pushing images we need to make repositories in case of private repos, that's why I think it should a way to interact with registries and repositories.

**Comment by shin-** [comment]
Hi @arycloud 

Thanks for your suggestion. The purpose of this library is to specifically provide bindings for the Docker Engine API. I see how an API client for Docker Hub would be useful, but I think it'd be overextending too much to include it here.
Additionally, I don't think there's a public, official API for Hub.
