### ISSUE TITLE
docker checkpoint error

### ISSUE THREAD

**Issue by wekay102200** [docker/docker-py#2123]
I have create checkpoint success with command docker checkpoint create 4ebe6d0d282b ttt,the checkpoint  create success.but when i use command docker checkpoint ls 4ebe6d0d282b,it happen error below:
_**ubuntu@ip-172-31-2-111:~$ docker checkpoint ls 4ebe6d0d282b
_Error response from daemon: open /var/lib/docker/containers/4ebe6d0d282b03779dc167d78bf96410edfc9c68d464a14fac0eab092b9fd078/checkpoints/ttt/config.json: no such file or directory_**_
my docker and os information is as below:
**_ubuntu@ip-172-31-2-111:~$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: true_**

**my os is Ubuntu Server 16.04 LTS.**

**Comment by wekay102200** [comment]
![2018-08-24_105453](https://user-images.githubusercontent.com/18589915/44562609-e25ff680-a78c-11e8-96d9-af1fff5d183b.png)

**Comment by shin-** [comment]
Hi @wekay102200 

I don't think this is a Python SDK issue. Please report it there instead: https://github.com/docker/for-linux/issues
