### ISSUE TITLE
image.save() is missing image name and tag

### ISSUE THREAD

**Issue by Cherishty** [docker/docker-py#2124]
When I am using image.save() provided in py-SDK to save my local image `<repo>/<image>:<tag>` to tarball, then run 
> docker load -i 

to load tar, load image successfully but both image name and tag are `<none>`, while
> docker save -o does NOT have this issue.

Comparing two tar balls which generate by py-SDK against command line, I find the former one does not contains a file called `repositories`, which should  contains below content:

`{"<repo>/<image>":{"<tag>":"<sha256_id>"}}`

Why image.save()  is missing this file? how to fix it?

**Comment by shin-** [comment]
Thanks for the report, that's indeed a bug on our end.

You can work around the issue by using `client.api.get_image('<repo>/<image>:<tag>')` in the meantime instead.
