### ISSUE TITLE
Question: Python api over Docker command like to standar

### ISSUE THREAD

**Issue by al3x609** [docker/docker-py#2125]
Is it possible to force only the use of the API to communicate with the docker daemon and block the use of the _docker_ _command_?

**Comment by shin-** [comment]
I imagine you could add a thin proxy in front of the Docker Engine that filters requests based on the declared `User-Agent` in the request's headers.

**Comment by TomasTomecek** [comment]
Users can do the same thing: write a proxy which will translate the `user-agent`s to the expected one. #just-sayin
