### ISSUE TITLE
"attrs" attribute from Container and Network seem not to be updated

### ISSUE THREAD

**Issue by askorski-fc** [docker/docker-py#2128]
Hi,

### First, a bit of context:

Using docker-py v3.5.0
For testing purpose I build a docker environment by:

1. importing and creating a docker client:

```
import docker as docker_module
docker = docker_module.from_env()
```

2. creating a "platform" network:

`network = docker.networks.create('platform')`

3. running containers providing them the network name:

```
lumis = docker.containers.run(
    '<image>:<tag>',
    name='lumis', detach=True,
    auto_remove=True,
    ports={8000: None},
    network=network.name,
)
```

### Then, what I am trying and the issue:

I am currently trying to get the ip address of the "lumis" container from its `Container` instance and it remains empty:

```
(Pdb) type(lumis)
<class 'docker.models.containers.Container'>
(Pdb) lumis.attrs['Id']
u'8e6919c42f7fad9fb4857eb42843f5bff731bf8a734750a66cf57624dd7ef4db'
(Pdb) lumis.attrs['NetworkSettings']['Networks']['platform']['IPAddress']
u''
```

In the same time, accessing the info via the `docker inspect` command works well:

```
$ docker inspect lumis -f '{{.Id}} {{.NetworkSettings.Networks.platform.IPAddress}}'
8e6919c42f7fad9fb4857eb42843f5bff731bf8a734750a66cf57624dd7ef4db 172.18.0.3
```

As you can see, the id of the container is identical in both methods but the IPAddress is different.
In fact, all "platform" network information is empty using `Container.attrs`:

```
(Pdb) pprint(lumis.attrs['NetworkSettings']['Networks']['platform'])
{u'Aliases': None,
 u'DriverOpts': None,
 u'EndpointID': u'',
 u'Gateway': u'',
 u'GlobalIPv6Address': u'',
 u'GlobalIPv6PrefixLen': 0,
 u'IPAMConfig': None,
 u'IPAddress': u'',
 u'IPPrefixLen': 0,
 u'IPv6Gateway': u'',
 u'Links': None,
 u'MacAddress': u'',
 u'NetworkID': u''}
```

Note that trying to access the wanted information by the network does not work better, since it returns an empty list of containers for the network:

```
(Pdb) type(network)
<class 'docker.models.networks.Network'>
(Pdb) network.name
u'platform'
(Pdb) network.attrs['Containers']
{}
```

Still in the same time, `docker network inspect` returns the correct information:

```
$ docker network inspect platform -f "{{.Containers}}"
map[
    bf1629c97f80927a040bcf2c699da89329469dc6d20f8a79192118a8a1a700de:{lumis 259aef734e1d94d3f16e4a1a0bdaf1f6e10f318f1fcd0b4323c656e292452d63 02:42:ac:12:00:03 172.18.0.3/16 }
    ...
]
```

Please let me know if I am using something the wrong way or if more information is needed.

---------------

For convenience, here is a simple script which highlights the issue:

```python
import subprocess
import docker as docker_module


docker = docker_module.from_env()

network = docker.networks.create('my_network')
container = docker.containers.run(
    'python:2-alpine',
    name='my_container',
    detach=True,
    auto_remove=True,
    ports={8000: None},
    network=network.name,
)

container_ip = (
    container.attrs['NetworkSettings']['Networks'][network.name]['IPAddress'])
network_containers = network.attrs['Containers']

print 'docker-py info:'
print '\tcontainer ip: {}'.format(container_ip)
print '\tnetwork_containers: {}'.format(network_containers)


container_ip = subprocess.check_output([
    'docker',  'inspect',  container.name, '-f',
    '{{.NetworkSettings.Networks.%s.IPAddress}}' % network.name
]).strip()
network_containers = subprocess.check_output([
    'docker', 'network', 'inspect', network.name, '-f', '{{.Containers}}'
]).strip()

print 'docker inspect info:'
print '\tcontainer ip: {}'.format(container_ip)
print '\tnetwork_containers: {}'.format(network_containers)


container.stop()
network.remove()
```

**Comment by shin-** [comment]
You need to call `reload()` to update attributes: https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.reload

**Comment by Tryph** [comment]
Thanks for the quick answer, it works perfectly.

I suggest to mention the `reload` method in the `attrs` descriptions to avoid further questions like this one.

**Comment by askorski-fc** [comment]
Thanks for the quick answer, it works perfectly.

I suggest to mention the reload method in the attrs descriptions to avoid further questions like this one.
