### ISSUE TITLE
docker 3.5.0 python API documentation

### ISSUE THREAD

**Issue by nkaliape** [docker/docker-py#2134]
On Python 3 env:
 pip list | grep docker
docker           3.5.0    
docker-pycreds   0.3.0    

We are able to connect to the docker installed server (which is remote).
But the API is broken similar to that of #1796 

@shin- Kindly help with resolution. Thanks in advance.

>>> cl = docker.APIClient('tcp://172.28.240.101:2376')
>>> cl.containers
<bound method ContainerApiMixin.containers of <docker.api.client.APIClient object at 0x10b9da2e8>>
>>> cl.containers.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**_AttributeError: 'function' object has no attribute 'list'_**
>>> docker.__version__
'3.5.0'
>>> cl.containers()
[{'Id': '3d1659c58d4d283a086ba85367bc ...

**Comment by shin-** [comment]
You're using the `APIClient` but you're trying to call methods from the `DockerClient`. Please refer to the documentation.
