### ISSUE TITLE
Streaming Logs Asynchronously

### ISSUE THREAD

**Issue by Immortalin** [docker/docker-py#2136]
Is it possible to have an async version of the logging function that would only yield when it has content?

**Comment by Immortalin** [comment]
Or to rephrase, what's the best way to dump logs to a browser asynchronously without blocking flask?

**Comment by mile95** [comment]
Hi! 

Did you manage to solve this or find a workaround? Thanks!

**Comment by mile95** [comment]
For anyone else wanting to stream the logs asynchronously , https://github.com/aio-libs/aiodocker makes it possible!

**Comment by bonastreyair** [comment]
@mile95 how exactly...? I'm trying to do:
```python 
async for chunk in container.log(stdout=True, follow=True):
    print(chunk.strip())
```
but I only get all logs at once when the docker job finishes and not as an async iterator
I'm using latests 0.21.0 version of aiodocker, Thanks! :pray:
