### ISSUE TITLE
Docker pull command inconsistent with client.images.pull

### ISSUE THREAD

**Issue by thomasyu888** [docker/docker-py#2151]
```
import docker
docker.version
'3.5.0'
client = docker.from_env()
client.images.pull("ubuntu")
```

The above will try to pull every tag.  But from command line:
```
docker pull ubuntu
```
Will only pull the `:latest` tag.

I know an easy solution is just to:
```
client.images.pull("ubuntu:latest")
```

Just thought I would point out the inconsistency.

**Comment by shin-** [comment]
Thanks for the report! This is working as intended: https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.pull
