### ISSUE TITLE
Ability to list all available tags in remote registry

### ISSUE THREAD

**Issue by circa10a** [docker/docker-py#2160]
I don't see any of this functionality listed in the docs, nor could I find an issue with related information.

This would be a really nice and helpful feature to have.

**Comment by shin-** [comment]
Thanks for the suggestion! However, unless that functionality becomes part of the [Docker Engine API](https://docs.docker.com/engine/api/v1.37/) at some point, it is out of scope for this project.

You may be interested in the following projects instead:
- https://github.com/davedoesdev/dxf
- https://github.com/yodle/docker-registry-client
