### ISSUE TITLE
Please support docker build --secret API as in Docker 18.09

### ISSUE THREAD

**Issue by haizaar** [docker/docker-py#2174]
Good day,
It will be nice to be able to do 
```
docker build --secret id=mysite.key,src=path/to/mysite.key .
```
through the API.

Thank you.

**Comment by haizaar** [comment]
Can anyone please update whether there are any plans to have this implemented soon?

**Comment by shin-** [comment]
That feature depends on buildkit, which is very difficult to support in the Python library in its current state. We're aware of it and some work will happen to make that integration easier, but there's no ETA at the moment.

**Comment by chris-crone** [comment]
@haizaar I've created an issue to track BuildKit support [here](https://github.com/docker/docker-py/issues/2230). I'll close this specific issue and reference it from there.
