### ISSUE TITLE
Package docker-py for ubuntu, fedora...

### ISSUE THREAD

**Issue by julienvey** [docker/docker-py#218]
We are trying to integrate docker-py into openstack requirements.
In order to do this, it needs to be packaged for at least ubuntu and fedora
Here is the review concerned https://review.openstack.org/#/c/76535/

Are there any plans about this ?

**Comment by bfirsh** [comment]
https://apps.fedoraproject.org/packages/python-docker-py
http://packages.ubuntu.com/search?keywords=python-docker

Looks like we're all good here.

**Comment by Frodox** [comment]
@tianon 
@bfirsh 

hi! what about supporting `docker` package also?
I used `python-docker`, but just faced with https://github.com/ansible/ansible/issues/42162 , and there are info 

> docker-py is no longer maintained (last release from November 2016), you should install docker instead

So... after uninstalling `python-docker` and installing `pip install docker` it works, but it would be great to install it as deb-package, and not pip-package.
