### ISSUE TITLE
Issue with getting a log from a detached container...

### ISSUE THREAD

**Issue by isvogor-foi** [docker/docker-py#2190]
Hi!
So I'm using python to start an existing container, as:
`my_container.start()` 
and then, I want to execute some long lasting script inside, and I do so by:
`my_container.exec_run('script.py', detach=True)` . So I'm detaching and doing something else... 
However, I have no access to the log what so ever. I've tried out various options and it seems I'm loosing options. Any ideas how to pickup the output that the script.py is outputing to stdout? 
Thanks!

**Comment by shin-** [comment]
You can't retrieve logs of an exec session you've `detach`ed from. You probably want to do the following instead:
```python
container.start()
result = container.exec_run('script.py', stream=True)
# something else...

for chunk in result.output:
  print(chunk)
```
