### ISSUE TITLE
3.6.0 not on readthedocs

### ISSUE THREAD

**Issue by adamchainz** [docker/docker-py#2191]
Version 3.6.0 is in the changelog file: https://github.com/docker/docker-py/blob/master/docs/change-log.md but not rendered on readthedocs: https://docker-py.readthedocs.io/en/stable/change-log.html . Is the readthedocs build broken? I've had it break on me before without me noticing.

**Comment by shin-** [comment]
Sorry, I forgot to trigger it. Should appear in a few minutes. Thanks for pointing it out!
