### ISSUE TITLE
3.6.0 sdist doesn't match the tag in the repository

### ISSUE THREAD

**Issue by benjaminp** [docker/docker-py#2194]
The docker package 3.6.0 sdist contains the file `docker/api/mixin.py`
```
$ curl -s https://files.pythonhosted.org/packages/cc/9c/50ec68951d10fc341b650a2f5a6ed3925f7e4adc245113acfe64eb61f46a/docker-3.6.0.tar.gz | tar tz | grep mixin
docker-3.6.0/docker/api/mixin.py
```
but this file doesn't appear in [the tag for the 3.6.0 release](
https://github.com/docker/docker-py/tree/3.6.0/docker/api).

**Comment by shin-** [comment]
My bad, it's a file I've been working on and forgot to clean up when cutting the release.

It doesn't affect the rest of the code in any way and is otherwise safe to ignore.
