### ISSUE TITLE
Add ability subscribe to socket and watch for container changes

### ISSUE THREAD

**Issue by Koc** [docker/docker-py#2195]
Hi! I want to create some small  daemon (like Traefik) which will listen socket and execute some actions when container starts or stops. Would be nice add some api for that.

**Comment by TomasTomecek** [comment]
https://docker-py.readthedocs.io/en/stable/api.html#docker.api.daemon.DaemonApiMixin.events

**Comment by Koc** [comment]
Wow, nice. Thanx
