### ISSUE TITLE
No std way to parse JSON status dicts to human readable format?

### ISSUE THREAD

**Issue by Addvilz** [docker/docker-py#2205]
`docker.api.build.BuildApiMixin#build`, among others, returns generator that can be consumed via `docker.utils.json_stream.json_stream` to obtain dicts of parsed status objects. Is there anything to convert these dicts to "human readable" format?

**Comment by shin-** [comment]
This library doesn't provide any formatting utilities if that's what you're asking.
You could look at how these streams are handled [in Compose](https://github.com/docker/compose/blob/master/compose/progress_stream.py) and reuse it or write something similar.

HTH!
