### ISSUE TITLE
i can't enter container ?

### ISSUE THREAD

**Issue by CyberTheReape** [docker/docker-py#2220]
hello. i did install vpn server in my vps machine. my vpn server working in docker. I want to enter into the docker but can't enter

CONTAINER ID--------IMAGE--------------------------------------------COMMAND---------------------- NAMES
178c21ef3157----------v2tec/watchtower------------------------------"/watchtower --clean.."---------"watchtower
118fcccda226-----------quay.io/outline/shadowbox:stable---------"/bin/sh -c /cmd.sh"--------------shadowbox

root@debian-s-4vcpu-8gb-ams3-01:~# docker exec -it shadowbox bash

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

root@debian-s-4vcpu-8gb-ams3-01:~# docker exec -it watchtower bash

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

whhat is problem ?

**Comment by shin-** [comment]
Your container doesn't include bash. Try `sh` instead.

Also this is the wrong repo.

**Comment by CyberTheReape** [comment]
Yes i know  . But i cant write other repo.  İ did write sh , shadowbox is opening.. but watchtower container not opening with sh.
İ am using outline manager vpn server. Now i want forward my vps port to docker container. İ will forward ports in container to my home computer.

EXAMPLE;
Vps port and ip》container 》vpn 》home

İ am using ipv6 ip address in my home. İ cant open port in my modem. İ did install vpn server for it. My vpn server working now. But i want use my vps ports with vpn ip address. There were 2 separate containers because I installed vpn server with docker.help me now please.if i can do this job i will feed 40 poor people.i don't have much information about docker yet.I need the help of professional craftsmen like you.handsome boy waiting for answer.
@shin-
