### ISSUE TITLE
Health property/method for Container object

### ISSUE THREAD

**Issue by wonderchang** [docker/docker-py#2229]
Is it possible to provide some properties or methods related to [HEALTHCHECK](https://docs.docker.com/engine/reference/run/#healthcheck) in Container object? This is convenient to know the HEALTHCHECK result by using much simpler way rather than just calling Low-level API [`inspect_container`](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.inspect_container).

I found someone had proposed before https://github.com/docker/docker-py/pull/1726 but it's long time ago, so is there any plan?

---

And I think it is great if there is a method `Container.raise_for_health(timeout)` that can check container itself whether is healthy or not until timeout. The spec may like below:

  1. Return `None` when it changes to `healthy` status before timeout
  2. Raise `HealthCheckError` exception when it changes to `unhealthy` status before timeout
  3. Raise `HealthCheckTimeout` exception when it reach the timeout (still `starting` status)

Then, the client usage will like,

```python
client = docker.from_env()
container = client.containers.run('nginx', healthcheck={'test': 'curl localhost'})
container.raise_for_health(timeout=60)
```

**Comment by chris-crone** [comment]
Hi @wonderchang! Thanks for the suggestion!

I think that this is too high-level and specific for the SDK. If one needs to check the health of a container; I'd expect that this would be done via an inspect and some logic in the application code. This would match the pattern that we have in our [Go client](https://github.com/docker/cli).

**Comment by wonderchang** [comment]
Sure, but how about the **health property**? Like other essential properties `id`, `name`, and `status`.

**Comment by chris-crone** [comment]
@wonderchang The health of a container is volatile unlike the static properties you listed. The SDK would have to either keep the property up to date asynchronously or update it on each call. Neither of those are really good solutions.

I think it's best to push this kind of work to the end developer so that it's visible to them.

**Comment by chris-crone** [comment]
Looking a bit more, some of the other properties are also volatile (like `status` and `label`). @shin- Is there a specific reason we don't have a health property?

**Comment by wonderchang** [comment]
@chris-crone Thank you for answering!

In my point of view, when you start to implement `Container` object, you are not just a SDK at all. It becomes more high-level abstractions and has more detail encapsulations. And to be Pythonic, it is worth to wrap them for high-level usage because the client code will looks very simple and readable.

**Comment by shin-** [comment]
The idea is to avoid the proliferation of properties that in turn need to be maintained and may appear in different locations in the attribute dictionary depending on the API version. As a result, we limit the number of quick access attributes to a few essentials. And to that point, I would personally disagree with the notion that a `health` attribute is essential; most containers do not use healthchecks at all.

**Comment by wonderchang** [comment]
> most containers do not use healthchecks at all.

Why? People tends to check from the outside container?

**Comment by roblevy** [comment]
FYI, I've hacked together a response to [this SO question](https://stackoverflow.com/q/60291082/2071807) before I knew that you'd already rejected the idea of waiting on a health check.

For things like database engines, waiting on a health check is vital because the container will be "Started" long before the database is up and running.

**Comment by maiamccormick-toast** [comment]
I get the reasoning for not supporting health check result as a `container` property, but in case another datapoint is useful, this functionality would make a LOT of sense for my current project. (We got it working with @roblevy's hack linked above, but it's weird from a readability/code ergonomics perspective to have a separate docker API client for something you expect to be supported by the SDK.)

**Comment by rhoban13** [comment]
Is this worth revisiting given that docker compose now supports the docker compose supports the notion of `depends_on` `condition` to [control-startup](https://docs.docker.com/compose/startup-order/#control-startup)?  It'd be really nice to get that same behavior by simply:

```
container1 = client.containers.run("image", detach=True)
# Block until container is healthy
while not container1.is_healthy():
   time.sleep(2)
# Start container2 which depends on container1 being healthy
container2 = client.containers.run("image2")
```

**Comment by BrianOpteran** [comment]
Adding in a +1 that this is essential behaviour to me. The attitude that no-one uses healthchecks is clearly wrong. I've been using them (as have others) for a pretty long time. In docker-compose I use them all the time too as above.

Now I'm managing a set of containers, the first thing I need to do after the first container of a stack is up is to check it's health before continuing with getting any other containers up. :-/

**Comment by rhoban13** [comment]
https://github.com/docker/docker-py/pull/3147/files added `healthy` as a property to the container.  I suspect that should do the trick.  Of course we'll need call possibly call `reload` in a loop to re query the docker engine, but this looks dooable.
