### ISSUE TITLE
client.containers.run() documentation is missing supported options

### ISSUE THREAD

**Issue by wvaske** [docker/docker-py#2232]
These options seem to be implemented in containers.py (RUN_HOST_CONFIG_KWARGS) but are not in the documentation for client.containers.run()

cgroup_parent
cpu_rt_period
cpu_rt_runtime
kernel_memory
lxc_conf
mem_reservation
uts_mode
version

**Comment by wvaske** [comment]
See PR https://github.com/docker/docker-py/pull/2233

**Comment by chris-crone** [comment]
PR merged, closing.
