### ISSUE TITLE
Official Node.js API

### ISSUE THREAD

**Issue by sh7dm** [docker/docker-py#2236]
Add Node.js API.
P. S. I'm sorry if I submitted this issue to wrong repo

**Comment by shin-** [comment]
This is an issue tracker for the Python SDK. Please use the [forums](https://forums.docker.com/) instead.

Note also that while there is no officially supported library for Nodejs, the community has published properly maintained, stable packages, such as [dockerode](https://github.com/apocas/dockerode) that you could use.
