### ISSUE TITLE
Pull multiple images

### ISSUE THREAD

**Issue by dsseng** [docker/docker-py#2237]
Add `pullMultiple` function (e.g. `pullMultiple(['redis', 'ubuntu', 'node'])`) or allow `pull` to accept array, like this: `pull(['redis', 'ubuntu', 'node'])`

**Comment by TomasTomecek** [comment]
why not have that logic in your code?

**Comment by sh7dm** [comment]
@TomasTomecek I think it will be much convenient to have this in library

**Comment by TomasTomecek** [comment]
I don't understand what's so unconventient about this:
```python
for im in image_list:
  client.pull(im, tag="latest")
```
The problem with adding such code to the library is... how do you handle errors or even parallelism? Such implementation could become pretty complex, that's why I think it's better to have the logic in an application, not in the library.
