### ISSUE TITLE
SSHAdapter pool_connections too big

### ISSUE THREAD

**Issue by rumpl** [docker/docker-py#2246]
`docker-compose` has an issue when [connecting to a remote daemon over SSH](https://github.com/docker/compose/issues/6463).

`docker-py` sets the number of connections [to 25](https://github.com/docker/docker-py/blob/f302756599a61d6775fbdf2beab8f1de7e0022c4/docker/api/client.py#L152) which is a problem since `sshd` defines `MaxSessions` to 10 by default.

My questions:
* why is the default so high in `docker-py`?
* could `docker-py` set it to lower by default for the SSH transport so that it works out of the box with an ssh server with default configuration? 

In my tests I had to put the limit (`num_pools` argument for `ApiClient`) to 9, there must be an off-by-one error somewhere in there...

**Comment by shin-** [comment]
I think that's due to [`DEFAULT_NUM_POOLS`](https://github.com/docker/docker-py/blob/f302756599a61d6775fbdf2beab8f1de7e0022c4/docker/constants.py#L19). 25 is fine for everything else.

Maybe as a quick fix, we can hard-set the num_pools for the SSH transport to (9/10), then look at making it configurable later.

**Comment by rumpl** [comment]
Why not :)

**Comment by shin-** [comment]
Another option would be to do that [here](https://github.com/docker/compose/blob/master/compose/cli/docker_client.py#L119) with something like
```python
if kwargs['base_url'].starts_with('ssh://'):
  kwargs['num_pools'] = 10
```

**Comment by rumpl** [comment]
Thing is, compose doesn’t yet have anything for different transports, would be a shame to add it there now. 

A flag would be better I think and maybe some env var?

**Comment by rumpl** [comment]
Also, as I said in the first post, for some reason num_pools should be 9, not 10, some dependency of docker-py is not counting as everyone else

**Comment by ijc** [comment]
I wonder -- could it be counting the underlying network connection as one, then allowing 9 additional sessions on top (essentially meaning the first sessions counts as two)?
