### ISSUE TITLE
SSH Tunneling connection to remote Docker Daemon

### ISSUE THREAD

**Issue by jeanbritz** [docker/docker-py#2250]
Good day!
I want to be able to connect to my remote server using SSH and execute Docker commands on it using the docker-py SDK.
I don't know if it is possible at all, but I have look through the source code and have find an adapter called `SSHAdapter`. I have tried to setup everything correctly on my side, but cannot get a positive response from the Docker Daemon.
You can follow my setup [here](https://github.com/jeanbritz/pyqt-docker-client/tree/master/example/ssh_connection).
The readme explains how I setup the SSH on my Windows machine. My Docker is running on Ubuntu Linux 16.04.1 (more accurately Backbox 5.2).
The example code in `ssh_connection.py` shows how I reproduce or attempt to connect to the Docker Daemon via SSH'ing

**Python version**
3.7.0

**Python Requirements:**
docker==3.7.0
docker-pycreds==0.4.0
paramiko==2.4.2

Running `ssh_connection.py` on my Windows 10 machine, while running a Backbox VM with docker I produce the following output:
**Console**
[Click here](https://pastebin.com/d54Akc8e)

**Paramiko Log**
[Click here](https://pastebin.com/ypRivs4X)

My docker service file:
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2376

```
Any idea what I might have missed?

**Comment by rumpl** [comment]
It doesn't seem so...

@jeanbritz, could you try by setting `pool_connections` to 10 for example?

**Comment by jeanbritz** [comment]
Hi @simonferquel, I have check to see if there are any related issues before I posted, but could not find anything similar. The only related issue I could find is [this](https://github.com/docker/for-azure/issues/1) But that is when you use a Docker Swarm. I want to know if it is possible to get this to work on a Docker Daemon?

**Comment by jeanbritz** [comment]
Hi @rumpl,
I have set the `pool_connections` to 10 in my example code, but it does not make a difference. It is also hard-coded in the docker-py SDK to 25.

I've read [here](https://docker-fabric.readthedocs.io/en/stable/guide/apiclient.html#ssh-tunnelling) which have done something similar. I have not written test code using the library mentioned there, because it is quite old.
They mentioned that they use `socat` to forward the SSH tunnel connection to the Docker socket (`unix:///var/run/docker.sock`) 
Is this a feasible way of getting this to work?

**Comment by ulyssessouza** [comment]
@jeanbritz Can you post the output of a `whereis docker` in the target machine?
`docker-compose` expects the docker cli to be in the `$PATH` of the login shell (note that it's not the interactive shell)
For example, if you have it as `/usr/bin/docker` (and of course `/usr/bin` is in your `$PATH`) it should be good.

**Comment by jeanbritz** [comment]
Hi @ulyssessouza ,
Here are the results:
_$ whereis docker_:
`docker: /usr/bin/docker /etc/docker /usr/share/docker.io /usr/share/man/man1/docker.1.gz
`
_$ env | grep PATH_:
`PATH=/home/darkhorse/bin:/home/darkhorse/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

I did get the SSH Tunneling to work on a other Debian machine, but not on my Ubuntu (Backbox).
So it might be SSH configuration on my Ubuntu machine, but it is hard to pinpoint where the issue is.
