### ISSUE TITLE
Recv data from exec_start socket

### ISSUE THREAD

**Issue by RacingDawn** [docker/docker-py#2276]
my example is as follows:
- firstly i create the docker client with tls, and the client works.
```
docker_endpoint='tcp://127.0.0.1:8137'
cert_dir = '/etc/docker/pki/'
        tls_config = TLSConfig(client_cert=(cert_dir + 'cert.pem', cert_dir + 'key.pem'), ca_cert=cert_dir + 'ca.pem',)
self.dockerClient = docker.APIClient(base_url=docker_endpoint, tls=tls_config)
```
- then i create terminal exec
```
execCommand = [
            "/bin/sh", "-c",
            'TERM=xterm-256color; export TERM;'
            'export DOCKER_ENDPOINT=%s; export CONTAINER_ID=%s;'
            '[ -x /bin/bash ] && /bin/bash || /bin/sh'
            % (self.base_url, containerId)]
        execOptions = {
            "tty": True,
            "stdin": True
        }
execId = self.dockerClient.exec_create(containerId, execCommand, **execOptions)
```
- i get socket by starting the terminal exec
```
stream_tmp = self.dockerClient.exec_start(execId["Id"], socket=True, tty=True)
```
- then i read the data from socket
```
docker_stream_stdout = stream_tmp.socket.recv(2048)
self.log.error(docker_stream_stdout)
message = str(docker_stream_stdout, encoding='utf-8')
```

the docker_stream_stdout is b"\x17\x03\x03\x00\xac\x00\x00\x00\x00\x00\x00\x00\x14Xt\xce\xb7\x82s5` \x89Q}w^-\xd8d\xb2i\xe7V\x02\x7f\r\xed\x85Z\xcf\xc1\xf05\x8b\xdfp\xca\x8a\x8a\x1e\x9e\xda\xba4\x08L`>\xebo\xa25`$\x88<\x90<\xc87\x81L\xe6!\xcc\xc6\xec\xf7\xe3<l\xc6\xd4M\x1c\x87*\x18\x9c8Z\x95\x1b'^\x8eOi\xd5\xc5\x0c\xd0c\xb8\x863R\x03\x81\x16\xf6fb\xbdO\xb3\xd6\\\x12\n3\x11\xa0\xd4\x1b1\xdc\x1d\xaf\x18\x83\xee\xa2\xc7V\xa4~\x8c\x1a\xc8\xcew\xd1\xa7\x064P\xb1l\xc6\x8dz\xe3pu\xd8\xef\x88\n\x12bQ\x95\x02>\x12\x80j\x1f\xbbl\xee\xdbe\\\x85"

the it can't be encoded by utf-8

so how to convert the docker_stream_stdout to the really type; or how to read the data from socket in the true way?

the log:
![image](https://user-images.githubusercontent.com/13477849/54439685-43283e00-4774-11e9-8c3e-b110158b9874.png)

**Comment by shin-** [comment]
See the [stream format](https://docs.docker.com/engine/api/v1.39/#operation/ContainerAttach) documentation.

**Comment by RacingDawn** [comment]
> See the [stream format](https://docs.docker.com/engine/api/v1.39/#operation/ContainerAttach) documentation.

thank you, but i don't understand clearly. i used the exec_start to get the socket.
![image](https://user-images.githubusercontent.com/13477849/54488026-cf9f4180-48d7-11e9-855d-3b8f76c3f49d.png)
in the exec_start function the code is:
![image](https://user-images.githubusercontent.com/13477849/54488074-31f84200-48d8-11e9-9ee5-faeb1db19b13.png)

As mentioned earlier, when i created docker client without tls, the `docker_stream_stdout` can be encoded 'utf-8', but it can't be encoded 'utf-8' when i creat docker client with tls.
![image](https://user-images.githubusercontent.com/13477849/54488062-15f4a080-48d8-11e9-8f4a-72223b88ea64.png)

![image](https://user-images.githubusercontent.com/13477849/54488136-222d2d80-48d9-11e9-8e4f-678d2897841b.png)
the docs indicates the recv() return the bytes represent the object. so how i can resolve the bytes result?

**Comment by RacingDawn** [comment]
> See the [stream format](https://docs.docker.com/engine/api/v1.39/#operation/ContainerAttach) documentation.

thank you, i resolve it. I should use the stream_tmp to recv and sendall instead of the stream_tmp.socket when i create client with tls_config.
`stream_tmp = self.dockerClient.exec_start(execId["Id"], socket=True, tty=True)`
