### ISSUE TITLE
Docker client.images.pull does not throw error if pull fails

### ISSUE THREAD

**Issue by jah3xc** [docker/docker-py#2286]
I am using docker-py to pull images in my Python script.

I was seeing that even after pulling, I did not have the updated image.

After manually running `docker pull [img]` from the command line, I see that an `Out of Space On Disk` Error occurred. I removed some old images and re-ran, and everything worked fine.

Why does the SDK not throw an exception if the pull fails? If that is the desired behavior, how can I manually check that the pull was successful?

**Comment by shin-** [comment]
See my answer on a similar issue here: https://github.com/docker/docker-py/issues/2226#issuecomment-453665165

**Comment by jcsirot** [comment]
Closing as duplicates #2226
