### ISSUE TITLE
exec_run don't close the file descriptor

### ISSUE THREAD

**Issue by zom3y3** [docker/docker-py#2306]
Here is my test code.

import docker
client = docker.from_env()
container = client.containers.run("ubuntu", network_disabled=False, detach=True, auto_remove=True, remove=True)
exit_code, output = container.exec_run("ps")

I use "exec_run" to execute the system command, but the file descriptor won't be closed, and it will cause file descriptors leak problem.

Maybe you should close the websocket after call "exec_run".

**Comment by TomHellier** [comment]
was this fixed? what did you see!
