### ISSUE TITLE
Pass a file to container using exec_run

### ISSUE THREAD

**Issue by junaidrazzaq** [docker/docker-py#2323]
How do I pass a file to container using `exec_run` function.

I want to replicate the following docker exec command:

`docker exec -i -u postgres <Insert the id find above> pg_restore -C -d postgres < filename`

Above command loads a postgres backup. `filename` is the name of the file and resides on host machine from which exec command is being run.

I am trying this:

```
containers[0].exec_run("/bin/bash -c 'pg_restore -C -d postgres <'" + filename, stdout=True, stderr=True, user='postgres')
print(exec_log[1])
```

Here the file resides inside another docker container in which a python application is running which uses python docker client.

I am getting this:
`b'/bin/bash: 2019-04-29-postgres_db.dump: No such file or directory\n'`

I have looked into `put_archive` but that would require extracting the file inside the container. Is there a way of doing this using `exec_run` or any other simpler way?

Thanks

**Comment by jcsirot** [comment]
Hello @junaidrazzaq The easiest solution is probably sharing a local volume if both containers are running on the same host.
To create a local volume with the API: https://docker-py.readthedocs.io/en/stable/volumes.html
And mount the volume with the volumes parameters of `client.containers.run`
