### ISSUE TITLE
Wait for client.containers.run to finish creating the image.

### ISSUE THREAD

**Issue by kierun** [docker/docker-py#2350]
I am using `containers.run` with `detach=True` since I need to be able to continue my script -- this is part of a [behave](https://behave.readthedocs.io/en/latest/) script. A `Given` step creates a container than is then used by a `when` step to do something.

However, I cannot fathom how to have my code wait for the docker container to be ready to accept data/commands. At the moment, I have an ugly `sleep(60)` in there which clearly is the *wrong way to do it*.

**Comment by staehle** [comment]
Does your container printout in its logs a "I'm ready" statement that you can scan for in your application?
https://docker-py.readthedocs.io/en/latest/containers.html#docker.models.containers.Container.logs

**Comment by kierun** [comment]
No, it does not.

What I ended up doing was waiting to see if I could SSH into the container. It's not ideal but works well enough for my needs.
