### ISSUE TITLE
How to create a mount point in a docker container.

### ISSUE THREAD

**Issue by LukeJohnson29** [docker/docker-py#2356]
I've been trying to figure out how to create a container and mount volumes to it. I followed the documentation in Low Level API and I get this error.

AttributeError: 'DockerClient' object has no attribute 'create_container' In Docker SDK for Python 2.0, this method is now on the object APIClient. See the low-level API section of the documentation for more details.

It appears that the documentation is out of date. I want to create volumes with user chosen names in user chosen file paths on the host system, but I can't find the correct way to do this.

Currently I'm creating binds and trying to create a container using types.HostConfig.

**Comment by shin-** [comment]
`DockerClient` is the high-level client. To use the low-level API, you'll need to instantiate an [`APIClient` object](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.client.APIClient) instead. One easy way to do this is `import docker; client = docker.from_env().api`

**Comment by LukeJohnson29** [comment]
Thanks! I'll give this a try.

**Comment by LukeJohnson29** [comment]
Thank you. This work splendidly.
