### ISSUE TITLE
Running a docker container with low level API

### ISSUE THREAD

**Issue by LukeJohnson29** [docker/docker-py#2358]
I'm unsure about how exactly you run a container with the low level API. I tried a more complex one that I created a port configuration and host configuration for and it didn't appear to work. After that I tried running the 'hello-world' image and even that appears to not run. I am using the 'client.create_container('hello-world')' method like that.

**Comment by shin-** [comment]
Like so:

```python
ctnr = client.create_container('hello-world')
client.start(container_id)
```
