### ISSUE TITLE
container.name not updating on container rename

### ISSUE THREAD

**Issue by TheJKM** [docker/docker-py#2372]
I'm having some trouble with the name parameter of a container object not updating when I rename the container. The following code:
~~~~
#!/usr/bin/env python3
import docker
c = docker.from_env()
container = c.containers.get(container_id="ab934aa23c4c")
print(container.name)
container.rename(name="main_db_new")
print(container.name)
~~~~
Should print (assuming the container is named "main_db"):
~~~~
main_db
main_db_new
~~~~
Instead it prints:
~~~~
main_db
main_db
~~~~

I'm running docker-py on:
Docker, Python and SDK versions:
~~~~
docker==4.0.2
docker-pycreds==0.4.0
Python 3.6.8
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:11:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:59:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
~~~~

OS: Ubuntu 18.04.2 LTS (fully updated as of today)

**Comment by shin-** [comment]
You'll need to call [`container.reload()`](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.reload).

**Comment by TheJKM** [comment]
Thanks, that works. May bad, seems like I missed ist in the documentation.
