### ISSUE TITLE
ImportError: cannot import name 'format_extra_hosts' from containers.py

### ISSUE THREAD

**Issue by parin13** [docker/docker-py#2388]
**docker version** 
> 
> Client:
>  Version:           18.09.8
>  API version:       1.39
>  Go version:        go1.10.8
>  Git commit:        0dd43dd87f
>  Built:             Wed Jul 17 17:41:19 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.8
>   API version:      1.39 (minimum version 1.12)
>   Go version:       go1.10.8
>   Git commit:       0dd43dd
>   Built:            Wed Jul 17 17:07:25 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
> 
 pip dependencies

> docker==3.7.3
> docker-compose==1.24.1
> docker-py==1.8.0
> docker-pycreds==0.4.0
> dockerpty==0.4.1

After having this all setup in my system when i want to run compose with command:

`docker-compose up -d
`
i got this stack 

> 
> Traceback (most recent call last):
>   File "/usr/local/bin/docker-compose", line 6, in <module>
>     from compose.cli.main import main
>   File "/usr/local/lib/python3.6/dist-packages/compose/cli/main.py", line 22, in <module>
>     from ..bundle import get_image_digests
>   File "/usr/local/lib/python3.6/dist-packages/compose/bundle.py", line 13, in <module>
>     from .network import get_network_defs_for_service
>   File "/usr/local/lib/python3.6/dist-packages/compose/network.py", line 9, in <module>
>     from docker.types import IPAMConfig
>   File "/usr/local/lib/python3.6/dist-packages/docker/types/__init__.py", line 2, in <module>
>     from .containers import ContainerConfig, HostConfig, LogConfig, Ulimit
>   File "/usr/local/lib/python3.6/dist-packages/docker/types/containers.py", line 4, in <module>
>     from ..utils.utils import (
> ImportError: cannot import name 'format_extra_hosts'
>

**Comment by shin-** [comment]
The `docker` and `docker-py` packages are using the same namespace and causing issues when they're both installed in the same environment. Uninstall the `docker` and `docker-py` pip packages, and reinstall only `docker`.

**Comment by parin13** [comment]
@shin- thankx, solved the issue,
 
1) uninstalled docker-compose  package i.e 

> pip uninstall docker-compose


2) reinstalled it : 

> sudo curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

> sudo chmod +x /usr/local/bin/docker-compose
