### ISSUE TITLE
Cannot mount volumes with spaces on it

### ISSUE THREAD

**Issue by hithwen** [docker/docker-py#2394]
While docker cli accepts volumes with spaces:
`docker run -v /Users/hithwen/Library/Application\ Support/config:/etc/my-app/config myimage`

When using the pyhton library and a `Mount`
```
client.containers.run(
    "myimage",
    mounts=[
        Mount(source='/Users/hithwen/Library/Application\ Support/config', target='/etc/my-app/config')]
)
```

I get:

`docker.errors.APIError: 400 Client Error: Bad Request ("create /Users/hithwen/Library/Application\ Support/config: "/Users/hithwen/Library/Application\\ Support/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")`

Using versions:
* Docker version 18.09.2
* docker==3.6.0
* Python 3.7.3
* Mac Os 10.14.6

Originally reported in https://github.com/docker-library/python/issues/410

**Comment by shin-** [comment]
Please make sure to include all the [necessary information](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues) in your report.

**Comment by hithwen** [comment]
Updated

**Comment by shin-** [comment]
Add `type=bind` to your `Mount` declaration. The default is `volume`, which is not what you want here.

https://docker-py.readthedocs.io/en/stable/api.html#docker.types.Mount
