### ISSUE TITLE
Cannot Search images with Docker SDK for python

### ISSUE THREAD

**Issue by Rev0kz** [docker/docker-py#2404]
Please I installed Docker API for python on a Linux debian without installing Docker Engine as shown below:  

`pip install docker`

Afterwards I opened a python interpreter and type the following commands:  

```
>> import docker
>> client = docker.from_env() 
>> client.search.images("nginx")  
```

However it sent the following error message:  

```
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```   
It says no such file or directory although I just typed these commands via the python interpreter.

Any help please?

**Comment by shin-** [comment]
You need to be connected to a Docker Engine for this to work.

**Comment by Rev0kz** [comment]
Okay. Thanks. It is working now.
