### ISSUE TITLE
Network object attrs field does not contain containers in the network

### ISSUE THREAD

**Issue by Mr-Sourdough** [docker/docker-py#2435]
Environment:
```
docker==4.0.1
Python 3.6.8
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
OS: Linux Mint 19.0 Tara
Issue:
In the field `attrs` for the `Network` object, the list for key `Containers` is empty. The network was run using `docker-compose` and adding containers using the SDK does not change anything.

**Comment by feliperuhland** [comment]
Hi @Mr-Sourdough, this is a docker behavior, and the Go client do the same thing.
To get the container list, you need to use `client.networks.get("<container-id>")`.

**Comment by Mr-Sourdough** [comment]
Used what you suggested and it worked. Thanks!
