### ISSUE TITLE
Capture output on error from stdout

### ISSUE THREAD

**Issue by garethr** [docker/docker-py#2439]
I'm running a container which runs a set of tests against content mounted into the container. I expect this to sometimes fail. When it does, the command exits with a non-zero status code.

When running this container using `docker-py` the command exiting with a non-zero status code causes the client to raise an exception.

Capturing the `docker.errors.ContainerError` works, but the output of the command does not appear to be accessible? I can access `.stderr` but not `.stdout`?

Is there a way of achieving what I'm trying to do with the client at the moment? ie.

1. Run a container
2. Capture stdout, even when the command run returns a non-zero response

**Comment by feliperuhland** [comment]
Hi @garethr 

Did you try running with `detach=True` and then get `container.logs()`?

**Comment by garethr** [comment]
@feliperuhland I didn't, thanks for the suggestion. What's the best way of making that synchronous? ie. I want to grab the output (presumably from `container.logs()`) when the container finishes and exits.

**Comment by feliperuhland** [comment]
@garethr `container.logs(follow=True)` will do the trick.

However, I think `stream=True` is a better way to do it.

> `stream (bool)` – If true and detach is false, return a log generator instead of a string. Ignored if detach is true. Default: `False`.

**Comment by feliperuhland** [comment]
@ulyssessouza I think we can close this issue.

@garethr if you have more questions, you can open another issue.

Have a nice day :)
