### ISSUE TITLE
Support --stop-timeout in run request (API 1.25)

### ISSUE THREAD

**Issue by Guluis** [docker/docker-py#2449]
API 1.25 added the --stop-timeout to the run command. It needs to be added to the docker API.
https://docs.docker.com/engine/api/v1.25/#

**Comment by ndeloof** [comment]
Stop-timeout is actually already supported for a while by the API https://github.com/docker/docker-py/blob/master/docker/api/container.py#L227

**Comment by kennylajara** [comment]
> Stop-timeout is actually already supported for a while by the API https://github.com/docker/docker-py/blob/master/docker/api/container.py#L227

Not really, `stop_timeout` is not being copied from run to create. But I just opened a PR to solve the issue.
