### ISSUE TITLE
How to avoid create container endless

### ISSUE THREAD

**Issue by xiaochenluo** [docker/docker-py#2461]
docker-py will create container endless when it not receive a response from docker engine like  ReadTimeOut. So, I will get a ton of created containers after. How to avoid this kind of situation？ 

python version: 3.5.2
docker-py version: 3.5.2
docker CE: 18.09.6

**Comment by feliperuhland** [comment]
Hi @xiaochenluo 

Could you provide some steps to reproduce this issue?

**Comment by xiaochenluo** [comment]
Sorry, no recent focus on my github lot. Set the value of `timeout` larger of the client will solve the problem.
