### ISSUE TITLE
"swarm service inspect" description in https://docker-py.readthedocs.io/en/1.10.0/api/

### ISSUE THREAD

**Issue by hdlbq** [docker/docker-py#2464]
the description of "swarm service inspect" seems strange in:
https://docker-py.readthedocs.io/en/1.10.0/api/
```
inspect_service
Create a service, similar to the docker service create command. See the services documentation for details.
```

Thanks

**Comment by shin-** [comment]
Thanks for the report. That's tied to the version of the code at time of release, which for 1.10.0 was 3 years ago, so we won't do anything to fix this.
