### ISSUE TITLE
parsing docker client.build() output

### ISSUE THREAD

**Issue by aayoushee** [docker/docker-py#2468]
I am using the low level API of Docker SDK for python. I wanted to parse the build output , the json response I am getting is not pretty intuitive and if I parse on the basis of keys like 'stream' and 'error', there are two problems I am facing:
- I am not aware of all possible keys it can have (like 'aux' etc.)
- even "\n" comes as a separate key value pair making the logs difficult to clean
Please direct me to a doc in case I have missed it, I am referring to https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.build docs.

**Comment by feliperuhland** [comment]
Hi @aayoushee 

That output is from docker daemon.
I believe you need to parse yourself.

If you share your code (some of it), I can help you.

**Comment by aayoushee** [comment]
Hi @feliperuhland , thank you for your response
I am using the following code to fetch and clean the response
build_response = [str(line.decode('unicode-escape').rstrip()) for line in
                              self._cli.build(path=dir_path, buildargs=build_args,
                                              tag=image_tag)]
I want to make the response more readable and intuitive

**Comment by feliperuhland** [comment]
Hi @aayoushee 

I did some test here with this code (**NOTE: this code is just a draft.**):

```python
from io import BytesIO
import docker
dockerfile = '''
# Shared Volume
FROM busybox:buildroot-2014.02
VOLUME /data
CMD ["/bin/sh"]
'''
f = BytesIO(dockerfile.encode('utf-8'))
cli = docker.from_env()
response = cli.api.build(fileobj=f, rm=True, tag='yourname/volume', decode=True)
for line in response:
    if line.keys()[0] in ('stream', 'error'):
        value = line.values()[0].strip()
        if value:
            print(value)
```

The result was:

```sh
Step 1/3 : FROM busybox:buildroot-2014.02
---> 9875fb006e07
Step 2/3 : VOLUME /data
---> Using cache
---> 26b557c5ce73
Step 3/3 : CMD ["/bin/sh"]
---> Using cache
---> d8c0b5415315
Successfully built d8c0b5415315
Successfully tagged yourname/volume:latest
```

**Comment by aayoushee** [comment]
Thanks, this was very helpful but I was wondering if 'stream' and 'error' are the only keys present in the output as in the above snippet only these two keys are parsed

**Comment by feliperuhland** [comment]
There is at least one more; I filtered because those were what docker shows on the CLI.

**Comment by feliperuhland** [comment]
@ulyssessouza I think we can close this issue.

@aayoushee if you have more questions, please open a new issue.

Have a nice day :)
