### ISSUE TITLE
docker search

### ISSUE THREAD

**Issue by gregoan** [docker/docker-py#2474]
Hi,

I would like to translate the following commands in Python : 

```
docker login 10.72.2.70:5002
docker search 10.72.2.70:5002/digit_c2_child_gregoan
```
**---> Elements are well visible**

I'm doing : 

```
import docker
...
client = docker.from_env()
client.login(username=registry_username, password=registry_password, registry=docker_registry_server)

# Returns an error
return_type = self.client.images.search(term="10.72.2.70:5002/digit_c2_child_gregoan")

# Doesn't return anything
return_type = self.client.images.search(term="digit_c2_child_gregoan")
```
Any idea about what I'm doing wrong ?

Regards.

**Comment by feliperuhland** [comment]
Hello, @gregoan 

Did you try the registry API?

https://docs.docker.com/registry/spec/api/#listing-repositories

**Comment by gregoan** [comment]
Hi Felipe,

Thank you for your message.

No I didn't because the goal is to expose a WS returning a list of element being the tag list (the goal is to offer the restore of a specific image identified from tag list)

In the present case, are you suggesting to use the HTTP implementation instead of the Python one so "Listing Image Tags" ?

Regards.

**Comment by feliperuhland** [comment]
The docker-py project is a client for docker API, so every command from docker-py it's an HTTP request, actually.

Docker-py is (in most cases) a client for docker API using docker-engine reference https://docs.docker.com/engine/api/v1.40/, and the description of [Image Search](https://docs.docker.com/engine/api/v1.40/#operation/ImageSearch) is `Search for an image on Docker Hub`.

I didn't find any way to search for image in all the repositories, so I think the best way to get image information of a different register is using the registry API.

**Comment by gregoan** [comment]
Do you have/know a python API doing such kind of thing (registry) ?
---> I found many potential API and I'm not sure which one is the best and one crashed my Python environment.

**Comment by feliperuhland** [comment]
Hi @gregoan 

I didn't use any library for that, sorry for that.
Every time I need to get something from the registry, I use the API for that.

You can use the reference documentation for that: https://docs.docker.com/registry/spec/api/.

**Comment by gregoan** [comment]
Hi,
I used docker-registry-client Python module and it's working fine.
Thank you again for your help.
