### ISSUE TITLE
How get the ws object from exec_run() like attach_socket()

### ISSUE THREAD

**Issue by unihon** [docker/docker-py#2488]
I want get a websocket object from exec_run(), but I just get a `socket.SocketIO` and it's not writeable.

![image](https://user-images.githubusercontent.com/42078581/71889358-ef606880-317c-11ea-8d60-9f50f92c407c.png)

How to get a ws object from exec_run() like attach_socket().

**Comment by feliperuhland** [comment]
Hi @unihon 

I did a quick look at the documentation and I think you could use the low-level-api that returns a websocket: https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.attach_socket

I hope this help.

**Comment by unihon** [comment]
I have tried this (attache_socket)，but attache_socket just attach to the PID 1 of the container, and I want to get a WS object of not just the process of PID 1.

**Comment by feliperuhland** [comment]
Sorry, but that's the only way to return a WebSocket through the docker API.

I can try to reproduce your steps later today.

**Comment by unihon** [comment]
I found a related method and it met my needs. 

![image](https://user-images.githubusercontent.com/42078581/71944181-f4b1c780-31fd-11ea-893b-469195bed30c.png)

Duplicate of #2255 

thanks
