### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by myugan** [docker/docker-py#2493]
When i trying for docker connection using https it will show this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://x.x.x.x:2376/v1.35/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sciprt.py", line 93, in <module>
    api_ver = client.version()["ApiVersion"]
  File "/usr/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'Client sent an HTTP request to an HTTPS server.'")
```

But, i got the response when hit the endpoint manually like `https://x.x.x.x:2376/containers/json`

**Comment by feliperuhland** [comment]
Hi @myugan, the exception `Client sent an HTTP request to an HTTPS server` indicates that some TLS information is missing.
You can have more information in the [Client](https://docker-py.readthedocs.io/en/stable/client.html) documentation.

Are you using `docker.from_env()` function or `docker.DockerClient` class to connect to the Docker backend?

**Comment by myugan** [comment]
I'm used `docker.APIClient` class to docker backend.

**Comment by feliperuhland** [comment]
Are you using `True` or a `TLSConfig` class as `tls` parameter?

**Comment by myugan** [comment]
Not yet, how to use that?

**Comment by feliperuhland** [comment]
You need to use TLS to connect to an HTTPS backend. Here is a description from the docs:

```
tls (bool or TLSConfig):
Enable TLS. Pass True to enable it with default options, or pass a TLSConfig object to use custom configuration.
```

https://docker-py.readthedocs.io/en/stable/api.html#docker.api.client.APIClient

**Comment by myugan** [comment]
Ok, thankyou @feliperuhland you can closed this issue.

**Comment by feliperuhland** [comment]
Sure, but I can't close the issue.

You can close it and open another one if you need anything else.
:)
