### ISSUE TITLE
More detailed documentation for healthcheck with run

### ISSUE THREAD

**Issue by JanoschDeurer** [docker/docker-py#2497]
The `run` method on `client.containers` has an argument `healthcheck`. However, apart from that it is given as a dict there is few documentation. I looked in the `Healthcheck` class and guessed that the content of the dict equals to the arguments of this class, which is the case. I think it would be helpful to either refer to the `Healthcheck` class or to write a similar documentation for this.

**Comment by feliperuhland** [comment]
Hi @JanoschDeurer 
Maybe the [docker api documentation](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate) can help you.

**Comment by JanoschDeurer** [comment]
Hey @feliperuhland, thanks for the response :) I had already found out how to use the healthcheck. My ticket was only about the documentation. I think a simple reference to the healthcheck class would suffice.

**Comment by feliperuhland** [comment]
Ok, sorry about that. What do you think to write a pull request for that?

**Comment by JanoschDeurer** [comment]
Sorry it took me so long. Here is my pull request :)
