### ISSUE TITLE
Wrong pywin32 version for python3.5

### ISSUE THREAD

**Issue by tcaiazzi** [docker/docker-py#2498]
Hi, 
the pywin32 dependecy in requirements.txt for python3.5 seems wrong. 
The 219 version does not exist for python3.5. 

![pywin](https://user-images.githubusercontent.com/26346836/73355755-21a34880-4299-11ea-9c64-fca340eeb864.PNG)

**Comment by milas** [comment]
This will be fixed in the upcoming 6.0.0 release.
