### ISSUE TITLE
Support OpenSSH's IdentityFile config option

### ISSUE THREAD

**Issue by HaaLeo** [docker/docker-py#2533]
# Description
As a developer I want `docker-py` to load the identity file according to my setting specified in `~/.ssh/config`, not only the "default" `id_rsa` file.

# Example
I have a `~/.ssh/config` file with contents:
```ssh
Host myHost
    User myUser
    HostName myIp
    IdentityFile C:/Users/me/.ssh/id_rsa_custom_file
    IdentitiesOnly yes
```

Now I would like `docker-py` to pick up `C:/Users/me/.ssh/id_rsa_custom_file` for trying to connect to the remote host (For example when I want to run `docker-compose -H "ssh://myHost" ps`. However right now it does not.

When I rename `C:/Users/me/.ssh/id_rsa_custom_file` to `C:/Users/me/.ssh/id_rsa` it works just fine. However this is not an option for me since I have multiple identity files and hosts that I want to use.

# Proposal
Add something like this to the [`sshcon.py`](https://github.com/docker/docker-py/blob/c285bee1bc59f6b2d65cee952b5522c88047a3bc/docker/transport/sshconn.py#L105):
```python
if 'identityfile' in host_config:
    self.ssh_params['key_filename '] = host_config['identityfile']
```

**Comment by apatrushev** [comment]
This was broken again since 4.4.0... :-(
