### ISSUE TITLE
Bug or Misleading Docu: All docker images will be downloaded when the image tag is not specified

### ISSUE THREAD

**Issue by bonacci-johannes** [docker/docker-py#2545]
BUG
Setup: Python3.8: docker 4.2.0

When starting a clean postgres container using python docker sdk the docker sdk pulls all postgres images.

It would be helpful to update the docu mentioning that the version tag should be specified.
Or even more handy, introduce a default to the latest version?

Here is the code:
```python
import docker
from docker.models.containers import Container
client = docker.from_env()
container: Container = client.containers.run(
    image='postgres', remove=True, auto_remove=True, detach=True,
    ports={'5432': '5432'},
    environment=
    [
        'POSTGRES_PASSWORD=pwd',
        'POSTGRES_USER=test',
        'POSTGRES_DB=test'
    ])
```
Bash output of 'docker images' before running the code:
```shell
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

Bash output of 'docker images' after running the code:
```shell
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
postgres            10.12               1fb929c54703        7 days ago          200MB
postgres            10-alpine           1bd67b33a51c        2 weeks ago         70.3MB
postgres            10.12-alpine        1bd67b33a51c        2 weeks ago         70.3MB
postgres            10.11               5fea18bb7e20        2 months ago        250MB
postgres            10.11-alpine        fb495265b81f        2 months ago        72.4MB
postgres            10.10-alpine        a071f71cc9bb        5 months ago        71.8MB
postgres            10.10               9a05a2b9e69f        5 months ago        211MB
postgres            10.2-alpine         400ef39e0dbf        2 years ago         39.5MB
...
...
...
```

**Comment by thaJeztah** [comment]
defaulting to `:latest` would make sense, and would be in line with what the `docker` CLI does (https://github.com/docker/cli/blob/6deb4f1f634003188e8319b8266ccdc588651fb1/cli/command/image/pull.go#L56-L63), which requires the `-a` / `--all-tags` option to be set to pull all tags (note that for `push` the `docker cli` currently has the same behavior as is reported here, but this is changed in the upcoming release: https://github.com/moby/moby/pull/40302

```console
Usage:	docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry

Options:
  -a, --all-tags                Download all tagged images in the repository
      --disable-content-trust   Skip image verification (default true)
      --platform string         Set platform if server is multi-platform capable
  -q, --quiet                   Suppress verbose output
```

**Comment by bonacci-johannes** [comment]
> defaulting to :latest would make sense, and would be in line with what the docker

Thanks for the response, this default behavior would improve the usability a lot.

**Comment by thaJeztah** [comment]
I'm not sure if maintainers will get to making this change soon, but contributions are welcome if you're interested in making those changes
