### ISSUE TITLE
module 'socket' has no attribute 'AF_UNIX

### ISSUE THREAD

**Issue by maherjaballi** [docker/docker-py#2547]
Hello, plz when i want to use package docker in windows i have this issue any solution ? 
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
odoo.tools.convert.ParseError: "module 'socket' has no attribute 'AF_UNIX'"
thx

**Comment by ctrl-Felix** [comment]
AF_UNIX is only available for Unix machines, as you are running windows it will not work. You could change it to `AF_INET` which should make it work than

**Comment by toxicrecker** [comment]
doesn't works even after changing `AF_UNIX` to `AF_INET` in `unixconn.py`

Error:
```
File "c:\Python38\lib\site-packages\docker\transport\unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
TypeError: connect(): AF_INET address must be tuple, not str
```

**Comment by moti-malka** [comment]
Any idea? i have same issue

**Comment by ctrl-Felix** [comment]
Have you checked https://stackoverflow.com/questions/48651321/python-socket-error-af-inet-address-must-be-tuple-not-str?

**Comment by olegshtch** [comment]
AF_UNIX recently supports on Windows https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by milas** [comment]
Although Windows now supports `AF_UNIX`, Python does not support it on Windows. See https://github.com/python/cpython/issues/77589.
