### ISSUE TITLE
build() output is hard to consume

### ISSUE THREAD

**Issue by mmerickel** [docker/docker-py#255]
Currently the build output is not parsed by docker-py so we get back json chunks. It'd be nice if docker-py could parse the chunks, raise if it sees an error and concatenate the stream output.

**Comment by Oloremo** [comment]
Folks, I have kinda the same problem described here as "sometimes all the data is sent on a single line ????". Sometimes generator returns multiple lines, like(my debug):
```
String is: {"stream":"\r\n"}
{"stream":"Preparing to unpack .../libkrb5-3_1.12.1+dfsg-19+deb8u2_amd64.deb ...\r\n"}
```
Is it known issue? How can I avoid it? For some reason I only experience it on docker 1.12 mac os, and on linux it seems to work just fine.

**Comment by bfirsh** [comment]
Compose's `json_stream` helper is now included in the development version. For an example of how to use it, see this implementation:

https://github.com/docker/docker-py/blob/1984f68730512a1c07017118f4e229c7949ff8a8/docker/models/images.py#L96-L169
