### ISSUE TITLE
Support DriverOpts in connect_container_to_network

### ISSUE THREAD

**Issue by haboustak** [docker/docker-py#2550]
I'm currently working on a project that includes a Docker network driver plugin, and the needs of the driver require additional information when connecting a container to the network.

Docker added support for driver options to the `EndpointConfig` model in [API version 1.32](https://docs.docker.com/engine/api/v1.32/#operation/NetworkConnect) (`Docker 17.09`).

It's not very well documented, but the [docker network connect](https://docs.docker.com/engine/reference/commandline/network_connect/) CLI command has supported a `--driver-opt` option to `docker network connect` since at least `18.09`, so I think it's reasonable to add it to the python SDK.

**Comment by vmorris** [comment]
I would also like to see this supported.

**Comment by vmorris** [comment]
Thanks!
