### ISSUE TITLE
May I translate this project into Korean?

### ISSUE THREAD

**Issue by tina1296** [docker/docker-py#2552]
Hi :) I am Na Eun Kwon a university student in Kwangwoon University. I want to translate READ ME documentation for your project contribution and other Koreans who want to learn about docker.py.
So may I translate these infos into Korean?
If I could, plz tell me how I can share the translated results.
Thank you.

**Comment by TomasTomecek** [comment]
> So may I translate these infos into Korean?

Absolutely, open source licenses make this easily possible: https://github.com/docker/docker-py/blob/master/LICENSE#L90

The easiest thing you can do is to translate the document and push it to master branch of your fork. Then you can point people to your fork for the translation.

As for the upstream repo, one could create a new document with a specific name suffix specific for the translation - I presume maintainers of this project don't speak Korean so it would be difficult to maintain that file though.

**Comment by tina1296** [comment]
Thanks for your reply :) I know it would be difficult to maintain without someone who can speak Korean. However, me and my project team members will translate documents like README and continue to revise them for contribution. We want to help Koreans who want to learn and know about Docker through our contributions and contribute to Docker-py project. And would you help me know the website that I can check if there are translations of documents? I will wait for your reply Thank you!!

**Comment by TomasTomecek** [comment]
> Thanks for your reply :) I know it would be difficult to maintain without someone who can speak Korean. However, me and my project team members will translate documents like README and continue to revise them for contribution. We want to help Koreans who want to learn and know about Docker through our contributions and contribute to Docker-py project. And would you help me know the website that I can check if there are translations of documents?

Since I am not affiliated with the [docker GitHub organization](github.com/docker) I cannot answer that.

But @thaJeztah can I'd say.

**Comment by thaJeztah** [comment]
I don't know of there's existing translations. We don't translate our repositories, because it's difficult to keep the translations updated, so instead we stick to using English.
