### ISSUE TITLE
DeprecationWarning: urllib.parse.splitnport() is deprecated as of 3.8, use urllib.parse.urlparse() instead

### ISSUE THREAD

**Issue by graingert** [docker/docker-py#2566]
https://github.com/docker/docker-py/blob/9a24df5cdd03c679dc929735e4766e19ff1c2bdb/docker/utils/utils.py#L23

**Comment by ssbarnea** [comment]
Are we ever going to see a hotfix for this? Some of us have the "bad" habit of running CI/CD pipelines with warnings-as-errors.

**Comment by frainfreeze** [comment]
This seems to be addressed in #2944 - can we get this merged into next release @aiordache @ulyssessouza ?
