### ISSUE TITLE
Pass --gpus 1 as argument to client.containers.run

### ISSUE THREAD

**Issue by philipperemy** [docker/docker-py#2597]
I need to do something like this:

```
docker run --gpus 2 -it --rm -v $(pwd):/volume/ /bin/bash -c <cmd>
```

Can somebody tell me how to pass custom variables such as `--gpus` to docker?

**Comment by Aierhaimian** [comment]
Can anybody tell me how to pass `--gpus` to docker when using `client.containers.run()` API ?

**Comment by philipperemy** [comment]
@Aierhaimian you can't at the moment. And probably not anytime soon. You need to use a fork of docker-py. I forgot where it is but you should be able to find it in the docker-py issues with the tag "gpu". I'm going to close this issue as some similar issues already exist.
