### ISSUE TITLE
Feature request: Add "--add-host" paramater support

### ISSUE THREAD

**Issue by NonCreature0714** [docker/docker-py#2600]
Feature request for internal DNS resolution related to https://github.com/moby/moby/pull/40007 which uses a magic string to append a container's ID with appropriate IP to `/etc/hosts`.

This includes the `--host` flag for `docker service create`.

The issue was prompted because some applications attempt to use DNS to verify a local hostname, and, when not finding the container's hostname in /etc/hosts, fails.

**Comment by NonCreature0714** [comment]
Nevermind

**Comment by Ramjivan** [comment]
Reopening the request to add support for
`reopening th--add-host=host.docker.internal:host-gateway`
