### ISSUE TITLE
docker container exits automatically

### ISSUE THREAD

**Issue by dexhunter** [docker/docker-py#2654]
Hi, I am learning to use the docker api but I had some problems. A simple example of my problem is when I run something like `client.containers.run('alpine', detach=True)` the container will exit immediately. I don't know what I did wrong there since I am expecting the same behavior as `docker run -dit alpine`. I have also tried to set `restart_policy` but still not working. Could someone please help? Thank you!

P.S. versions
![image](https://user-images.githubusercontent.com/6930518/90951178-9383ef00-e482-11ea-85b8-de65d79b3329.png)

**Comment by slashtechno** [comment]
> ok, I found the problem can be solved by setting `tty=True, stdin_open=True`

I'm having the same problem. When doing testing with the Docker CLI, it seems that only one flag (in the CLI), or parameter (docker-py) needs to be used. I'm also interested to what causes this problem.

**Comment by James-Ilosta** [comment]
I have the same problem, I also tried what you suggested dexhunter and I get the same result.
