### ISSUE TITLE
Connection using TLS fails if `REQUESTS_CA_BUNDLE` env variable is set

### ISSUE THREAD

**Issue by ander2** [docker/docker-py#2672]
I wanted to open a client connection to a Docker daemon using `TLS` but I got the following error:

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate
```

After checking the certificates, checking that the docker command was working (`docker --tls --tlscert cert.pem --tlskey key.pem --tlscacert ca.pem -H ubuntu:2376  version`) and after making some debugging I realised that having the `REQUESTS_CA_BUNDLE` environment variable set, makes the DockerClient fail, as it looks like it ignores the certificate passed in the `TLSConfig`'s `ca_cert` param.  If I unset the `REQUESTS_CA_BUNDLE` var or set it to my then same value as `ca_cert`, then it works.

The `DockerClient` should use the `ca_cert` passed in the `TLSConfig`.

**Comment by erikgb** [comment]
Seems like a duplicate of #2433.

**Comment by ander2** [comment]
Yes, it look like it's the same issue.

Closing.
