### ISSUE TITLE
APIClient will try to fetch docker API version during instanciation

### ISSUE THREAD

**Issue by AtomBaf** [docker/docker-py#2676]
Hi 

Starting with version 4.3.1, when instanciating the APIClient without an explicit version param, then a request is made to check the server version.
In my case this is causing an error since I'm using a custom authentication system (kerberos).

In 4.3.0, I used to instanciate the APIClient, and then set the auth property (inherited form requests.Session) to my custom scheme. After that, I was able to use the APIClient normally.

Workaround for now: I'm explicitely setting the version param to avoid the version check during object instanciation.

IMHO, here are some possible solutions:
 - never perform something during object construction, there are plenty of reason (for my case, use custom auth) for instanciating the object and then, after, actually doing the requests. Especially if the object is inherited from requests.Session.
 - forget the object inheritance, use composition instead, and allow the user to pass an explicit session object in the constructor.

Thanks for your library, happy to help if needed

**Comment by milas** [comment]
This is working as designed given the client architecture. As noted here, an explicit version can be passed during construction to prevent automatic API version negotiation.
