### ISSUE TITLE
Requirements are too strict with pip 20.3

### ISSUE THREAD

**Issue by sodul** [docker/docker-py#2714]
We install the docker package alongside other ones that have similar dependencies. Unfortunately the requirement.txt entries for the docker package are strict and conflicting with other projects such as hvac.
https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The required versions need to be relaxed in order to be installable with pip 20.3

**Comment by milas** [comment]
The upcoming release has relaxed restrictions and removed many extraneous transitive dependencies. Once 6.0.0 is out, please open a new issue if you have trouble with the latest `pip`.
