### ISSUE TITLE
How can I get details error messages of Docker command?

### ISSUE THREAD

**Issue by dclong** [docker/docker-py#2747]
I got the following error message while using `docker-py` to build a Docker image. How can I get more details error message which is shown when using the docker build command?
```
File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends         nodejs npm     && npm install -g n     && n lts     && npm cache clean --force     && apt-get autoremove     && apt-get autoclean' returned a non-zero code: 1
```

**Comment by feliperuhland** [comment]
Hi @dclong 

You could have a `try/except` block to get the error message.
A `BuildError` will be raised if an error occurs during the image build, and the log will be available through the `build_log` attribute.
Note that `build_log` will return an `iterator` object.

Here is an example:

```py
In [9]: try:
   ...:     cli.images.build(path=".", dockerfile="dockerfile-tmp")
   ...: except docker.errors.BuildError as exc:
   ...:     for line in exc.build_log:
   ...:         print(line.get("stream", line.get("error")))
   ...:
```

Have a nice day :)

**Comment by dclong** [comment]
@feliperuhland, thank you very much! This is very helpful!
