### ISSUE TITLE
Docker stats stream are not produced in json formt

### ISSUE THREAD

**Issue by christosMichael** [docker/docker-py#2749]
I am running the below code, however am not able to get the results decoded in json format, instead it returns a generator.

    client = docker.from_env()
    
    container = client.containers.get('prometheus')
    
    stats = container.stats(decode=True, stream=True)

When I print stats am seeing just a generator object:

    <generator object APIClient._stream_helper at 0x000001F0DFE42270>

**Comment by ulyssessouza** [comment]
That's a stream of the chunked response. That's why it's a generator. And as you've set in the `stats` call, that's a stream. So it works as expected
