### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by acepeep** [docker/docker-py#2751]
When I run the script below:

```
#! /usr/bin/env python3
import docker
client = docker.DockerClient(base_url="tcp://10.90.1.48:2377")
print(client.info())
```

I get the error: 

`Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    client = docker.DockerClient(base_url="10.90.1.48:2377")
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 222, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`

But if I run the commend from the command-line 

`docker -H 10.90.1.48 info`

I get a valid response: 

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.6
```

**Comment by aiordache** [comment]
Hi @acepeep! 

In the `docker -H 10.90.1.48 info` you don't specify the port. Can you run the same command with the url you set in the python code?

**Comment by acepeep** [comment]
You were right it was a port issue, but of course, I swear I had checked that....
