### ISSUE TITLE
[4.4.3] Changelog missing introduction of maxreplicas feature from #2741

### ISSUE THREAD

**Issue by hartwork** [docker/docker-py#2774]
Hi!

While inspecting the diff between 4.4.2 and 4.4.3 for Gentoo just now I noticed that there are features added that the changelog for 4.4.3 doesn't say a word about. I found those changes in pull request #2741 which seems mis-attributed to milestone 4.5.0 still today. Are you aware?

Best, Sebastian

**Comment by aiordache** [comment]
Hi @hartwork!  Thank you for noticing this!

It was added to the release 4.4.3 by mistake, sorry! The intention was to add it to the 4.5.0 release as a new feature but I forgot to exclude it during the last release. We will try to improve the way we track the fixes for a release to avoid doing these mistakes.

I'll update the release changelog.

**Comment by hartwork** [comment]
> I'll update the release changelog.

Looking at https://github.com/docker/docker-py/blob/5.0.0-release/docs/change-log.md , later change logs seems to be be in sync with 4.4.3 reality now — cool! I'll close the ticket as fixed. Please re-open if that was too eager, thanks!
