### ISSUE TITLE
prune_builds is not available for version < 1.31

### ISSUE THREAD

**Issue by ele18081** [docker/docker-py#2779]
Hello, 

I use docker-py with ansible. 
Everything run well, I can manage container as desired.

Except for the "prune" command, i get the following error:

> InvalidVersion: prune_builds is not available for version < 1.31

I don't understand wich version of which dependency/software is referenced through this message and if it's relevant. 
I'm on the version 4.4.1 of docker-py and i don't see any release of 1.31.

The command "docker image prune" is working correctly without using ansible by the way.

Do you have any additional informations ?

Kind regards.

**Comment by feliperuhland** [comment]
Hi @ele18081

The version mentioned is from the [Docker Engine API](https://docs.docker.com/engine/api/).

What version of Docker are you using? You can get that from the `docker version` command.

**Comment by ele18081** [comment]
Hi @feliperuhland, thank you for this information. I couldn't find it in the documentation. 

I'm in version 1.13.0 so this explain the issue. I'll close and find a way to update my infrastructure.

Have a nice day :)
