### ISSUE TITLE
mount soure inside conainer create error.

### ISSUE THREAD

**Issue by kathirvelmuniraj** [docker/docker-py#2783]
docker run -it --mount type=bind,source="`realpath $(pwd)/$TASKID/input`",target=/mnt/input --mount type=bind,source="`realpath $(pwd)/$TASKID`",target=/mnt/output  <image>

expected same in docker sdk python

docker.errors.APIError: 400 Client Error: Bad Request ("create f-base_dataoutput/ee482f103a7bb0fb15ec60e0939268a9: "base_dataoutput/ee482f103a7bb0fb15ec60e0939268a9" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")

**Comment by feliperuhland** [comment]
Hi @kathirvelmuniraj 

The error is about the volume name, not the source.

Could you check that?

Have a good day :)

**Comment by lizzi2122** [comment]
https://github.com/docker/docker-py/issues/2783#issue-821794369

**Comment by lizzi2122** [comment]
https://github.com/docker/docker-py/issues/2783#issue-821794369

**Comment by Bass-03** [comment]
hey @feliperuhland 

I ran into this issue today, It occurs to me the regex checks for an even number of characters.

for instance, it would not match my user name `mundo` which would mean I can't mount a path in my home folder.

This would work better IMO `[a-zA-Z0-9]+[a-zA-Z0-9_.-]` 

IN the case of the error in this issue, it matches `base` but the next character is an underscore, which does not match becasue it should match the first group `[a-zA-Z0-9]` and it doesn't 

Check this out, current regex
![image](https://user-images.githubusercontent.com/10700343/211180115-330301bd-61c9-4ece-9cd7-aff3f8e2f902.png)

proposed regex:
![image](https://user-images.githubusercontent.com/10700343/211180134-a163cfdc-8cbc-4fd6-b420-09d8f03e4d6b.png)

Let me know if that makes sense.
Also, there might be a workaround according to https://github.com/docker/docker-py/issues/2663

Let me know what you think

**Comment by milas** [comment]
The error message from the Docker API isn't the best, but the logic upstream is correct, see: https://github.com/moby/moby/blob/3a5598affa1c3ab7dd5c4ae5c6ccfe863abc288e/daemon/names/names.go

In the case of this issue, the problem was that the volume name provided was `base_dataoutput/ee482f103a7bb0fb15ec60e0939268a9`, which includes a `/`, which is not a valid character for a volume name

**Comment by Bass-03** [comment]
hey @milas 

Thanks for that link, I see the real regex is `^[a-zA-Z0-9][a-zA-Z0-9_.-]+$`, you are right the error message is misleading.

For the record here, the solution is to specify the mount type to `bind`, since we are talking python, this is an example

``` python
from docker.types import Mount

# Mount(path_in_container, path_in_host, type)
data_mount = Mount('/app/output/', '/tmp/some_folder',  type='bind') 
```
