### ISSUE TITLE
docker.from_env() not working on fask/python API

### ISSUE THREAD

**Issue by rmansillasoto** [docker/docker-py#2790]
Hello,

Do you have any clue why this stop working from a few weeks or so? 

`File "app.py", line 32, in <module>
srt_ddbb      |     client = docker.from_env()`

`docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

I´ve tested with versions from 3.3.1 to 4.4.0 but I got the same error everytime. The last time I used the library worked perfectly but not at this time.

Regards,
Raúl.

**Comment by feliperuhland** [comment]
Hi @rmansillasoto 

Could you please share your docker version and operational system?

Thank you!

**Comment by feliperuhland** [comment]
Hi @rmansillasoto  

Could you confirm that the docker engine is running?

Have a nice day :)

**Comment by rmansillasoto** [comment]
Hello Felipe,

I have discovered today that it was due to a failure in our jenkins pipeline :-/ 

Thanks a lot!
Raúl

Enviado desde mi iPhone

**Comment by feliperuhland** [comment]
No problem.

Could you close the issue?

Have a nice day :)
