### ISSUE TITLE
Support for Docker Compose API

### ISSUE THREAD

**Issue by haohanyang** [docker/docker-py#2794]
Does the current Python SDK have support for Docker Compose CLI?

**Comment by feliperuhland** [comment]
Hi @haohanyang 

In fact, it's the opposite; docker-compose uses docker-py to access the docker engine.

You can use [Docker Compose](https://github.com/docker/compose) itself for that:

```sh
pip install docker-compose
```

Have a nice day :)

**Comment by haohanyang** [comment]
Thanks.
I want to setup a backend(flask) and do something like `docker-compose -p myProject scale worker=5` via an API gateway(like`HTTP /rpc/scale?worker=5`). How can I possibly do it?

**Comment by feliperuhland** [comment]
Hi @haohanyang 

Definitely, you will need `docker-compose` for that.

You can start [here](https://github.com/docker/compose/blob/master/compose/cli/main.py); that is the CLI main function.

Have a nice day :)

**Comment by feliperuhland** [comment]
@ulyssessouza we can close this issue.

@haohanyang, if you have more questions, feel free to open a new issue.

**Comment by ulyssessouza** [comment]
Hello @haohanyang !

As @feliperuhland said, `docker-compose` depends on `docker-py` as a library.
And note that `docker-compose` is a final product, thus it does not have any kind of API to be used as code dependency on any means. Given that, the use `docker-compose` as a library is on your own responsibility.
