### ISSUE TITLE
Through DOCKER service create SDK API can we add/drop capabilities ?

### ISSUE THREAD

**Issue by vickydgm** [docker/docker-py#2802]
How can I be able to do these below capabilities add/drop functionality through Docker SDK API.

'--cap-drop ALL --cap-add NET_ADMIN --cap-add NET_RAW --cap-add MAC_ADMIN \
             --cap-add KILL --cap-add SYS_PTRACE --cap-add SYS_ADMIN \
             --cap-add NET_BIND_SERVICE --cap-add DAC_OVERRIDE \
             --cap-add SETGID --cap-add SETUID --user 1000',

**Comment by nuhour** [comment]
same problem.not support util now,i guess

**Comment by feliperuhland** [comment]
Hi @vickydgm I´m going to check that later today

@ulyssessouza could you assign this issue to me?

Thanks and have a good day :)

**Comment by nuhour** [comment]
> Hi @vickydgm I´m going to check that later today
> 
> @ulyssessouza could you assign this issue to me?
> 
> Thanks and have a good day :)



> 嗨@vickydgm今天晚些时候我要检查一下
> 
> @ulyssessouza您可以将这个问题分配给我吗？
> 
> 谢谢，祝你有美好的一天:)

thx for ur commit.

**Comment by nuhour** [comment]
@feliperuhland thx for ur commit.

**Comment by vickydgm** [comment]
Thanks @feliperuhland
