### ISSUE TITLE
[5.0.0] Dropped dependency six but remains importing six in 32 Python files?

### ISSUE THREAD

**Issue by hartwork** [docker/docker-py#2807]
Hi!

While bumping docker-py for Gentoo I noticed that commit c8fba210a222d4f7fde90da8f48db1e7faa637ec dropped the dependency on six from `setup.py` and `requirements.txt`. When grepping the sources I find 32 more Python files that still import six so I would expect some trouble at runtime in an environment where no six is available (if we ignore dependencies pulling six in, indirectly). Is that known and intended?

Thanks and best, Sebastian

**Comment by feliperuhland** [comment]
Hi @hartwork 

That makes total sense, and we will remove those dependencies.

@ulyssessouza could you assign this issue to me?

Thanks and have a good day :)

**Comment by consideRatio** [comment]
Thank you @hartwork for reporting this issue, and everyone involved contributing to this project! :heart: :tada:

@feliperuhland are you still interested in working on this? I would suggest going for it if you don't find an open PR already about it.

Thank you again everyone contributing to this project, I'm one among many users who rely on it indirectly :heart:

**Comment by feliperuhland** [comment]
I won't be able to finish that task.

Have a nice day.

**Comment by hartwork** [comment]
@feliperuhland thanks for being transparent about it.

@aiordache this seems like a low hanging fruit, yet somewhat important. Are you aware of someone who can take over? Else: If I came up with a pull request myself, would you have a minute for review in the next few days?

**Comment by feliperuhland** [comment]
Hi @hartwork

I'm going to dedicate my time to other projects.
I have a small WIP here https://github.com/feliperuhland/docker-py/pull/new/remove-six

I hope that helps.

**Comment by hartwork** [comment]
Thanks.

Here's a direct link to @feliperuhland's commit if anyone else wants to have a look:
https://github.com/feliperuhland/docker-py/commit/71411f5596dd0b3ef523af3b0af4c81e2827cc04

**Comment by asottile** [comment]
fixed in #2863

**Comment by hartwork** [comment]
@asottile awesome, thank you! :pray:

**Comment by hartwork** [comment]
@docker any chance for a new release?

**Comment by thaJeztah** [comment]
Let me close this one, as it was fixed in https://github.com/docker/docker-py/pull/2863

I'll ask @ulyssessouza if it's possible to tag a new release
