### ISSUE TITLE
Container creation does not support passing the platform

### ISSUE THREAD

**Issue by felixfontein** [docker/docker-py#2822]
While this is not documented in the API docs (https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate), the Go client uses that: https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/client/container_create.go#L42

It would be great if Docker SDK for Python could support the `platform` parameter for container creation as well.

**Comment by felixfontein** [comment]
This issue is about the low-level API, not the high-level API. The high-level API supports that parameter, but uses it differently than the `docker` CLI tool: the high-level API only uses it for pulling images, while the `docker` CLI tool passes it on for the `create` command to the daemon as well.

**Comment by JonZeolla** [comment]
I would also like this feature

**Comment by felixfontein** [comment]
I tried to implement it in #2927.
