### ISSUE TITLE
AWS ECR & client.images.pull() auth_config

### ISSUE THREAD

**Issue by MJLongstreth-tiq** [docker/docker-py#2827]
I am trying to pull images from a private registry hosted in AWS ECR.  I am using boto3 to pull an authorization token from AWS ECR, which returns a response syntax:
```
{
    'authorizationData': [
        {
            'authorizationToken': 'string',
            'expiresAt': datetime(2015, 1, 1),
            'proxyEndpoint': 'string'
        },
    ]
}
```

I am trying to pull an image with the SDK using:
```
docker_auth = response['authorizationData'][0]
```
OR
```
docker_auth = response['authorizationData'][0]['authorizationToken']
```
```
docker_client = docker.from_env()
docker_client.images.pull(repository=repository, tag=tag, auth_config=docker_auth)
```

`docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://repository/manifests/tag: no basic auth credentials")`

I believe I may need to create a `docker_clients.configs.create()` object, but from the documentation available here:
https://docker-py.readthedocs.io/en/stable/configs.html

It is unclear what information I need to pass and structure of same.  Any advice, help would be appreciated.

I should note, I have the same token in my `$HOME/.docker/config.json` file and it works for pulling an image from my registry using the CLI.

**Comment by bruce-szalwinski** [comment]
I've added a `login` step before the `pull` that does the equivalent of the cli commands for logging into ecr:

## cli
```
 echo "aws --region ${region} ecr get-login-password | docker login -u AWS --password-stdin https://${registry_id}.dkr.ecr.${region}.amazonaws.com"
```

## python

### login

```python 
    def login(self, ecr: Ecr, repo: EcrModel):
        (username, password) = ecr.credentials()
        registry = repo.registry_uri()
        self.logger.info(f"logging into: registry={registry}")
        self.docker_client.login(
            username=username, password=password, registry=registry
        )
```

### credentials

```python
    def credentials(self):
        authorization_data = self.get_authorization_token()
        data = base64.b64decode(
            authorization_data.authorizationData[0].authorizationToken
        )
        return data.decode("utf-8").split(":")
```

### get_authorization_token

```
    def get_authorization_token(self) -> AuthorizationData:
        response = self.ecr.get_authorization_token()
        return AuthorizationData.parse_obj(response)
```

### DataModel

maps the response from get_authorization_token

```python
class AuthorizationDatum(BaseModel):
    authorizationToken: str
    expiresAt: datetime
    proxyEndpoint: HttpUrl


class AuthorizationData(BaseModel):
    authorizationData: List[AuthorizationDatum]
```
