### ISSUE TITLE
Add capability add/drop option for creating and updating services

### ISSUE THREAD

**Issue by matusnovak** [docker/docker-py#2831]
Recently the `--cap-add` option has been added to stack/service commands. Link to the PR: https://github.com/docker/cli/pull/2687

It is done by adding `CapabilityAdd` and `CapabilityDrop` into the `TaskTemplate -> ContainerSpec`  within the request body. See here: https://github.com/thaJeztah/cli/blob/master/cli/compose/convert/service.go#L153-L154

At the moment, there is no such option in docker-py when creating services -> https://docker-py.readthedocs.io/en/stable/services.html

**Comment by feliperuhland** [comment]
Hi @matusnovak 

I opened a Pull Request for that feature #2809

**Comment by matusnovak** [comment]
Thank you @feliperuhland I will be very glad once that gets merged. I am closing this issue.
