### ISSUE TITLE
Update pywin32

### ISSUE THREAD

**Issue by arossert** [docker/docker-py#2835]
Currently, pywin32 is fixed on version 227, my project needs a newer version of pywin32 (the latest is 300) and this cause pip conflicts, can you please update the version?

**Comment by milas** [comment]
This will be fixed in the upcoming release.

**Comment by arossert** [comment]
@milas when is the next version planned to be released?

**Comment by milas** [comment]
A `6.0.0b1` version has been released: https://pypi.org/project/docker/6.0.0b1/

Final release should be soon, but feel free to give that a shot for now! :slightly_smiling_face:
