### ISSUE TITLE
Swap out `requests` to avoid LGPL dependency

### ISSUE THREAD

**Issue by ashb** [docker/docker-py#2837]
This library depends upon `requests`, and while requests itself is Apache 2 licensed, it depends upon `chardet` which is LGPL'd.

This leads to confusing licensing situations for projects using this python docker client, and it is the view of the Apache Software Foundation that _any_ LGPL dep places some restrictions on the downstream projects, and thus has to be avoided.

See https://github.com/psf/requests/pull/5797 for the latest attempt to change the dependency upstream (which at the time of writing appears to be a Wont Fix, so I closed the PR)

So: I would like to propose that `requests` is switched out to [`httpx` library](https://www.python-httpx.org/) -- it is broadly API compatible with requests.

I am happy to attempt this PR, but first I wanted to raise the issue and see if a PR will be accepted!

**Comment by feliperuhland** [comment]
That would be nice!

**Comment by ashb** [comment]
Requests no longer pulls in a LGPL'd module, so we can close this.
