### ISSUE TITLE
undeclared dependency on six package

### ISSUE THREAD

**Issue by kapilt** [docker/docker-py#2842]
installing docker python in a fresh py3, and attempt to use, fails due to undeclared dependency on the python six package (auth.py)

**Comment by cliffwoolley** [comment]
@ulyssessouza - This seems related to your recent change https://github.com/docker/docker-py/pull/2788 ?

**Comment by cliffwoolley** [comment]
There seem to still be quite a few files in the 5.0.0 package that `import six`.
```
docker/transport/npipeconn.py
docker/transport/unixconn.py
docker/transport/npipesocket.py
docker/transport/sshconn.py
docker/api/plugin.py
docker/api/secret.py
docker/api/image.py
docker/api/exec_api.py
docker/api/container.py
docker/api/swarm.py
docker/api/config.py
docker/credentials/store.py
docker/models/images.py
docker/types/healthcheck.py
docker/types/services.py
docker/types/base.py
docker/types/containers.py
docker/auth.py
docker/utils/build.py
docker/utils/json_stream.py
docker/utils/socket.py
```

**Comment by cliffwoolley** [comment]
Looks like this duplicates https://github.com/docker/docker-py/issues/2807 .

**Comment by MartinWallgren** [comment]
six was removed from setup.py in [this commit](https://github.com/docker/docker-py/commit/c8fba210a222d4f7fde90da8f48db1e7faa637ec)

**Comment by geerlingguy** [comment]
Yeah... a lot of my automation has been failing since a couple weeks ago when this new release was made. Finally found the source of it :) (ref: https://github.com/geerlingguy/drupal-container/issues/33)
