### ISSUE TITLE
Error getting list of containers from client.containers.list()

### ISSUE THREAD

**Issue by arahja** [docker/docker-py#2875]
I apologize if I am missing something obvious. I am trying to use docker-py version 5.0.0 (I have also seen this in 4.2.0) with python 3.6 to connect to my local docker engine and run commands, but I receive an error when I attempt to access the list of running containers. I have received this same error on the docker:stable container and on a server running Ubuntu 18.04. I was not able to find any references to this in your issues list.

### Code causing the issue:

import docker
docker_client = docker.DockerClient(base_url='unix://var/run/docker.sock', version="1.41")
docker_containers = docker_client.containers()

### Error recieved:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/docker/models/resource.py", line 67, in __call__
    raise TypeError(
TypeError: 'ContainerCollection' object is not callable. You might be trying to use the old (pre-2.0) API - use docker.APIClient if so.

### Ubuntu 18.04 server setup:
docker==5.0.0
Python 3.6.9
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by nijave** [comment]
`docker.containers.list()`

Object types are properties on Docker client (no `()`) with methods like `get`, `list`, `create`
