### ISSUE TITLE
could not import docker module with python 2.7

### ISSUE THREAD

**Issue by daeseokyoun** [docker/docker-py#2876]
I tried to install docker-py==4.2.0 to work properly with python 2.7.
but the websocket-client==1.1.1 was relased recently. while initializing websocket-client, it tried to import ```selectors``` but it is not abled to import in python 2.7 because pip for python 2.7 do NOT have selectors module.

So I install 0.57.0 after uninstall 1.1.1.

I think it should be handled when install docker-py by pip for python 2.7.

thanks.

**Comment by JohnPreston** [comment]
Not to sound like a a-hole, but I think your problem is that you are using python 2.7. It is long passed its "End of Life" for support. Systems might still use it but I would recommend you upgrade yours to at least python 3.8

**Comment by milas** [comment]
Python 2.7 is EOL and unsupported by this library
