### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by matthewchung74** [docker/docker-py#2879]
I've been reading about security issues with building docker images within a docker container by mounting the docker socket. 

That got me wondering, are there security issues with building images using docker-py on a plain ubuntu host (not in a docker container) since it also communicates on the docker socket? 

I'm also confused as to why there would be security differences between running docker from the command line vs this sdk, since they both go through the socket?

Any help is appreciated.

**Comment by TomasTomecek** [comment]
Please define what you mean by "security issues", that's a very broad term.

It's true it does not matter whether you use the go client library or this python client, you are still talking to the HTTP API which has complete root access with all the capabilities to the host system.

**Comment by matthewchung74** [comment]
Thanks for responding @TomasTomecek and yes, that is broad. I was thinking of security as the author of the docker file being able to take over the host machine, for the use case of a CI/CD. 

If I'm doing docker builds for other people, and then running the containers locally for a verification test, I'm nervous of what could happen, given docker usually runs as root on the host. If there are any suggestions, I'd appreciate it.

**Comment by TomasTomecek** [comment]
In such a case, you should always analyze the provided dockerfile and make sure you understand it. Building it and running the subsequent container is best done in a locked down environment, i.e disposable virtual machine.

There is many articles online about this, I suggest googling them.

**Comment by matthewchung74** [comment]
Thank you.
