### ISSUE TITLE
Type hints, py.typed

### ISSUE THREAD

**Issue by gitpushdashf** [docker/docker-py#2901]
Hi,

This looks like an awesome library. Thank you!

It would be nice if it had type hints and a py.typed file to indicate that mypy can use it for static type analysis.

https://mypy.readthedocs.io/en/latest/installed_packages.html?highlight=py.typed#creating-pep-561-compatible-packages

The type hints look like this:

```
def foo(bar: str, baz: bool) -> str:
    if baz is True:
        return f"{bar} is true"
    else:
        return f"{bar} is false"
```

Is this something you'd be interested in?

**Comment by GhostLyrics** [comment]
Duplicate of https://github.com/docker/docker-py/issues/2796

**Comment by gitpushdashf** [comment]
My bad! Closing this one.
