### ISSUE TITLE
installing latest 5.0.3 on windows machines is still using pywin32==227 but not pywin32==301

### ISSUE THREAD

**Issue by keerthiadu** [docker/docker-py#2902]
[Bump pywin32 from 227 to 301 ]( https://github.com/docker/docker-py/commit/e0d186d754693feb7d27c2352e455c5febb4a5cd) was already merged in to bump pywin32 from 227 to 301. But, when installing latest 5.0.3 on windows machines is resulting in install of pywin32==227

Most likely extras_require needs updated
https://github.com/docker/docker-py/blob/a48a5a9647761406d66e8271f19fab7fa0c5f582/setup.py#L19

**Comment by xoxys** [comment]
This issue exist on Python Poetry projects as well even if v5.0.3 is used already, https://github.com/thegeeklab/docker-tidy/security/dependabot/poetry.lock/pywin32/open

**Comment by jackwhelpton** [comment]
Also being bitten by this. FYI, there's a further update to `pywin32`, to 302. 302 is the first version to support Python 3.10, so is a key thing for us... is that covered by this ticket, or should I cut a new one for pywin32==302?

**Comment by tharun634** [comment]
> Also being bitten by this. FYI, there's a further update to `pywin32`, to 302. 302 is the first version to support Python 3.10, so is a key thing for us... is that covered by this ticket, or should I cut a new one for pywin32==302?

This ticket doesn't do it, but there already is a PR which covers it, #2857

**Comment by gitpushdashf** [comment]
Any update on this? There's known vulnerabilities with pywin 227: https://security.snyk.io/vuln/SNYK-PYTHON-PYWIN32-1316226

**Comment by Martin-Molinero** [comment]
Ping!
This issue means that you basically **can't use python 3.10 and docker in windows**. @StefanScherer @ulyssessouza @aiordache there are a few PRs already open to solve this, can they be reviewed/shipped anytime soon?

**Comment by jmackay-godaddy** [comment]
Docker team, **PLEASE** can you accept any of the many already submitted fixes for this? People using docker through python and also on github cloud are getting security notifications due to your library. This bug has been open for 8 months.

**Comment by aabmets** [comment]
I got around this problem by removing all docker software and using an alternative, as all docker software seems to have become abandonware and incompatible with the current Python version.

**Comment by fproulx-boostsecurity** [comment]
> I got around this problem by removing all docker software and using an alternative, as all docker software seems to have become abandonware and incompatible with the current Python version.

Which alternative did you end up using @aabmets ?

**Comment by aabmets** [comment]
> > I got around this problem by removing all docker software and using an alternative, as all docker software seems to have become abandonware and incompatible with the current Python version.
> 
> Which alternative did you end up using @aabmets ?

My use case was somewhat unique - using a container manager was an option, not a requirement. I needed to run QuestDB for a project and in addition to the docker container they also had a direct executable file, so just chose to run the exe directly from Python code in a subprocess.

**Comment by Dramelac** [comment]
Is docker still a thing ??

It's been 8 months that **this blocking problem prevents all Windows users to use the python docker lib** in version Python 3.10... More and more user must **downgrade** Python or drop Docker support...
And this is not even a technical problem, **many PRs are already available** for a very long time to correct this critical problem...

Knowing that one of the strategy of docker today is to put forward Docker Desktop (pro) with the Windows environment, it is all the more surprising / **worrying** that nothing is happening on this issue!

last hope? @StefanScherer could you address this issue to someone **please** ?

**Comment by SpangleLabs** [comment]
Looks like they're considering just abandoning the package #2989

**Comment by droserasprout** [comment]
I think it's a dangerous situation when the only fully-featured Docker management library (correct me if I'm wrong) is abandoned. Furthermore, contains significant vulnerabilities.

Are there any volunteers to maintain a fork? We could create an organization like `docker-py-ng` and export all issues and pull requests there using https://github.com/gavinr/github-csv-tools or similar tools. I have some experience maintaining Python projects, but I have been very constrained in my free time lately. 399 issues and 122 PRs are a great amount of work.

**Comment by bblommers** [comment]
Ideally the project is donated of course, but if there is no further communication around this, I wouldn't mind help maintaining a fork @droserasprout . Another of my OSS projects relies heavily on `docker-py`, so it would be nice to have some continuity.

Considering the project scope and personal time-constraints it could just be a maintenance fork, where we only consider security fixes and version compatibility PR's.

**Comment by droserasprout** [comment]
Sorry, I didn't notice the discussion of potential forking in another issue. Also, it appeared that docker-py [is not the only](https://github.com/docker/docker-py/pull/2989#issuecomment-1179720247) Docker library around.
