### ISSUE TITLE
Implementation of compose v2 into this library

### ISSUE THREAD

**Issue by mikeynay** [docker/docker-py#2934]
With the transition from compose `V1` to compose `V2` is there scope to include the new compose commands into the `docker-py` module?

I understand that compose `V1` is written in python already and is just an import away for a python dev.  The change to `Go`  with `V2` make this a little trickier.

An example of a community that would use this is the ansible community, which have a current issue open regarding the changes to docker compose.
[https://github.com/ansible-collections/community.docker/issues/216](url)

**Comment by pandvan** [comment]
The proper link to Ansible collection's issue is https://github.com/ansible-collections/community.docker/issues/216

**Comment by milas** [comment]
This library is a lower-level client for the Docker API and does not include any Compose logic, nor do we have plans to add such functionality to this project.
