### ISSUE TITLE
New(er) Alpine builds of ruby have permission issue installing bundler when running Docker-in-Docker

### ISSUE THREAD

**Issue by luke-hill** [docker/docker-py#2938]
I'll try explain this as clear as possible.

## Problem:

1) Use a simple Dockerfile, one that just installs bundler using ruby (I used the one below)

```
FROM ruby:2.7.2-alpine

ENV BUNDLER_VERSION 2.1.4
ENV LANG=C.UTF-8 \
    BUNDLE_JOBS=6 \
    BUNDLE_RETRY=3

RUN apk add --no-cache --update build-base git jq curl

RUN mkdir -p /app
WORKDIR /app

RUN gem install bundler -v $BUNDLER_VERSION
```

2) Observe the build fails when used inside a docker in docker context (For example dind on Jenkins)
```
Step 8/12 : RUN gem install bundler -v $BUNDLER_VERSION
 ---> Running in 273aecf2e9e9
ERROR:  While executing gem ... (Gem::FilePermissionError)

    You don't have write permissions for the /usr/local/bundle directory.
```

-------------------------------------------

## Solution:

Use alpine `3.13` specifically. i.e. change line 1 of my Dockerfile to `FROM ruby:2.7.2-alpine3.13`

However is this version of alpine likely to exist forever? I'm currently seeing alpine 3.13 for ruby 2.7 series and the 3.0 series. But soon we will be going to the 3.1 series.

--------------------------------------------

I also created: https://github.com/rubygems/rubygems/issues/5286 whereby I tried to see if bundler was the culprit. Turns out the version of docker alpine is the issue

**Comment by luke-hill** [comment]
Hi all. Is this the right repo for this>? Anyone got any advice / ways to fix?

**Comment by milas** [comment]
Not a `docker-py` issue - see https://github.com/moby/moby/issues/43311#issuecomment-1197970141
