### ISSUE TITLE
Import issue within docker-py

### ISSUE THREAD

**Issue by naomielst** [docker/docker-py#2948]
Hi, I ran into an issue with docker-py: 

> cannot import name 'APIClient' from 'docker.api'

This happens for each Python version tested: 3.7, 3.8, 3.9 and 3.10.
docker-py version is 1.10.6. 

For more details see here - https://github.com/celery/pytest-celery/runs/5083799951?check_suite_focus=true#step:7:59

**Comment by felixfontein** [comment]
Please note that `docker-py` is the old (deprecated) package for Docker SDK for Python (versions < 2.0.0); since 2.0.0 the package was renamed to `docker`. You should only use `docker-py` if you need Python 2.6 support, for anything more modern use `docker`.

**Comment by naomielst** [comment]
Thanks!
