### ISSUE TITLE
container.remove() does not support timeout

### ISSUE THREAD

**Issue by thigm85** [docker/docker-py#2951]
It is possible to increase `container.stop()` timeout by passing a `timeout` parameter. The same seems not to be possible for `container.remove()`. 

Is there a way to increase `container.remove()` timeout?

**Comment by milas** [comment]
This is not supported by the engine API, see https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerDelete

You can pass `force=True` to _immediately_ kill the container before removing it.

If you'd like to gracefully stop, call `stop()` followed by `remove()`.
