### ISSUE TITLE
Container.wait timeout seems to not work

### ISSUE THREAD

**Issue by ldeluigi** [docker/docker-py#2964]
I'm using `docker==5.0.3`.  In this line:
```python
rc = compile_container.wait(timeout=2) # seconds
```
I'm expecting to wait up to 2 seconds for the container to end computation. I tried with an infinite loop program and it blocks there indefinetly.

**Comment by felixfontein** [comment]
According to the docs (https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.wait), `timeout` is the **requests timeout**. So if the docker daemon does not respond to the request in 2 seconds, a `ReadTimeout` exception will be raised. But if it responds, the call will wait until the container finishes, no matter how long that takes.

**Comment by ldeluigi** [comment]
ok, thanks for the explanation
