### ISSUE TITLE
pywin32 dependency mismatch?

### ISSUE THREAD

**Issue by aabmets** [docker/docker-py#2994]
The **_requirements.txt_** file of docker-py contains the following line: 
`pywin32==301; sys_platform == 'win32'`,

but the `extras_require` dict in the **_setup.py_** file contains the line:
`':sys_platform == "win32"': 'pywin32==227'`

Is it correct that docker-py defines two different pywin32 versions? If not, then which one should it be using?

Under Windows, docker-py always installs pywin32 version 227.
Please help me understand, why docker-py does not use the latest pywin32 version 304 for Windows platform?

Please fix or advise.

**Comment by gitpushdashf** [comment]
#2902 should explain the issue.

**Comment by aabmets** [comment]
Solution: abandon docker and use an alternative which is being actively maintained.
