### ISSUE TITLE
unable to stream container logs

### ISSUE THREAD

**Issue by kvchen** [docker/docker-py#300]
Using the following code, I've been unable to stream logs without the generator blocking infinitely:

```
import docker

base_url = 'unix://var/run/docker.sock'
client = docker.Client(base_url=base_url,
                       version='1.14',
                       timeout=10)

command = 'echo hello world'
container = client.create_container('ubuntu:14.04', command=command)

client.start(container)
log_stream = client.logs(container, stream=True)

for line in log_stream:
	print(line)
```

but waiting for the container to complete and reading the logs without streaming works just fine. Am I consuming the output incorrectly, or is there another issue here?

I'm currently using Docker 1.2.0 on Arch, with Python 3.4.1.

**Comment by shin-** [comment]
Fixed by #441 ? Please re-open if the bug reappears in docker-py>=0.7.2

**Comment by bo0ts** [comment]
Just experienced this issue with python 2.7.10 and docker-py 1.2.3.

Is this still related to this bug?

**Comment by raimo** [comment]
Experiencing with docker-py 1.6.0 as well

**Comment by shin-** [comment]
Can you share a code example that fails consistently? Also [the more info you can provide, the better](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#reporting-issues) so we can start investigating.

**Comment by leej3** [comment]
I ran up against this. I wonder is it the stream kwarg of run that is confusing  people (it confused me). I would expect the following to be a non-blocking call and return a generator:

```
client.containers.run(
        'alpine',
        "/bin/sh -c 'echo hello;sleep 10; echo bye bye'",
        detach=False,
        stream=True,
        )
```

What I wanted was actually:
```
 container = client.containers.run(
    'alpine',
    "/bin/sh -c 'echo hello;sleep 10; echo bye bye'",
    detach=True,
    )
for line in container.logs(stream=True):
    print(line.decode("utf-8"))
```

**Comment by lnxpy** [comment]
Hey @kvchen,
I found a way to fix this problem. In spite I'm creating a Django container, you just need to create a loop in the streaming process and print the log line like this:
```python
print('Running the container..')
container = client.containers.run('something', detach=True)
process = container.logs(stream=True, follow=True)
print('Stream logging the container..')
for line in process:
    print(line)
```
It creates a streaming loop in order to print each request that comes to the container. The output goes to be:
```shell
$ python test.py
Running the container..
Stream logging the container..
```
Then, create some requests to the endpoint and it shows..
```shell
$ python test.py
Running the container..
Stream logging the container..
b'Watching for file changes with StatReloader\n'
b"Invalid HTTP_HOST header: '172.17.0.3:8000'. You may need to add '172.17.0.3' to ALLOWED_HOSTS.\n"
b'Bad Request: /\n'
b'[16/Sep/2020 10:27:26] "GET / HTTP/1.1" 400 58366\n'
b"Invalid HTTP_HOST header: '172.17.0.3:8000'. You may need to add '172.17.0.3' to ALLOWED_HOSTS.\n"
b'Bad Request: /favicon.ico\n'
b'[16/Sep/2020 10:27:26] "GET /favicon.ico HTTP/1.1" 400 58286\n'
```

Hope it works for you. It works properly on my project [DBMQ](github.com/lnxpy/dbmq).
