### ISSUE TITLE
Almost a year with no releases and bugfixes

### ISSUE THREAD

**Issue by xSAVIKx** [docker/docker-py#3000]
Hello Docker maintainers.

Looking at the number of open issues and no response from the team within the issues it looks like the Python API is abandoned and won't be maintained. Python 3.10 is GA for a while already and Python 3.11 coming soon.

Are there any plans to continue the support of this SDK? Maybe it worth donating the project to some open-source organization that'd be able to at least keep it up-to-date and fix security vulnerabilities in time? Also maybe just having some maintainers review the suggestions/PRs from the community will help.

Guys, please respond. There are just so many projects depending on the SDK.

**Comment by xSAVIKx** [comment]
I was just pointed to this PR: https://github.com/docker/docker-py/pull/2989.

So the project indeed is abandoned. I hope they'll decide to donate it.

**Comment by JonZeolla** [comment]
As of a couple days ago this project has started to see activity again 🤔

**Comment by milas** [comment]
We are working on a new release to address many of the outstanding issues. Specifically, it should improve compatibility with the latest Python releases (PRs are also running unit tests against 3.11 prereleases now to catch any issues early), address dependency issues including unsatisfiable constraints on some platforms like Windows, and fix many bugs/gaps.

A beta has been published and is available on PyPI: https://pypi.org/project/docker/6.0.0b1/

**Comment by xSAVIKx** [comment]
@milas thx a lot for getting back to us (the community) and continuing with the project.

And I guess if you need some hands on it, there'd be a lot of people ready to help.

**Comment by milas** [comment]
6.0.0 has been released: https://github.com/docker/docker-py/releases/tag/6.0.0

See the "Upgrade Notes" section for details around upgrading – API-wise, it should be drop-in compatible with 5.0.x, so it's hopefully a pain-free upgrade for most projects.

There are a _ton_ of good improvements in 6.0.0 thanks to the community! ❤️

---

There are still many excellent PRs open, and we'll continue to work through them as we can. If you've got an open PR, please consider merging/rebasing from latest `main`, ensure it passes CI (especially DCO!!), and include tests.

To help set expectations a bit, smaller PRs focused on API gaps (e.g. missing parameters) or broken functionality are much more likely to be reviewed and accepted in a timely fashion. We are unlikely to have the capacity to take on large refactors or breaking changes right now.

Lastly, if you spot any **regressions** in 6.0.0, please do open a new issue or PR, as those will certainly have highest priority!
