### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by peterd550** [docker/docker-py#3030]
When I run
pip3 install --upgrade --no-index /tmp/docker-py-2.5.1.tar.gz
I get the following issue

Defaulting to user installation because normal site-packages is not writeable
Processing /tmp/docker-py-2.5.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-e1wftyj8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-e1wftyj8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-blt8jpfq
         cwd: /tmp/pip-req-build-e1wftyj8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-e1wftyj8/setup.py", line 12, in <module>
        if 'docker-py' in [x.project_name for x in pip.get_installed_distributions()]:
    AttributeError: module 'pip' has no attribute 'get_installed_distributions'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Justintime50** [comment]
It seems this was fixed in 3.4? May want to do a fresh install of a newer version?

https://github.com/docker/docker-py/issues/2001

**Comment by milas** [comment]
Yes, v2.5.1 is very old. I'd recommend using one of the 6.0.0 betas, which should resolve a lot of issues, particularly around install: `pip install docker==6.0.0b2` (find latest on PyPI or GitHub releases)
