### ISSUE TITLE
run/pull issues on windows

### ISSUE THREAD

**Issue by dtrifiro** [docker/docker-py#3033]
Hello,

while trying to run a fairly simple code example on github actions on `windows-latest` (windows server 2022):
```python
client = docker.from_env()
client.containers.run("python:3.8-slim", command="python -c 'print(\"hello\")'")
```
I get the following error:

```console
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\docker\api\client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.41/containers/create```
```

This can be easily reproduced on github actions:
- [python script](https://github.com/dtrifiro/dockerpy-windows-example/blob/4e33f3cb980c428011bbaaa9e16f0980fe475e6e/main.py)
- [github actions workflow file](https://github.com/dtrifiro/dockerpy-windows-example/blob/4e33f3cb980c428011bbaaa9e16f0980fe475e6e/.github/workflows/run.yml)
- [github actions logs](https://github.com/dtrifiro/dockerpy-windows-example/runs/7908188882?check_suite_focus=true#step:5:7)

Note that this code runs perfectly on linux/mac.

I've found a similar issue (https://github.com/docker/docker-py/issues/2101), although in this case pulling the image before running it does not help.

What does help though, is removing the tag part from the image name. Running
```python
client.containers.run("python", command="python -c 'print(\"hello\")'")
```
works just fine, although I have no way of specifying which tag to use.

Running `client.images.pull("python", tag="3.8-slim")` results in the same error as above.

Some final considerations:

By enabling some DEBUG logging in `requests`, I see the folfowing calls/response statuses
```console
"POST /v1.41/images/create?tag=3.8-slim&fromImage=python HTTP/1.1" 200 
"GET /v1.41/images/python:3.8-slim/json HTTP/1.1" 404
```
right before the `HTTPError` from `raise_for_status`, so I'm assuming what's failing is the GET call here:

https://github.com/docker/docker-py/blob/2494d63f36eba0e1811f05e7b2136f8b30f7cdb7/docker/models/images.py#L465-L477

**Comment by milas** [comment]
Unfortunately, this is a limitation of GitHub Actions runners & Windows Server 2022, which only support Windows containers. See https://github.com/actions/runner-images/issues/1143.

I just confirmed on a Windows 11 machine with Docker Desktop installed (and in Linux container mode) that your script works as expected.

Thanks for the detailed issue, but there's not anything that can be done on the `docker-py` side here to make this possible.
