### ISSUE TITLE
container name "/blabla" is already used by container 'HASH"

### ISSUE THREAD

**Issue by AymanRbati** [docker/docker-py#3036]
i get this error when i use then parameter "name" when running a container  :

```
appContainer = client.containers.run(
image=imageTag,
remove=True,
stdout=False,
stderr=True,
name="appcontainer"
network_mode="host",
volumes=volumes,
privileged=True,
command=command
)
```

the name parameter is useful for me to see logs of the container

**Comment by milas** [comment]
Please see the rest of the error message:
> You have to remove (or rename) that container to be able to reuse that name.

You already have a container with the same name running. You will need to either stop & remove that container or pick a different name. You can run `docker ps -a --filter name=blabla` to find the container and `docker rm -f blabla` to remove it.
