### ISSUE TITLE
Does not work on Docker Desktop?

### ISSUE THREAD

**Issue by YaoJusheng** [docker/docker-py#3038]
When run the `Docker Desktop` on `Ubuntu 20.04`, I not found any image by using `docker-py`, but turn off the `Docker Desktop`, it works.

On my computer, docker-desktop, nvidia-docker are installed. Is it that they have an effect on `docker-py`?

It seems that `docker-py` does not find the image downloaded and the container started in the desktop, as if it is divided into two container environments, and `docker-py` can only recognize one of them, but it can be displayed normally in the terminal.

So, what is the cause of this problem?

**Comment by milas** [comment]
This is working as designed.

Docker Desktop uses a VM for isolation and security, so it has a different socket path than Docker Engine - if you have both installed, it's possible to use them independently.

For Docker Desktop on Linux, the socket path is `~/.docker/desktop/backend.sock`. You can provide this as an environment variable to the Python process:
```
DOCKER_HOST="unix://${HOME}/.docker/desktop/backend.sock"
```
It's also possible to provide it explicitly via `base_url ` to the client constructor if not using `docker.from_env()`.
