### ISSUE TITLE
mem_limit doesn't work when it have specific units

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#305]
When I set this settings to create_container API.
Using `docker inspect` to check memory setting is still 0.
docker-py version: 0.4

```
{'command': None,
 'cpu_shares': None,
 'detach': True,
 'mem_limit': u'100m',
 'name': u'Test',
 'user': None,
 'working_dir': None}
```

If I change the value without unit. It works.

```
{'command': None,
 'cpu_shares': None,
 'detach': True,
 'mem_limit': u'1000000',
 'name': u'Test',
 'user': None,
 'working_dir': None}
```

**Comment by jlamcanopy** [comment]
It is still does not work. When is the next release?

**Comment by shin-** [comment]
The issue is more than a year old, there have been many releases since then. What are you trying to do and what error are you getting?

**Comment by jlamcanopy** [comment]
I'm trying to set mem_limit to 5g but it does not limit memory of the docker container. I inspect the container this is what I got from grep Memory:

        "Memory": 0,
        "MemorySwap": 0,
        "Memory": 0,
        "MemorySwap": 0,

**Comment by shin-** [comment]
Can you run `pip freeze | grep docker-py && python --version && docker version` and paste the output here? Also, being able to see your `create_container` call would definitely help if you don't mind sharing it.

**Comment by jlamcanopy** [comment]
Hi @shin- 
```
pip3 freeze | grep docker-py && python3 --version && docker version
docker-py==1.4.0
Python 3.4.2
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

For create_container:
```
cli.create_container(image='jupyter:latest', mem_limit='5g')
```

Inspecting the docker container will give the result above.

**Comment by shin-** [comment]
Thanks, I'll look into it.

**Comment by shin-** [comment]
I haven't been able to reproduce your issue using identical versions of python, docker, and docker-py.

Can you try running the following script and reporting with the output? Thanks.
```python
import docker

c = docker.Client(version='auto')
print('VERSION: ', c.version())

c.pull('busybox:latest')
ctnr_id = c.create_container(image='busybox:latest', mem_limit='5g')
print('CONTAINER ID: ', ctnr_id)
ctnr_data = c.inspect_container(ctnr_id)
print('Mem Limit (config): ', ctnr_data['Config']['Memory'])
print('Mem Limit (host config): ', ctnr_data['HostConfig']['Memory'])
```

**Comment by harpingon** [comment]
I have same problem, I can't run your example because of
   
    docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19

Some more investigation reveals this:
After the initial c.create_container , the Memory parameter is there with my 2g

     docker inspect garycowelle5sysbld140 | grep -i mem
        "Memory": 2147483648,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,



But, after calling c.start , the configuration is gone:

    docker inspect garycowelle5sysbld140 | grep -i mem
          "Memory": 0,
          "MemorySwap": 0,
          "CpusetMems": "",
          "MemorySwappiness": null,

After stopping the container, configuration is still gone:
    docker inspect garycowelle5sysbld140 | grep -i mem
        "Memory": 0,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,


Create another container using docker-py:
    $ docker inspect fdde29acfea6 | grep -i mem
        "Memory": 2147483648,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,

But this time, start it with docker command line:
     $ docker start fdde29acfea6
     fdde29acfea6
     $ docker inspect fdde29acfea6 | grep -i mem
        "Memory": 2147483648,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,

configuration remains.

So, seems to me that the docker-py start is clobbering some of the host config?

Hope this helps
