### ISSUE TITLE
Pushing a docker image fails but no APIError is thrown

### ISSUE THREAD

**Issue by zadigus** [docker/docker-py#3050]
I am using `docker==6.0.0` and I have the following code:
```python
    def push_image_to_hosted_docker(self, image_name, image_tag):
        docker_registry_url = f"{self._hostname}:{self._docker_hosted_port}"
        full_image_name = f"{docker_registry_url}/{image_name}:{image_tag}"
        try:
            docker_client = self._log_on_docker_registry(docker_registry_url)
            docker_client.images.build(
                path=os.path.join(self._resources_folder, image_name),
                tag=full_image_name,
            )
            result = docker_client.images.push(full_image_name)
            print(result)
        except APIError as e:
            raise CommandFailed(
                f"Unable to build and push docker image {image_name} to docker registry {docker_registry_url}"
            ) from e
```
When I run the same with the docker cli, I get the (expected) error that
```
unauthorized: access to the requested resource is not authorized
```
When I run my python code, the `result` variable is filled up with
```
'{"status":"The push refers to repository [env-8356413.hidora.com:18443/docker-image]"}\r\n{"status":"Preparing","progressDetail":{},"id":"d5bbfbb14447"}\r\n{"status":"Preparing","progressDetail":{},"id":"994393dc58e7"}\r\n{"status":"Layer already exists","progressDetail":{},"id":"d5bbfbb14447"}\r\n{"status":"Layer already exists","progressDetail":{},"id":"994393dc58e7"}\r\n{"errorDetail":{"message":"unauthorized: access to the requested resource is not authorized"},"error":"unauthorized: access to the requested resource is not authorized"}\r\n'
```
i.e. essentially the same as with the docker cli. However, the python call
```python
docker_client.images.push(full_image_name)
```
does not throw an exception, contrary to what is advertised in [the documentation](https://docker-py.readthedocs.io/en/stable/images.html), where it is written that the `push` method raises a docker.errors.APIError if the server returns an error.

Am I misinterpreting something here? how can I make it work? of course, I don't want to parse the `result` variable and look if there is an error inside.

**Comment by milas** [comment]
The push API is a bit unusual and the low-level Python API client is mostly passing things through as-is here.

The `APIError` would be returned if the server immediately failed, e.g. returned a non-2xx status code.

However, with the way that it works, the build process has started, so the status streaming kicks off, and then an error (auth) occurs, but the HTTP status has already been sent.

If you use `stream=True` & `decode=True`, you'll get a generator with `dict` objects, and could iterate through them looking for the existence of the `errorDetail` field. You'll still need to iterate through the result, but the chunking/parsing will be handled for you.

**Comment by zadigus** [comment]
Ok, thanks for your explanations.
