### ISSUE TITLE
client.containers.run immediately terminates despite detach

### ISSUE THREAD

**Issue by leander-elw** [docker/docker-py#3052]
Versions:
* Python: 3.9.13
* Docker: 20.10.17
* Docker-SDK: 6.0.0

System:
* NixOS: 22.05
* Architecture: linux/amd64

**Issue**: Creating a new container via client.containers.run(image=..., command=..., detach=True) immediately runs the container despite detach being set to True. It is not possible to connect the container to a newly created docker-network.

**Expected behavior**: A container is started and in the running state similiar to "docker container run -dt image command". Connecting the container to a network is possible within Python and on Cli. Connection is reflected within "docker network inspect".

**Received behavior**: The container stays in the "created"-state during program-execution and exits when the program is finished. Connecting the container to a network is not possible. 

**Code to reproduce issue:**
I'm using alpine/ash but the problem persisted also with ubuntu/bash.

```
import docker

client = docker.from_env()
container = client.containers.run(image="alpine", command="ash", detach=True)

network = client.networks.create("foobar")

print(f"Containers connected pre 'network.connect': {network.containers}")
network.connect(container)
print(f"Containers connected post 'network.connect': {network.containers}")

network.remove()
client.close()
```

**Comment by milas** [comment]
Your entrypoint is exiting immediately, which is why the container is exiting.

Note also that you need to call `network.reload()` for it to update internal state after calling `connect()`.

I don't see any issues with this fixed example:
```python
import docker

client = docker.from_env()
container = client.containers.run(image="alpine", command="ash", detach=True, auto_remove=True, tty=True)

network = client.networks.create("foobar")

print(f"Containers connected pre 'network.connect': {network.containers}")
network.connect(container)
network.reload()
print(f"Containers connected post 'network.connect': {network.containers}")

container.remove(force=True)
network.remove()
client.close()
```

```
Containers connected pre 'network.connect': []
Containers connected post 'network.connect': [<Container: b2bdd17e8dd2>]
```
