### ISSUE TITLE
specify multiple tags for images.build()

### ISSUE THREAD

**Issue by vladak** [docker/docker-py#3053]
While rewriting a shell script used to build Docker images to Python, I noticed that the [build() API](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build) accepts just a single tag while the `docker` CLI can accept multiple:
```shell
docker build \
 	    -t $IMAGE:$VERSION \
 	    -t $IMAGE:$VERSION_SHORT \
 	    -t $IMAGE:latest .
```
Would it be possible to change build() to accept a tag list ?

If not, can anyone provide a way how to achieve the same with the docker Python API ?

**Comment by milas** [comment]
You can use [Image::tag()](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.Image.tag) to add additional tags to an image after building it.
