### ISSUE TITLE
container.status do not update after container.stop()

### ISSUE THREAD

**Issue by jiaoL06** [docker/docker-py#3054]
the property of container.status still is running after container.stop(), Does the function contianer.stop() not update the property of container.status?

**Comment by milas** [comment]
The `Container` helper methods delegate to the underlying client API but don't update the model objects themselves 😐 

They're really more useful as convenience methods, but you'll probably want to refresh it if you're doing operations on it and then need to use the object's state.

**Comment by jiaoL06** [comment]
Thank you for your answer.
