### ISSUE TITLE
Documentation for build `path` argument

### ISSUE THREAD

**Issue by rhoban13** [docker/docker-py#3067]
The `path` argument passed to `build` in the [documentation](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build) says 

> path (str) – Path to the directory containing the Dockerfile

I suspect this really means "path to the build context"?  Doesn't have to necessarily be the same as the directory containing the `Dockerfile` - is that right?

**Comment by milas** [comment]
Yes, see #3043 for a PR improving this. It's the build context, so if it includes a `Dockerfile` that'll be used by default, but you can specify a custom path with the `dockerfile` arg or provide the contents directly via `fileobj` arg
