### ISSUE TITLE
Container not starting after creation

### ISSUE THREAD

**Issue by brejoc** [docker/docker-py#307]
Ubuntu: 14.04 (x64)
docker.io: 0.9.1~dfsg1-2 (
docker-py: 0.4.0 (installed via pip)

I'm trying to start a container with docker-py, but `c.start(…)` only returns None. This is the test-script I've been using:

``` Python
import docker
from pprint import pprint

c = docker.Client(base_url='unix://var/run/docker.sock',
          version="1.10",
          timeout=20)
c.version()
print("Images:")
print("======")
pprint(c.images())
my_container = c.create_container('ubuntu', '/bin/bash')


print("my_container:")
print("============")
pprint(my_container)

print("------------------------")
print("trying to start %s" % (my_container['Id'], ))
erg = c.start(my_container['Id'])
print("erg: %s" % (erg, ))
```

And [this is my output](http://paste.dajool.com/pfd6bndrr/caepzl). Am I missing something?

**Comment by fkromer** [comment]
Despite of am using `tty=True` and `stdin_open=True` ...

```python
import docker
client = docker.from_env()
rcappdb = client.containers.run('rcapplication_database:latest', command='rcapplication_database_create /database new.db', tty=True, stdin_open=True, detach=True)
rcappdb.exec_run(['rcapplication_database_devserver', '/database', 'new.db']) # is the container not running here for at least 3 seconds?
(some Traceback)
APIError: 500 Server Error: Internal Server Error ("Container 9707dbaed711af4fee65981416e22773d5f281d76666e32ca8fbdc6b3aeecc37 is not running")
```

... I still have the problem that the container goes into `exit` after 3 seconds?

```
❯ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                         PORTS               NAMES
9707dbaed711        rcapplication_database:latest    "rcapplication_dat..."   4 seconds ago       Exited (0) 1 second ago                            brave_davinci
```

**Comment by akanksha-atrey** [comment]
> I am using `tty=True` and `stdin_open=True` ...
> 
> ```python
> import docker
> client = docker.from_env()
> rcappdb = client.containers.run('rcapplication_database:latest', command='rcapplication_database_create /database new.db', tty=True, stdin_open=True, detach=True)
> rcappdb.exec_run(['rcapplication_database_devserver', '/database', 'new.db']) # is the container not running here for at least 3 seconds?
> (some Traceback)
> APIError: 500 Server Error: Internal Server Error ("Container 9707dbaed711af4fee65981416e22773d5f281d76666e32ca8fbdc6b3aeecc37 is not running")
> ```
> 
> ... but I have still the problem that the container goes into `exit` after 3 seconds?
> 
> ```
> ❯ docker ps -a
> CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                         PORTS               NAMES
> 9707dbaed711        rcapplication_database:latest    "rcapplication_dat..."   4 seconds ago       Exited (0) 1 second ago                            brave_davinci
> ```

Did you end up solving this? Currently having the same issue.
