### ISSUE TITLE
Dependency error 

### ISSUE THREAD

**Issue by wrender** [docker/docker-py#3071]
Hi, I'm using our own pypi mirror that was made with bandersnatch, I get the following error, when trying to install docker in my virtual environment.:

`pip3.10 install docker
Looking in indexes: http://domain.com/repos/pypi/web/simple
Collecting docker
  Using cached http://domain.com/repos/pypi/web/packages/d5/b3/a5e41798a6d4b92880998e0d9e6980e57c5d039f7f7144f87627a6b19084/docker-6.0.1-py3-none-any.whl (147 kB)
Collecting packaging>=14.0
  Using cached http://domain.com/repos/pypi/web/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl (40 kB)
Collecting requests>=2.26.0
  Using cached http://domain.com/repos/pypi/web/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl (62 kB)
Collecting urllib3>=1.26.0
  Using cached http://domain.com/repos/pypi/web/packages/6f/de/5be2e3eed8426f871b170663333a0f627fc2924cc386cd41be065e7ea870/urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting websocket-client>=0.32.0
  Using cached http://domain.com/repos/pypi/web/packages/78/d5/2b5719b738791cd798e8f097eba4bb093ff5efca5cef2f3d37a72daa111f/websocket_client-1.4.2-py3-none-any.whl (55 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached http://domain.com/repos/pypi/web/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting idna<4,>=2.5
  Using cached http://domain.com/repos/pypi/web/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached http://domain.com/repos/pypi/web/packages/1d/38/fa96a426e0c0e68aabc68e896584b83ad1eec779265a028e156ce509630e/certifi-2022.9.24-py3-none-any.whl (161 kB)
INFO: pip is looking at multiple versions of packaging to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of docker to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement charset-normalizer<3,>=2 (from requests) (from versions: 3.0.0)
ERROR: No matching distribution found for charset-normalizer<3,>=2`

**Comment by milas** [comment]
> ERROR: Could not find a version that satisfies the requirement charset-normalizer<3,>=2 (from requests) (from versions: 3.0.0) ERROR: No matching distribution found for charset-normalizer<3,>=2

The `requests` package relies on `charset-normalizer`. While v3.x of that exists as of recently (Oct 20), the latest released version of requests does not accept it.

Your PyPI proxy needs to serve a compatible version, e.g. https://pypi.org/project/charset-normalizer/2.1.1/.
