### ISSUE TITLE
`Image.history()` returned wrong type.

### ISSUE THREAD

**Issue by tuna2134** [docker/docker-py#3076]
At the document, image.history() return `str` type, but it return `list` type.

**Comment by Khushiyant** [comment]
Yes, as mentioned in docs [here](https://docker-py.readthedocs.io/en/stable/images.html?highlight=image+history#docker.models.images.Image.history), it should return str but it returns the `history` as `list` object

> history()
> Show the history of an image.
> 
> Returns:
> The history of the image.
> 
> Return type:
> (str)
> 
> Raises:
> docker.errors.APIError – If the server returns an error.


For examples:

Basic alpine image return below history as `list`

> `[{'Comment': '', 'Created': 1701999570, 'CreatedBy': '/bin/sh -c #(nop)  CMD ["/bin/sh"]', 'Id': 'sha256:<SHA>', 'Size': 0, 'Tags': ['alpine:latest']}, {'Comment': '', 'Created': 1701999570, 'CreatedBy': '/bin/sh -c #(nop) ADD file:<file> in / ', 'Id': '<missing>', 'Size': 7728526, 'Tags': None}]
`
