### ISSUE TITLE
No Module Found

### ISSUE THREAD

**Issue by James-Ilosta** [docker/docker-py#3077]
Hi, I use:

pip install docker

as suggested. When I then use import docker I get:

![image](https://user-images.githubusercontent.com/116352311/208114104-2467a341-ebfa-4a5e-bde7-11916307639c.png)

Do you have any suggestions?

**Comment by milas** [comment]
If you're using Python virtualenvs or have multiple Python installs, ensure you've installed it into the correct one.

Unfortunately, there's too many different possibilities for what could be causing this, but I don't believe it's related to this library, and I can't really provide much guidance for your specific setup

**Comment by James-Ilosta** [comment]
Hi Milas,

Thanks for your comment. I had multiple versions of python and I was downloading docker with a different pip version to the python version I was using

Thanks!
