### ISSUE TITLE
Can't start container. Unsure why

### ISSUE THREAD

**Issue by James-Ilosta** [docker/docker-py#3078]
I’m trying to run docker at the moment from the python api. I’m just trying to make a container and then run commands using the exec_run command, however, my container seems to exit immediately after using the following:

import docker
from docker.types import Mount

import os

client = docker.from_env()
source_directory = "C:\\Users\\usr\\data"
target="/data"
volume=os.getcwd() + "/data"

image_selected='openfoam/openfoam7-paraview56'
container=client.api.create_container(image_selected)
container=client.containers.get(container['Id'])
print(container)
container.start()

I’ve tried to add in a pause command with the following:
container=client.api.create_container(image_selected,  command="while true; do sleep 10000000; done")

and this doesn’t have any effect and the container still exits immediately.
![image](https://user-images.githubusercontent.com/116352311/208909199-de671070-80cc-4bb9-8c76-cce416df338f.png)
 
I don’t suppose you would have any idea on how to troubleshoot. As far as I’m aware there are no errors that are outputted.

Here is the terminal output. I tried to use container.start() 2 times so that is why there are 3 of the initial messages:
 
![image](https://user-images.githubusercontent.com/116352311/208909235-e86444fd-8f8c-4bd1-8d6d-c7c52df8e898.png)

Do you have any ideas?

**Comment by semwai** [comment]
Hello, this works in my project:
```python
self.container = client.containers.run(
            self.image,
            command='sleep 36000',
            working_dir='/app',
            volumes=[f'{self.volume.id}:/app'],
            tty=False,
            detach=True,
            network_disabled=True,
            name=f"container_{unique_id}"
        )
```
there may be a problem with the 'openfoam/openfoam7-paraview56' image, try another one to test

**Comment by James-Ilosta** [comment]
Thanks for the comment. I just tried another image and the same happens

**Comment by naufalafif** [comment]
seems to be the problem with the image
the only way I found to make it run is by changing the entrypoint. using entrypoint + command also doesn't work
executing the original entrypoint from interactive mode is working tho. look at image below

```py
import docker
from docker.types import Mount

import os

client = docker.from_env()

image_selected='openfoam/openfoam7-paraview56'
client.images.pull(image_selected)
container=client.api.create_container(
    image_selected,
    entrypoint=["/bin/sh","-c","sleep 1h"],
)
container=client.containers.get(container['Id'])
print(container)
container.start()
```

interactive mode

![Screenshot 2023-04-05 073305](https://user-images.githubusercontent.com/12013083/229944940-55df1fa6-c3d5-4907-aad6-38d76838cec4.png)
