### ISSUE TITLE
Enhancement of images API

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#309]
In `images` API, maybe can provide a parameter to determine return images with `<none>` REPOSITORY or TAG or not.

**Comment by mminer** [comment]
If I understand it correctly, an image with `<none>` for its repository and tag is considered a "dangling" image. You can list dangling images by supplying filters to the `images` method.

```python
client.images(filters={'dangling': True})
```

**Comment by bfirsh** [comment]
What @mminer said. :+1:
