### ISSUE TITLE
Add support for --cidfile in container.run() and container.create()

### ISSUE THREAD

**Issue by mschuckmann** [docker/docker-py#3096]
The docker cli supports the --cidfile command line option to provide the container ID inside the container, this feature seems to be missing in the current docker-py api but I would expect it that it would not be difficult to add to reach parity with the docker cli.

**Comment by milas** [comment]
The `--cidfile` file argument in the Docker CLI writes the container ID to a file _on the host_ (not inside the container).

You can mimic this in Python code by using the `ID` from the response and then writing it to a file of your choosing. This isn't functionality we plan to add directly to this library.
