### ISSUE TITLE
How can I read container logs with a timeout?

### ISSUE THREAD

**Issue by FerrerPablo** [docker/docker-py#3101]
I have some logs that may or may not be produced by my container.

I would like to read the logs, but use a timeout in case they are not produced. I use container.logs(stream=True, follow=True) and check the lines until I find the one I'm looking for. This is fine if the logs indeed appear in the container, but if they don't, I would like to stop looking at the generator and continue with my program.

The problem is that the generator will hang when next() is called and no new lines exist. Is there a way to limit the time next() takes?

Any help is appreciated. Thanks!

**Comment by FerrerPablo** [comment]
Well, shit.

After hours of searching and postinf the question here, I was completely out of ideas so I said to myself "hey I could try this ChatGPT thing everyone talks about" well it came up with a pretty nice solution and it solved the issue for me. Here's what it gave me in case anyone's interested. I'll be having an existential crisis if you need me:

> You can use a queue.Queue to buffer the log lines received from the container, and a threading.Thread to read from the log stream in the background and put the log lines into the queue.

> Here's an example implementation:

```python
import docker
import queue
import threading
import time

client = docker.from_env()
container = client.containers.get('pvr-user-manager')
since = context.last_container_start

log_queue = queue.Queue()

def read_logs():
    stream = container.logs(stream=True, follow=True, since=since)
    for line in stream:
        log_queue.put(line)

log_thread = threading.Thread(target=read_logs)
log_thread.start()

while True:
    try:
        # Wait up to 30 seconds for a log line to become available
        line = log_queue.get(timeout=30)
    except queue.Empty:
        print('No logs were found in the last 30 seconds')
        break
    
    # Print the log line to the console
    print(line.decode().rstrip())
    
    # Check if the log thread has finished (i.e., if the log stream has closed)
    if not log_thread.is_alive() and log_queue.empty():
        break
```

> In this implementation, we're using a queue.Queue called log_queue to buffer the log lines received from the container. We're also using a threading.Thread called log_thread to read from the log stream in the background and put the log lines into the queue.

> In the main loop, we're using the get() method of log_queue to wait up to 30 seconds for a log line to become available. If a log line is available, we print it to the console using print(). If no log lines are available, we print a message to the console and break out of the loop.

> We're also checking if the log_thread has finished (i.e., if the log stream has closed). If the log_thread has finished and the log_queue is empty, we break out of the loop.

**Comment by andrelaszlo** [comment]
@FerrerPablo I know I'm late, but I think this leads to a memory leak, since the thread will still be running indefinitely after the `log_queue.get` times out.

The correct way seems to be (I haven't tested it yet) to close the stream returned by `logs()`, see [CancellableStream](https://github.com/docker/docker-py/blob/df3f8e2abc5a03de482e37214dddef9e0cee1bb1/docker/types/daemon.py#L12-L18):

```
>>> events = client.events()
>>> for event in events:
...   print(event)
>>> # and cancel from another thread
>>> events.close()
```
