### ISSUE TITLE
[REQUEST] use package with containerd

### ISSUE THREAD

**Issue by Pymann** [docker/docker-py#3105]
Hello guys,

I know the containerd is a container-engine capable to replace docker.
There is any possibility to use this package in connection with containerd, because the docker.sock will not exist anymore?

**Comment by milas** [comment]
containerd is a low-level framework/library for container engines. It's heavily used by the Docker Engine (and was originally spun out from the Docker codebase).

Also, the `docker.sock` is not going anywhere and is still supported and the default way to communicate with the Docker API locally. It's used by the Docker CLI, Compose, etc.
