### ISSUE TITLE
CVAT Error 

### ISSUE THREAD

**Issue by sulaiman1988** [docker/docker-py#3109]
the error occurs when making automatic annotation on CVAT:
Interaction error occurred
Error: Request failed with status code 503. 
"HTTPConnectionPool(host='host.docker.internal', port=54658): Max retries exceeded with url: / 
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f061c0ff1f0>: 
Failed to establish a new connection: [Errno 111] Connection refused'))".

**Comment by milas** [comment]
There's not enough information to help here.

This does not appear to be a `docker-py` issue, however. Your HTTP code ran and got a 503 response code. Can you `curl host.docker.internal:54658` successfully?
