### ISSUE TITLE
Can't create config object

### ISSUE THREAD

**Issue by Josh-Klassen-Dejero** [docker/docker-py#3110]
Much like https://github.com/docker/docker-py/issues/2025 the config model is failing to create a new object due to 'name' KeyError

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "docker\models\configs.py", line 10, in __repr__
    return f"<{self.__class__.__name__}: '{self.name}'>"
  File "docker\models\configs.py", line 14, in name
    return self.attrs['Spec']['Name']
```

This https://github.com/docker/docker-py/pull/2793 appears to be the fix that was implemented and should likely be implements for configs as well (if not other models that might have this issue)

**Comment by KentaroJay** [comment]
@Josh-Klassen-Dejero 
Hello, I would like to contribute to this issue. May I ask you to put more detail to replicate the situation?
- OS
- Docker version
- docker-py version
- python version
- files you faced this problem

**Comment by Josh-Klassen-Dejero** [comment]
- Windows 10 Pro 64bit version 21H2 build 19044.2965
- Docker Desktop 4.19.0
- docker-py 6.0.1
- Python 3.8.10
- it happened for all config files

**Comment by MrCapsLock** [comment]
Can confirm. Any update about this problem?
