### ISSUE TITLE
Can't pass multi-line command

### ISSUE THREAD

**Issue by dondublon** [docker/docker-py#3119]
Hello. I try to send multi-line command, and this is the results:
```
    command = 'python -c \"print(\'hello world\')\"'  # works
    command = 'pip install pip -U'  # works
    command = 'pip install pip -U && echo'  # doesn't work
    command = 'pip install pip -U \n&& echo'  # doesn't work
    command = 'pip install pip -U \\\n&& echo'  # doesn't work

    create("python:3.10", command)
```
All case that doesn't work show me the error:
` returned non-zero exit status 1: b"ERROR: Invalid requirement: '&&'\n\n` and similar, like there is pip `-r` key somewhere. 
The OS is xubuntu, docker is run on a localhost in regular way. Could you please help?

**Comment by milas** [comment]
Commands are not run by a shell, so `&&` is actually getting passed as an argument to `pip`.

You can either do something like `sh -c 'pip install pip -U && echo'` or run multiple commands depending on your use case/requirements.

**Comment by dondublon** [comment]
Thanx. I can't split, this is the given condition (a test task). i'll try with sh -c.

**Comment by dondublon** [comment]
Yes, sh -c works, thank you!
