### ISSUE TITLE
volumes and -v behave inconsistent

### ISSUE THREAD

**Issue by Pymann** [docker/docker-py#3137]
I docker inspect and have two different containers, respecting the mount options:
the volumes differ, therefore there is bug in library, producing inconsistency in comparison to the docker run command:

argument:
'volumes': ['/tmp/pulseaudio.socket:/tmp/pulseaudio.socket', '/tmp/pulseaudio.client.conf:/etc/pulse/client.conf', '/home/EU.BSHG.COM/ehrhardtn:/home/docker', '/home/EU.BSHG.COM/ehrhardtn/.conan/data:/opt/conan-user/.conan/data', '/home/EU.BSHG.COM/ehrhardtn/.conan/.conan.db:/opt/conan-user/.conan/.conan.db', '/media/sf_C_DRIVE:/media/sf_C_DRIVE', '/tmp/.X11-unix:/tmp/.X11-unix']

and -v option with same content dont do same.

Again its visible with docker inspect:
volumes stays null for a normal docker run, but is filled by docker-py package. Btw. the mounts parts stay equal.
It can cause conan to end in --locked errors.

docker-py:
"Volumes": {
"/etc/pulse/client.conf": {},
"/home/docker": {},
"/media/sf_C_DRIVE": {},
"/opt/conan-user/.conan/.conan.db": {},
"/opt/conan-user/.conan/data": {},
"/tmp/.X11-unix": {},
"/tmp/pulseaudio.socket": {}
},

docker run
"Volumes": null,

It should be easy to reproduce, you start any container with docker run -v a:b and via docker-py with volumes argument. Finally docker inspect both.

**Comment by milas** [comment]
`docker-py` provides low-level access to the Engine API. If you pass `volumes`, it will go the API.

Omit that argument and continue to include `host_config::mounts` and you should have the same behavior as the CLI where `Config::Volumes` is `null`.

**Comment by Pymann** [comment]
there is a difference between host-config mounts and container-mounts ?

**Comment by Pymann** [comment]
There are still some gaps in your api.... The high lvl api mounts option sets both, checking docker inspect, the host mounts and normal mounts are configured. binds stays empty. With the low lvl api, I guess, you can pass by host-config-mounts. what Iam not intending. Therefore... setting normal mounts only is not possible.

**Comment by Pymann** [comment]
you are not completely right with host_congig binds I can produce same result (docker inspect), you have with -v option.
