### ISSUE TITLE
build images with tag with https prefix never ends

### ISSUE THREAD

**Issue by axel7083** [docker/docker-py#3153]
## Reproduces

```
docker_client = docker.from_env()
docker_client .images.build(path="{my-path}", tag="https://dummy:latest", dockerfile="{dockerfile-path})
```

Using the debugger, we can see it loop on the _post request here:

https://github.com/docker/docker-py/blob/84414e343e526cf93f285284dd2c2c40f703e4a9/docker/api/build.py#L264-L271

**Comment by naufalafif** [comment]
https://dummy:latest is not a valid image tag

Docker image tags can only contain lowercase and uppercase letters, digits, underscores, periods, and dashes. https://docs.docker.com/engine/reference/commandline/tag/

if you are trying to use custom registry, there's no need to add https prefix
