### ISSUE TITLE
python script failed with redundant `\n`using docker `exec_run` 

### ISSUE THREAD

**Issue by anabioticsoul** [docker/docker-py#3154]
I'm using the python API to execute python script.
```python
autoware_container.exec_run(cmd="/opt/ros/melodic/bin/rostopic pub -l /config/waypoint_replanner autoware_config_msgs/ConfigWaypointReplanner \"{replanning_mode: true, velocity_max: 2.0}\"", user="autoware", privileged=True, detach=True)

```

The console is as follows:
```log
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/rostopic", line 34, in <module>
    import rostopic\n
ImportError: No module named rostopic\n
```

The same log with following shell script:
```sh
docker exec -it autoware-$USER bash -c /opt/ros/melodic/bin/rostopic pub -l /config/waypoint_replanner autoware_config_msgs/ConfigWaypointReplanner "{ velocity_max: 2.0}"

```

But the it works well when I manually used bash in separate steps (command line).
It seems that the `\n` leads to the failure. Is there any lower level API to execute the python script?
```[tasklist]
### Tasks
```

**Comment by naufalafif** [comment]
docker-py code above produce different command from the one you shared. can you try again without privileged & user params

**Comment by anabioticsoul** [comment]
I finally found that `\n` didn't impact the execution of the python script. The module was not imported indeed. Thank you so much!
