### ISSUE TITLE
Cannot run `make test`

### ISSUE THREAD

**Issue by john-b-yang** [docker/docker-py#3171]
Hello, I followed the instructions to build `docker-py` locally by cloning a fork of the repository and running `python setup.py develop`.

I am attempting to run the tests with `make test`, but when I run this command, I get the following error:

```
$ make test
docker build \
	--pull \
	-t docker-sdk-python3 \
	-f tests/Dockerfile \
	--build-arg APT_MIRROR .
make: docker: No such file or directory
make: *** [Makefile:34: build-py3] Error 127
```

Can I get guidance on what to do? Thanks in advance!

**Comment by milas** [comment]
```
make: docker: No such file or directory
```

You need Docker installed and working to run the tests and other Makefile tasks, many of them use containers.

**Comment by john-b-yang** [comment]
I see, thanks for the clarification!
