### ISSUE TITLE
Is there any method to run a container from a docker file?

### ISSUE THREAD

**Issue by marcelomachado** [docker/docker-py#3177]
I would like to run a container from a python application using this docker library.  I know that is possible to execute a container like this:
```python
import docker
client = docker.from_env()
client.containers.run('alpine', 'echo hello world')
```

I would like to know if it is possible to run a container from a docker compose programmatically. For instance:

```python
import docker

compose= toYaml("""
version: '3.3'
services:
        alpine:
            volumes:
                - V:Z'
            environment:
                - X=Y
            ports:
                - '8080:8080'
            image: alpine
""")

client = docker.from_env()
client.containers.run(compose)
```

**Comment by milas** [comment]
No, Compose itself is a CLI tool and does not expose an API.

If you want to build/orchestrate containers with Compose, you can use subprocesses to shell out to it, e.g. `docker compose up --build`.
