### ISSUE TITLE
Unable to update port bindings in existing container

### ISSUE THREAD

**Issue by evergreen-shankar** [docker/docker-py#3179]
Hi, I am using `docker sdk v6.1.3` in python code. I have used below code to update. When i run `docker ps` the port is still showing the old one. Could you please help here to update into existing container.
`
    
    import docker
    
    # Create a Docker client
    client = docker.from_env()
    
    # Specify the container name or ID
    container_id = "test"
    
    # Define the new port bindings
    new_port_bindings = {
        "104/tcp": 104
    }
    
    try:
        # Get the container
        container = client.containers.get(container_id)

    # Update the port bindings in the configuration
    container.attrs["HostConfig"]["PortBindings"] = {
        port: [{"HostPort": str(host_port)}]
        for port, host_port in new_port_bindings.items()
    }

    con_port = container.attrs["HostConfig"]["PortBindings"]
    print(con_port)

    # Commit the updated configuration to the container
    container.update()

    print(f"Updated port bindings for container '{container_id}'")

    except docker.errors.NotFound as e:
        print(f"Container '{container_id}' not found: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")
`

**Comment by 10Nayanamb** [comment]
You cannot directly modify the port bindings of an existing container using python docker sdk, please have a look, https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container

**Comment by milas** [comment]
This is a design decision within the engine, so there's no way for the Python bindings to add support for this.
