### ISSUE TITLE
docker.errors.APIError: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by George-Tang16** [docker/docker-py#3184]
Hello team,

 I got "docker.errors.APIError: 500 Server Error: Internal Server Error ("b'{"message":"unauthorized: access to the requested resource is not authorized"}'") ".  Would yo mind sharing your expertise with me and help out with fixing it?

Thanks in advance,
George

**Comment by milas** [comment]
Hi, there's unfortunately not enough detail to help here, and it's not clear this is an issue with the Python bindings, as it seems to be communicating with the engine but getting a permission error.

I would make sure that you have correct registry permissions, etc.
