### ISSUE TITLE
Usage memory returned by Docker-Py is different thanthe one returned by "docker stats"

### ISSUE THREAD

**Issue by nicolargo** [docker/docker-py#3210]
From Docker-Py => 1626112 (1.6 MB):

```
$ python
Python 3.9.18 (main, Sep  7 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.from_env()
>>> containers = client.containers.list(all=True)
>>> containers[0].stats(stream=False)['memory_stats']['usage']
1626112
```

From docker stats ==> 448 KiB:

```
$ docker stats --format 'json' --no-stream
{"BlockIO":"2.85MB / 0B","CPUPerc":"0.00%","Container":"b293b6d5cc44","ID":"b293b6d5cc44","MemPerc":"0.00%","MemUsage":"448KiB / 30.81GiB","Name":"ccs_deployer_nhe","NetIO":"125kB / 0B","PIDs":"1"}
```

**Comment by milas** [comment]
`docker-py` is returning the data as it comes from the Engine API.

The Docker CLI's output does not include cached memory. There's an explanation in the code @ https://github.com/docker/cli/blob/3c0c68a45ae5b729a8b3e91b60783d818c315738/cli/command/container/stats_helpers.go#L227-L249.

To get the same number, you can replicate that logic, e.g. for cgroupsv2, that's `usage - inactive_file`.

**Comment by nicolargo** [comment]
Ok @milas thanks for the clarification.
