### ISSUE TITLE
Unable to import large tarballs using import_image

### ISSUE THREAD

**Issue by ssssam** [docker/docker-py#322]
Hi! I've been looking at improving the import_image() entry point.

The docs currently say:

> If src is a string or unicode string, it will be treated as a URL to fetch the image from. To import an image from the local machine, src needs to be a file-like object or bytes collection. To import from a tarball use your absolute path to your tarball. To load arbitrary data as tarball use whatever you want as src and your tarball content in data."

If src is a file-like object, I get the following error:

    Traceback (most recent call last):
    File "./docker-write-test.py", line 48, in <module>
        response = client.import_image(src=f)
    File "/usr/lib/python2.7/site-packages/docker/client.py", line 527, in import_image
        fic = open(src)
    TypeError: coercing to Unicode: need string or buffer, instance found

If src is a filename, the import works for small tarballs, but fails for larger ones:

    Traceback (most recent call last):
    File "./docker-write-test.py", line 48, in <module>
        response = client.import_image(src=f.name)
    File "/usr/lib/python2.7/site-packages/docker/client.py", line 528, in import_image
        data = fic.read()
    MemoryError

That's because the import_image() command tries to read the whole image into memory and send it as one request. It works up to about 500MB of image size on my system, but no further.

The Requests library allows us to stream the tarball using HTTP chunked encoding. I've got this to work, but it requires manually creating a generator object to read 'src' in chunks and pass it to the post() function. It should be easier than this but https://github.com/kennethreitz/requests/issues/1648 prevents it from working right if we pass a 'file' object to post() directly.

**Comment by shin-** [comment]
With #448 merged we should be good to close this.
