### ISSUE TITLE
Fixed, but needs release 7.0.1 or later - Tag validation fails on registries with `:PORT` specified (`localhost:5000/example:latest`)

### ISSUE THREAD

**Issue by consideRatio** [docker/docker-py#3240]
https://github.com/docker/docker-py/pull/3191 introduces a regex to validate what valid tags are. This led to a validation failure for `localhost:5000/example:latest`, and according to the description in https://docs.docker.com/reference/cli/docker/image/tag/#description should be allowed. It has practically worked before as well, so I think this is too narrow validation.

There is an example in [docker docs](https://docs.docker.com/reference/cli/docker/image/tag/#tag-an-image-for-a-private-registry) that also fails validation: `myregistryhost:5000/fedora/httpd:version1.0`

![image](https://github.com/docker/docker-py/assets/3837114/2856a6f7-75b1-48d9-bfe7-6bb398296b18)

**Comment by alexrashed** [comment]
Chiming in here from the side: This was discussed in localstack/localstack#9864. I think this issue has already been fixed with https://github.com/docker/docker-py/pull/3196, but unfortunately there hasn't been a release containing the fix yet.
