### ISSUE TITLE
Container.attrs["State"]["Running"] remains False after starting a container

### ISSUE THREAD

**Issue by emendir** [docker/docker-py#3269]
After creating a Container object and starting it, the container's `attrs` field still says the container is not running.
Only when creating a new Container object does the `attrs` field show the correct status.

I wonder if any other fields of the `attrs` attribute are affected?

Here is ascript demonstrating the problem:
```python
import docker
from time import sleep
client = docker.from_env()

container = client.containers.create("nginx")

container.start()
sleep(5)

print(container.attrs["State"]["Running"]) # prints False
print(client.containers.get(container.id).attrs["State"]["Running"]) # prints True
```

**Comment by massi1008** [comment]
This is intended behaviour, see the docs: https://docker-py.readthedocs.io/en/stable/containers.html#container-objects
> Note that local attributes are cached; users may call [reload()](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.reload) to query the Docker daemon for the current properties, causing [attrs](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.attrs) to be refreshed.
