### ISSUE TITLE
Broken dependency on six

### ISSUE THREAD

**Issue by andyp1per** [docker/docker-py#344]
Trying to use ansible on Amazon Linux EC instances with docker-py. My playbook does this:

- command: easy_install pip creates=/usr/bin/pip
- command: pip install docker-py creates=/usr/lib/python2.6/site-packages/docker/client.py
- command: pip install --upgrade six

The last step should not be necessary but if I omit it I get this:

failed: [54.172.99.39] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-fivtwwcvtrwybqrmybkqqvlzvtlnqjqw
Traceback (most recent call last):
  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1412696774.24-69218506797267/docker", line 312, in <module>
    from docker.client import APIError as DockerAPIError
  File "/usr/lib/python2.6/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client # flake8: noqa
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 30, in <module>
    from . import errors
ImportError: cannot import name errors

FATAL: all hosts have already failed -- aborting

**Comment by Hi-king** [comment]
Similar problem happened to me with python2.7 and local machine

**Comment by shin-** [comment]
Hm, it would probably be wise to require a more recent version of six. Thanks for reporting this.

**Comment by gdw2** [comment]
Encountered this problem today.  Thanks for the workaround @Hi-king !

**Comment by nicolargo** [comment]
Also encountered on my system: CentOS 7 with Python 2.7.5. Thks @Hi-king !
