### ISSUE TITLE
How to use command parameters that have embedded quotes?

### ISSUE THREAD

**Issue by mkoistinen** [docker/docker-py#348]
For example:

```` python
command = '/usr/bin/xvfb-run -a -s "-screen 0 1600x1200x24" ...'
c.create_container(image=settings.MYIMAGE, stdin_open=True, tty=True, command=command)
````

The resulting command always strips out the double quotes, resulting in failures. I've tried everything I can think of to escape, but the result is always:

````
/usr/bin/xvfb-run -a -s -screen 0 1600x1200x24 ...
````

Which isn't really what I need.

**Comment by mpetazzoni** [comment]
FWIW when you use a list for the command, you don't need quotes at all. Each element of the list is exactly one command line argument, even if it contains spaces.

```python
command = ['/usr/bin/xvfb-run', '-a', '-s', '-screen 0 1600x1200x24', '...']
```

HTH

**Comment by ats0stv** [comment]
Facing the same issue. The below command in python runs smoothly.
```check.py --coverage 'Hello World' --blabla something
All Raw Arguments
['--coverage', 'Hello World', '--blabla', 'something']
All Args
Namespace(blabla='something', coverage='Hello World')

Print Coverage
Hello World

Print blabla
something
```

The same script when I have it within the docker container and run using `docker run`, the text inside quotes is split into multiple vars of the list.

```docker run --rm -i sample --coverage 'Hello World' --blabla something
All Raw Arguments
['--coverage', 'Hello', 'World', '--blabla', 'sometext']
usage: check.py [-h] [--coverage COVERAGE] [--blabla BLABLA]
check.py: error: unrecognized arguments: World

``` 
My dockerfile definition is as follows
```
FROM sample_base

ENTRYPOINT ["/check.py"]
CMD ["--help"]
```

Breaking my head for the past couple of hours. Any help is much appreciated

**Comment by Andyccs** [comment]
> No, it did not, the quotes were stripped out again. I ended up changing the command to be a script with some of the params that require quotes embedded there. But, someone is surely going to need this ability.

This works for me, but kind of ugly.
