### ISSUE TITLE
Client occasionally hangs when using attach(stream=True)

### ISSUE THREAD

**Issue by hamiltont** [docker/docker-py#368]
When using the output generator returned by attach, I occasionally see a hang. Ctrl-C points to this line

    block = socket.recv(size)

Here is my code - perhaps the looping around attach is causing this problem -- perhaps you cannot safely call `attach(stream=True)` twice on one container? I typically see only one `"Looping for output..."` message,

    # Fetch container output while we are running
    while setup_util.is_running(cid):
      output = c.attach(cid, stream=True)
      for line in output:
        # TODO: Occasionally there is a bug with the output generator 
        # and it hangs indefinitely
        print "DOCKER:tfb-%s: %s" % (test_dir_name, line.strip())
      print "Looping for output..."
      time.sleep(100.0 / 1000.0) # Sleep 100ms

**Comment by shin-** [comment]
I'll close this for now, but let me know if you encounter that issue again.
