### ISSUE TITLE
Get built image id when using `stream=True`

### ISSUE THREAD

**Issue by defunctzombie** [docker/docker-py#392]
Apologies if I am unable to locate how to do this via the docs. I have a tool which uses the `.build` api with the `stream=True` flag to print the stream as it is available. One downside to this tho is the loss of built image ID information. Is there a way to get that after the build completes? Right now I am specifying `tag=<name here>` when doing the build but it would be nice to avoid having to explicitly specify a temporary tag and just get the final image id.

**Comment by shin-** [comment]
This has been added as a feature with the new `DockerClient` in 2.0.0

```python
import docker
dc = docker.from_env()
image = dc.images.build(path='.')
print(image.id) # sha256:e1a0edbefee23e8756909d07814cd325b245ac6a0ecbd7a1fa91ac1ad8d086c9
```
