### ISSUE TITLE
requests.exceptions.SSLError: hostname '192.168.59.103' doesn't match 'boot2docker'

### ISSUE THREAD

**Issue by tbronchain** [docker/docker-py#406]
Hey guys,

I'm try to access some boot2docker (1.3.1 - mac) VMs built under custom name with docker-py (latest pip version - 0.6.0), and it seems there is something wrong in the SSL module.

```
[thibaultbronchain@mactibo ~:]$    export DOCKER_HOST=tcp://192.168.59.103:2376
[thibaultbronchain@mactibo ~:]$    export DOCKER_CERT_PATH=/Users/thibaultbronchain/.boot2docker/certs/Docker-Wordpress-NoASG-DualNode-0
[thibaultbronchain@mactibo ~:]$    export DOCKER_TLS_VERIFY=1
[thibaultbronchain@mactibo ~:]$python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> from docker.client import Client
>>> from docker.utils import kwargs_from_env
>>> client = docker.Client(**kwargs_from_env())
>>> kwargs_from_env()
{'tls': <docker.tls.TLSConfig object at 0x10a970b10>, 'base_url': 'https://192.168.59.103:2376'}
>>> client.images()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/docker/client.py", line 634, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/Library/Python/2.7/site-packages/docker/client.py", line 76, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '192.168.59.103' doesn't match 'boot2docker'
>>> ^D
[thibaultbronchain@mactibo ~:]$docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

Thanks for the help!

**Comment by mparker17** [comment]
Is it worth re-opening this issue until it's been fixed upstream?

I can confirm that I'm getting the error on Mac OS/X 10.10.1 (14B25) "Yosemite", running Python 2.7.8, Boot2Docker-cli version: v1.4.1 (Git commit: 43241cb), fig 1.0.1, and VirtualBox 4.3.20 r96996.

**Comment by shin-** [comment]
Does this help? https://github.com/docker/docker-py/issues/424#issuecomment-67710118

**Comment by dzwicker** [comment]
using the ```/etc/hosts``` fix works. But make sure to use 
```export DOCKER_HOST=tcp://boot2docker:2376```
after the call to
```$(boot2docker shellinit)```
as it reexport the ```DOCKER_HOST``` with the ip i think.

**Comment by indygreg** [comment]
Yes, updating `/etc/hosts` is a workaround. But not every user has permission to update `/etc/hosts`. This includes my use case, where I'm using docker-py as part of testing automation and the Docker hostname is not static. Requiring root or write privileges to `/etc/hosts` is a non-starter.

**Comment by tbronchain** [comment]
Same problem here. I'm using docker-py to develop an automation tool,
automatically editing /etc/hosts file doesn't fit my needs.
Also, I may have multiple VMs running, and in this case, the hosts fix is
invalid.

**Comment by shin-** [comment]
Guys, you need to report that to the boot2docker maintainers, there's nothing I can do at my level about this issue.

**Comment by indygreg** [comment]
You can work around this in docker-py. Read https://github.com/docker/docker-py/issues/406#issuecomment-68078631 again.

You could also throw a big giant warning in the docs that urllib3/requests is busted so future souls don't have to search out this issue.

**Comment by indygreg** [comment]
Also, this is purely a Python bug, not a boot2docker bug.

**Comment by shin-** [comment]
Sure, but ideally `assert_hostname=True` should work in the context of boot2docker, too. But I'll look into the proposed fixes, thanks.

**Comment by shin-** [comment]
Hopefully this helps https://github.com/docker/docker-py/commit/7a623c4019a4eeae964a74369a4b0d92821672da

**Comment by shin-** [comment]
Also note that if the bug was introduced in `requests>=2.5.0`, you shouldn't have any issue using the pinned dependencies from the `requirements.txt` file, which states `requests==2.2.1`.

**Comment by indygreg** [comment]
`requirements.txt` files are typically intended for "complete environments." In many cases, `docker-py` is used as a library as part of a larger tool. As such, its `requirements.txt` are likely completely ignored. A better way to do version enforcement is with `install_requires` in `setup.py`. See https://packaging.python.org/en/latest/requirements.html. Please note that it is not a good practice to pin versions in `install_requires` (like it is in `requirements.txt`).

**Comment by shin-** [comment]
I understand this, which is why we have strict requirements in requirements.txt and minimum requirements in setup.py (although if it was entirely up to me I'd pin versions everywhere ~ but that's another debate).

I only wanted to provide as much information as possible for people that might be affected. :) next release will prioritize system-provided urllib3 over the vendored version, so we should cover most cases this way.

Thank you for helping resolve this.
