### ISSUE TITLE
Support Identity Auth

### ISSUE THREAD

**Issue by dlorenc** [docker/docker-py#414]
I'm not sure what this should look like in the docker-py API, but docker-py should support the new identity-based auth from this proposal:
https://github.com/docker/docker/pull/8265

**Comment by bfirsh** [comment]
@aanand might know.

**Comment by dlorenc** [comment]
@public Did you get anywhere on this?

**Comment by dlorenc** [comment]
ping
@public, @bfirsh

Is anyone looking at this?/

**Comment by proppy** [comment]
ping @shin-

**Comment by bfirsh** [comment]
Work on identity auth has been stalled indefinitely. :(

Might be worth closing this issue...

**Comment by dlorenc** [comment]
It's stalled in general, or just for docker-py? Is machine going to use TLS certs instead?

Is there a discussion somewhere I can see?

**Comment by bfirsh** [comment]
@dlorenc It's stalled in general I'm afraid. Machine is going to use TLS certs.

The only discussion is here, I think: https://github.com/docker/docker/pull/8265

**Comment by shin-** [comment]
Thanks @bfirsh for following up.

I'm going to close this issue since this is now an upstream concern. Feel free to re-open or create a new issue if the situation changes.

**Comment by dlorenc** [comment]
Sounds good. I was mainly concerned about docker-py not working with docker machine. If docker machine is using TLS this should be fine.
