### ISSUE TITLE
Add helper API on top of core API

### ISSUE THREAD

**Issue by hamiltont** [docker/docker-py#417]
It seems that the current architecture of `docker-py` is to exactly mirror the API of docker, and not add any "helper functions" on top. I totally agree that the docker-py core should mirror the API of docker as closely as possible. However, I keep finding myself re-writing common helpers over and over when integrating docker-py with other code. 

Would the maintainers be opposed to adding a `helper` API on top of the existing core API that adds  common operations, such as checking if a container or image exists, converting raw strings into more pythonic types, etc? I'm happy to provide some initial PRs to build a base for this new API if someone gives me a green light

**Comment by gtaylor** [comment]
We had to figure out how to handle this very issue with boto a few years ago. Initially, I felt that a separate package with the more sane API would make the most sense. However, that would mean juggling two projects with two potentially different release cadences, with a really confusing backwards compatibility story (boto evolves/evolved fast, like Docker).

We eventually settled on a layered approach. The official Amazon Java SDK was imitated closely in ``layer1``, and a more humane API took form in ``layer2``. You can see this in practice in the [dynamodb2 module](https://github.com/boto/boto/tree/develop/boto/dynamodb). Amazon's DynamoDB API was particularly difficult to deal with at first, so this second layer brought some much-needed sanity and usability to the table.

However, some developers really do need access to the "native" level in order to specially optimize or handle some more complex cases. Most end up using layer2, because it's easier, but this setup allows everyone to be happy.

I don't know what this would look like in docker-py, but figured I'd share experiences from another Python module that also had to track a rapidly changing upstream API. It sounds like you are leaning that way, anyway.

FWIW, I'd gravitate towards a module name that suggests its primary purpose (helpers, conveniences, friendliness). Maybe something like ``docker.humane``.

**Comment by Julian** [comment]
FWIW I am +1 on this being a separate package, and I've already started assembling some helpers that I've used -- to add to your list, `temporary_image` and `temporary_container`, which create images and containers and delete them in a contextmanager. Possibly by the time I'm done I'll have shoved them into a separate library myself anyhow.

**Comment by hamiltont** [comment]
@Julian great ideas! FWIW I've got some basic code but it's a bit stalled, if anyone wants to take point on a PR for this I'm happy to deposit my current code into a gist in case it's useful

**Comment by Julian** [comment]
Nice! I've got some as well, although it's a bit stuck on not having an
easy way to write tests for it unfortunately, but maybe starting to put
some stuff in the same place would get this kick started, yeah.

**Comment by shin-** [comment]
I'll try to kickstart something today or tomorrow if it helps.

**Comment by shin-** [comment]
Thrown a branch together for starters, added a few commonly requested functions. See https://github.com/docker/docker-py/tree/efficiency ; Feel free to send PRs against this branch, even if it's WIP.

**Comment by ssanderson** [comment]
I've started working on a separate project with the goal of providing a higher-level object-oriented API on top of the REST API implemented here: https://github.com/quantopian/dockorm.  It's currently built with deployment of IPython/Jupyter notebook servers in mind, but the library itself is pretty generic besides using IPython's traitlet system to provide configuration: https://github.com/quantopian/dockorm.

**Comment by hamiltont** [comment]
Here's a simple idea that I've used a few times, maybe it will help out here. 

```
import os
import threading
import sys

def log_for_docker(generator, line_prefix='', print_empty=False):
  '''
  To get generator, use `client.logs(container=cid, stream=True)`
  It's perfectly reasonable to use this method once for STDOUT and 
  once for STDERR 
  '''
  def log_docker(generator, print_empty, line_prefix):
    for line in generator:
      if print_empty or line.strip():
        sys.stdout.write(line_prefix)
        sys.stdout.write(line)
  r_log = threading.Thread(target=log_docker, args=(generator,print_empty, line_prefix))
  r_log.daemon = True
  r_log.start()
```

Naturally this might cause output to be mixed when using multiple threads, but I've yet to have such serious issues that I've cared. If someone wants to modify this to take an output mutex, they could easily make it such that only one background thread is printing at a single time without hurting the performance of the main thread of execution. That's no guarantee that the main thread and the currently-printing background thread won't write at the same time, it would just help if you've got many container logs being tracked in one application

**Comment by hamiltont** [comment]
Usage for above code

```
    log_generator = cli.logs(container=cid, stream=True)
    log_for_docker(log_generator, 'RabbitMQ: ', True)
```

Output: 
```
RabbitMQ: 
RabbitMQ:               RabbitMQ 3.4.4. Copyright (C) 2007-2014 GoPivotal, Inc.
RabbitMQ:   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
RabbitMQ:   ##  ##
RabbitMQ:   ##########  Logs: tty
RabbitMQ:   ######  ##        /var/log/rabbitmq/rabbit@WebJuice-sasl.log
RabbitMQ:   ##########
RabbitMQ:               Starting broker...
RabbitMQ: =INFO REPORT==== 28-Feb-2015::23:55:38 ===
```

**Comment by hamiltont** [comment]
Another one that may be useful here while I'm at it. Ensures a container dies with the program. 

Naturally this could be modified to support it's own kwargs (stuff like `should_rm` or `timeout`) that are stripped from the dictionary passed to start

```
import atexit

def safe_start(client, *args, **kwargs):
  def container_cleanup(client, cid):
    client.stop(cid)

  client.start(*args, **kwargs)
  if len(args) == 1:
    atexit.register(container_cleanup, client, args[0])
  else:
    atexit.register(container_cleanup, client, kwargs['container'])
```

Called as: 

```
  # Both method work fine
  safe_start(cli, cid, publish_all_ports=True)
  safe_start(cli, container=cid, publish_all_ports=True)
```

**Comment by TomasTomecek** [comment]
I've already started working on a tool where one of the functionalities is to provide such helper functions:

https://github.com/DBuildService/dock/blob/master/dock/core.py#L151

**Comment by thomasem** [comment]
I'm trying to wrap my head around whether this issue matches with the problem I'm having. Currently `docker-py` returns fairly painful-to-use responses from the API for a Python application. Even worse if you're writing against multiple versions of the Docker/Swarm API where things may have dramatically changed.

I would prefer being able to parse any version of the API that's supported by `docker-py` to a common format for consumers of `docker-py`. This would make it easier to integrate with a variety of versions of Docker that you may be talking to. Especially useful for a provider of a Docker service.

My current solution is a parser module where you essentially do:

```python
import docker
import docker_parse

client = docker.Client(..., version='auto')
resp = client.info()

friendly_info = docker_parse.parse(client.version(), "info", resp)
```

Thoughts?

**Comment by bfirsh** [comment]
https://github.com/docker/docker-py/issues/1186. :tada:
