### ISSUE TITLE
Data lost in attach/execute/logs due to raw socket handling code

### ISSUE THREAD

**Issue by leth** [docker/docker-py#425]
As discussed in #336 requests's socket reads may stray into the HTTP body, but the data will be kept in a local buffer for future reads. The HTTP response raw socket code bypasses this buffer to use the socket directly, which leads to the lost data.

**Comment by shin-** [comment]
I believe this can be closed, feel free to ping if that's not the case.

**Comment by leth** [comment]
Anything which calls `Client._get_raw_response_socket` will still be affected. This includes: `attach_socket`, `attach`, `execute` and `logs`.

**Comment by leth** [comment]
@shin-: ping ;)
