### ISSUE TITLE
execute does not return error code

### ISSUE THREAD

**Issue by spinus** [docker/docker-py#444]
Hi I was using python API and I'm wondering how to get status code from a command?

Some exception with status code could be raised or maybe execute command can return 3 values (2 generators for stdout stderr and status code)?

**Comment by spinus** [comment]
:-( that's very very sad news. Thanks.

**Comment by spinus** [comment]
@dims hey, I found that they implemented this feature recently.
https://github.com/docker/docker/issues/9432
https://github.com/docker/docker/pull/9208
```
git tag --contains 90928eb1140fc0394e2a79d5e9a91dbc0f02484c
v1.4.0
v1.4.1
```
is there any hope to see this in docker-py then?

**Comment by dims** [comment]
@spinus yep, should be possible to add the support. definitely promising.

**Comment by dims** [comment]
Looks like the docker CLI calls /exec/xxxxxx/json to get information about the executed process and there is a "ExitCode" in the response json.

http://paste.openstack.org/show/155353/

**Comment by athoune** [comment]
I use somme ugly monkey patch, for that :

```python
class ExecuteFuture(object):

    def __init__(self, client, command_id, flow):
        self.client = client
        self.command_id = command_id
        self.flow = flow

    def __iter__(self):
        return self.flow

    def wait(self):
        if six.PY3:
            return bytes().join(
                [x for x in self.client._multiplexed_buffer_helper(self.flow)]
            )
        else:
            return str().join(
                [x for x in self.client._multiplexed_buffer_helper(self.flow)]
            )

    def inspect(self):
        url = self.client._url('/exec/{0}/json'.format(self.command_id))
        res = self.client._get(url)
        self.client._raise_for_status(res)
        return res.json()

def execute_return(self, container, cmd, detach=False, stdout=True, stderr=True,
            stream=False, tty=False):
    if utils.compare_version('1.15', self._version) < 0:
        raise errors.APIError('Exec is not supported in API < 1.15')
    if isinstance(container, dict):
        container = container.get('Id')
    if isinstance(cmd, six.string_types):
        cmd = shlex.split(str(cmd))

    data = {
        'Container': container,
        'User': '',
        'Privileged': False,
        'Tty': tty,
        'AttachStdin': False,
        'AttachStdout': stdout,
        'AttachStderr': stderr,
        'Detach': detach,
        'Cmd': cmd
    }

    # create the command
    url = self._url('/containers/{0}/exec'.format(container))
    res = self._post_json(url, data=data)
    self._raise_for_status(res)

    # start the command
    cmd_id = res.json().get('Id')
    res = self._post_json(self._url('/exec/{0}/start'.format(cmd_id)),
                        data=data, stream=stream)
    self._raise_for_status(res)

    return ExecuteFuture(self, cmd_id, res)

```

The answer is iterable, and you can inspect the command. Is it nice enough for a pull request?

**Comment by pixelbombs** [comment]
@athoune I'm not sure using a specific class/object for an alternate version of execute is the best way to go, I think ideally you'd want it as an option in the original execute function or as an alternate execute function.

That being said, I cannot thank you enough for sharing your code with us, it helped me create my own version of execute that returns the exit code instead of the output.

Thank you thank you thank you thank you!

**Comment by pixelbombs** [comment]
For what it's worth, this is my solution to the problem (and a huge shoutout to @athoune for his answer which helped me). Named ```docker_call``` after our favorite ```subprocess``` function, it does virtually the same thing as ```Client.execute``` except it returns the return code instead if ```stream=True``` it will print the output of ```stdout``` and ```stderr``` to the console:
```python
def docker_call(cmd, docker_client, container_name, smart_replace=True, verbose=True):
    if smart_replace:
        cmd = do_smart_replace(cmd)
    if isinstance(cmd, six.string_types):
        cmd = shlex.split(str(cmd))
    data = {
        'Container': container_name,
        'User': '',
        'Privileged':False,
        'Tty': False,
        'AttachStdin': False,
        'AttachStdout': verbose,
        'AttachStderr': verbose,
        'Detach': False,  #Might need this option in the future.
        'Cmd': cmd
    }

    url = docker_client._url('/containers/{0}/exec'.format(container_name))
    res = docker_client._post_json(url, data=data)
    docker_client._raise_for_status(res)
    cmd_id = res.json().get('Id')
    res = docker_client._post_json(docker_client._url('/exec/{0}/start'.format(cmd_id)), data=data, stream=verbose)
    docker_client._raise_for_status(res)
    for i in docker_client._multiplexed_buffer_helper(res):
        logging.debug(i)
    url = docker_client._url('/exec/{0}/json'.format(cmd_id))
    res = docker_client._get(url)
    docker_client._raise_for_status(res)
    return res.json().get('ExitCode')
```

**Comment by spinus** [comment]
@pixelbombs you don't have to break compatibility. You can return Stream object or str like now it is done and add attribute "exit_code". Like http://amoffat.github.io/sh/#exit-codes
