### ISSUE TITLE
volume ro mode don't work

### ISSUE THREAD

**Issue by blackfader** [docker/docker-py#445]
I use docker-py 0.7.0 ,
```
bind_dir={"/home/data": {'bind':'/data','ro':True}}
conn.start(container_id, binds=bind_dir,
                 publish_all_ports=False, links=None, privileged=True,
                 dns=None, dns_search=None, volumes_from=None, network_mode=None)
```
but it is't read only volume in container.

docker inspect 

```
    "Volumes": {
        "/data": "/home/data"
    },
    "VolumesRW": {
        "/data": true
    }
```

is it a bug?

**Comment by shin-** [comment]
Which Docker version are you using?

**Comment by blackfader** [comment]
docker1.4.1

**Comment by shin-** [comment]
Hey, I tried to write some tests to reproduce this issue but couldn't. [Could you run this code for me](https://gist.github.com/shin-/38584274e225922a34dc) and share the output?

Thanks.

**Comment by shin-** [comment]
I'll close this for now, feel free to reopen if you're still encountering the issue and can share the results of the code snippet posted above.
