### ISSUE TITLE
how to detect when build fails

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker-py#449]
This is not an issue, more of a best practice question.

I am using build method and am asking for stream. I've realized that it's not easy to detect when build fails. Should I really parse the response json and look for "error" key in there? Or is there a better way to figure out that the build failed?

**Comment by shin-** [comment]
> Should I really parse the response json and look for "error" key in there?

Personally that is what I would do. I'll keep this open and see if anyone else using docker-py to build regularly has a better answer.

**Comment by leth** [comment]
Here's the docker daemon API docs for 'build': https://docs.docker.com/reference/api/docker_remote_api_v1.16/#build-an-image-from-dockerfile-via-stdin

**Comment by TomasTomecek** [comment]
@leth 
Unfortunately there is no specification, just "example response". Would be nice to have proper specification what one can get from the `/build` API call.
@shin- 
Thanks for info. I guess that we can close this.

**Comment by vitalyisaev2** [comment]
Our Jenkins builds dozens of images every day using the `docker-py`-powered scripts. It would be very convenient to have an exception thrown in `docker.Client.build` when something goes wrong.
