### ISSUE TITLE
Client.build attempts to clean up resources it does not own

### ISSUE THREAD

**Issue by Julian** [docker/docker-py#458]
https://github.com/docker/docker-py/blob/master/docker/client.py#L479-L480 tries to close the context whenever it's present, but it possibly does not own (== did not create) that object, since it could have come from `fileobj` when `custom_context` is `True`.

**Comment by shin-** [comment]
Thank you for the report! Would you like to submit a fix?

**Comment by Julian** [comment]
Possibly, I'm still fighting through a couple of issues to get my actual app to work, but after that I'll have a look.

**Comment by shin-** [comment]
Fix is in docker-py 0.7.2 !

**Comment by Julian** [comment]
Awesome, thanks for the quick turnaround, appreciated!
