### ISSUE TITLE
Docker 1.5 flags

### ISSUE THREAD

**Issue by dreamcat4** [docker/docker-py#471]
--pid
--read-only
--memory-swap

In Docker 1.5 comes a new option of `--pid`, which allows the container to see all the host's PID namespace. Here is mentioned in the 1.5 changelog:

https://github.com/docker/docker/commit/a3934504f905e29187c895a44ddf5ed8ce874414#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR29

And here the PR source code, which has been merged ready for 1.5:

https://github.com/docker/docker/pull/10080/files

If we can please have `--pid` option added to docker-py, so that fig can also be able to set it? Requesting this feature as a user, to run jpetazzo's pipework in fig. Which needs new `--pid` option.

It would be a bonus if can be ready in time before next fig releases, either 1.10 or 1.20.
Many thanks.

**Comment by dreamcat4** [comment]
Renamed to encompass all of the new Docker 1.5 flags (not just --pid).

**Comment by shin-** [comment]
#482 #483 #485 

`--memory-swap` is already supported, the parameter is called `memswap_limit`.
