### ISSUE TITLE
Feature: Create Automated Builds with API

### ISSUE THREAD

**Issue by MrMMorris** [docker/docker-py#472]
This use case just occurred to me: developers are working away on their own branch and they want to put it onto a server. Currently, this would require manually creating a new automated build for that branch, waiting for it to build and then pushing the image to a server. 

It would be nice if you could create new automated builds through the API. Then I could just add a git update hook to run when a new branch is created and create a new build. Either that, or have a setting that says: "Create automated build for all branches" or something.

Thoughts?

**Comment by shin-** [comment]
I think you're on the wrong repository? The best way to suggest improvements to hub.docker.com is to send an e-mail to support@docker.com !

FWIW, a public API for the hub is on our roadmap / in the works.
