### ISSUE TITLE
Ability to declare a container volume only (no host binding)

### ISSUE THREAD

**Issue by xilon-jul** [docker/docker-py#477]
There is no support for container volume only. We are compelled to declare a binding on the host which is not what we always want. Docker provides container only volumes (no host mapping) in the form -v /container/volume/path.

**Comment by shin-** [comment]
You should be able to specify volumes without associated binds. I'm not sure what you mean by "no support"...

**Comment by xilon-jul** [comment]
I'm going to have a look and make a try... maybe I got a bit confused by the documentation. I will close the issue if its already possible. Thank you.

**Comment by xilon-jul** [comment]
Sorry, definitely got confused, this is already working. Closing the issue.

See example with : module version docker-py==0.7.1

from docker import Client
import time

docker = Client(base_url='unix://var/run/docker.sock')
response1 = docker.create_container('debian:wheezy', detach=True, volumes=['/new'],
    command="/bin/bash", name='mycontainer2')
docker.start(response1['Id'])
time.sleep(1)
response = docker.create_container('debian:wheezy',
    command="/bin/bash",stdin_open=True)
docker.start(response['Id'], volumes_from='mycontainer2')
time.sleep(1)
print(docker.logs(response['Id']))
