### ISSUE TITLE
You may want to look at your wiki

### ISSUE THREAD

**Issue by berfarah** [docker/docker-py#481]
[Seems like it has been heavily spammed?](https://github.com/docker/docker-py/wiki)
`https://github.com/docker/docker-py/wiki`

![image](https://cloud.githubusercontent.com/assets/1395723/6110940/218a34fe-b03a-11e4-8cb0-fff76406a041.png)

**Comment by shin-** [comment]
Thanks for the heads up! I'll look into it.

**Comment by shin-** [comment]
Deactivated the wiki since we weren't using it anyway.
