### ISSUE TITLE
Support for Docker stats 

### ISSUE THREAD

**Issue by nicolargo** [docker/docker-py#491]
Hi, 

the version 1.17 of the Docker's API introduces the stats entry point.

It will be nice to have this new feature inside the docker-py lib.

The following method in the client.py file should do the job:

```
    def stats(self, container):
        if utils.compare_version('1.17', self._version) < 0:
            raise errors.InvalidVersion(
                'stats was only introduced in API version 1.17'
            )
        if isinstance(container, dict):
            container = container.get('Id')
        url = self._url("/containers/{0}/stats".format(container))
        return self._result(self._get(url), True)
```

**Comment by shin-** [comment]
Hi, I just merged a PR to integrate this. Please think to do a small search before posting an issue next time :)

**Comment by shin-** [comment]
#484
