### ISSUE TITLE
Document possible exceptions

### ISSUE THREAD

**Issue by tfoote** [docker/docker-py#499]
I was catching APIError until I ran into this issue: https://github.com/docker/docker-py/issues/398

At which time my scripts which were deployed started failing. 

It would be great to have full documentation of which exceptions were possible for each method documented at: https://docker-py.readthedocs.org/en/latest/api/

**Comment by bfirsh** [comment]
This is mostly fixed in #1186 now, but it doesn't include some external exceptions like timeouts. Perhaps we should close this is favour of handling those on a case-by-case basis.
