### ISSUE TITLE
RFE: try to figure out version automatically

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker-py#503]
### Story
I have a docker daemon with version "1.16", my docker-py client has default version "1.17". As soon as I try to do some api calls, it fails with:
```
APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.17, server: 1.16)")
```
Nothing new.

### Solution
I would prefer if docker-py could try to change the version so it would match server's api version, if possible.

### Workflow

1. `d = docker.Client()`
2. `d.images()`
3. Exception is thrown
4. docker-py retries request with different version (the one from exception)
 * if it succeeds, warn user that version should be changed explicitely
 * if it fails, it fails

What do you think? If it makes sense, I can create a PR.

**Comment by shin-** [comment]
I'd like that. You can actually hit the unversioned API endpoint `/version` to fetch the server's version preemptively. We had a start here: #281 but the PR was abandoned by its author.

**Comment by TomasTomecek** [comment]
okay, will try to create a PR (no promises)

**Comment by TomasTomecek** [comment]
@shin- just checked the original PR. Are you fine with detecting api version in Client's constructor? That's gonna be a change in behavior. Right now there are no requests in constructor. I was actually thinking about hooking api discovery before first request (downside: first request will take longer).

**Comment by HackToday** [comment]
I think it is not good to automatic check the versions, the right ways, should the client specify what version of API to talk.

**Comment by shin-** [comment]
@HackToday see discussion on #505, but you will always be able to specify the API version manually no matter what.
