### ISSUE TITLE
Misleading response if docker host has no internet

### ISSUE THREAD

**Issue by hamiltont** [docker/docker-py#512]
I kept getting `docker.errors.APIError: 404 Client Error: Not Found ("No such image: rabbitmq:latest (tag: latest)")` for my line `container = cli.create_container(image='rabbitmq:latest', hostname='my_host')`

The root problem was boot2docker/boot2docker#357 - basically my docker host had no internet access and was unable to pull the image. Would it be feasible to have a better error message in this case?

**Comment by shin-** [comment]
That's the error from the daemon, so you'll need to bring it up to [the main project](https://github.com/docker/docker) instead.  :)
