### ISSUE TITLE
can't get random port mapping

### ISSUE THREAD

**Issue by osallou** [docker/docker-py#513]
I try to reproduce the -P behavior of docker to expose a port from container to a random port on host, but I can't get it work using library. I am using v1.0.0 of lib and v1.5.0 of docker.

I can specify myself the binding and it works:

         self.docker_client.start(container=container.get('Id'),
                                        network_mode='host',
                                        port_bindings={22: 4567}
                                        )

gives me in Hostconfig of inspect command

        "PortBindings": {
            "22/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "4657"
                }
            ]
        },

If I set:

                response = self.docker_client.start(container=container.get('Id'),
                                        network_mode='host',
                                        publish_all_ports=True,
                                        port_bindings={22: None}
                                        )
 or

                response = self.docker_client.start(container=container.get('Id'),
                                        network_mode='host',
                                        publish_all_ports=True
                                        )

I do not get any binding when inspecting  HostConfig:

     "HostConfig":
     .....
       "PortBindings": null,
     ....
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },

How can we reproduce the random port assignment?

Thanks

**Comment by shin-** [comment]
Do you declare the port you want to open in the `create_container` method?

**Comment by osallou** [comment]
Yes, the port is set in the ports section of the create_container:  [22]

**Comment by osallou** [comment]
Here is an example program, where I expose port 22 and publish ports.

    from docker import Client
    docker_client = Client(base_url='tcp://127.0.0.1:2376')
    container = docker_client.create_container(image='centos:latest',
                                                command='/bin/sleep 30',
                                                cpu_shares=1,
                                                mem_limit='1g',
                                                ports=[22])
    print 'ID: '+str(container.get('Id'))
    response = docker_client.start(container=container.get('Id'),
                                        network_mode='host',
                                        publish_all_ports=True
                                        #port_bindings={22: None}
                                        )
   print str(response)

Inspect gives:

In Config:
        "ExposedPorts": {
            "22/tcp": {}
        },
....
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "ContainerIDFile": "",
        "Devices": null,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LxcConf": null,
        "NetworkMode": "host",
        "PidMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": true,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "VolumesFrom": null
    },

    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },

**Comment by shin-** [comment]
Thanks, I'll look into it.

**Comment by shin-** [comment]
Ah, seems like this is an issue with `network_mode=host`. I'm not sure whether this is a bug or expected behavior, but it's definitely a docker engine issue:

```
$ docker run -d -p 22 -P --net=host busybox /bin/sleep 30
a3ed61864c579635e6120aaae09a944a964c011c5218add99412da1da76d74d9
$ docker port a3ed 22
FATA[0000] Error: No public port '22/tcp' published for a3ed 
```

**Comment by shin-** [comment]
Please create an issue in the [docker/docker](https://github.com/docker/docker/issues) tracker instead.

**Comment by istinspring** [comment]
So now it's 2017 and i have exactly same damn problem the TC got in 2015

**Comment by delikat** [comment]
Still seeing this as well.
