### ISSUE TITLE
Is it possible to allow requests 2.5.2+

### ISSUE THREAD

**Issue by tbeadle** [docker/docker-py#515]
I am aware of the issue with boot2docker and the assert_hostname thing, but it appears that the requests library made a change as of version 2.5.2 related to assert_hostname.  See:

http://docs.python-requests.org/en/latest/community/updates/#id2
https://github.com/shazow/urllib3/pull/526

I am not a Mac user and don't use boot2docker, but I was wondering if this change to 'requests' would allow docker-py to start using the newer versions of the library.  It would be nice if my system didn't have to stay with requests 2.4.3 just to support docker-py.

**Comment by TomasTomecek** [comment]
I am using docker-py with latest requests. Just uncommented the `< 2.5.0` line and installed it like that.

**Comment by shin-** [comment]
I'll look into it. 

> It would be nice if my system didn't have to stay with requests 2.4.3 just to support docker-py.

Well to be fair, you could use Docker or virtualenv to isolate your environment :) But I understand the sentiment.

**Comment by TomasTomecek** [comment]
> you could use Docker or virtualenv to isolate your environment

Or user install:
https://packaging.python.org/en/latest/installing.html#installing-to-the-user-site

**Comment by shin-** [comment]
Fixed by 9bed480
