### ISSUE TITLE
Test suite failing on lxc

### ISSUE THREAD

**Issue by LK4D4** [docker/docker-py#521]
Is this possible to detect which execdriver used by daemon and skip some tests?
ping @shin- 
https://jenkins.dockerproject.com/job/Docker%20Master%20(lxc)/label=ubuntu-aufs-lxc/85/console

**Comment by shin-** [comment]
Is that recent? Probably needs a rebase, I fixed it [2 weeks ago](https://github.com/docker/docker-py/pull/509)

**Comment by LK4D4** [comment]
@shin- Wow, thanks so much.
