### ISSUE TITLE
Unexpected interrupt work on some timeout and then kworker uses 100% CPU and wa IO

### ISSUE THREAD

**Issue by rpisarev** [docker/docker-py#528]
Hello all.

We wrote multiprocess program for running some commands. One process works for one docker image and container. On the same time can work 1-12 containers. Containers have size 200MB - 1.1GB. From current image process creates updated image ("yum upgrade -y") and after that process starts container from  updated image with some command. Command it's usually "sh -c ' yum install {package_install} -y && yum info". It works 10-500 sec. It usually works fine. But sometimes were unexpected fails. And then kworker uses 100% CPU and wa IO. After reboot it works again. 

There's some code:

def docker_run_command(docker_image, command):
____docker_client = Client(version="1.16", base_url='unix://var/run/docker.sock')
____start_time = datetime.utcnow()
____cntr = docker_client.create_container(image=docker_image, command=command)
____docker_client.start(container=cntr.get('Id'))
____while docker_client.inspect_container(container=cntr.get('Id'))["State"]["Running"]:  # <=== Here
________sleep(5)
____output = docker_client.attach(container=cntr.get('Id'), stdout=True, stderr=True, logs=True)
____end_time = work_time(start_time)
____docker_client.stop(container=cntr.get('Id'))
____docker_client.remove_container(container=cntr.get('Id'))
____return output, end_time
I expect in inspect_container() to get "safe" value. But it raises in the 6th line 
"Timeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)" and after that kworker uses 100% CPU and wa IO.
Mayby I use API wrong? 

rpm -qa|grep docker
python-docker-py-1.0.0-1.el7.x86_64
docker-1.4.1-5.el7.centos.x86_64

rpm -qa|grep requests
python-requests-2.3.0-2.el7.centos.noarch

**Comment by shin-** [comment]
You're overloading your machine with more containers than it can handle. Docker doesn't get enough CPU time to respond in the 60 seconds timeout. You should either:
* start less containers
* use `mem_limit` in `create_container` to limit the amount of resources each container will occupy on your machine

Since this is not a docker-py issue, I will now close this ticket. If you need additional help, please refer to the mailing list or #docker IRC channel.
