### ISSUE TITLE
containers API with trunc parameter

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#542]
No matter how I set trunc, output is always no-trunc.

    containers(all=True, trunc=False)
    containers(all=True, trunc=True)

Output:

    {u'Status': u'Up 30 minutes', u'Created': 1428546886, u'Image': u'sameersbn/redis:latest', u'Ports': [{u'Type': u'tcp', u'PrivatePort': 6379}], u'Command': u'/start', u'Names': [u'/aaa_gitlab_1/aaa_redis_1', u'/aaa_gitlab_1/redis_1', u'/aaa_gitlab_1/redisio', u'/aaa_redis_1'], u'Id': u'3b8fcc1081b950f27d53516a59257e6e87841a73590913f7b0ad14b5021320ad'}

**Comment by TomasTomecek** [comment]
This is really interesting. Looking at spec of the remote API, there is nothing related to truncation: https://docs.docker.com/reference/api/docker_remote_api_v1.17/#list-containers
I guess it would be worth checking how `docker ps` works.

**Comment by shin-** [comment]
It may have been deprecated in recent versions of the API without me noticing.
