### ISSUE TITLE
remove_container raise cannot concatenate 'str' and 'NoneType' objects (HTTP 500)

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker-py#545]
if call remove_container with container={} will got error:
 cannot concatenate 'str' and 'NoneType' objects (HTTP 500)
should we check the container is None?

**Comment by TomasTomecek** [comment]
If you check the code, none of the methods check `image` nor `container`. To me, it would make sense to add such checks. At least for `None`, as you pointed out.

**Comment by shin-** [comment]
Thank you for the report! Closing as a duplicate of #517
