### ISSUE TITLE
docker-py cannot bind local files into a container?

### ISSUE THREAD

**Issue by yousq** [docker/docker-py#546]
hi,all!
    I ofen bind host files into containers by using "-v /path/to/host/file:/container/file:ro", when I using command line client. 
    But now, I need to use docker-py to manage my containers. And I also need to do the same work:bind some host files into containers. And my code is like this (for example)

-----------
    ......
    "volumes":["/etc/localtime"],
    ......
    "binds":{
            "/etc/localtime":{
                     "bind":"/etc/localtime",
                     "ro":true
            }
    },
-----------
   unfortunately, problem emerged:
        APIError: 500 Server Error: Internal Server Error (
       "Cannot start container 1c1......d7051: setup mount namespace mounting
        /var/lib/docker/vfs/dir/575....9f73 into 
        /var/lib/docker/devicemapper/mnt/1c1f7f.....1edd7051/rootfs/etc/localtime not a directory")

what is the solution?

**Comment by jameskyle** [comment]
Getting the same error here. binding /etc/localtime is very common.

**Comment by mkuzmin** [comment]
I've met the same issue using Ansible: https://github.com/ansible/ansible-modules-core/issues/1158

**Comment by jameskyle** [comment]
Yeah, I was using ansible as well. But when I ran into the error I dug into ansibles module source and replicated it using docker-py directly.

**Comment by shin-** [comment]
Please provide the following information:
* OS used
* docker version
* docker-py version

**Comment by mkuzmin** [comment]
- Ubuntu 1.04.2
- Docker version 1.6.0, build 4749651
- docker-py 1.1.0

**Comment by schmunk42** [comment]
@mkuzmin Same here, I updated my vagrant base box to 14.04.2 which was released just a day ago.

**Comment by shin-** [comment]
Thanks, I'll look into it for 1.2

**Comment by shin-** [comment]
Guys, I'm having trouble reproducing this, can you try and run the following code and report back with the results? https://gist.github.com/shin-/94bc282e8a41f0d09786

Thanks!

**Comment by schmunk42** [comment]
@shin- How do I run the test case? Would I need to get docker-py source on the broken system?

**Comment by shin-** [comment]
No, just running the file in an environment where docker-py is installed
should do the trick.

On Thu, Apr 23, 2015 at 1:04 AM, Tobias Munk <notifications@github.com>
wrote:

> @shin- <https://github.com/shin-> How do I run the test case? Would I
> need to get docker-py source on the broken system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker-py/issues/546#issuecomment-95484155>.
>



-- 
Joffrey F, Software Engineer @docker
docker-py maintainer

**Comment by mkuzmin** [comment]
```
.
----------------------------------------------------------------------
Ran 1 test in 0.133s

OK
```
But the testcase seems incomplete. The issue happens only when the mounted file exist in an image already, and needs to be overwritten by a copy from a host.

**Comment by shin-** [comment]
I'll give that a shot in the morning, but looking at the code of both projects there's no reason it would work differently from using the Docker CLI.

**Comment by shin-** [comment]
I think I've found the issue: can you try specifying the binds in the `create_container` call, like such
```python
c.create_container(
    img, cmd, volumes=volumes, 
    host_config=docker.utils.create_host_config(binds=binds)
)
```

And see if that works?

**Comment by shin-** [comment]
(and then call `start` without specifying `binds`)

**Comment by mkuzmin** [comment]
I've got
```
E
======================================================================
ERROR: runTest (__main__.TestStartContainerWithFileBind)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_file_bind.py", line 62, in runTest
    img, cmd, volumes=volumes,
NameError: global name 'img' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
```

**Comment by shin-** [comment]
Sorry, I meant in your own code, replacing `img` and `cmd` by the appropriate image and command that need to be run.

**Comment by mkuzmin** [comment]
I'm just Ansible user, and don't write anything by myself.
Here is the code: https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L1191
But I don't have enough Python knowledge to perform the change you requested. sorry.

**Comment by shin-** [comment]
I've reported the issue upstream (https://github.com/docker/docker/issues/12759), but Ansible will probably need to be updated to provide `HostConfig` params in `create_container` instead of `start`

**Comment by shin-** [comment]
Closing, setting host config in `start` is deprecated starting with 1.2.3

**Comment by Brett55** [comment]
if host_config was deprecated in 1.2.3, where do I pass in binds now?
