### ISSUE TITLE
Beta support for docker machine

### ISSUE THREAD

**Issue by hamiltont** [docker/docker-py#556]
It would be great to have a module `docker.machine` already integrated into this project once [docker-machine](https://github.com/docker/machine) hits 1.0 - machine is turning into a really fantastic project and their dev team is quite active. If you ask around on Freenode (#docker-machine) and look at their [Roadmap](https://github.com/docker/machine/blob/master/ROADMAP.md) you'll find that their plans include a client/server setup with a REST api that external libraries can use to interact with `docker-machine`, very similar to docker itself. That will be a while coming, as they are currently working towards [0.3.0](https://github.com/docker/machine/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.3.0) milestone which will not address this client/server+REST setup. 

I have written some initial code to use `docker-machine` from Python. It's not optimal - it wraps the binary and uses subprocess. However, it works, and it allows me to use docker-machine from setups like Heroku by automatically downloading the docker-machine binary, creating a machine based off my environment variables, and connecting docker-py's client to the created machine. I'm well aware it's not optimal to wrap the binary (or to download random binaries from the internet....), but the code does work in a beta capacity. 

Question is - would docker-py be interested in a PR that contains my code to start test-driving beta support for docker-machine? My thought is that this could trigger other PRs to develop a more full-featured API for machine, with the internal codebase being switched to the server/client REST interface once it's available. For example, their current codebase is heavily centered around concept of Drivers and the Engine, so this would allow docker-py to start accepting PRs that have classes which represent these constructs. As their API becomes more finalized over time, these classes could also solidify 

[Here](https://github.com/hamiltont/WebJuice/blob/master/webjuice/utils.py#L52) is code to automate downloading docker-machine. 
[Here](https://github.com/hamiltont/WebJuice/blob/master/webjuice/utils.py#L102) is code to read environment variables and create a machine based off those variables. Pretty simple - any environment variable prefixed with `DM_` will be converted into an argument flag that's passed to `docker-machine create` e.g. `DM_DRIVER=digitalocean` translates into `docker-machine create --driver digitalocean`
[Here](https://github.com/hamiltont/WebJuice/blob/master/webjuice/utils.py#L173) is code that sets up `docker.Client` using the standard `kwargs_from_env`

**Comment by frewsxcv** [comment]
Relevant library: https://github.com/jgrowl/docker-machine-py/tree/master/docker_machine

**Comment by bfirsh** [comment]
This probably makes sense as a separate library - docker-py is just for the Engine API.
