### ISSUE TITLE
Incorrect file permissions and owner

### ISSUE THREAD

**Issue by filip91** [docker/docker-py#558]
Hi,

I write application for testing programs written in C inside of Docker container. It's important, that there are no root privileges inside the container, so I mapped folder with all required source codes from host under user "tester" created in Dockerfile.

My Dockerfile contains these steps:
```
FROM debian:latest

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
    gcc cppcheck check valgrind libc6-dev \
    libncurses5 libncurses5-dev make unzip ctags cloc

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/tester/data

RUN useradd -d /tmp/tester/data -c 'docker default user'  tester \
  && chown -R tester:tester /tmp \
  && find /tmp -type d -exec chmod 755 {} \; \
  && find /tmp -type f -exec chmod 644 {} \;

USER tester
```

Container is started as daemon with docker-py like:
```python
container = client.create_container(image='my-image:latest', command='/bin/bash',
                                    detach=True, stdin_open=True, tty=True,
                                    working_dir='/tmp/tester/data', user='tester',
                                    volumes=['/tmp/tester/data', '/tmp'])

client.start(container, read_only=True, binds={
    "/tmp/folder-with-files": {
        'bind': "/tmp/tester/data,
        'ro': False
    }
})
```

I send commands via docker exec while container is running in background. Problem is, that I can't work with files inside the container. I run "whoami" and it shows the user "tester", but when I run "ls -lha .", I got "ls: cannot open directory .: Permission denied". However I can show content of every other location in container like "/", "/tmp" and also "/tmp/tester", but "/tmp/tester/data" isn't working and fail with permission denied. Strange is, that owner of this directory isn't tester, but someone with uid 1003.

```
$ pwd
/tmp/tester
$ whoami
tester
$ ls -lha
total 12K
drwxr-xr-x 3 tester tester 4.0K Apr 23 10:54 .
drwxr-xr-x 3 tester tester 4.0K Apr 23 11:32 ..
drwx------ 2   1003   1004 4.0K Apr 23 11:32 data
$ ls -lha data
ls: cannot open directory data: Permission denied
```

I have no idea what is wrong and why it isn't working. Please, could someone figure out the cause of this problem?

Operating system is Ubuntu 14.04 LTS with docker 1.6.0 and docker-py in version 1.1.0.

**Comment by shin-** [comment]
Can you try to run the equivalent commands with the docker CLI and see if the problem happens there too?

**Comment by filip91** [comment]
Equivalent commands are
```
$ docker run -d -i -t -w /tmp/tester/data -u tester -v /tmp -v /tmp/folder-with-files:/tmp/tester/data:rw --read-only my-image:latest /bin/bash
$ docker exec -i <some_id> pwd
/tmp/tester/data
$ docker exec -i <some_id> whoami
tester
$ docker exec -i <some_id> ls -lha
total 8.0K
drwxrwxr-x 2 tester tester 4.0K Apr 24 07:26 .
drwxr-xr-x 3 tester tester 4.0K Apr 24 07:27 ..
-rw-rw-r-- 1 tester tester    0 Apr 24 07:26 Dockerfile
```
Because docker-py can't send stdin to running container, I have to run all ```exec``` commands via ```subprocess.Popen()```, where stdin is supported. 

As you see, via CLI is ```ls``` working as expected.

**Comment by filip91** [comment]
I figured out, that uid 1003 and gid 1004 belong to user in host system, who run whole application. Why docker didn't set ownership and permissions for user "tester" defined in Dockerfile, but via CLI is ownership as expected?
