### ISSUE TITLE
Inconsistent of docker-py and docker remote API

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#560]
Check the remote API document:
  http://docs.docker.com/reference/api/docker_remote_api_v1.18/#search-images

Response of remote API is 
      
       "is_official": false,
       "is_automated": false,

But docker-py's response is

       "is_official": false,
       "is_trusted": false,

**Comment by aidanhs** [comment]
Never trust the docker api docs until you've actually tested against the daemon. They're generally about right, but sometimes vary between "a bit off" to "completely inaccurate".

Case in point, docs for 1.17 version http://docs.docker.com/reference/api/docker_remote_api_v1.17/#search-images (same as 1.18).
But running against daemon:
```
~ $ curl http://docker03:2375/v1.17/images/search?term=sshd
[{"description":"Dockerized SSH service, built on top of official Ubuntu images.","is_official":false,"is_trusted":true,"name":"rastasheep/ubuntu-sshd","star_count":2}
,{"description":"Fedora docker file for ssh service which managed by supervisor","is_official":false,"is_trusted":true,"name":"kumarpraveen/fedora-sshd","star_count":1}
,{"description":"","is_official":false,"is_trusted":true,"name":"iliyan/docker-nginx-sshd","star_count":1}
,{"description":"","is_official":false,"is_trusted":true,"name":"moul/sshd","star_count":1}
[...]
```

You might want to raise an issue against docker itself :)

**Comment by shin-** [comment]
Thanks @aidanhs ! 

As a general rule, docker-py almost never tampers with the way response data is formatted. I'll close this issue, but feel free to raise the issue on [the docker repo](https://github.com/docker/docker/issues)

**Comment by shin-** [comment]
https://github.com/docker/docker/issues/12748
