### ISSUE TITLE
Get containers with None Names

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#561]
I tried to create and destroy with two containers very often.

The response from **containers()** API will return *None* value of key *Names* sometimes.

    {'Status': 'Dead', 'Created': 1429869422, 'Image': 'busybox:latest', 
    'Labels': {}, 'Ports': [], 'Command': '/bin/sh', 
    'Names': None, 'Id': u'51bce5b06abf3e27cf1f6526105cac1f5022b828d8aaf3cc089044115f3a4adb'}

**Comment by shin-** [comment]
Looks like a docker engine issue. Feel free to report it on docker/docker.

**Comment by rgbkrk** [comment]
I've seen this several times too. Should Names be an empty list in that case?

**Comment by shin-** [comment]
The CLI is sending "null" which is automatically translated to None. I don't think docker-py should tamper with that.

**Comment by blueyed** [comment]
Reported/forwarded it at: https://github.com/docker/docker/issues/16706.

**Comment by blueyed** [comment]
@linlinlinlin @shin- 
I would appreciate your help/feedback on https://github.com/docker/docker/issues/16706 (Docker version etc), in case you've investigated into this issue before.

**Comment by blueyed** [comment]
Fixed in docker: https://github.com/docker/docker/pull/16736
Should be in 1.9 and possibly 1.8.3.
