### ISSUE TITLE
Add support for env-file

### ISSUE THREAD

**Issue by vpetersson** [docker/docker-py#565]
Sorry if I've overlooked anything here, but I was trying to add support for env-file in Ansible ([issue](https://github.com/ansible/ansible-modules-core/issues/792)). However, upon further investigation, it appears as this is blocked by the lack of this support in docker-py. 

My assumption is purely based on the fact that I could not find any references to this and that it isn't mentioned [here](https://github.com/docker/docker-py/blob/master/docker/client.py#L934-L939).

**Comment by shin-** [comment]
Unsurprisingly, `--env-file` is a client-side feature of the docker CLI, so it's debatable whether this should be included in that project or not. I'll explore the possibility.

**Comment by vpetersson** [comment]
Ah, good point. Yeah that kinda makes sense.

**Comment by vpetersson** [comment]
@shin- Let me know what you think.

**Comment by vpetersson** [comment]
@shin- When will the next version be posted to PyPi?
