### ISSUE TITLE
We are using docker-py in the atomic command.

### ISSUE THREAD

**Issue by rhatdan** [docker/docker-py#567]
We have received a bug report that atomic does not properly support docker listening on TCP, while I don't recommend people running docker in this way, do to the security problems, docker-py should probably support it. More info in the atomic issue below.

https://github.com/projectatomic/atomic/issues/41

**Comment by rhatdan** [comment]
@roldancer Opened issue here with docker-py

**Comment by shin-** [comment]
I commented on https://github.com/projectatomic/atomic/issues/41 by the way. Need more info before I can look into this.

**Comment by jasinner** [comment]
Can we revisit this request? We can now enable TLS for encryption and auth on Docker TCP Socket, which makes it secure I believe. However atomic run doesn't work with Docker TCP Socket. For the details of how to configure the client see:
https://docs.docker.com/engine/security/https/
specifically:
export DOCKER_HOST=tcp://$HOST:2376 DOCKER_TLS_VERIFY=1

**Comment by shin-** [comment]
#999 ?

**Comment by rhatdan** [comment]
Looks good to me. So the next update to docker-py should fix this issue.
