### ISSUE TITLE
LogConfig attributes are lost if links are specified to client.start(container)

### ISSUE THREAD

**Issue by ssanderson** [docker/docker-py#578]
```
Python 3.4.0 (default, Apr 11 2014, 13:05:11)

In [1]: import docker

In [2]: docker.__version__
Out[2]: '1.2.1'

In [3]: !docker --version
Docker version 1.6.0, build 4749651

In [36]:  c = client.create_container('ubuntu', command='/bin/bash -c "echo foo"', host_config={'LogConfig': {'Type': 'syslog', 'Config': {}}})

In [37]: client.start(c)

In [38]: client.inspect_container(c)['HostConfig']['LogConfig']
Out[38]: {'Config': {}, 'Type': 'syslog'}

In [41]:  c = client.create_container('ubuntu', command='/bin/bash -c "echo foo"', host_config={'LogConfig': {'Type': 'syslog', 'Config': {}}})

In [42]: client.start(c, links=[('pgbouncer', 'pgbouncer')])

In [43]: client.inspect_container(c)['HostConfig']['LogConfig']
Out[43]: {'Config': None, 'Type': 'json-file'}
```

The analogous command line invocation: `docker run -d --link pgbouncer:pgbouncer --log-driver syslog`  seems to work fine.

**Comment by shin-** [comment]
[Do not](https://github.com/ansible/ansible-modules-core/pull/1208#issuecomment-97250044) [pass host config](https://github.com/docker/docker/issues/10695) [to `start()`](https://github.com/docker/docker/issues/12759) if you can help it.

**Comment by shin-** [comment]
Closing by #593

**Comment by sandkumaCode** [comment]
I have been trying to add syslog config to create_container but have not been able to.
I am using 
dct = {'type': LogConfig.types.SYSLOG, 'config': {}}
 host_config_p=self._docker_client.create_host_config(log_config=dct)
 options.update(host_config_p)

 result = yield self._docker_client.create_container(**options)

but its not affecting still the default json remains

**Comment by shin-** [comment]
```python
import docker
from docker.utils.types import LogConfig

c = docker.Client()
hc = c.create_host_config(log_config={'type': LogConfig.types.SYSLOG, 'config': {}})
ctnr = c.create_container(image='busybox', command='ls -la', host_config=hc)
```

Also, the syntax if you want to provide keyword arguments is `**options` (double star), `*options` being for positional arguments. In that case:

```python
import docker
from docker.utils.types import LogConfig

options = {
  'image': 'busybox',
 'command': 'ls -la'
}

c = docker.Client()
options['host_config'] = c.create_host_config(log_config={'type': LogConfig.types.SYSLOG, 'config': {}})
ctnr = c.create_container(**options)
```

**Comment by sandkumaCode** [comment]
Thanks a lot for the quick response i was having issues with converting host_config to json...
as json.dumps crashes any way to have a json serializable host_config?

**Comment by sandkumaCode** [comment]
>python
Python 2.7.7 (default, Jun  1 2014, 14:17:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> from docker import Client
>>> from docker import Client
>>> cli = Client()
>>> from docker.utils.types import LogConfig
>>> cli.create_host_config(log_config={'type': LogConfig.types.SYSLOG, 'config': {}})
{'LogConfig': {'Type': 'syslog', 'Config': {}}}
>>> import json
>>> hs = cli.create_host_config(log_config={'type': LogConfig.types.SYSLOG, 'config': {}})
>>> json.dumps(hs)
'{"LogConfig": {"Type": "syslog", "Config": {}}}'
>>>
when i do this in rep it works fne but in code running on trusty this json.dumps is giving me error that hs is not JSON Serializable

**Comment by sandkumaCode** [comment]
the above issue was happening in defered code so i put the hos_config this way
options['host_config'] = {"LogConfig": {"Type": "syslog", "Config": {}}}
which before create_container was:
'host_config': {'LogConfig': {'Config': {}, 'Type': 'syslog'}}
when the containers were started and did docker logs for this container i still see json prints 
another container that i start with the docker run comand with --log-driver configured properly logs to syslog and i when i do a docker logs that container id i just see that its configured syslog

**Comment by sandkumaCode** [comment]
One observation if we have options in create_container and if we follow up with start that has options too is the create_container option overridden?
if i put configs in create_container and then do a start with just container id it works fine
when i put options in start that when i am getting issues....
