### ISSUE TITLE
 ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)

### ISSUE THREAD

**Issue by allan-simon** [docker/docker-py#580]
I'm using docker.py through the mean of the docker plugin for ansible
and when i try to build a new image I go 

msg: ConnectionError(ProtocolError('Connection aborted.', error(111, 'Connection refused')),)

I'm running the command as root , and I've already tried the solution here http://stackoverflow.com/questions/29703274/python-docker-py-connection-refused  but it doesn't work 

also when running directly the  `docker build` command from my shell, it works without any problem.

**Comment by shin-** [comment]
Gonna need: OS, docker-py version, docker version, value of your `DOCKER_HOST` environment (if any). Also you should report that on the ansible plugin repo as well.

**Comment by allan-simon** [comment]
* OS:  ubuntu 12.04 
 * docker 1.4 
 * docker-py the latest installed by pip  (1.2.1 )
 * no env variable for DOCKER_HOST

**Comment by allan-simon** [comment]
my bad, my ansible tasks had installed package "docker"  which is totally not related to  lxc-docker and which was causing conflict of binary
