### ISSUE TITLE
inspect_image exception is missing detail compared to command line docker inspect

### ISSUE THREAD

**Issue by joshunger** [docker/docker-py#583]
Remove yourself from the docker group.

Then, try to execute self.client.inspect_image().

EXPECTING: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?[]

ACTUAL: ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

Would it be possible to add this additional information to the exception?  It is very helpful when debugging this error.

Thanks.

**Comment by TomasTomecek** [comment]
I would be in favor of something like this:
```
Can't access docker daemon: 127.0.0.1:12345
```
or
```
Can't access docker daemon: /var/run/docker.sock
```
For me, endpoint access and TLS mismatch are two different things.

**Comment by shin-** [comment]
Thank you for reporting this.
Seems like a corner case... I think the information provided right now is sufficient. And I don't want to assume anything about the underlying system (keep in mind people are going to use different ways to contact the API (HTTP(S), TCP, UNIX...), a `ConnectionError` can mean many things. 

You've got the perfect example of that by the way, with the CLI suggesting to use TLS when this has nothing to do with your issue.

I'll close the issue but feel free to add to it if you think there's more to be discussed.
