### ISSUE TITLE
events() generator is generating str, not dict

### ISSUE THREAD

**Issue by bo0ts** [docker/docker-py#585]
I was baffled by the following (on Python 2.7):

    for ev in client.events():
        assert isinstance(ev, str), 'ev is not a string' # Does not trigger
        assert isinstance(ev, dict), 'ev is not a dict' # Does trigger

Is that as intended or am I right in assuming that this should actually be a `dict`?

**Comment by shin-** [comment]
```
for ev in client.events(decode=True):
    assert isinstance(ev, dict)
```

Needs to be documented :)
