### ISSUE TITLE
Can't set --volumes-from when creating containers

### ISSUE THREAD

**Issue by windworship** [docker/docker-py#596]
Guys, I got an Error when I try to set --volumes-from in create_container:

Error:'volumes_from' parameter has no effect on create_container(). It has been moved to start()

However, setting volumes-from in start() rather than create_container() means swarm can't **automatically generate affinities**. So we actually create the container on some node without the volumes-from container, which results in an Error:

 406 Client Error: Not Acceptable ("Cannot start container : container <> not found, impossible to mount its volumes")

I know this could be fixed by adding affinity in create_container(), but I don't see the point why we can't set --volumes-from in create_container, especially after I found --volumes-from is acceptable on creating containers on Docker remote API.

**Comment by shin-** [comment]
Use [HostConfig](http://docker-py.readthedocs.org/en/1.2.2/hostconfig/)
