### ISSUE TITLE
Accept DOCKER_CERT_PATH environment variable

### ISSUE THREAD

**Issue by rgbkrk** [docker/docker-py#601]
As an alternative to having to build the tls config, accept the DOCKER_CERT_PATH variable (as used by Docker and swarm).

**Comment by shin-** [comment]
Use `docker.utils.kwargs_from_env`. [Docs here](http://docker-py.readthedocs.org/en/latest/boot2docker/). As a design point, I think it's better that nothing be hidden from sight of the user (i.e. only use environment values if it's done explicitly).

**Comment by rgbkrk** [comment]
Thank you, seeing that now. I'm most interested in getting this to work with swarm, using the same default setup so the env setup is the same across tools.
