### ISSUE TITLE
Run Flask app using docker-py in backgound

### ISSUE THREAD

**Issue by aabdulwahed** [docker/docker-py#616]
I have an issue to create containers running python flask app, here is what I did to run my image "my Dockerfile" 

```
     FROM ubuntu:14.04

     MAINTAINER Ahmed Abdullah <ahmedaabdulwahed@gmail.com>

     # install pre-requisites packages

     RUN apt-get update && apt-get install -y apache2 git python-pip curl \

     python python-dev python-distribute tar git curl nano wget dialog \

     net-tools build-essential

     # add pot services to container

     ADD /pots /usr/pots

     WORKDIR /usr/pots

     RUN pip install .

     EXPOSE 80

     CMD python server.py
```

I built the image using that docker file, and when I created a new container using docker command line the container and flask app started successfully but, when i used docker-py APIs , the container status was "Exited (0)" and the service status is down, so is there any idea how can I run a flask app as a daemon using docker-py

**Comment by shin-** [comment]
I can't help if I don't know what code you're running.

**Comment by aabdulwahed** [comment]
Kindly check out the code I am running:

        $ git clone https://github.com/aabdulwahed/cloudpots.git

        $ sudo pip install .

        $ cd agent/services

        $ sudo python manage.py


Also, you'll find the code of calling docker-py in <code>cloudpots/agent/client/container/</code> 
, pots dir where I am adding to container using dockerfile in <code>cloudpots/pots/</code> and my docker file in <code>cloudpots/docs/Dockerfile</code>

     # creating my potservice image
    
     $ sudo docker build -t potservice .
    
    # starting new container 

     $ sudo docker run -p 4040:80 -it potservice

**Comment by shin-** [comment]
Sorry, I didn't express myself properly. 

Please provide me with a code snippet that is focused to the problem you're having (in that case, the code that creates and starts a container). I don't have the time or patience to go through your whole project to figure out how you're using docker-py.

**Comment by aabdulwahed** [comment]
Here is a sample of code to create and start containers **container.py**

    import simplejson as json
	from docker import Client

	_DOCKER_BASEURL_= 'unix://var/run/docker.sock'
	_PORTS_ = [2200]

	class ContainerEngine():

		def __init__(self):
		        self.ports = [22]

		def new_client(self,base_url=_DOCKER_BASEURL_):
		        return Client(base_url)

		def create_container(self,client,
		                        image_id,
		                        command=None,
		                        mem_limit=None,
		                        cpu_shares=None,
		                        private_ports = []):

		        """Initiate and Create Container"""
		        return client.create_container(image_id,
		                                        command,
		                                        detach=True,
		                                        ports = private_ports ,
		                                        mem_limit=mem_limit,
		                                        cpu_shares=cpu_shares)

		def start_container(self,client, container_id, container_endpoints={}):
		        """Start Container"""
		        return client.start(container_id, port_bindings = container_endpoints)

	c = ContainerEngine()

	client = c.new_client()

	id = c.create_container(client, 'potservice', cpu_shares='1')

	c.start_container(client, id, container_endpoints={'80':'1616'})


and flask app **pot.py** and **server.py** that I created an Image for it.

       $ mkdir pots ; cd pots
       $ vi pot.py

	import os, sys, requests, json
	from flask import request
	from flask import Flask, session, render_template
	import subprocess

	pot = Flask(__name__,  static_url_path = "/imgs", static_folder = "%s/imgs"%(os.path.dirname(os.path.abspath(__file__))))



	# generate random key for flask session
	pot.secret_key = os.urandom(24)



	# execute command line
	def run(command):
		pipe = subprocess.PIPE
		p = subprocess.Popen(command,stdout=pipe,stderr=pipe,shell=True)
		return p.stdout.read()+"\n"+p.stderr.read()

	# main page
	@pot.route('/')
	def index():
		return render_template('<h1>Hello World<h2>')


	@pot.route('/exec')
	def execute():
		command = "bash /pots/bootstrap.sh"
		try:
		        if 'cmd' in request.args:
		                command = request.args['cmd']
		        return json.dumps({'command': run(command)})
		except:
		        return json.dumps({'ERROR':'expected command line'})


	if __name__ == '__main__':
		pot.run()


and **server.py** 

    from pot import pot
	import cherrypy
	from cherrypy.process.plugins import Daemonizer
	# add pot service in background
	Daemonizer(cherrypy.engine).subscribe()



	if __name__ == '__main__':

	    # Mount the application
	    cherrypy.tree.graft(pot, "/")

	    cherrypy.server.unsubscribe()

	    # Instantiate a new server object
	    server = cherrypy._cpserver.Server()

	    server.socket_host = "0.0.0.0"
	    server.socket_port = 80
	    server.thread_pool = 30

	    server.subscribe()


	    cherrypy.engine.start()
	    cherrypy.engine.block()


**Dockerfile**

     FROM ubuntu:14.04

     MAINTAINER Ahmed Abdullah <ahmedaabdulwahed@gmail.com>

     # install pre-requisites packages

     RUN apt-get update && apt-get install -y apache2 git python-pip curl \

     python python-dev python-distribute tar git curl nano wget dialog \

     net-tools build-essential

     # add pot services to container

     ADD /pots /usr/pots

     WORKDIR /usr/pots

     RUN pip install .

     EXPOSE 80

     CMD python server.py


**setup.py**

from setuptools import setup

	setup(
		name='cpot-manager',
		version='0.1',
		description='CLOUDPOTS provides creating container based clusters',
		author='Ahmed Abdullah', author_email='info@cloudpots.com',
		url='http://cloudpots.com/',
		install_requires=['flask', 'requests','configobj', 'cherrypy']
	)

**Comment by bfirsh** [comment]
@aabdulwahed Are you still having this issue? If so, feel free to re-open the issue and we can take a look. :)

**Comment by aabdulwahed** [comment]
@bfirsh No thanks for support!
