### ISSUE TITLE
Are ``docker.Client()``'s methods thread safe?

### ISSUE THREAD

**Issue by delcypher** [docker/docker-py#619]
My current use case for ``docker-py`` requires that multiple threads communicate with Docker. Right now I'm creating an instance of ``docker.Client()`` for each thread which leads to slow start up time. I could speed it up by having all threads share a single ``docker.Client()`` instance but I can only do this if its methods are thread safe. Are they?

It doesn't seem to be documented.

**Comment by TomasTomecek** [comment]
Well, since docker-py is a thin docker engine client, I don't see a problem how the methods could be thread unsafe. The only thing from my PoV could be the `HTTP` transport: if `requests`/`urllib3` connection is thread safe, I assume that docker-py is too.

**Comment by delcypher** [comment]
@TomasTomecek ``requests`` and ``urllib3`` claim to be thread safe. At a glance it looks like no additional state is maintained between method calls (although I could be wrong) in ``Client`` but I'm not very familiar with the code so I could be wrong.

**Comment by TomasTomecek** [comment]
Not sure what you are trying to achieve but I guess that you can try the thread safety within your dev environment.

**Comment by jhale** [comment]
Old issue, but I had no problems using a sharing a Docker client factory between threads.

**Comment by Dlougach** [comment]
Actually, I just found out the hard way that requests.Session object (which the client inherits from) is [not thread-safe](https://github.com/psf/requests/issues/2766). 

If you get random `BadStatusLine` or `ChunkEdencodingError` exceptions while streaming logs in a separate thread, this is probably the reason.
