### ISSUE TITLE
Build() should default to `pull=False`

### ISSUE THREAD

**Issue by glogiotatidis** [docker/docker-py#622]
The default behavior of docker cli when building does not pull by default. You must provide the `--pull` flag. I suggest that `docker-py` follows the same rule and default to `pull=False`

https://github.com/docker/docker-py/blob/master/docker/client.py#L309

**Comment by TomasTomecek** [comment]
+1

**Comment by glogiotatidis** [comment]
btw `pull` parameter doesn't do anything with current release version of docker due to https://github.com/docker/compose/pull/1494

**Comment by shin-** [comment]
Fixed by #624
