### ISSUE TITLE
memory_limit and memswap_limit support in host_config

### ISSUE THREAD

**Issue by nusnewob** [docker/docker-py#623]
Unable to set memory_limit and memswap_limit in host_config, both are missing from supported parameters in utils.py.

Containers created using python client,

	[{
	        "Config":  {
	        ...
	        "Memory": 2147483648,
	        "MemorySwap": -1,
	       ...
	       "HostConfig": {
	        ...
	        "Memory": 0,
	        "MemorySwap": 0,
	        ...

Containers created using commandline with --memory=2048MB --memory_swap=-1

	[{
	        "Config":  {
	        ...
	        "Memory": 2147483648,
	        "MemorySwap": -1,
	       ...
	       "HostConfig": {
	        ...
	        "Memory": 2147483648,
	        "MemorySwap": -1,
	        ...

As results, limits are only configured in Config and not Host_Config and therefore make no effect.

**Comment by ssanderson** [comment]
@shin- I think this is fallout from https://github.com/docker/docker/pull/10298.  docker-py currently accepts mem_limit as a direct argument to `create_container`, but it looks like it should be moved and/or forwarded to create_host_config?

**Comment by ssanderson** [comment]
(I'm seeing this issue as well by the way)

**Comment by shin-** [comment]
It's a 1.7 change. I'll take care of it today.

**Comment by shin-** [comment]
https://github.com/docker/docker/issues/13663
