### ISSUE TITLE
Attaching and streaming logs from containers started with tty=true does not work properly

### ISSUE THREAD

**Issue by dano** [docker/docker-py#630]
Currently, when docker-py attaches to a container, it will always try to read the output stream as if it was multiplexed, unless the API version is below 1.6:
```python
        # Stream multi-plexing was only introduced in API v1.6. Anything before
        # that needs old-style streaming.
         
        if utils.compare_version('1.6', self._version) < 0:
            def stream_result():
                self._raise_for_status(response)
                for line in response.iter_lines(chunk_size=1,
                                                decode_unicode=True):
                    # filter out keep-alive new lines
                    if line:
                        yield line

            return stream_result() if stream else \
                self._result(response, binary=True)

        sep = bytes() if six.PY3 else str()

        if stream:
            return self._multiplexed_response_stream_helper(response)
        else:
            return sep.join(
                [x for x in self._multiplexed_buffer_helper(response)]
            )
```
`Client.logs` similarly assumes a multiplexed response stream after calling the `container/<id>/logs` API, unless the API is below version 1.11, in which cases it just calls `attach` with the `logs=True` keyword argument.

However, the docker API docs note that if a container is opened with the tty=true option, [you just get the a raw stream, not a multiplexed one](http://docs.docker.com/reference/api/docker_remote_api_v1.18/#attach-to-a-container):

>Stream details:
>
>When using the TTY setting is enabled in POST /containers/create , the stream is the raw data from >the process PTY and client's stdin. When the TTY is disabled, then the stream is multiplexed to >separate stdout and stderr.

The code for both `attach` and `logs` need to handle cases where the container that is being attached to/streamed from has tty=true. Currently, you'll end up not seeing any output, or seeing delayed and incompleted output from such containers.

**Comment by shin-** [comment]
Closing via #669
