### ISSUE TITLE
old releases on pypi

### ISSUE THREAD

**Issue by binarydud** [docker/docker-py#641]
Could older releases be made available via pypi. If I pin a version right now and a new release is made, that pin no longer works. For instance, I had 1.2.2 pinned in a requirements.txt file and now I can't get that to install because it's no longer visible

**Comment by shin-** [comment]
Um, works for me...
```
$ pip install docker-py==1.2.2
Downloading/unpacking docker-py==1.2.2
[snip]
$ pip freeze | grep docker
docker-py==1.2.2
```

**Comment by binarydud** [comment]
my bad, it is working now. Not sure what was going on. When it didn't work the first time and I couldn't see the previous versions on the pypi page, I assumed the versions were being removed.
