### ISSUE TITLE
exec_start with detach=True and stream=True not working as expected

### ISSUE THREAD

**Issue by xavileon** [docker/docker-py#655]
Maybe I'm doing something wrong or do not understand the underlying API but here it goes.
I want to launch a command on a container in the background and read the stream of the command result. A microtest would be:
```
from docker import Client

cli = Client(base_url='unix://var/run/docker.sock')

exec_id = cli.exec_create(
        'container_name', 
        'timeout 10 sh -c "sleep 5 && echo loreipsudeim"', 
        stdout=True,
        stderr=True)
generator = cli.exec_start(exec_id, detach=True, stream=True)

for x in generator:
    print x
```

From the docker-py documentation, it seems that when stream=True, a blocking generator is returned. I'd expect the generator to block until there's no output from the command but that's not the case. What should be the expected behavior?

Is it supported the use case I propose?

I'm on docker 1.6.2 (seen this in 1.7 too) and docker-py 1.2.3.

**Comment by xavileon** [comment]
Setting detach=False did the trick.

**Comment by missedone** [comment]
right, Detached mode: run command in the background, so it's the expected behavior
see also: https://docs.docker.com/reference/commandline/exec/
