### ISSUE TITLE
`expand_registry()` fails on private registry with authentication

### ISSUE THREAD

**Issue by navi7** [docker/docker-py#658]
`expand_registry()` in `utils/utils.py` tries to ping the registry at  `https://private.registry.com/v2/` endpoint. 
If that endpoint returns `401 Authorization required`  then the exception
```
errors.DockerException("HTTPS endpoint unresponsive and insecure mode isn't enabled.")
```
is raised.

**Comment by shin-** [comment]
Fixed by #617
