### ISSUE TITLE
Cannot pull from private registry with HTTP authentication

### ISSUE THREAD

**Issue by ffdybuster** [docker/docker-py#663]
We have a private (v1) registry accessible via HTTPS which is protected with HTTP authentication (credentials set up via `.dockercfg`). Unfortunately, using docker-py to pull from this registry via
``` .py
import docker.client
client = docker.client.Client()
client.pull('our.registry.server:1234/bla', tag='latest')
```
doesn't work:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 747, in pull
    repository, insecure=insecure_registry
  File "/usr/local/lib/python2.7/dist-packages/docker/auth/auth.py", line 59, in resolve_repository_name
    return expand_registry_url(parts[0], insecure), parts[1]
  File "/usr/local/lib/python2.7/dist-packages/docker/auth/auth.py", line 38, in expand_registry_url
    "HTTPS endpoint unresponsive and insecure mode isn't enabled."
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```
The problem is that in `auth.py`, `expand_registry_url` determins whether `https://our.registry.server:1234` works by accessing that URL (with something added) and aborting if any HTTP status code >= 400 is returned. Since we use HTTP authentication, this yields the HTTP status code 401, which causes the function to raise the above exception.

While this problem can be overcome in `expand_registry_url` by adding `https://`, its caller `resolve_repository_name` explicitly checks for that and bails out if a scheme is specified.

**Comment by shin-** [comment]
Change your config to allow unauthenticated access to the ping endpoint, [as seen here](https://github.com/docker/docker-registry/blob/master/contrib/nginx/nginx.conf#L42-L45)
