### ISSUE TITLE
build() output is forced to stream=True with any server API version >= 1.8

### ISSUE THREAD

**Issue by jbaviat** [docker/docker-py#665]
The build output is forced to stream=True with my Docker's version, and for any version >= 1.8.

Hence, there is no easy way to retrive the built image ID (cf. #255 and #392).

In file `docker/client.py`, method `build`, around line 347:
```python
         if utils.compare_version('1.8', self._version) >= 0:
             stream = True
```

My Docker version:
```
﻿Client version: 1.7.0
Client API version: 1.19
...
Server version: 1.7.0
Server API version: 1.19
```

Is there possibly something I'm missing there?

**Comment by shin-** [comment]
Already addressed and the two issues you've linked to contain a code snippet that responds to your particular use case.
