### ISSUE TITLE
ADD and COPY files.

### ISSUE THREAD

**Issue by onizo** [docker/docker-py#668]
I'm trying to find the function to ADD and/or COPY files from my docker host to the container. I've searched through the documentation a few times and can't seem to find what I need.

Would it be better to mount volumes?

In this case, I'm spinning up an nginx container and need to copy global.conf into /etc/nginx/conf.d and nginx.conf to /etc/nginx/.

**Comment by rrbarrero** [comment]
+1
As "workaround", you can inject the file in the building process at the temp folder. I use this:
sudo find /var/lib/docker/tmp/ -type d -name 'docker-build*' -exec cp $STARTFILE {} \;
in a shell script and run it with subprocess.

**Comment by shin-** [comment]
Working on this as part of #771

**Comment by rrbarrero** [comment]
Ah! thanks.

**Comment by shin-** [comment]
Merged into master!
