### ISSUE TITLE
exec_start can't get the cmd result

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker-py#670]
When i use exec_start execute a shell cmd in container,i cant get the cmd return value.

I excute cmd like:
ins=cli.exec_create("dd28a6fb9277","ls /test",True,True,False)
output=cli.exec_start(ins,False,False,False)
i got:
ls: cannot access /test: No such file or directory

But i want to get 0 or a none zero value. 
eg:
localhost# ls /test;echo $?
ls: cannot access /test: No such file or directory
2

**Comment by shin-** [comment]
Use `Client.exec_inspect`

```python
cli.exec_inspect(ins)['ExitCode']
>>> 2
```
