### ISSUE TITLE
"Client and server don't have same version"

### ISSUE THREAD

**Issue by Jeffdude** [docker/docker-py#673]
I am getting [this exception](https://gist.github.com/Jeffdude/6c9226d03256352a0007) after running 
```
import docker
cli = docker.Client(base_url="unix:///var/run/docker.sock")
cli.images()
```
I have installed on a fresh CentOS VM with
`yum install docker` and `pip install docker-py`
Some more info:
```
[root@master-1 httpd]# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
[root@master-1 httpd]# pip show docker-py
---
Metadata-Version: 1.1
Name: docker-py
Version: 1.3.0
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires: requests, six, websocket-client
```
I don't think this should be happening after such a fresh install.
My question is, what are my options to resolve this conflict? I know I can just downgrade docker-py, can I also upgrade docker?

Thanks.

**Comment by shin-** [comment]
You have several options: 
- upgrade docker to 1.7.0
- indicate the API version corresponding to your current docker installation (1.18) in the `docker.Client` constructor, like this: `c = docker.Client(version='1.18')`
- Tell docker-py you want it to detect the version it needs to use automatically `c = docker.Client(version='auto')`

HTH!

**Comment by Jeffdude** [comment]
Okay thank you very much! `version='auto'` is a perfect option in this case. Glad that exists!
