### ISSUE TITLE
Support tar file in load_image API

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#687]
docker load command support input tar file:
```
docker load --input fedora.tar
```
Maybe *load_image* API can support it to input by tar file path.
```python
c.load_image("/tmp/fedora.tar")
```
Also give a brief example of using current *load_image* API to read stream from tar file. 
I don't know how to pass binary data into load_image API. 
Thanks!

**Comment by shin-** [comment]
```python
c = docker.Client()
with f = open('./fedora.tar', 'r');
    c.load_image(f)
```

**Comment by mpeuster** [comment]
Maybe it helps other who stumble across it: 

It should be mode "br".

```
c = docker.Client()
with f = open('./fedora.tar', 'br'):
    c.load_image(f)
```
