### ISSUE TITLE
docker-py for libnetwork

### ISSUE THREAD

**Issue by danehans** [docker/docker-py#694]
Are you aware of an API client for libnetwork written in Python? If not, would Docker accept a PR to add libnetwork-py?

**Comment by abronan** [comment]
@danehans support for networking in docker-py is on the way, you can take a look at #729 :)

**Comment by danehans** [comment]
@abronan thanks for the follow-up. i'll keep an eye on #729

**Comment by shin-** [comment]
#729 was merged, closing!
