### ISSUE TITLE
/etc/hosts broken when network_disabled=True

### ISSUE THREAD

**Issue by spinus** [docker/docker-py#701]
When I start container like:
```
client.create_container('debian:sid', command="cat /etc/hosts", network_disabled=True).start()
```
`/etc/hosts` file is empty. And when I use `host_config` with `extra_hosts`, extra hosts entries are not added to `/etc/hosts` file (and as mentioned, the file is empty/damaged).

But when I start container with shell, like:
```
docker run -ti --net=none --rm debian:sid cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
`/etc/hosts` is fine.

Hence, I assume `network_disabled` option break /etc/hosts file somehow (or does not run any minimal initialization?).

**Comment by shin-** [comment]
`--net=none` and `network_disabled` are two different things. The command you're running with docker-py is actually equivalent to `docker run --networking=false debian:sid cat /etc/hosts`

```
$ docker run -t --networking=false ubuntu cat /etc/hosts 
Warning: '--networking' is deprecated, it will be removed soon. See usage.
$ docker run -t --net=none ubuntu cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```

Here's the equivalent docker-py line you would use:
```python
client.create_container(
    'debian:sid', 
    'cat /etc/hosts', 
    host_config=docker.utils.create_host_config(network_mode='none')
)
```

HTH!

**Comment by spinus** [comment]
@shin- good stuff. Thank you for explanations! I didn't know that.

**Comment by shin-** [comment]
Happy to help - docker-py should probably warn about `network_disabled` being deprecated somewhere.
