### ISSUE TITLE
docker-py version "1.4.0-dev" network_mode bug with docker 1.7.1

### ISSUE THREAD

**Issue by mnowster** [docker/docker-py#714]
With the introduction of [this code](https://github.com/docker/docker-py/blame/master/docker/utils/utils.py#L432) to cater for docker 1.8's `network_mode` option of `default`, it now breaks the integration tests if you are on docker 1.7 with:

`NotFound: 404 Client Error: Not Found ("Cannot start container 1a0b16410775af68692e174462b94c8ebd9e79be31da27d3b870b63dd83d2625: error locating network with name default: network default not found")`

I propose that we add in a `compare_version` around the setting of the `network_mode` and if the API version < 1.20 we don't set it to `default`, so that we are backwards compatible for docker 1.7.

**Comment by alunduil** [comment]
+1, also seeing this on docker-py-1.3.1.

**Comment by aanand** [comment]
@alunduil Are you certain it's happening on docker-py 1.3.1? The offending commit was merged into master after the 1.3.1 release. Do you have steps to reproduce?

**Comment by alunduil** [comment]
No, I'm not sure of anything anymore.  I was seeing this behavior with docker-compose-1.3.3 (and 1.4.0), docker-py-1.3.1, and docker-1.7.1 but have a working docker-1.8.1 now.  Disregard my noise, it's probably nothing.

**Comment by shin-** [comment]
Fixed by #732
