### ISSUE TITLE
Slightly incorrect documentation for user parameter in create_container?

### ISSUE THREAD

**Issue by eleweek** [docker/docker-py#715]
The documentation for `user` parameter in `create_container` says: 

`user (str or int): Username or UID`

However, supplying it as python's int(`client.create_container(user=1000, ...)`) gives 
```docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal number into Go value of type string")```

Supplying it as string works. So this code `client.create_container(user="1000", ...)` works fine. 

I guess it is a minor issue, though only because Celery printed the exception as "500 Server Error: Internal Server Error", so the critical piece of information was missing(`json: cannot unmarshal number into Go value of type string`). So I guess it is a minor issue, but I figured I should report it.

**Comment by aanand** [comment]
Sounds like we should stringify the value you pass in.
