### ISSUE TITLE
Parsing "generator" output

### ISSUE THREAD

**Issue by jpwilliams** [docker/docker-py#717]
Certain calls (like `.pull()`) can return a "generator" stream. I can log these out fine as JSON objects, though how can I make 'em look all pretty CLI-wise?

(I'm aware this is not really a bug so expecting a quick close, though I couldn't seem to find any information on this!)

**Comment by aanand** [comment]
Compose has a [progress_stream module](https://github.com/docker/compose/blob/master/compose/progress_stream.py) which attempts to replicate the stream parsing and terminal output behaviour of the Docker client. It's out of date, but should be somewhat reusable. We should make it a utility module of docker-py or dockerpty.

**Comment by bfirsh** [comment]
Some of Compose's functionality is now included in docker-py. Here's an example of the implementation:

https://github.com/docker/docker-py/blob/1984f68730512a1c07017118f4e229c7949ff8a8/docker/models/images.py#L96-L169
