### ISSUE TITLE
ER: Support "device" for mapping host devices to containers 

### ISSUE THREAD

**Issue by joelacrisp** [docker/docker-py#725]
We have some special host device files we need to access from inside the containers, it doesn't look as if the docker-py library permits passing --device?

**Comment by shin-** [comment]
You're looking to use the `devices` param in `docker.utils.create_host_config`. Unfortunately it looks like it's missing from the documentation, but the feature does exist already.

**Comment by joelacrisp** [comment]
Ok thanks!

**Comment by shin-** [comment]
Documentation updated in 5d95f24264d25991e9f7caf23e9c860bcdb11874

**Comment by iafilatov** [comment]
I think 5d95f24 specifies how the `devices` key looks in the resulting host config dict, not what the param should look like. Inside `create_host_config` the param is passed to `parse_devices` (https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L369), which expects it to be a list of strings like you would use in `docker run --device=...`.

**Comment by shin-** [comment]
Correct - although, we should support both forms IMO, but it doesn't look like we do at the moment.
