### ISSUE TITLE
add support for volume api of docker engine 1.9

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker-py#744]
https://github.com/docker/docker/pull/14242

**Comment by aanand** [comment]
:+1: this would be fantastic.

**Comment by choleraehyq** [comment]
Is there anybody working on this? I'd like to give a hand.

**Comment by odigity** [comment]
It was finished 11 days ago.  (See issue 14242 linked above.)

I'm guessing it will get released in 1.9.0.

**Comment by choleraehyq** [comment]
Great!

**Comment by TomasTomecek** [comment]
@odigity I think that @choleraehyq meant code in docker-py, not engine

**Comment by cholerae** [comment]
@odigity Oh, I meant code in docker-py.
@TomasTomecek Thanks for reminding me.

**Comment by odigity** [comment]
My bad.

**Comment by shin-** [comment]
Sorry for the delayed response, had to figure out priority for that, but I'll be working on this in the next week or two.
