### ISSUE TITLE
integration_test.py assumes busybox image is present

### ISSUE THREAD

**Issue by bboreham** [docker/docker-py#745]
It used to do a `pull` near the bottom of the file, but now you've changed the way the script gets run, that code is no longer executed.

**Comment by aanand** [comment]
Yep. Fixed in https://github.com/docker/docker-py/pull/743, but since Travis' Docker support is uncooperative, I'm going to move it into a separate PR.

**Comment by aanand** [comment]
See https://github.com/docker/docker-py/pull/747

**Comment by bboreham** [comment]
Yeah, we moved to CircleCI for Docker-based tests.
