### ISSUE TITLE
Passing host_config parameters in start() overrides the host_config that was passed in create()?

### ISSUE THREAD

**Issue by eleweek** [docker/docker-py#750]
I had a `host_config` with `extra_hosts` defined. I used this `host_config` to create a container. When starting container, I passed extra volumes_from parameter. However, this lead to `extra_hosts` seemingly not doing their job. 

After I moved `volumes_from` from `start()` to `create_host_config` everything started working OK. 

I figured, I should report this, since I spent a couple of hours figuring this out. IMO, start() should override the necessary parts of host_config(and not the whole thing). Or raise an exception.

**Comment by shin-** [comment]
It's a docker issue, not a docker-py issue. You should get a deprecation warning when passing arguments to `start`, and the current plan is to remove that ability entirely in the near future.

**Comment by eleweek** [comment]
> You should get a deprecation warning when passing arguments to start

There was a warning, and I guess I shouldn't have ignored it! :) 

> and the current plan is to remove that ability entirely in the near future

Sounds great! In the meantime, maybe it'd be nice to retrieve current config from docker and check if it has any non-default settings? (And then e.g. raise an exception)

**Comment by aanand** [comment]
> Sounds great! In the meantime, maybe it'd be nice to retrieve current config from docker and check if it has any non-default settings? (And then e.g. raise an exception)

Unfortunately, difficult (maybe impossible) to do reliably, due to how much munging of the config dictionary is done by both docker-py and the daemon.

**Comment by kawasakitoshiya** [comment]
I spent a few days on this issue :(
