### ISSUE TITLE
Remove client side validation of LogConfig

### ISSUE THREAD

**Issue by dnephin** [docker/docker-py#759]
As @mnowster calls out in https://github.com/docker/compose/issues/1869#issuecomment-131059698 doing validation of things on the client (`docker-py`) means that any time a new log driver is added we have to: add it to the enum, review, create a new release.

It's likely that `docker-py` will always lag behind engine.

We should remove `LogConfigTypesEnum` and just let the server validate it.

**Comment by shin-** [comment]
#718

**Comment by dnephin** [comment]
Ah, my searches missed it because I only looked in issues not PRs!

Thanks!
