### ISSUE TITLE
Some examples in the documentation don't work with Python 3

### ISSUE THREAD

**Issue by rutsky** [docker/docker-py#773]
For example this one:

```
>>> from docker import Client
>>> cli = Client(base_url='tcp://127.0.0.1:2375')
>>> for line in cli.pull('busybox', stream=True):
...     print(json.dumps(json.loads(line), indent=4))
```

will produce:

```
TypeError: the JSON object must be str, not 'bytes'
```

Maybe explicitly document such differences, e.g. by adding something like "Note: On Python 3 you need to decode `line` from bytes to `str`: json.loads(line.decode())"?

**Comment by dnephin** [comment]
I noticed this while adding python3 support to compose. The streams that you receive from `stream=True` calls are bytes (I was expecting `str`).

There is an option to have the endpoint return already loaded (which handles the encoding).  It would be nice to get streams of `str`, but that would be a breaking change, so I'm not sure we can do it initially.

We can at least update the examples to include the encode.

**Comment by grahamlyons** [comment]
Python 3 users will already be used to dealing with byte-decoding so documenting this would be the best approach.

Altering the return types of these methods to indicate either `str` or `bytes` would be relatively simple:
https://github.com/docker/docker-py/blob/6fe1c7f/docker/models/containers.py#L228-L229

How about changing those mentions to something like this:
```
        Returns:
            (generator or str|bytes): Logs from the container.
```
