### ISSUE TITLE
Automatically push successful builds to dockerhub

### ISSUE THREAD

**Issue by paulbellamy** [docker/docker-py#784]
Would be great to have the joffrey/docker-py image on hub.docker.com kept up to date with the latest successful builds.

**Comment by shin-** [comment]
I just added the most recent release tags to the automated build configuration so you should be able to pull `1.3.1` and `1.4.0` now. The tag `latest` should be synced with `master`. 

Did you have anything else in mind that would help?

**Comment by paulbellamy** [comment]
That's great, thanks.

In particular, I was wondering if there is a way to hook up travis-ci to push to dockerhub on a successful, build. But I'm not sure what the integration there is like.

**Comment by shin-** [comment]
We don't merge anything into master if the tests don't pass - so we should be safe there. Thanks for the feedback!
