### ISSUE TITLE
Client.port() only reports the UDP exposed port mapping if the same port is configured to be mapped on UDP and TCP.

### ISSUE THREAD

**Issue by devmapal** [docker/docker-py#792]
E.g.:
`docker ps`
```
CONTAINER ID  IMAGE         COMMAND        CREATED        STATUS        PORTS                                         NAMES
6348dd5bc7c2  ubuntu:14.04  /usr/bin/bash  8 seconds ago  Up 8 seconds  0.0.0.0:49153->80/udp, 0.0.0.0:49159->80/tcp  expose_ports
```

`In ipython`
```
In [1]: docker_client.port('6348dd5bc7c2', 80)
Out[1]: [{u'HostIp': u'0.0.0.0', u'HostPort': u'49153'}]
```

The reason seems to lie in `/docker/api/container.py`, line 208-210
```python
def port(self, container, private_port):

...

h_ports = port_settings.get(s_port + '/udp')
if h_ports is None:
    h_ports = port_settings.get(s_port + '/tcp')
```

Instead of basically only accepting a port number for `private_port` and trying for udp and tcp exposed ports, I'd suggest that the method rather accepts an explicit `private_port` input like `1234/tcp`.

**Comment by devmapal** [comment]
`pip freeze | grep docker-py && python --version && docker version`

```
docker-py==0.7.2
Python 2.7.6
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```

**Comment by shin-** [comment]
Thanks for the report!

While this has no bearing on that particular bug, I would strongly encourage you to upgrade `docker` to a more recent version if you can.

**Comment by devmapal** [comment]
Yes, I would love to upgrade docker, but for now I'm unfortunately stuck with the version from the official ubuntu 14.04 package repositories, which is 1.0.1
