### ISSUE TITLE
sporadic TypeError in test_792_explicit_port_protocol

### ISSUE THREAD

**Issue by rade** [docker/docker-py#795]
We are [seeing](https://circleci.com/gh/weaveworks/weave/3037) some sporadic failures in test_792_explicit_port_protocol:
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/docker-py, inifile: 
plugins: cov
collected 25 items

tests/integration_test.py .....s..................F

=================================== FAILURES ===================================
_______________ TestRegressions.test_792_explicit_port_protocol ________________

self = <tests.integration_test.TestRegressions testMethod=test_792_explicit_port_protocol>

    def test_792_explicit_port_protocol(self):
    
        tcp_port, udp_port = random.sample(range(9999, 32000), 2)
        ctnr = self.client.create_container(
            BUSYBOX, 'true', ports=[2000, (2000, 'udp')],
            host_config=self.client.create_host_config(
                port_bindings={'2000/tcp': tcp_port, '2000/udp': udp_port}
            )
        )
        self.tmp_containers.append(ctnr)
        self.client.start(ctnr)
        self.assertEqual(
>           self.client.port(ctnr, 2000)[0]['HostPort'],
            six.text_type(tcp_port)
        )
E       TypeError: 'NoneType' object has no attribute '__getitem__'

tests/integration_test.py:1735: TypeError
=============== 1 failed, 23 passed, 1 skipped in 17.65 seconds ================
```

Note that this doesn't fail all the time.

This is presumably related to #793.

**Comment by tomwilkie** [comment]
And again: https://circleci.com/gh/weaveworks/weave/3038

**Comment by dnephin** [comment]
I'm running that test in a loop (against docker 1.8.1) and not seeing any failures yet (after 30+ iterations). What version of docker are you running against?

I can also try with more tests in case it's test pollution.

**Comment by rade** [comment]
The test is run in the latest `joffrey/docker-py` container. The server is 1.8.2.

**Comment by dnephin** [comment]
I've re-run the travis build for master a few times https://travis-ci.org/docker/docker-py and it isn't failing there yet either. I'll try a couple more.

**Comment by dnephin** [comment]
I've been running the entire suite in a loop and haven't been able to reproduce the error.  Is it possible that the error is triggered by your configuration? 

Maybe try modifying the test to expose more details about the failure? (from the current error it's not clear what is None, or what state the container is in)

**Comment by rade** [comment]
Is it possible that it might be picking a random port that is already taken?

One would think this would cause `start` to blow up, but perhaps it doesn't.
