### ISSUE TITLE
Cannot pull image with docker-py 1.5.0

### ISSUE THREAD

**Issue by dag24** [docker/docker-py#807]
```
$ sudo docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
```

When using docker-py 1.5.0:
```
Failed to pull the specified image: {registry}/{namespace}/{image_name}:latest
APIError(HTTPError(u'400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.20/images/create?tag=latest&fromImage=[snip]',),)
```

Reverting to docker-py 1.4.0 fixes this.

**Comment by dag24** [comment]
To clarify, I have redacted the registry, namespace and image_name from the above.

**Comment by shin-** [comment]
docker-py 1.5.0 specifies API version 1.20 as the default, but your docker daemon only supports up to API 1.19 (1.20 was introduced with Docker 1.8.x)

You can easily fix this by pinning the version you want to use when constructing the `Client`, i.e.

```
import docker
c = docker.Client(version='1.19')
```

**Comment by shin-** [comment]
Assuming this is solved, feel free to reopen if that's not the case.
