### ISSUE TITLE
Proper way to get build status?

### ISSUE THREAD

**Issue by andyshinn** [docker/docker-py#828]
I noticed that a failed build doesn't throw an exception or fail in any way. This is in contrast with the command line client that will exit non-zero on a build failure. I'd like to be able to catch and exception on build failure.

What is a good way to figure out build status currently?

**Comment by dnephin** [comment]
It's not pretty, but you can see how we do it in compose here: https://github.com/docker/compose/blob/b6b9b002/compose/service.py#L738-L745

**Comment by TomasTomecek** [comment]
I did ask the same thing back then: https://github.com/docker/docker-py/issues/449

**Comment by andyshinn** [comment]
The Compose example is helpful. Thanks! I think this is definitely something worth calling out in documentation so i'm not going to jump to close just yet.

**Comment by dnephin** [comment]
Actually, I think I linked you to the wrong code. The actual error handling is here:

https://github.com/docker/compose/blob/b6b9b002e5c0b1687fac3e5e1e5c095b1c97bf8d/compose/progress_stream.py#L46-L47

I just took a look at the output from the API. I'm seeing this as the last message in the stream:

```
{
  'errorDetail': {
    'message': u"The command '/bin/sh -c exit -1' returned a non-zero code: 2",
    'code': 2
  },
  'error': u"The command '/bin/sh -c exit -1' returned a non-zero code: 2"
}
```

**Comment by andyshinn** [comment]
There are actually a couple spots I will cherry pick. Along with the progress stream, https://github.com/docker/compose/blob/b6b9b002/compose/service.py#L716-L729 seems like a better example of calling cli.build in general.

**Comment by bfirsh** [comment]
The development version now includes a build function which raises an exception on failure.
