### ISSUE TITLE
DNS does not work

### ISSUE THREAD

**Issue by kyleko** [docker/docker-py#829]
Hi all,

I met a problem regarding DNS in "/etc/resolv.conf" in container.

When I start container with "docker run -i -t --dns=mydns image cmd", 
the mydns will be written into "/etc/resolv.conf" as my expectation.

However, when I start container with docker-py as:

```python
import docker

c = docker.Client(base_url='unix:///var/run/docker.sock',version='1.18')

image_name = 'centos:6'

args = {'tty': True, 'name': 'kyle-test', 'hostname': 'instance-kyle-test', 'environment': {}, 'network_disabled': True, 'mem_limit': 536870912, 'cpu_shares': 1024}

c.create_container(image_name, **args)
c.start(container_id,dns=['8.8.8.8','8.8.4.4'])
```

Although I can see "8.8.8.8" and "8.8.4.4" in output of "docker inspect" of container, 
There is nothing written in "/etc/resolv.conf"

Did I miss anything?

-
[ENV]
docker-py==1.5.0
Python 2.7.5
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64

[OS]
CentOS Linux release 7.1.1503 (Core)

**Comment by shin-** [comment]
Sorry, I didn't realize this had been sitting here for so long.

Your issue is you're passing parameters to `Client.start`, which isn't working properly for recent versions of Docker. In fact, doing so should display a deprecation warning.

For more info on this, see #822 

To remedy your issue, the proper way to proceed is to provide a host config in `create_container` with a properly set `dns` parameter, as such:

```python
import docker

c = docker.Client(base_url='unix:///var/run/docker.sock',version='1.18')

image_name = 'centos:6'

args = {'tty': True, 'name': 'kyle-test', 'hostname': 'instance-kyle-test', 'environment': {}, 'network_disabled': True, 'mem_limit': 536870912, 'cpu_shares': 1024}

host_config = c.create_host_config(dns=['8.8.8.8', '8.8.4.4'])
ctnr = c.create_container(image_name, host_config=host_config, **args)
c.start(ctnr)
```
