### ISSUE TITLE
create_host_config mem_limit ignored

### ISSUE THREAD

**Issue by harpingon** [docker/docker-py#835]
docker-py 1.5.0
docker engine 1.8.2

    hc=c.create_host_config(port_bindings=pbind, mem_limit='1g')
    c.create_container(image=sysimage, hostname=syscontainer, detach=True, ports=fullportlist,   name=syscontainer, environment={"SYSBUILDER":sys,"SYSMODE":"install"}, host_config=hc)

docker inspect output:

    docker inspect containername | grep -i mem
        "Memory": 0,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,

The port_bindings of the host_config is being correctly used.

I saw a previous ticket on this which seemed to suggest this was resolved earlier, but I'm seeing this problem with 1.5

**Comment by shin-** [comment]
This has been reported before, but I haven't been able to reproduce it. can you help me investigate? https://github.com/docker/docker-py/issues/305#issuecomment-149387309

**Comment by dnephin** [comment]
I think I remember seeing something about earlier 3.x kernels not supporting this option. What version does `uame -a` report?

**Comment by harpingon** [comment]
It's RHEL 7.1 

Linux hostname 3.10.0-229.14.1.el7.x86_64

**Comment by harpingon** [comment]
I have same problem, I can't run your example because of
   
    docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19

Some more investigation reveals this:
After the initial c.create_container , the Memory parameter is there with my 2g

     docker inspect garycowelle5sysbld140 | grep -i mem
        "Memory": 2147483648,
        "MemorySwap": 0,
        "CpusetMems": "",
        "MemorySwappiness": null,



But, after calling c.start , the configuration is gone:

      docker inspect garycowelle5sysbld140 | grep -i mem
           "Memory": 0,
           "MemorySwap": 0,
           "CpusetMems": "",
           "MemorySwappiness": null,

After stopping the container, configuration is still gone:

       docker inspect garycowelle5sysbld140 | grep -i mem
          "Memory": 0,
          "MemorySwap": 0,
          "CpusetMems": "",
          "MemorySwappiness": null,


Create another container using docker-py:

       $ docker inspect fdde29acfea6 | grep -i mem
         "Memory": 2147483648,
         "MemorySwap": 0,
         "CpusetMems": "",
         "MemorySwappiness": null,

But this time, start it with docker command line:

        $ docker start fdde29acfea6
        fdde29acfea6
        $ docker inspect fdde29acfea6 | grep -i mem
         "Memory": 2147483648,
         "MemorySwap": 0,
         "CpusetMems": "",
         "MemorySwappiness": null,

configuration remains.

So, seems to me that the docker-py start is clobbering some of the host config?


Some versions for you:

      ('VERSION: ', {u'KernelVersion': u'3.10.0-229.14.1.el7.x86_64', u'Os': u'linux', u'BuildTime': u'Wed Oct  7 17:25:19 UTC 2015', u'ApiVersion': u'1.20', u'Version': u'1.8.2', u'GitCommit': u'0a8c2e3', u'Arch': u'amd64', u'GoVersion': u'go1.4.2'})

     $ pip freeze | grep docker
     docker-py==1.5.0

    $ docker --version
    Docker version 1.8.2, build 0a8c2e3

    $ uname -r
    3.10.0-229.14.1.el7.x86_64

    $ cat /etc/redhat-release
    Red Hat Enterprise Linux Server release 7.1 (Maipo)

    $ python --version
    Python 2.7.5





     
Hope this helps

**Comment by shin-** [comment]
@harpingon How do you call Client.start? Any arguments in addition to the container ID?

**Comment by shin-** [comment]
Here's a code sample you can run with a more recent version of docker (that other comment was in reply to someone using Docker 1.6.x)
```python
import docker

c = docker.Client(version='auto')
print('VERSION: ', c.version())

c.pull('busybox:latest')
ctnr_id = c.create_container(image='busybox:latest', host_config=c.create_host_config(mem_limit='5g'))
print('CONTAINER ID: ', ctnr_id)
ctnr_data = c.inspect_container(ctnr_id)
print('Mem Limit (config): ', ctnr_data['Config']['Memory'])
print('Mem Limit (host config): ', ctnr_data['HostConfig']['Memory'])
```

**Comment by harpingon** [comment]
Yes, we're passing ports in start:

         c.start(syscontainer, port_bindings=pbind)

**Comment by shin-** [comment]
you're running into #750 .

**Comment by harpingon** [comment]
Yes I see that now. I will just refrain from using anything other than container name in start.

API moves fast :)

Thanks for your help. Closing this.
