### ISSUE TITLE
docker build: support --build-arg argument

### ISSUE THREAD

**Issue by leonty** [docker/docker-py#837]
Docker 1.9 offers a new command line parameter to customize the Dockerfile at the build time:

The ARG instruction defines a variable that users can pass at build-time to the builder with the docker build command using the --build-arg = flag.
https://docs.docker.com/engine/reference/builder/#arg

**Comment by leonty** [comment]
Hi shin, I have a ready PR for this... just have stuck with the signing...

**Comment by leonty** [comment]
Done!

**Comment by shin-** [comment]
The PR for this has been merged - closing.
