### ISSUE TITLE
docker.Client.logs(tail=0) returns all logs instead of no logs

### ISSUE THREAD

**Issue by exarkun** [docker/docker-py#845]
This is a confusing behavior.  It also makes it harder to follow a container's logs (with `stream=True`) without getting at least some old log data.  A work-around is required, specifying `tail=1` and then discarding the first line of output.

**Comment by dnephin** [comment]
I believe this is the behaviour of the API (http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#get-container-logs), so we shouldn't be modifying that on the client.  You might need to open this issue on the docker project.

**Comment by shin-** [comment]
The CLI behaves properly, so this is most likely a docker-py bug.

**Comment by dnephin** [comment]
Ah, good call

**Comment by exarkun** [comment]
Thank you!
