### ISSUE TITLE
support --since on docker logs

### ISSUE THREAD

**Issue by nhumrich** [docker/docker-py#847]
The docker CLI has a `--since` option on `docker logs` where you can provide a timestamp for the logs.
This is really useful in scripting, 

    print all logs
    last_timestamp = timestamp of last log
    ... do stuff ...
    print all logs since timestamp

There is really no way to achieve this right now without grabbing all the logs, and manually throwing out all the old ones.

**Comment by shin-** [comment]
#796 - I still need to review it but I think it's looking well on its way.

**Comment by shin-** [comment]
#796 has been merged and is in 1.6.0 - closing this as a result.
