### ISSUE TITLE
Dockerfile image, python started to mount the volume

### ISSUE THREAD

**Issue by staugur** [docker/docker-py#849]
**I met this kind of situation.**
My Dockerfile(pushed to my registry):

    FROM registry.saintic.com/base 
    MAINTAINER SaintIC <staugur@saintic.com>
    RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
         rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm && \
         yum install -y nginx &&\
         [ -d /data ] || mkdir /data ; ln -s /usr/share/nginx/html/ /data/wwwroot
    EXPOSE 80 443
    ENV LANG en_US.UTF-8
    CMD /etc/init.d/nginx start && /bin/bash

My python file:

    #coding:utf8
    import docker
    volume = '/data/test'
    if volume:
      volumes=[]
      #volumes.append(volume)
      cfs = ['%s:/data/wwwroot:rw' % volume]
    else:
      print 'quit'
    c = docker.Client(base_url='unix:///var/run/docker.sock')
    #Can add "volumes=volumes"，Because now volumes is an empty list.
    #print "volume and cfs==> %s:%s" %(volumes,cfs)
    rc = c.create_container(image='registry.saintic.com/nginx',stdin_open=True,tty=True,host_config=c.create_host_config(binds=cfs))
    cid = rc['Id'][:12]
    rs = c.start(resource_id=cid)
    if rs == None:
      print '\033[0;32;40mSuccess:Start Container %s\033[0m' % cid
    else:  
      print "\033[0;31;40mStart Failed.\033[0m"
      
Now run!**All normal!**
![enter description here][1]

But when my python file is changed to this time:

    #coding:utf8
    import docker
    volume = '/data/test'
    if volume:
      volumes=[]
      volumes.append(volume)
      cfs = ['%s:/data/wwwroot:rw' % volume]
    else:
      print 'quit'
    c = docker.Client(base_url='unix:///var/run/docker.sock')
    rc = c.create_container(image='registry.saintic.com/nginx',stdin_open=True,tty=True,volumes=volumes,host_config=c.create_host_config(binds=cfs))
    cid = rc['Id'][:12]
    rs = c.start(resource_id=cid)
    if rs == None:
      print '\033[0;32;40mSuccess:Start Container %s\033[0m' % cid
    else:  
      print "\033[0;31;40mStart Failed.\033[0m"
     

The results are as follows:
![enter description here][2]

  
Note 1, the./info.sh script in the picture is as follows:

    #!/bin/bash
    docker inspect $1 | jq .[0].HostConfig.Binds
    docker inspect $1 | jq .[0].Volumes
    docker inspect $1 | jq .[0].VolumesRW
    
Note 2, I refer to the document is:
[http://docker-py.readthedocs.org/en/latest/volumes/][3]

  [1]: https://saintic.top/img/right.png "right.png"
  [2]: https://saintic.top/img/volumes.png "volumes.png"
  [3]: http://docker-py.readthedocs.org/en/latest/volumes/

**Comment by shin-** [comment]
Can you try and repost your images? I'm not able to see them at the moment, so I'm not sure what's wrong.

**Comment by staugur** [comment]
I've pushed it to hub docker, the base image is registry.saintic.com/base, or staugur/base.

**Comment by shin-** [comment]
I mean your screenshots in the first post.

**Comment by staugur** [comment]
I come from China, English is not very good, so may not fully understand what you mean.
My screenshots are https://saintic.top/img/right.png and https://saintic.top/img/volumes.png

**Comment by shin-** [comment]
Thanks! They didn't show up for me before.

**Comment by staugur** [comment]
You are welcome.

**Comment by shin-** [comment]
Your `cfs` variable is incorrect, you have the origin and destination reversed.

The syntax is `<path_on_host_machine>:<path_inside_container>:<mode>`.

In your case, you want to change it to `cfs = ['/data/wwwroot:%s:rw' % volume]`

**Comment by staugur** [comment]
Container directory is /data/wwwroot, should be mounted on a host of/data/test.
What do you mean variable cfs written backwards?

**Comment by staugur** [comment]
Oh,yes!
You are right!
In my python file, volume = '/data/wwwroot', cfs = ['/data/test:%s:rw' % volume], everything is OK.
My screenshots:
https://saintic.top/img/change.png

**Comment by shin-** [comment]
Glad I could help!

Issue has been resolved, so I'll close this ticket.
