### ISSUE TITLE
Require to add ARG instruction support in Client.build()

### ISSUE THREAD

**Issue by himikk** [docker/docker-py#856]
ARG intodiced in docker 1.9

The ARG instruction defines a variable that users can pass at build-time to the builder with the docker build command using the --build-arg <varname>=<value> flag. If a user specifies a build argument that was not defined in the Dockerfile, the build outputs an error.

http://docs.docker.com/engine/reference/builder/

**Comment by dnephin** [comment]
This was already added in #846, it's in master and will be in the next release.
