### ISSUE TITLE
Can't pull images with . In name.

### ISSUE THREAD

**Issue by hibooboo2** [docker/docker-py#860]
Docker images that have a `.` in their name cannot be pulled with docker-py. This is a result of:

https://github.com/docker/docker-py/blob/master/docker/auth/auth.py#L46

**Comment by shin-** [comment]
Mh, the only reason we go through that validation is to be able to extract the tag name from the repo name. It seems things have diverged substantially in the docker/docker codebase since the last time we touched this, notably with https://github.com/docker/docker/pull/8456

**Comment by shin-** [comment]
I'm working on a fix for this, but just to amend my previous comment: we also use the result of resolve_repository_name to figure out what auth config to send to the daemon.

Currently comparing to how the CLI does this nowadays to figure out the best way to proceed.
