### ISSUE TITLE
Is there an api flag for equivalent of `docker run -rm` ?

### ISSUE THREAD

**Issue by ikreymer** [docker/docker-py#870]
I would like to create containers that are removed automatically when they exit, just realized that `docker run -rm` exists but there does not appear to be a flag for this in `create_container` ? Or am I missing something? Thanks

**Comment by dnephin** [comment]
I believe that functionality is handled by the client. That's how we handle it in Compose: https://github.com/docker/compose/blob/master/compose/cli/main.py#L639-L641

This is likely why `--rm` is incompatible with `-d`, because the client wouldn't have any idea when the container exited.

**Comment by ikreymer** [comment]
ok, thanks, I will look for a different way to do it..

**Comment by shin-** [comment]
See also: #77 #330

**Comment by ikreymer** [comment]
hi, thanks for the follow up, I narrowed down my issue to the following.
I am already using remove_container and that works great.
But, occasionally I have seen `create_container` throw an exception: `APIError: 500 Server Error: Internal Server Error ("Container created but refresh didn't report it back")` and the container exists but gets stuck in the 'created' state.

Would it perhaps be possible to return the container id in this case so that it can still be removed with `remove_container`

**Comment by shin-** [comment]
That would be a [swarm](https://github.com/docker/swarm/issues) issue. Nothing we can do about it at the client level.
