### ISSUE TITLE
create_container --restart flag support

### ISSUE THREAD

**Issue by smythp** [docker/docker-py#875]
Is there support for the --restart flag for "docker run"? Would like to be able to set restart policy for newly created containers, but can't find --restart equivalent in the docs.

**Comment by aanand** [comment]
It's called `restart_policy`, and it's part of host config:

```python
from docker.utils import create_host_config

client = # instantiate a client
client.create_container(host_config=create_host_config(restart_policy='always'))
```

**Comment by smythp** [comment]
Thanks! This is a great help.
