### ISSUE TITLE
Incorrect detail  status of pull new image

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#876]
Using ``pull`` API to pull an image. But sometime it response detail information with ``total:-1``.

```
{u'id': u'379cc190f32e',
 u'progress': u'7.395 MB',
 u'progressDetail': {u'current': 7395421, u'total': -1},
 u'status': u'Downloading'}
```

**Comment by shin-** [comment]
docker-py doesn't control the output of the API. Please report this bug on the [docker/docker](https://github.com/docker/docker/issues) issue tracker.
