### ISSUE TITLE
Have a way to provide file path relative to Dockerfile if `fileobj` is being used.

### ISSUE THREAD

**Issue by prat0318** [docker/docker-py#877]
During `cli.build`, when i do not use `path` for fetching my `Dockerfile`, but instead use a `fileobj`, docker daemon is never able to find relative file paths when given in Dockerfile like `ADD ./foo /etc/foo`. I am not sure which dir is chosen as the base when reading from `fileobj` and how can i get relative file `./foo` to be added.

**Comment by dnephin** [comment]
I think this is by design. If you use a `fileobj` that file is the context for your build. It should be a tarball, and any `ADD` directives would look in the tarball for the files.

I think this is incompatible with `path`, where it builds the tarball for you first.

**Comment by prat0318** [comment]
ah thanks, @dnephin.
