### ISSUE TITLE
All values in lxc_conf are passed to docker-egine as string

### ISSUE THREAD

**Issue by bheras** [docker/docker-py#879]
Hi,

I know that LXC will be deprecated, but I've noticed a small bug: all values in lxc_conf passed in host_config when creating containers are converted to string. This causes some issues with options like 'lxc.cgroup.cpu.shares' as docker-engine expects an int when unmarshalling the json, so any value expected as non-string from the docker-engine side will fail:

```
ERRO[173466] Handler for POST /v1.21/containers/create returned error: json: cannot unmarshal string into Go value of type int64 
ERRO[173466] HTTP Error                                    err=json: cannot unmarshal string into Go value of type int64 statusCode=500
```

The issue is in utils/utils.py, L624:
```
    if isinstance(lxc_conf, dict):
        formatted = []
        for k, v in six.iteritems(lxc_conf):
            formatted.append({'Key': k, 'Value': str(v)})
        lxc_conf = formatted
```

A quick and dirty solution would be to replace `str(v)` for `v` so the decision on the type used would recall on the user. 

Otherwise, we could go farther and map the types expected from docker-engine for every `lxc-conf` value in order to match the docker API.

Tested on this gear:
```
$ pip freeze | grep docker-py && python --version && docker version && uname -a && lsb_release -a
docker-py==1.6.0
Python 2.7.6
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Linux dockertest01 3.19.0-39-generic #44~14.04.1-Ubuntu SMP Wed Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

I could try to provide a pull request if necessary.

Thanks!

**Comment by shin-** [comment]
Looking at the engine code,
* [`LxcConf` is of type `LxcConfig`](https://github.com/docker/docker/blob/9d14866d7173e974b9eff34e251b16083647f056/runconfig/hostconfig.go#L229)
* [`LxcConfig.values`  is a slice of `KeyValuePair`](https://github.com/docker/docker/blob/9d14866d7173e974b9eff34e251b16083647f056/runconfig/hostconfig.go#L168)
* [`KeyValuePair.Value` is always a string](https://github.com/docker/docker/blob/9d14866d7173e974b9eff34e251b16083647f056/runconfig/hostconfig.go#L16)

As a result, it seems to me that converting values to a string pre-emptively is always correct. Do you experience an issue caused by this specifically?

**Comment by bheras** [comment]
Thanks for the reply,

I didn't have time to check the engine code, but I just found issue: a layer 8 one (mine) :P

I'm using argparse and configparse. I have defined some "profiles" in my config file and I call the rest from command line arguments (image, name, entrypoint, ports, etc.).

This is my code on the create_container part:

```
...
dockerhost = Client(base_url=cparser.get('environment', args.environment), timeout=240, version='1.19')
...
cpushares = cparser.get('cpu_profiles', args.cpu_shares)    
hc_cpushares = {'lxc.cgroup.cpu.shares': cpushares}                                                                                                                                                    
...
dockerhost.create_container(image=args.image_path, name=args.name, entrypoint=args.entrypoint, command=args.cmd, ports=create_ports, cpu_shares=cpushares, host_config=dockerhost.create_host_config(port_bindings=hc_ports, binds=hc_volumes, mem_limit=cparser.get('ram_profiles', args.mem_limit), lxc_conf=hc_cpushares))
```

And these are my sections defining the "profiles":

```
[cpu_profiles]
micro = 128
small = 256
medium = 512
big = 1024

[ram_profiles]
micro = 256m
small = 512m
medium = 1024m
big = 2048m
```

So the thing is... I should have used configparse's **getint()** instead of get() or just call int() before cparser.get. Did a couple of tests using lxc as execdriver and it works like a charm, so I'm closing this as "It didn't happen".

I shouldn't have missed that one, sorry about wasting your time! :(

**Comment by shin-** [comment]
No worries, happy to help. :+1:
