### ISSUE TITLE
command line tools needed for talking to docker daemon in a shell script

### ISSUE THREAD

**Issue by jizhilong** [docker/docker-py#885]
Hi, guys.In some circumstance, such as building images in a jenkins container, I need to run some commands like `docker tag`, `docker push`, etc.But I don't want to install another binary package for docker client in the jenkins container,   so I made a trade-off by using commands like `python -c "from docker import client;client.Client(version='1.20').push('10.18.5.203:8080/mypackage','$commit_id', insecure_registry=True)"`, and such long commands make my scripts messy.If there was a command line tool `dockerpy`, those long commands can be simplified with `dockerpy push -v 1.20 --insecure_registry 10.18.5.203:8080/mypackage:$commit_id`.

**Comment by TomasTomecek** [comment]
It's not that hard to implement such thing yourself. I would actually open such request, providing a client without server overhead, at docker engine tracker.

**Comment by dnephin** [comment]
> But I don't want to install another binary package for docker client  ... If there was a command line tool `dockerpy`

These are conflicting requirements, you don't want to install one binary, but you want to create another one that will be installed?

I don't think there is any reason to create a `dockerpy` binary that would be a clone of the `docker` cli binary.

It is possible to build a client-only binary from the current docker/docker repo.

**Comment by jizhilong** [comment]
> These are conflicting requirements, you don't want to install one binary, but you want to create another one that will be installed?
Not conflicting actually, since docker-py is already on our pip requirements list, and no extra overhead of installing another binary would be added  if there is a `dockerpy` cli tool within the `docker-py` repo.

> It is possible to build a client-only binary from the current docker/docker repo.
It's possible, but not as simple and straightforward as a line of command `pip install docker-py` .

**Comment by dustymabe** [comment]
This feature request might be relevant: https://github.com/docker/docker-py/issues/1031

**Comment by jizhilong** [comment]
build client binary from docker/docker is not that complicated, I'll close this issue.

**Comment by TomasTomecek** [comment]
In 1.12, there was a split in packaging. `docker` binary is a client only since then: https://github.com/docker/docker/pull/20639

**Comment by jizhilong** [comment]
@TomasTomecek thanks for the sharing.

**Comment by dustymabe** [comment]
hey all. you can also use https://github.com/containscafeine/shipy that @containscafeine wrote. It is just a few python files that builds on docker-py and you can use it like: `python shipy run --name batman -p 8080:8080 centos ping 8.8.8.8`
