### ISSUE TITLE
Remove container on exit?

### ISSUE THREAD

**Issue by patrick-bark** [docker/docker-py#890]
Hey, when I run docker from the command line there is a --rm option for the run command that removes the container on exit. Is there no way to implement this in docker-py?

**Comment by shin-** [comment]
[It's handled client-side](https://github.com/docker/docker-py/issues/77#issuecomment-28085394). See also #870 #330

**Comment by shin-** [comment]
It's fairly easy to implement the behavior using docker-py:
```
client.start(container_id)
client.wait(container_id)
client.remove_container(container_id)
```

**Comment by patrick-bark** [comment]
Awesome, thank you
