### ISSUE TITLE
create_container with host_config with links parameter failing

### ISSUE THREAD

**Issue by patrick-bark** [docker/docker-py#891]
Sorry I don't mean to throw up too many tickets, but this is looking like a bug.

I am using docker-py to spin up a container that needs to be linked to my database, but when I add the links parameter to the host-config, it fails with the error:

    json: cannot unmarshal array into Go value of type string

My docker-py call is:

    container = cli.create_container(image='src_app_main', name=issue_id, working_dir='/Indy/src/auto_build', command=run_com, host_config={'links': [('db', 'db')], 'volumes_from': ['log_data', 'repo_data']})

This command works perfectly without the links parameter in the host config. I have tried both the list of tuples and the dictionary option of describing the links

Versions:

docker-py: 1.6.0

docker: 1.9.1

**Comment by shin-** [comment]
You want to use `cli.create_host_config(links=...)` for the array to be converted into the format expected by the docker API, and pass the result of that command into the `host_config` parameter. Let me know if that helps.

**Comment by patrick-bark** [comment]
Thank you again, that worked

**Comment by shin-** [comment]
Cool!
