### ISSUE TITLE
Docker-py API don't expect getting data in list-like types (except list itself)

### ISSUE THREAD

**Issue by frol** [docker/docker-py#896]
Most of the places in Docker-py have checks like `isinstance(smth, list)`, but this won't play nicely when you pass a `tuple` or a `set`.

For example, you just cannot pass anything but `list` or `str`/`unicode`/`bytes` type to `volumes` argument to `create_container()`.

**Comment by frol** [comment]
Hint: The best way, I could think of, to check for a list-like types might be `isinstance(smth, collections.Container) and not isinstance(smth, six.string_types) and not isinstance(smth, dict)` (this can be splitted and usually is already done in the code-base, so you don't need to check for `not ...` because you handle those cases before checking for `collections.Container` types).

**Comment by shin-** [comment]
The documentation is explicit about needing lists here, so I don't consider that an issue. Conversion from any of these types to a list is trivial as well.

**Comment by frol** [comment]
> Conversion from any of these types to a list is trivial as well.

In the most cases (if not all), there is no reason for limiting a user by requiring the `list` type. The error messages are also misleading in some cases. For example, when I pass `volumes` to `create_container` as a `tuple` instead of a `list`, I get:

```Python
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 138, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.21/containers/create?name=ddots-test_solution-ddots-compiler-gpp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ddots/testing_system/worker/docker_manager.py", line 99, in init_container
    container_reference = self._docker_client.create_container(**init_options)
  File "/usr/lib/python3.5/site-packages/docker/api/container.py", line 117, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python3.5/site-packages/docker/api/container.py", line 128, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 146, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'json: cannot unmarshal array into Go value of type map[string]struct {}'")
```
