### ISSUE TITLE
Feature request: allow to pull by digest

### ISSUE THREAD

**Issue by awasilyev** [docker/docker-py#909]
from cli I am able to run something like:

docker pull my.hub.int/image@sha256:82280d2495907dae5781870ed8d053436b68b947ce1d06aab36174bffbfd1159

it will be useful to have such ability in the python client.

**Comment by shin-** [comment]
I believe that is supported. Are you seeing different results?

**Comment by awasilyev** [comment]
I check https://github.com/docker/docker-py/blob/master/docker/api/image.py#L150 before and did not see anything related to digest. Wrong place to check?

**Comment by shin-** [comment]
It is handled here supposedly: https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L335

**Comment by awasilyev** [comment]
is it documented anywhere or could you please provide me with usage example?

**Comment by kadel** [comment]
@awasilyev As far as I know you need docker-py version 1.6.0 and up for this. 
Than you can use it just like this:
```
docker_client.pull('my.hub.int/image@sha256:82280d2495907dae5781870ed8d053436b68b947ce1d06aab36174bffbfd1159') 
```

I couldn't find any documentation about this and about 1.6.0 requirement by trail and error :-(
