### ISSUE TITLE
Documentation needed for network overlay

### ISSUE THREAD

**Issue by zbyte64** [docker/docker-py#910]
I've discovered you can have a docker container use an overlay as it's network by setting `network_mode` to the network id. But I have not been able to figure out how to bind ports to the overlay network.

Looking for the docker-py equivalent of:
`docker run -d --name books-ms-db -p 8080   --net my-network mongo`

**Comment by shin-** [comment]
`ports=[8080]` in `create_container` should do what you need, unless I'm misunderstanding.

**Comment by zbyte64** [comment]
It actually does. It wasn't clear to me that the container binded to a port because the `port` method didn't return any results.

**Comment by shin-** [comment]
`port`, only lists the ports that are exposed to the host.You can use `inspect_container` instead to ensure the container is properly configured. :+1:

**Comment by zbyte64** [comment]
Ya, so that actually doesn't work...

If I run this on docker I get the port binded to localhost even though I specified a different network:
`docker run -d --net test7 -e RETHINKDB_JOIN_ADDR=10.0.3.2:29015 -p 28443 -v /etc/docker:/certs zbyte64/rethinkdb-tlsproxy`

But if I tell docker-py `publish_all_ports` or `ports=[28443]` along with `network_mode=test7` then no actual port binding happens. :-1:

**Comment by zbyte64** [comment]
Did more digging. If you specify the network id instead of the network name then docker will not bind your ports to the host. So if you want to use overlay with port binding then you must pass the network name to the `network_mode`. This behaviour does not seem to be documented anywhere....

**Comment by aanand** [comment]
@zbyte64 Do you mean to say that passing the network *name* results in port binding working, whereas passing the network *ID* results in it failing?

ping @mavenugo

**Comment by zbyte64** [comment]
Yes. But I think this recently changed with docker 1.10.1, it seems to be ignoring that all together.

In any event, it would be nice if the docs stated the canonical way to specify using an overlay network.
