### ISSUE TITLE
Parse DriverStatus returned by info()

### ISSUE THREAD

**Issue by dvenza** [docker/docker-py#913]
The info() method should return something usable programmatically. Currently it returns a dictionary containing the `DriverStatus`, a key that contains a list of "stuff".

Parsing this DriverStatus key is a nightmare:
```
[['\x08Role', 'primary'], ['\x08Strategy', 'spread'], ['\x08Filters', 'health, port, dependency, affinity, constraint'], ['\x08Nodes', '2'], ['bf12', 'bf12:2375'], [' └ Status', 'Healthy'], [' └ Containers', '2'], [' └ Reserved CPUs', '0 / 33'], [' └ Reserved Memory', '0 B / 132.1 GiB'], [' └ Labels', 'executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs'], ['bf13', 'bf13:2375'], [' └ Status', 'Healthy'], [' └ Containers', '2'], [' └ Reserved CPUs', '0 / 33'], [' └ Reserved Memory', '0 B / 132.1 GiB'], [' └ Labels', 'executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs']]
```

I can understand that users of the API cannot expect any field to be available, depending on the docker version they are querying, but at least generate nested dictionaries for the nodes and remove extraneous characters.

**Comment by shin-** [comment]
```python
> info = client.info()
> driver_status = dict(info['DriverStatus'])
> print(driver_status)
{u'Backing Filesystem': u'extfs',
 u'Dirperm1 Supported': u'true',
 u'Dirs': u'194',
 u'Root Dir': u'/var/lib/docker/aufs'}
```

Looks fine to me. We could do the dict conversion directly in the `info()` method, but the advantages seem marginal.

As for the "extraneous characters" you're seeing, they're present because your OS/storage driver combination prints them out when docker queries the info. It's not `docker-py`'s responsibility to remove them.

**Comment by dvenza** [comment]
I'm happy this works for you, for me it does not.
Even if I call dict() on that list I reported earlier, I still get keys that are quite difficult to match, I have to cleanup the data. I am using a very standard OS/Storage driver combination, Ubuntu and the default storage driver, the difference is that I am querying the Swarm endpoint and not the Docker engine endpoint.

Since everything is Docker standard in my install I expected the client API to "just work" and present a clean interface, but I guess I have to check with the Swarm guys.

**Comment by TJNII** [comment]
I vote this should be a general improvement across the library.  The pull() method behaves similarly:

```
In [24]: cli.pull('ubuntu:14.04')
Out[24]: u'{"status":"Pulling from library/ubuntu","id":"14.04"}\r\n{"status":"Already exists","progressDetail":{},"id":"8387d9ff0016"}\r\n{"status":"Already exists","progressDetail":{},"id":"3b52deaaf0ed"}\r\n{"status":"Already exists","progressDetail":{},"id":"4bd501fad6de"}\r\n{"status":"Already exists","progressDetail":{},"id":"a3ed95caeb02"}\r\n{"status":"Digest: sha256:0844055d30c0cad5ac58097597a94640b0102f47d6fa972c94b7c129d87a44b7"}\r\n{"status":"Status: Image is up to date for ubuntu:14.04"}\r\n'
```

While I could do some magic to parse this, this output is clearly meant to be printed to the user and not parsed by a machine.  Compare this with the output of the docker-api rubygem comparable operation:

```
=> #<Docker::Image:0x00000000d1f010
 @connection=#<Docker::Connection:0x000000018deef0 @options={}, @url="tcp://172.17.0.149:4444">,
 @id="sha256:3876b81b5a81678926c601cd842040a69eb0456d295cd395e7a895a416cf7d91",
 @info=
  {"RepoTags"=>["ubuntu:14.04"],
   "RepoDigests"=>[],
   "Parent"=>"",
   "Comment"=>"",
   "Created"=>"2016-01-19T23:31:24.889720757Z",
   "Container"=>"1351fd9fceb3cee2ceaa8fc342651f91ae84e445bfbb0d93f066dc34a36911c4",
   "ContainerConfig"=>
    {"Hostname"=>"dfc2eabdf236",
     "Domainname"=>"",
     "User"=>"",
     "AttachStdin"=>false,
     "AttachStdout"=>false,
     "AttachStderr"=>false,
     "Tty"=>false,
     "OpenStdin"=>false,
     "StdinOnce"=>false,
     "Env"=>nil,
     "Cmd"=>["/bin/sh", "-c", "#(nop) CMD [\"/bin/bash\"]"],
     "Image"=>"a4c5be5b6e596241b4530ade26294afa8d8a4a2b9163c30e36c87f879b0f5073",
     "Volumes"=>nil,
     "WorkingDir"=>"",
     "Entrypoint"=>nil,
     "OnBuild"=>nil,
     "Labels"=>nil},
   "DockerVersion"=>"1.8.3",
   "Author"=>"",
   "Config"=>
    {"Hostname"=>"dfc2eabdf236",
     "Domainname"=>"",
     "User"=>"",
     "AttachStdin"=>false,
     "AttachStdout"=>false,
     "AttachStderr"=>false,
     "Tty"=>false,
     "OpenStdin"=>false,
     "StdinOnce"=>false,
     "Env"=>nil,
     "Cmd"=>["/bin/bash"],
     "Image"=>"a4c5be5b6e596241b4530ade26294afa8d8a4a2b9163c30e36c87f879b0f5073",
     "Volumes"=>nil,
     "WorkingDir"=>"",
     "Entrypoint"=>nil,
     "OnBuild"=>nil,
     "Labels"=>nil},
   "Architecture"=>"amd64",
   "Os"=>"linux",
   "Size"=>187925225,
   "VirtualSize"=>187925225,
   "GraphDriver"=>{"Name"=>"aufs", "Data"=>nil},
   "id"=>"sha256:3876b81b5a81678926c601cd842040a69eb0456d295cd395e7a895a416cf7d91"}>
```

The Ruby binding returns an object which is immediately usable.  Furthermore, compare the error handling of the two libraries:

docker-py:
```
In [25]: cli.pull('someimage/that:doesntexist')
Out[25]: u'{"status":"Pulling repository docker.io/someimage/that"}\r\n{"errorDetail":{"message":"Error: image someimage/that not found"},"error":"Error: image someimage/that not found"}\r\n'
```

docker-api gem:
```
[7] pry(main)> Docker::Image.create('fromImage' => 'someimage/that:doesntexist')
Docker::Error::NotFoundError: No such image: someimage/that:doesntexist
from /var/lib/gems/2.1.0/gems/docker-api-1.26.0/lib/docker/connection.rb:46:in `rescue in request'
```

Docker-py returns a string of newline-delimited JSON strings that contain values intended for human consumption.  To use this I'll have to parse these strings searching for keys which I don't know.  The docker-api gem throws an exception which is immediately and easily handleable as an error.

As Docker-py is an API binding I expect the output of it's methods to be easily machine parsable, in my opinion that's the whole point of using the binding: to make coding against the API easy.  Returning data representations which must be massaged into a form which is machine parsable simply isn't good design for a binding.  Please use this issue to improve your return formats.  Thank you.

**Comment by dnephin** [comment]
@TJNII I think that is unrelated. You can specify `stream=True`, which returns a list of dicts as you would expect. It's not really possible to go changing all the response types across the entire library without releasing a V2 since it's a backwards incompatible change. I think most people are just using the `stream=True` option.

If you want to open an issue about `pull()` raising `NotFound` that sounds appropriate for a feature request.

**Comment by shin-** [comment]
This issue seems to be Swarm specific, and will be closed as a result - feel free to reopen if the situation evolves.

**Comment by dvenza** [comment]
Then you should state in the documentation that docker-py is not compatible with swarm.
This is what I get by doing dict() on driverstatus. The entries for each host have the same key and get overwritten. I am using the latest Swarm and Docker and docker-py versions.

Do you really think this is ok?

```
>>> dict(info["DriverStatus"])
 __len__ = {int} 21
 ' └ Containers' (140416914380776) = {str} '6'
 ' └ Error' (140416987361072) = {str} '(none)'
 ' └ Labels' (140416987358960) = {str} 'executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs'
 ' └ Reserved CPUs' (140416987212576) = {str} '0 / 33'
 ' └ Reserved Memory' (140416987213024) = {str} '11 GiB / 132.1 GiB'
 ' └ Status' (140416987359056) = {str} 'Healthy'
 ' └ UpdatedAt' (140416914380568) = {str} '2016-03-02T12:25:21Z'
 '\x08Filters' (140416909775472) = {str} 'health, port, dependency, affinity, constraint'
 '\x08Nodes' (140416909930880) = {str} '10'
 '\x08Role' (140416909933232) = {str} 'primary'
 '\x08Strategy' (140416909776432) = {str} 'spread'
 'bf12' (140416909932560) = {str} '192.168.45.3:2375'
 'bf13' (140416909933456) = {str} '192.168.45.4:2375'
 'bf14' (140416909703856) = {str} '192.168.45.5:2375'
 'bf15' (140416909703912) = {str} '192.168.45.6:2375'
 'bf16' (140416909704976) = {str} '192.168.45.7:2375'
 'bf17' (140416909704808) = {str} '192.168.45.8:2375'
 'bf18' (140416909703968) = {str} '192.168.45.9:2375'
 'bf19' (140416914281840) = {str} '192.168.45.10:2375'
 'bf20' (140416914282904) = {str} '192.168.45.11:2375'
 'bf21' (140416914281504) = {str} '192.168.45.251:2375'
```

**Comment by shin-** [comment]
Did you create an issue on the [Swarm tracker](https://github.com/docker/swarm/issues)?

**Comment by dvenza** [comment]
Thank you for your link, very helpful.
There is already an open issue here: https://github.com/docker/swarm/issues/1214

What I'm trying to point out here is that people try to use the Python API with Swarm and get back a data structure that is difficult to parse and this is not documented anywhere.

At least keep this bug open until Swarm is fixed.
