### ISSUE TITLE
Probably invalid version checking in container creation

### ISSUE THREAD

**Issue by etki** [docker/docker-py#914]
Hi.
I've stumbled upon something i think is a not up-to-date code.

utils.py at line 794 in my distribution (1.6.0) states following:

    if compare_version('1.10', version) >= 0:
        message = ('{0!r} parameter has no effect on create_container().'
                   ' It has been moved to start()')
        if dns is not None:
            raise errors.InvalidVersion(message.format('dns'))
        if volumes_from is not None:
            raise errors.InvalidVersion(message.format('volumes_from'))

As far as i can read from docs, this is not true - both Dns and VolumesFrom are seen in HostConfig for API 1.21. Even if everything is okay with this code, there is still a problem i'm struggling to solve - some of the HostConfig options can be specified in `.container_create()`, but not on `.start()`, e.g. logging driver and options may be set only during creation, but if i need to use custom DNS, i have to specify it on `.start()` call, and this will override whole HostConfig, erasing my logging configuration. Since this code directly raise exceptions, i have no option but to create whole dict directly and pass it to `container_from_configuration()`.

I'm sorry i'm not doing direct pull request instead of issue, but i don't have enough time to figure out correct version constraints and get into projects conventions - sadly, i'm no pythonist and can't do it.

**Comment by shin-** [comment]
Yeah, the error message is obsolete - `dns` and `volumes_from` should be provided in the [host config](https://docker-py.readthedocs.org/en/latest/hostconfig/) - thanks for bringing it up.

**Comment by shin-** [comment]
Just to clarify, the reason you're seeing this error is because you're trying to pass `dns` or `volumes_from` as a parameter to `create_container` directly. While that used to be valid for older versions of Docker, it has since been moved to the `host_config`. 

Also note that you don't need to build the config dictionary by hand - just use `Client.create_host_config` as described [here](https://docker-py.readthedocs.org/en/latest/hostconfig/)

**Comment by etki** [comment]
Ow, that message about moving those parameters to start bugged me out and i didn't even think to check host config (and was afraid of creating container config because of volumes_from comma-concatenating). Thank you!
