### ISSUE TITLE
Can docker-py be used with requests 2.2.1?

### ISSUE THREAD

**Issue by zerthimon** [docker/docker-py#917]
Ubuntu 14.04 Trusty official repo has requests version 2.2.1
Would docker-py work with this version ?

P.S:
Docker-py requires requests >= 2.5.2 which in turn requires newer urllib3 which requires upgrading lots of system libraries.

**Comment by dnephin** [comment]
I would recommend http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by zerthimon** [comment]
@dnephin yeah I know about virtualenv.
I have a need to build a deb package for it, I've alreay done that, but I have to replace official libraries like requests and urllib3 and that broke some other software in the system.

**Comment by dnephin** [comment]
I use https://github.com/spotify/dh-virtualenv to create deb packages, so that I can use the virtualenv

**Comment by zerthimon** [comment]
@dnephin 
I need docker-py to be importable like a system module, a package built with dh-virtualenv still needs special handling (i have a software that needs docker-py, that I cannot modify)

So question remains, can I build and run docker-py with an official ubuntu requests package (2.2.1)

**Comment by TomasTomecek** [comment]
(fedora packager here: what we do is that when dep is not available in required version, we patch docker-py, unpin requirements and pray -- running (integration) test suite may be a good way to figure out if it works)

**Comment by shin-** [comment]
The reason we bumped the version of the requests package way back then (release 1.1.0) was because a lot of people were encountering issues with SSL connections that were caused by the outdated version of requests.

If your package doesn't require connecting to a daemon over HTTPS, using an outdated version of requests might work, but there won't be any guarantee or support for it.

**Comment by zerthimon** [comment]
Thanks everyone for answers, this issue may be closed.
