### ISSUE TITLE
get the output from docker.exec_start in stdout or logging

### ISSUE THREAD

**Issue by openStove** [docker/docker-py#925]
Hi,

I'm trying to get the output from docker.exec_start in stdout or better in logging
- Out of the box, I don't see any output in stdout
- I don't know how to use the output from "stream=True", it is a generator, but could you tell me howto use it : stream it to stdout or logging ?

**Comment by TomasTomecek** [comment]
```python
for line in d.exec_start(exec_id, stream=True):
  print(line)
  logger.debug(line)
```
