### ISSUE TITLE
Start container with timeout?

### ISSUE THREAD

**Issue by DarkFranX** [docker/docker-py#933]
Hi everyone,

Is there any way to start a container with a time limit?

**Comment by shin-** [comment]
Is this what you're looking for?
```python
import docker
from requests.exceptions import ReadTimeout

c = docker.Client()
ctnr = c.create_container('busybox', 'sleep 45')
c.start(ctnr)
try:
  c.wait(ctnr, timeout=5)
except ReadTimeout as e:
  print('too slow!')
  c.kill(ctnr)
```

**Comment by DarkFranX** [comment]
Not exactly.

In fact, I am executing untrusted code inside a container and I want to
limit that code execution time.

Isn't my script stopping at c.start() and wait for container's result?

Or am I completely lost and my script hangs on c.stop() while the code is
executed inside the container? If yes, then your solution might just work!

Will check that tomorrow and get back to you,

Thank you very much!

**Comment by shin-** [comment]
Yeah, `Client.start` is non-blocking. `Client.stop` will typically block until the container is stopped, or the command has timed out (default 10 seconds).

**Comment by DarkFranX** [comment]
Mind = blown. Don't know how I could have missed that. Probably the 'docker run command' that had me suppose Client.start was doing the same thing.

**Comment by shin-** [comment]
Yeah, `docker run` is a combination of `create_container` + `start` + `wait` (unless you use the `-d` parameter).

Glad I could help - feel free to reach out if you're still having trouble.

**Comment by sahil-b-shah** [comment]
This pattern is not working in the current version.

**Comment by kennylajara** [comment]
The pattern works, the code needs to be adapted:

```python
# Create container
container = docker_client.containers.create(
    image_name,
    command,
    auto_remove=True,
    name=container_name,
    detach=False,
    mem_limit="128m",
)
# Run container
container.start()
try:
    # Wait for container to finish
    container.wait(timeout=30)
except ConnectionError as e:
    # If timeout, kill container
    test_passed = False
    container.kill()
```
