### ISSUE TITLE
logs() separate param for stream and follow

### ISSUE THREAD

**Issue by dnephin** [docker/docker-py#934]
From: https://github.com/docker/compose/pull/2720/files#r52222296

Current the `follow` param is set based on `stream`

I think `follow=True` does imply `stream=True`, but `stream=True` doesn't imply `follow=True`, you may still want to stream without following.

**Comment by TomasTomecek** [comment]
This is about performance, right? (and I guess integrity, one can only have a single piece of code to handle streamed response)

**Comment by dnephin** [comment]
I don't think it's just about performance. It's to support `follow=False, stream=True`. 

Stream is a client-side option, follow is a server side option. We want to be able to stream (read the http response line by line and return an iterator instead of buffering the entire response), and not follow the logs.

Otherwise running `logs(stream=False)` on a container with lots of logs would cause the process to use lots of memory (which I guess in a sense is performance related).
