### ISSUE TITLE
AutoVersionClient requires docker daemon running

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker-py#941]
How about moving code which populates `Client._version` from constructor to a lazy property? Validation would be left in-place.

https://github.com/docker/docker-py/blob/master/docker/client.py#L73

Can definitely send a PR which does that.

Related: https://github.com/projectatomic/atomic/issues/302

**Comment by aanand** [comment]
OK, I see the problem, but I'm not sure docker-py should change its behaviour here - in general I like things to fail as early as possible, and it's also nice that you currently know exactly *when* the version check will be performed.

I feel like you shouldn't be initialising a `docker.Client` at the top level of a module if you need to wait for a daemon to start first?

**Comment by TomasTomecek** [comment]
> I feel like you shouldn't be initialising a docker.Client at the top level of a module if you need to wait for a daemon to start first?

That's exactly how we plan to solve that.

I was just thinking that this feature could be beneficial for others. If you, as docker-py upstream, would like to keep this behavior, feel free to close.

**Comment by TomasTomecek** [comment]
feel free to close if you are not interested in this
