### ISSUE TITLE
Hostconfig doc should provide the available list of ulimit names

### ISSUE THREAD

**Issue by achimnol** [docker/docker-py#943]
Currently, [the doc about hostconfig](https://docker-py.readthedocs.org/en/latest/hostconfig/) does not state what option names are available for ulimits parameter, such as `nproc`, `nofile`. The exact list for this parameter is defined by [docker/go-units](https://github.com/docker/go-units) subproject of docker, as in [ulimit.go#L46](https://github.com/docker/go-units/blob/master/ulimit.go#L46).
Although such "shorthand" names of ulimit options might be a "common sense" knowledge for system engineers, I think it would be better to provide the exact list of options for each configuration parameter whenever possible.

**Comment by dnephin** [comment]
I don't think we should duplicate the list, but linking to it sounds appropriate.
