### ISSUE TITLE
create_container with links fail

### ISSUE THREAD

**Issue by osallou** [docker/docker-py#945]
docker: 1.10.1
docker-py: 1.7.0

    conf = cli.create_host_config(
          binds={ '/root': { 'bind': '/backups', 'mode': 'rw'}},
          links=[(container['Id'],'dbbackup')]
        )
    backup_container = cli.create_container({
       'image': 'xxxx',
       'entrypoint': 'xxxx',
       'command': 'xxxx',
       'volumes': '/backups',
       'host_config': conf
    })

Print *conf* shows:

    {'Binds': [u'/root:/backups:rw'], 'NetworkMode': 'default', 'Links': ['2963be1d5b449041bf91682fcb1bb553b711c7bfa8ef067576dbbb6539831223:dbbackup']}

But an error is raised:

    docker.errors.APIError: 500 Server Error: Internal Server Error ("json: cannot unmarshal object into Go value of type string")

**Comment by osallou** [comment]
Seems to work now, don't understand.... but closing issue

**Comment by osallou** [comment]
nope... simply catching the error, that's why it disappeared from logs. Issue still present, sorry

**Comment by shin-** [comment]
I think you're missing `**` in front of your dictionary for the `create_container` call.

**Comment by osallou** [comment]
what do you mean? (I am using Python 2 by the way)

setting

    'host_config': **conf

Would be nice to have an example in documentation, like for volumes.

**Comment by shin-** [comment]
No. You're calling `create_container` with a single dictionary argument. I assume you want it to be a `kwargs` dictionary, in which case you're missing the `**` in front of it.

```python
backup_container = cli.create_container(**{
   'image': 'xxxx',
   'entrypoint': 'xxxx',
   'command': 'xxxx',
   'volumes': '/backups',
   'host_config': conf
})
```
