### ISSUE TITLE
SSL_CERTIFICATE_VERIFY_FAILED on 1.7.1 but not on 1.7.0

### ISSUE THREAD

**Issue by mmerickel** [docker/docker-py#949]
I'm not sure why such a large part of the SSL handling code was rewritten in a bugfix release but nonetheless I'm seeing a regression. My machine/scripts are now failing to connect to my docker 1.10.2 instance. I'm using `docker.utils.kwargs_from_env(assert_hostname=False)` which is returning a valid-looking tls object (correct paths to cert/key/ca) and base_url. Things work fine on 1.7.0 like I said.

I'm using a new virtualenv with latest packages - only difference is 1.7.0 vs 1.7.1.

```
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by shin-** [comment]
#950
