### ISSUE TITLE
Unable to search private docker registry, error 500

### ISSUE THREAD

**Issue by badc0re** [docker/docker-py#960]
I have docker registry v2 (distribution), when i try to tag, push and pull the image everything is working, but when i try to search the registry i have error 500:

```
url = http://some-registry.myservice.home:5000/v2/
repo = some-registry.myservice.home:5000/my-sdk
self.mydocker.login('bla','bla', registry=url)
self.mydocker.search(repository_url)

APIError: 500 Server Error: Internal Server Error ("Unexpected status code 404")
```

**Comment by shin-** [comment]
Does your registry have an index extension? As far as I recall, searching on private registries isn't available by default, which is why you're seeing this issue.

**Comment by badc0re** [comment]
The index extension is still not supported in v2 ...

https://github.com/docker/distribution/blob/731c43e3dbe30fb87b830bab3a46d940ed649a8a/ROADMAP.md

**Comment by shin-** [comment]
Ah, my bad. 
Still, in that case, it seems docker-py is behaving as expected.
