### ISSUE TITLE
default NetworkMode should be "bridge", not "default"

### ISSUE THREAD

**Issue by tbsf** [docker/docker-py#986]
https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L646
 
```python
 if network_mode:
        host_config['NetworkMode'] = network_mode
    elif network_mode is None and compare_version('1.19', version) > 0:
        host_config['NetworkMode'] = 'default'
```
  
should be:

```python
  if network_mode:
        host_config['NetworkMode'] = network_mode
    elif network_mode is None and compare_version('1.19', version) > 0:
        host_config['NetworkMode'] = 'bridge'
```
 
The value of "default" gives an error like the following:

```
FAILED! => {"changed": true, "failed": true, "msg": "Docker API Error: Cannot start container 400145f2e47c2f686abf1513d9d0c49b1fce1e6c8c9f2303c24c61085d5b094c: invalid network mode: default"}
```

Running on Mac OS 10.11.3

```
ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
Host is 
Ubuntu 15.10

```docker-py==1.7.2
Python 2.7.10
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.5.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.5.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by tbsf** [comment]
Created PR with this fix:

https://github.com/docker/docker-py/pull/987

**Comment by shin-** [comment]
It seems to be working fine for me.
```python
In [1]: import docker

In [2]: c = docker.Client()

In [3]: c.create_host_config()
Out[3]: {'NetworkMode': 'default'}

In [4]: c.create_container('busybox', 'top', host_config=_3)
Out[4]: 
{u'Id': u'd8a885ec91c58e36c441ed4825528f7e047dfcde5b6678b867afe798a3b32c7d',
 u'Warnings': None}

In [5]: c.start(_4)

In [7]: c.containers()
Out[7]: 
[{u'Command': u'top',
  u'Created': 1457728245,
  u'HostConfig': {u'NetworkMode': u'default'},
  u'Id': u'd8a885ec91c58e36c441ed4825528f7e047dfcde5b6678b867afe798a3b32c7d',
  u'Image': u'busybox',
  u'ImageID': u'sha256:3240943c9ea3f72db51bea0a2428e83f3c5fa1312e19af017d026f9bcf70f84b',
  u'Labels': {},
  u'Names': [u'/high_galileo'],
  u'NetworkSettings': {u'Networks': {u'bridge': {u'Aliases': None,
     u'EndpointID': u'b7df815663775e2f12f2651a6901dfe29d649cac6bb39fc12ed8ed0f4d0f8597',
     u'Gateway': u'172.17.0.1',
     u'GlobalIPv6Address': u'',
     u'GlobalIPv6PrefixLen': 0,
     u'IPAMConfig': None,
     u'IPAddress': u'172.17.0.2',
     u'IPPrefixLen': 16,
     u'IPv6Gateway': u'',
     u'Links': None,
     u'MacAddress': u'02:42:ac:11:00:02',
     u'NetworkID': u''}}},
  u'Ports': [],
  u'Status': u'Up About a minute'}]

```

Also, note that your host is on API version 1.18, so this shouldn't affect you either way. Maybe `ansible` is passing the `default` value to `network_mode` even though your client doesn't support it?

**Comment by shin-** [comment]
This also appears to be consistent with the CLI's behavior: https://github.com/docker/docker/blob/131e2bf12b2e1b3ee31b628a501f96bbb901f479/runconfig/hostconfig.go#L28-L35

**Comment by tbsf** [comment]
It looks like the 1.15 API introduces the NetworkMode option:

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.15/

**Comment by tbsf** [comment]
Looking at this more, in the Ansible docker module, there is nothing passed for version to the create_host_config option, so version defaults to 1.21 and causes the network_mode to be set to default.

**Comment by shin-** [comment]
That wouldn't work with your 1.6.2 daemon though (you'd get an error like this one `APIError: 400 Client Error: Bad Request "client is newer than server (client API version: 1.23, server API version: 1.22)"`

Are you sure your setup is as you describe it?

**Comment by tbsf** [comment]
When docker.utils.create_host_config is called:

```python
    if not version:
        warnings.warn(
            'docker.utils.create_host_config() is deprecated. Please use '
            'Client.create_host_config() instead.'
        )
        version = constants.DEFAULT_DOCKER_API_VERSION
```

sets version = '1.21'

```python
    if network_mode:
        host_config['NetworkMode'] = network_mode
    elif network_mode is None and compare_version('1.19', version) > 0:
        host_config['NetworkMode'] = 'default'
```

causes host_config['NetworkMode'] to be 'default'.

Parameters passed to create_host_config (as JSON):

```
{
 "publish_all_ports": true, 
 "links": null, 
 "lxc_conf": null, 
 "network_mode": null, 
 "binds": null, 
 "port_bindings": {
  "2888": [
   "0.0.0.0", 
   2888
  ], 
  "3888": [
   "0.0.0.0", 
   3888
  ], 
  "2181": [
   "0.0.0.0", 
   2181
  ]
 }, 
 "privileged": true
}
```

HostConfig returned from create_host_config (as JSON):

```
{
 "PortBindings": {
  "3888/tcp": [
   {
    "HostPort": "3888", 
    "HostIp": "0.0.0.0"
   }
  ], 
  "2181/tcp": [
   {
    "HostPort": "2181", 
    "HostIp": "0.0.0.0"
   }
  ], 
  "2888/tcp": [
   {
    "HostPort": "2888", 
    "HostIp": "0.0.0.0"
   }
  ]
 }, 
 "NetworkMode": "default", 
 "Privileged": true, 
 "PublishAllPorts": true
}
```

The version is used in the create_host_config function but not set.

**Comment by shin-** [comment]
Ah, that makes more sense. Your client is using the correct API version, but ansible makes unversioned calls to `docker.utils.create_host_config`, which it definitely shouldn't be doing. `default` is causing issues for your setup because the `docker` version you're using doesn't support that value, which was introduced later.

The reason we're not using `bridge` as the default value is that the default for Swarm engines is different. The bug should be reported to `ansible` - their code should be using `Client.create_host_config` instead of `docker.utils.create_host_config`.

**Comment by tbsf** [comment]
Ok, I'll take it over there.

One question I have is, I only see in 1.21 documentation for Docker:

```
NetworkMode - Sets the networking mode for the container. Supported standard values are: bridge, host, none, and container:<name|id>. Any other value is taken as a custom network’s name to which this container should connect to.
```

Does this mean the value of "default" is taken as a custom network's name in 1.21+? Is this different behavior than in 1.19/1.20?

**Comment by shin-** [comment]
`default` is just missing from the documentation. The daemon interprets it as "default for the current platform", which is `bridge` for Docker Engine, and `overlay` for Swarm.

In 1.20, specifying a value for `network_mode` became mandatory (the server will error out otherwise), which is why we have this special case where we insert a value if it's missing. API versions < 1.20 don't have that restriction, so we leave it to the user to do what they think is best.

See #698 and docker/docker#14530 for more info.

Hope that clears it up!
