### ISSUE TITLE
Support --oom-score-adj introduced in docker 1.10.0

### ISSUE THREAD

**Issue by adityamarella** [docker/docker-py#991]
OomScoreAdj config is pretty useful to mark not-so-critical containers for OomKilling before other containers. Is this in the pipeline of things to do? Is it ok, if I send a one-off pull request adding only this flag?

**Comment by shin-** [comment]
Sure, feel free to make a PR for it!

**Comment by adityamarella** [comment]
Here is the PR
https://github.com/docker/docker-py/pull/1002
