### ISSUE TITLE
Unit tests are broken?

### ISSUE THREAD

**Issue by adityamarella** [docker/docker-py#996]
I get whole bunch of these errors when I run `make test`. I am using docker 1.10.3 

> docker run --volumes-from dpy-dind-ssl --env="DOCKER_HOST=tcp://docker:2375" --env="DOCKER_TLS_VERIFY=1" --env="DOCKER_CERT_PATH=/certs" --link=dpy-dind-ssl:docker docker-py py.test tests/integration
> ============================= test session starts ==============================
> platform linux2 -- Python 2.7.11 -- py-1.4.31 -- pytest-2.7.2
> rootdir: /home/docker-py, inifile: pytest.ini
> plugins: cov
> collected 111 items
> 
> tests/integration/api_test.py EEEEEEEEEE
> tests/integration/build_test.py EEEEE
> tests/integration/container_test.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEs
> tests/integration/exec_test.py EEEEEEE
> tests/integration/image_test.py EEEEEEEEEs
> tests/integration/network_test.py EEssssEEssEEE
> tests/integration/regression_test.py EEEEEE
> tests/integration/volume_test.py EEEEEEE
> 
> ==================================== ERRORS ====================================
> _________________ ERROR at setup of InformationTest.test_info __________________
> tests/integration/conftest.py:19: in setup_test_session
>     c.inspect_image(BUSYBOX)
> docker/utils/decorators.py:21: in wrapped
>     return f(self, resource_id, *args, **kwargs)
> docker/api/image.py:143: in inspect_image
>     self._get(self._url("/images/{0}/json", image)), True
> docker/utils/decorators.py:47: in inner
>     return f(self, *args, **kwargs)
> docker/client.py:112: in _get
>     return self.get(url, **self._set_request_timeout(kwargs))
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:473: in get
>     return self.request('GET', url, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:461: in request
>     resp = self.send(prep, **send_kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:573: in send
>     r = adapter.send(request, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/adapters.py:415: in send
>     raise ConnectionError(err, request=request)
> E   ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
> ________________ ERROR at setup of InformationTest.test_search _________________
> tests/integration/conftest.py:19: in setup_test_session
>     c.inspect_image(BUSYBOX)
> docker/utils/decorators.py:21: in wrapped
>     return f(self, resource_id, *args, **kwargs)
> docker/api/image.py:143: in inspect_image
>     self._get(self._url("/images/{0}/json", image)), True
> docker/utils/decorators.py:47: in inner
>     return f(self, *args, **kwargs)
> docker/client.py:112: in _get
>     return self.get(url, **self._set_request_timeout(kwargs))
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:473: in get
>     return self.request('GET', url, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:461: in request
>     resp = self.send(prep, **send_kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:573: in send
>     r = adapter.send(request, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/adapters.py:415: in send
>     raise ConnectionError(err, request=request)
> E   ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
> ________________ ERROR at setup of InformationTest.test_version ________________
> tests/integration/conftest.py:19: in setup_test_session
>     c.inspect_image(BUSYBOX)
> docker/utils/decorators.py:21: in wrapped
>     return f(self, resource_id, *args, **kwargs)
> docker/api/image.py:143: in inspect_image
>     self._get(self._url("/images/{0}/json", image)), True
> docker/utils/decorators.py:47: in inner
>     return f(self, *args, **kwargs)
> docker/client.py:112: in _get
>     return self.get(url, **self._set_request_timeout(kwargs))
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:473: in get
>     return self.request('GET', url, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:461: in request
>     resp = self.send(prep, **send_kwargs)
> /usr/local/lib/python2.7/site-packages/requests/sessions.py:573: in send
>     r = adapter.send(request, **kwargs)
> /usr/local/lib/python2.7/site-packages/requests/adapters.py:415: in send
>     raise ConnectionError(err, request=request)
> E   ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
>

**Comment by shin-** [comment]
The `integration-dind-ssl` target has a race condition in. You can add `sleep 1` as the second line and it should work fine.

But yeah, it would be nice to have a good fix for it.

**Comment by adityamarella** [comment]
Thanks. `sleep 1` fixes those errors for now. I will get my changes in and see if I can fix the tests in the right way.
